### ISSUE TITLE
Include TP3 Performance tests

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1007]
There is a structure and performance test case that are currently implemented for Berkeley but ignored.
Include those and add the right annotation so those only get executed with the other titan performance tests. Make sure they pass.

**Comment by mbroecheler** [comment]
There is an open serialization issue in writeGyro. Awaiting feedback from Stephen. Have not yet run ProcessPerformanceTest to completion since that takes forever.

**Comment by mbroecheler** [comment]
The ProcessPerformanceTest finished. There is a failure which seems unrelated to Titan. Waiting on feedback from Daniel.

**Comment by mbroecheler** [comment]
Failure is supposed to be fixed. After next upgrade of TinkerPop, verify its passing then close this ticket.

**Comment by BrynCooke** [comment]
Tests run without failure
