### ISSUE TITLE
titan core 0.4.2 bug : com.esotericsoftware.kryo.KryoException: Buffer too small: capacity: 2, required: 8

### ISSUE THREAD

**Issue by mishraawake** [thinkaurelius/titan#1013]
I have a titan graph setup using following versions of software.

Cassandra version : 2.0.6

Titan version : 0.4.2

5 cassandra server with replication factor 3.

Recently, all of sudden, we have started getting following error intermittently.

com.esotericsoftware.kryo.KryoException: Buffer too small: capacity: 2, required: 8

I searched net and found that there is a bug filed relating to same error. Bug is pertaining to kryo API. https://code.google.com/p/kryo/issues/detail?id=124

Fix of above bug is not incorporated in titan-0.4.2 version.

On cassandra server we have not run repair database for many days (6 months). Can it be the issue with inconsistent data on cassandra server?

Can you please suggest the reason for this bug and how to approach solving it?

**Comment by mbroecheler** [comment]
That's hard to say. Often times, such bugs are caused by inconsistencies in Cassandra itself. I wasn't aware of the kryo bug, so that might be another issue.

**Comment by mishraawake** [comment]
But the problem is that we have already used titan 0.4.2 and it was running fine for last one year. Now it has started throwing this problem. We are almost stuck. 
At least we want to have some kind of sure way to debug the problem.  What is the way forward you are suggesting. 
Is there a tool which will help me to remove this inconsistency. Is there any support available from titan team.

We are in process to take decision of migrating our database layer from RDBMS to titan graph.  
And we can not afford some unknown production bug in that application.

**Comment by mbroecheler** [comment]
In that case, it does sounds like data corruption in Cassandra. Can you try
a repair? Does this issue only come up when reading certain types of data
or all data? Is your cluster in good health?

**Comment by mishraawake** [comment]
Cluster seems to be fine as i can see from nodetool. Issue comes only for certain types of data. i.e. for certain nodes. But that number is significant. Almost 100 nodes seems to have been effected. We are planning to run repair on our cassandra database and hoping error will go away.

Can you guide  me  through a method to see whether data is correct in cassandra by querying it through cql. We have with us the graph nodeId which has got corrupted but we don't know the way in which we can verify whether correct data present on cassandra or not.
