### ISSUE TITLE
Inconsistent handling of querying Set Properties 

### ISSUE THREAD

**Issue by szetheli** [thinkaurelius/titan#1016]
- Declare a Vertex property as Set
  t.makePropertyKey('anks').dataType(String.class).cardinality(Cardinality.SET).make()
- Add a Vertex with two values of that property
- Query the Vertex from the g.V
  gremlin>g.V.has('anks',g.v(237824)['anks'][0])
  ==>v[237824]
- Query the Vertex from the vertex
  gremlin>g.v(237824).has('anks',g.v(237824)['anks'][0])
  No matches

When using g.V, the query evaluates each of the values of the property for a match.
When using vertex, the query is comparing the collection of property values against the has value.

Expected: 
The two uses of has(property, propertyvalue) should be consistent.

**Comment by mbroecheler** [comment]
Yes, this is a known issue since Blueprints doesn't support SET semantics and Titan cannot overwrite the behavior. This is solved in the upcoming TinkerPop3.
