### ISSUE TITLE
some suggestion of building source

### ISSUE THREAD

**Issue by gointosunset** [thinkaurelius/titan#1017]
Hi, i don't know how to post my suggestion, so i post as a issus.
when i begin to build titan source, i use the command follow:

> $ mvn clean install -DskipTests -Dmaven.test.skip=true -e -X

1：i get error about <artifactId>asciidoctor-maven-plugin</artifactId> need support of jruby-complete 1.7.0 + , so i modify the follow configuration 

plugin>
____groupId>org.asciidoctor/groupId>
____artifactId>asciidoctor-maven-plugin/artifactId>
____inherited>false/inherited>
____executions>
________execution>
____________id>asciidoc-to-docbook/id>
____________phase>generate-resources/phase>
____________goals>
________________goal>process-asciidoc/goal>
____________/goals>
____________configuration>
________________sourceDirectory>${asciidoc.output.dir}/sourceDirectory>
________________sourceDocumentName>index.txt/sourceDocumentName>
________________outputDirectory>${docbook.output.dir}/outputDirectory>
________________backend>docbook5/backend>
________________doctype>book/doctype>
________________attributes>
____________________encoding>UTF-8/encoding>
____________________iconsdir>images/icons/iconsdir>
____________________imagesdir>images/imagesdir>
____________________toc>true/toc>
________________/attributes>
____________/configuration>
________/execution>
____/executions>
____dependencies>
________dependency>
____________groupId>org.jruby/groupId>
____________artifactId>jruby-complete/artifactId>
____________version>1.7.0/version>
________/dependency>
____/dependencies>
/plugin>

now building source success. 
then i thought my hadoop version is cdh-5.2.0 that compile with hadoop-2.5.0. so i try to build titan with hadoop-2.5.0. i find the maven controller hadoop version and using <artifactId>maven-enforcer-plugin</artifactId> to ensure dependencies version.
so i use the follow command to compile source

> $mvn clean install -DskipTests -Dmaven.test.skip=true -e -X -Dhadoop2.version=2.5.0

2：failing, because of dependencies conflict, the error cause by three dependecies, i solve by exclude them of default hadoop version invocaking, follow (need modify all pom.xml contain this three issus dependencies):

________dependency>
____________groupId>org.apache.hbase/groupId>
____________artifactId>hbase-client/artifactId>
____________version>${hbase.version}/version>
____________optional>true/optional>
____________exclusions>
________________exclusion>
____________________artifactId>avro/artifactId>
____________________groupId>org.apache.avro/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>jruby-complete/artifactId>
____________________groupId>org.jruby/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>asm/artifactId>
____________________groupId>asm/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-annotations/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-common/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-mapreduce-client-core/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-auth/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
____________/exclusions>
________/dependency>

________dependency>
____________groupId>org.apache.hbase/groupId>
____________artifactId>hbase-server/artifactId>
____________version>${hbase.version}/version>
____________optional>true/optional>
____________exclusions>
________________exclusion>
____________________artifactId>avro/artifactId>
____________________groupId>org.apache.avro/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>jruby-complete/artifactId>
____________________groupId>org.jruby/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>asm/artifactId>
____________________groupId>asm/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-annotations/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-client/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-common/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-mapreduce-client-jobclient/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-hdfs/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-mapreduce-client-core/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-auth/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
____________/exclusions>
________/dependency>

________dependency>
____________groupId>org.apache.solr/groupId>
____________artifactId>solr-core/artifactId>
____________version>${solr.version}/version>
____________exclusions>
________________exclusion>
____________________groupId>org.apache.zookeeper/groupId>
____________________artifactId>zookeeper/artifactId>
________________/exclusion>
________________exclusion>
____________________groupId>com.spatial4j/groupId>
____________________artifactId>spatial4j/artifactId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-common/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-auth/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-hdfs/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
________________exclusion>
____________________artifactId>hadoop-annotations/artifactId>
____________________groupId>org.apache.hadoop/groupId>
________________/exclusion>
____________/exclusions>
________/dependency>

now, building has become success. 
then i add cloudera repository to maven parent pom.xml as follow

____repositories>
________repository>
____________id>cloudera/id>
____________url>https://repository.cloudera.com/artifactory/cloudera-repos//url>
________/repository>
____/repositories>

> $mvn clean install -DskipTests -Dmaven.test.skip=true -e -X -Dhadoop2.version=2.5.0-cdh5.2.0

building success, 
====================end of building====================
3：when i using the my building package i find some word in source about guava version, so i chang guava version to 14.0.1. so i modify maven pom
________dependency>
____________groupId>com.google.guava/groupId>
____________artifactId>guava/artifactId>
____________version>14.0.1/version>
________/dependency>  

then anything is working well.

this is all my find, thank you !

**Comment by dalaro** [comment]
Hi,
1. I'm unable to reproduce this error.
2. Build profiles for Hadoop distros, including CDH5, are welcome.  However, I can't test this, and I'm not sure if it's actually correct; I notice that it does not seem to modify titan-hadoop.
3. The guava version is probably the single most sensitive one in Titan's dependency list, since so many of Titan's dependencies in turn depend on different versions of Guava (#854).  I don't think we can merge this last change.
