### ISSUE TITLE
Verify that ConfigOptions only use supported primitives

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1018]
After removing Kryo, Titan does no longer support serializing arbitrary objects. All such instances have been removed inside the core graph module, but there might be cases where the configuration system relies on non-supported classes.

For instance, BerkeleyJE used some ConfigOption instances that made references to BerkeleyJE specific classes (e.g. LockMode, IsolationLevel). Those need to be replaced by String variants (or other suitable data types). See BerkeleyJEStoreManager#ISOLATION_LEVEL as an example and utilize ConfigOption.getEnumValue() has a helper method.

Please go through all ConfigOption and ensure that they only use objects explicitly supported by the serializer.

**Comment by dalaro** [comment]
@mbroecheler StandardSerializer maps some enum types to a simple serializer that avoids the need for ConfigOption.getEnumValue:

```
        ...
        registerClassInternal(45,Order.class, new EnumSerializer<>(Order.class));
        registerClassInternal(46,Multiplicity.class, new EnumSerializer<>(Multiplicity.class));
        registerClassInternal(47,Cardinality.class, new EnumSerializer<>(Cardinality.class));
        registerClassInternal(48,Direction.class, new EnumSerializer<>(Direction.class));
        registerClassInternal(49,ElementCategory.class, new EnumSerializer<>(ElementCategory.class));
        registerClassInternal(50,ConsistencyModifier.class, new EnumSerializer<>(ConsistencyModifier.class));
        registerClassInternal(51,SchemaStatus.class, new EnumSerializer<>(SchemaStatus.class));
        registerClassInternal(52,LogTxStatus.class, new EnumSerializer<>(LogTxStatus.class));
        registerClassInternal(53,MgmtLogType.class, new EnumSerializer<>(MgmtLogType.class));
        registerClassInternal(54,Timestamps.class, new EnumSerializer<>(Timestamps.class));
        registerClassInternal(55,TimeUnit.class, new EnumSerializer<>(TimeUnit.class));
        registerClassInternal(56,Mapping.class, new EnumSerializer<>(Mapping.class));
        ....
```

Most of those are Titan or TP3 enums, though at least one (TimeUnit) is part of Java.

Why do you want to move to ConfigOption.getEnumValue(string, enumclass) instead of just adding additional type mappings to StandardSerializer for the rest of the enums required by Titan, and leaving getEnumValue for third-party extensions?

**Comment by mbroecheler** [comment]
I want to avoid cyclic dependencies. Hence, anything that is not titan-core should not use enums for serialization. That was the problem with BerkeleyJEStoreManager#ISOLATION_LEVEL - to add that to the serializer would have introduced a cyclic dependency (or some ugly reflection business).

So, within titan-core we should register the enums. Outside, we should use the helper method to go through string.
