### ISSUE TITLE
Better support for Timestamp

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1019]
I think we should try to make `com.thinkaurelius.titan.core.attribute.Timestamp` the standard representation of time inside Titan rather than having users rely on Date, Calendar or what-have-ya. To that effect, we should:

1) Provide methods on Timestamp to convert to and from Date and Calendar
2) Extend TimestampSerializer to automatically convert to Timestamp from Date and Calendar (by implementing the convert() method of the interface which calls the methods on Timestamp)
3) Providing suitable test coverage

**Comment by BrynCooke** [comment]
@mbroecheler 
I think what this is saying is that all temporal data will be stored as titan.Timestamp internally, but that also when users retrieve that data they would get back a titan.Timestamp which they can then convert in to the appropriate format.

I'm not sure that this is such a good idea as Java already has so many different representations of Temporal data, and we don't really want to add another one to the mix.

As Titan09 is targeted at Java8 perhaps we should strip support for everything except [Instant](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html). The new java8 date time APIS are very good and we can then strip out some of our custom code that does the same stuff.

Thoughts?

**Comment by mbroecheler** [comment]
Yes, that's a good idea. Is there also a class for duration now that we
could use instead of StandardDuration?

However, we should nevertheless increase our utility support for whatever class we ultimately end up using so that we automatically convert from Date, Calendar, String to that format if such is provided by the user. Likewise, we should think about how such data is returned to the user - in particular if the client is not a java application.

**Comment by BrynCooke** [comment]
Yes there is duration support. Also serialisation and parsing to ISO formats is easy. Currently we have code that does this.
We can still have a converter that accepts date, calendar etc as per the original suggestion. It would be up to the user to convert from instant back to date or calendar if they wanted to. (They won't unless they are calling legacy code)
