### ISSUE TITLE
Solr commit performance

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#1022]
I have noticed the following line is causing Solr to take ages to return from mutations:

req.setAction(UpdateRequest.ACTION.COMMIT, true, true);

The offending parameters is waitSearcher that causes the action to wait until the new results are visible in the Solr index before returning. This can take several seconds.

@mbroecheler Is it safe to remove this?

**Comment by mbroecheler** [comment]
check 0.5 and 0.9 branches
