### ISSUE TITLE
ElasticSearchIndex does not support simple types like boolean.

### ISSUE THREAD

**Issue by akosbordas** [thinkaurelius/titan#1024]
I would like index boolean data in my ES backend, however according to the ElasticSearchIndex class Titan supports only String, Numeric and GeoShape fields. Why is this restriction? ES supports boolean if you use it as a standalone indexer.

Btw.: This exception is a bit annoying: IllegalArgumentException("Unsupported type: " + add.value);
From the logs you can think that it's try to use the value as a type.

**Comment by boliza** [comment]
titan09 will support.
You can see this #769 ,also discuss https://groups.google.com/forum/#!topic/aureliusgraphs/YAbKt9Vscl0
