### ISSUE TITLE
Disable transaction cache for compute

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#1031]
Fixes compute union tests in test suite.
The issues is that when a compute traversal takes place adjacent vertices end up in the transaction cache. These vertices are not full vertices you cannot get properties or labels from them.

If a vertex program subsequently starts at one of the vertices then it will fail as it will be unable to get retrieve the property information or traverse to adjacent vertices.

The solution is to disable the transaction cache for compute.

**Comment by mbroecheler** [comment]
@BrynCooke This can be closed, right?

**Comment by BrynCooke** [comment]
Yup
