### ISSUE TITLE
Add deep profiling information

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1035]
by extending the profile step functionality added in TP3 M8 with information on index hits, cache performance, etc. With @rjbriody

**Comment by rjbriody** [comment]
@mbroecheler,  some notes on expected usage of the TinkerPop Metrics framework:

The metrics for the Traversal Steps are created automatically and held/managed by the StandardTraversalMetrics class.

In Titan, an individual step's `MutableMetrics` can be augmented by
- adding annotations via `setAnnotation`
- adding nested metrics via `addNested`

I think it makes sense for Titan to populate 2 separate nested metrics; one for index access and one for DB access. Each of these can annotated to describe index coverage.

**Comment by mbroecheler** [comment]
Temporarily blocked on https://issues.apache.org/jira/browse/TINKERPOP3-651

**Comment by mbroecheler** [comment]
This has been implemented under the assumption that Titan's custom steps can get access to a @MutableMetrics@ object.
Hence, hooking this up with the work @rjbriody is doing in TP3 should be trivial. Once that is complete, this feature needs to be documented.

**Comment by mbroecheler** [comment]
This has been added on the titan09 branch. @rjbriody Please test and let us know whether the information comes through.
I the information can be retrieved through TP3 this issue can be closed.

**Comment by mbroecheler** [comment]
@rjbriody Titan's profiling information has been flattened - i.e. no more AND/OR nesting. In addition, an optimization sub-metric has been added to measure the time taken by query optimization.

**Comment by rjbriody** [comment]
Cool. I will check it out.

**Comment by mbroecheler** [comment]
@rjbriody Happy with it? If not, please reopen.
