### ISSUE TITLE
Investigate lower bounds for (key-)slicequeries

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1041]
Investigate two occurrences where the lower bound is an all-0 bytebuffer longer than 1 (which can cause not all rows or columns being retrieved since a shorter all-0 bytebuffer would be considered smaller).
In ConsistentKeyLocker: LOCK_COL_START
In ConsistentKeyIDAuthority: LOWER_SLICE

Interestingly, changing LOWER_SLICE to zeroBuffer(1) causes test failures in VertexIDAssignerTest and its not clear why.

**Comment by mbroecheler** [comment]
Actually, the test failure has nothing to do with this and is a random failure (due to randomized id allocation) which I am looking into. SO, this is likely a safe change but we should be careful nevertheless since this is core stuff.

**Comment by dalaro** [comment]
I tweaked these and added comments around them with my rationale (080b8be609baf8cbadc2719ce1566965a35c9046).  I also found no failure when changing `LOWER_SLICE` to `zeroBuffer(1)`.
