### ISSUE TITLE
Cassandra 2.1 CQL3 Support

### ISSUE THREAD

**Issue by CasperWW** [thinkaurelius/titan#1052]
Cassandra 2.1 CLQ3 [shows](http://www.datastax.com/dev/blog/cassandra-2-1-now-over-50-faster) 160% and 150% (read and write respectively) performance gain over the deprecated Thrift framework. A huge optimisation with the combination Titan-Cassandra can be made.

**Comment by mbroecheler** [comment]
These benchmarks are based on tabular reads. When we did a comparison it turns out that the lack of multi-row query support in thrift led to an overall reduced performance.

**Comment by mbroecheler** [comment]
This is essentially a duplicate of #312

**Comment by briandilley** [comment]
So does that mean titan will never run on CQL?

**Comment by countrodrigo** [comment]
Does the CQL migration make sense with the latest C* versions (> 3.x) ?
