### ISSUE TITLE
HBase TP3 tests require M9

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1061]
TP3 test suite currently opens a graph before @BeforeClass gets called. This is fixed in SNAPSHOT but requires an M9 release of TP3 for the tests to work in Titan.

This issue just keeps track of this dependency. No need to do anything.

**Comment by dalaro** [comment]
I  think this was fixed in a6c94ca0cce89192b19cbc4a0c5adf99bbaff3be.
