### ISSUE TITLE
Support HBase 1.0

### ISSUE THREAD

**Issue by monkegoist** [thinkaurelius/titan#1065]
HBase 1.0 was released 2 months ago. Titan is currently compatible only with 0.98. It would be great if you, guys, added support for 1.0 as well.

**Comment by dminkovsky** [comment]
https://groups.google.com/forum/#!topic/aureliusgraphs/qtphiLXgcMM

**Comment by dalaro** [comment]
I reworked the titan-hbase compat layer to support HBase 1.0 alongside the existing supported versions.

I've only run HBaseGraphTest on each version.  This could really use additional testing.  Of HBase 1.0 versions, I've built and tested only against 1.0.2.  Theoretically, 1.1.x should also be supported now (falling back to the 1.0 compat shim), but I haven't tried it.

**Comment by dminkovsky** [comment]
Thank you Dan! This is really cool.
