### ISSUE TITLE
Connecting to Solr when authentication is required?

### ISSUE THREAD

**Issue by maccam912** [thinkaurelius/titan#1066]
I couldn't find anything in the documentation about how to connect to Solr if I have basic auth enabled, or even if it is possible. I asked here too: http://stackoverflow.com/questions/29973191/titan-securing-solr-with-basic-auth-as-an-index-backend

Right now titan silently fails to connect to Solr, and I would not know it didn't work if I didn't look directly at what Solr was doing. Is it planned to alert the user that a connection with Solr was not made? When failing to connect to a storage backend, the uesr is notified. There is also documentation on how to connect to a cassandra database requiring authentication.

(This could also apply to ElasticSearch)

**Comment by mbroecheler** [comment]
It is my understanding that this is currently not supported. Shouldn't be too hard to ad though if somebody wants to take a crack at it.

**Comment by fitzoh** [comment]
Have you tried embedding the credentials in the SOLR url?

```
index.search.backend=solr
index.search.solr.mode=http
index.search.solr.http-urls=http://user:password@localhost:8983/solr
```

We're currently using this method with DSE Search without any issues (other than #837).

**Comment by maccam912** [comment]
It seems like the problem is that SolrJ is stripping the credentials from the URL at some point. DSE Search says there is support from extending SolrJ, and when I am debugging, the URL Solr is requesting does not include the credentials. I think it's an issue of Solr not supporting basic auth.
