### ISSUE TITLE
Create test profile for maven that completes in reasonable time with good coverage

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1068]
this should EXCLUDE all of the TinkerPop3 tests, all performance and all memory tests.

Is it possible to make this the default profile that is executed when running mvn clean install? If so, we should have another profile that includes TP3 tests and finally a profile that includes those plus performance and memory.

**Comment by dalaro** [comment]
Sounds good.  I'll document the options controlling the Maven test set either in RELEASING.md (which exists already) or a new file like BUILDING.something.

**Comment by dalaro** [comment]
This is pushed to titan09, though not well tested.  The TP3 tests should be disabled by default.  To reenable them, add `-Dtest.skip.tp=false` to the Maven command line.  For example: `mvn clean install -Dtest.skip.tp=false`.  This is documented in BUILDING.md in the root of the repo.
