### ISSUE TITLE
Titan distribution folder is over chmod'd

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#108]
drwxrwxrwx 7 ubuntu ubuntu       4096 2012-09-06 18:03 titan-0.1.0

Get this like Faunus:

drwxr-xr-x 7 ubuntu ubuntu       4096 2012-09-21 07:20 faunus-0.1-alpha

**Comment by mbroecheler** [comment]
where does that need to happen? In the pom or before packaging it up?

**Comment by spmallette** [comment]
in distribution.xml...

https://github.com/tinkerpop/rexster/blob/master/rexster-server/src/assembly/distribution.xml

**Comment by mbroecheler** [comment]
the <fileMode>0775</fileMode> is already in there but Marko said it does not work.

**Comment by xedin** [comment]
Fix pushed to master as 12c1a7a6718925a58f619c80f07a63320274fd55. Distribution directory - 755, files - 644/normal, 775/executable, closing this issue.
