### ISSUE TITLE
Addition of WhereStep broke Titan's query optimizer

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1091]
since steps like `has('weight')` are no longer folded into TitanVertexStep (or TitanGraphStep).

@rjbriody Could you please add BerkeleyGraphTest to the set of tests that is executed by Jenkins on build. That ensures that Titan's test cases for the query optimizer are included since they aren't part of the TinkerPop test suite.

**Comment by mbroecheler** [comment]
In addition, there seems to be an issue around HasStep not being folded in correctly. Run `testTinkerPopOptimizationStrategies` in BerkeleyGraphTest to reproduce.

**Comment by okram** [comment]
This test does not exist. Which branch are you in? I work against `titan09`.

**Comment by okram** [comment]
Ah. I see it. Its in the base class. Note that `has(key)` is simply a `where(values('key'))` and `hasNot(key)` is now `where(not(values('key'))`. The `Contains.within() == null` stuff was a hack.

**Comment by okram** [comment]
Also, in your `testTinkerPopOptimizationStrategies` test cases you do this:

```
__.outE("knows").has("weight").has("weight", 1).order().by("weight", incr).range(10, 15)
```

This is equivalent to:

```
__.outE("knows").has("weight", 1).order().by("weight", incr).range(10, 15)
```

If you are filtering on weight, you don't need to check if the weight exists.

**Comment by okram** [comment]
This test fails too:

```
gts.V().has("id", sid).outE("knows").has("weight", P.between(1, 3)
```

I suspect because `P.between(1,2)` returns a `AndP` -- no more `P[]`. I don't understand you test case, but you will probably want to check to see if the `P` predicate is a `AndP` or an `OrP`. From there you get can `AndP.getPredicates()`.

Note that this is where we are going with nesting and `AndP.getPredicates()` can return yet more `OrP` and `AndP`s.

**Comment by mbroecheler** [comment]
Fixed in TP3.
