### ISSUE TITLE
TTL performance

### ISSUE THREAD

**Issue by simtitanuser** [thinkaurelius/titan#1096]
Hi, this is not really an issue but something I need to document.
After re-writing my Java code to take advantage of TTL, I'm now being asked to explain how it works. I understand that the process starts from the time the transaction is closed, but need to know if there are any limitations when dealing with millions of vertices and edges all created within a short period of time.
I've been struggling with Gremlin scripts in an attempt to measure the performance of TTL in Titan/Cassandra but they're proving difficult and unreliable. Can someone please shed some light on how the internals work and if there's a reliable way of performing such measurements.

Thanks.

**Comment by mbroecheler** [comment]
Please ask questions on the mailing list, not the bug tracker:
aureliusgraphs@googlegroups.com
