### ISSUE TITLE
May I know how do I create different graph instances on same HBase storage

### ISSUE THREAD

**Issue by sgottipa** [thinkaurelius/titan#110]
I am exploring titan to see whether I can use it in my domain.
We have a need where we need to store different graphs in the same HBase instance.

I see, in titan you can get a graph from TitanFactory and manipulate nodes/edges from there. But I don't see a way where it treats each graph instance as a first class citizen.
Am I missing something?

**Comment by mbroecheler** [comment]
Hey,
please use our mailing list for questions:
aureliusgraphs@googlegroups.com
groups.google.com/group/aureliusgraphs

This issue tracker is for bugs and features only.
Thank you,
Matthias
