### ISSUE TITLE
Relax immutable memory constraints from workerIterationStart and workerIterationEnd

### ISSUE THREAD

**Issue by levin-royl** [thinkaurelius/titan#1109]
If I understand correctly the 'memory' object in a VertexProgram object is a (key/value) cluster shared memory instance.

If so, I wanted to use workerIterationStart and workerIterationEnd to aggregate values computed during the 'execute' phase to pass on to the next iteration.
However, 'memory' is immutable during workerIterationStart and workerIterationEnd.

The response from Marko Rodriguez is as follows:

Off the bat, I don't see why these sub-stages would require memory to be immutable as they can just be like "faux vertex" contributions. However, realize that if it was mutable, it would not allow you to see the worker partition aggregations, only that the worker would be able to contribute to the memory key aggregation. 

If you make a ticket in TinkerPop3, I can think on it more and see about relaxing that constraint.

**Comment by mbroecheler** [comment]
This is a TinkerPop3 issue (which is the interface that Titan uses) and not directly a Titan issue. I know, this can be confusing.
Please file your ticket here:
https://issues.apache.org/jira/browse/TINKERPOP3

**Comment by levin-royl** [comment]
Hi,

Thanks but I am not sure how to open an issue there ...
When I press "create" I need to select one of the following:
- Apache Infrastructure
  https://issues.apache.org/jira/servicedesk/customer/infra
- Kylin https://issues.apache.org/jira/servicedesk/customer/kylin
- Atlas https://issues.apache.org/jira/servicedesk/customer/atlas

How should I proceed?

Thanks,

Roy.

**Comment by mbroecheler** [comment]
Good question, @levin-royl. @okram can you get that issues filed over there?
