### ISSUE TITLE
Bug in Titan ElasticSearch ext.create configuration

### ISSUE THREAD

**Issue by Alan47** [thinkaurelius/titan#1114]
I am trying to configure a tokenizer and an analyzer for Elasticsearch through the Titan create.ext properties. Here is the full JUnit-Test:

```
public class TitanESTest {

private static final String EXT = "index.search.elasticsearch.create.ext.index.";

@Test
public void runTest() {
    Builder titanBuilder = TitanFactory.build();
    titanBuilder.set("storage.backend", "inmemory");
    titanBuilder.set("index.search.backend", "elasticsearch");
    titanBuilder.set("index.search.elasticsearch.interface", "NODE");
    titanBuilder.set(EXT + "analysis.analyzer.myanalyzer.type", "custom");
    titanBuilder.set(EXT + "analysis.analyzer.myanalyzer.tokenizer", "mytokenizer");
    titanBuilder.set(EXT + "analysis.analyzer.myanalyzer.filter", "mylowercasefilter");
    titanBuilder.set(EXT + "analysis.filter.mylowercasefilter.type", "lowercase");
    titanBuilder.set(EXT + "analysis.filter.mylowercasefilter.language", "greek");
    titanBuilder.set(EXT + "analysis.tokenizer.mytokenizer.type", "whitespace");
    titanBuilder.set(EXT + "analysis.tokenizer.mytokenizer.max_token_length", 255);
    TitanGraph graph = titanBuilder.open();
    assertNotNull(graph);
}
```

This is a slightly simpler filter than presented here in the ElasticSearch docs:
https://www.elastic.co/guide/en/elasticsearch/reference/1.3/analysis-lowercase-tokenfilter.html

According to the Titan documentation, this should work. However, depending on the Titan version, I get different error messages (but all of them fail the test):

TITAN 0.9.0-M2
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.index.elasticsearch.create.ext]: analysis

TITAN 0.9.0-M1
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.index.elasticsearch]: create

TITAN 0.5.4:
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.index.elasticsearch.create.ext]: analysis

I also tried to put the parameters in a Titan *.properties file, without success (same errors as above). I also tried using a separate *.yaml file for the ES configuration and point Titan to it by using the `index.search.conf-file` property - no success (seems to be ignored).

**Comment by Alan47** [comment]
No comments on this one? :(

**Comment by kevinschumacher** [comment]
Related: issue #399 

@dalaro / @mbroecheler any update on this?

**Comment by dalaro** [comment]
I reproduced the "Unknown configuration element" exception locally on titan09.  There is a workaround for this bug: create a file and invoke `TitanFactory.open` on it.

I haven't tried to reproduce the index.search.conf-file exception yet.

**Comment by dalaro** [comment]
Re: "I also tried to put the parameters in a Titan *.properties file, without success (same errors as above)."  I checked this on titan09, and I'm not seeing this behavior.  It's not perfect apples-to-apples comparison, since titan09 is slightly newer than M2, but it's unlikely that this changed.

Here's the properties file that I used:

``` ini
storage.backend=berkeleyje
storage.directory=db
index.search.elasticsearch.interface=NODE
index.search.elasticsearch.ext.node.data=true
index.search.elasticsearch.ext.node.client=false
index.search.elasticsearch.ext.node.local=true
```

Here are the gremlin commands that I ran to sanity check it:

``` groovy
g = TitanFactory.open('1114.2.properties')
m = g.openManagement()
n = m.makePropertyKey('name').dataType(String.class).make()
m.buildIndex('byName', Vertex.class).addKey(n).buildMixedIndex('search')
m.commit()
g.tx().commit()
g.close()

g = TitanFactory.open('1114.2.properties')
v = g.addVertex()
v.property('name', 'alice')
g.tx().commit()

g.query().has('name', com.thinkaurelius.titan.core.attribute.Text.CONTAINS_REGEX, '.*ice').vertices()
// prints ==>v[4096] with no linear scan warning, indicating that it hit the index
```

I also tried converting the ES snippet that you posted into the following properties file:

``` ini
storage.backend=inmemory
index.search.backend=elasticsearch
index.search.elasticsearch.interface=NODE
index.search.elasticsearch.create.ext.index.analysis.analyzer.myanalayzer.type=custom
index.search.elasticsearch.create.ext.index.analysis.analyzer.myanalyzer.type=custom
index.search.elasticsearch.create.ext.index.analysis.analyzer.myanalyzer.tokenizer=mytokenizer
index.search.elasticsearch.create.ext.index.analysis.analyzer.myanalyzer.filter=mylowercasefilter
index.search.elasticsearch.create.ext.index.analysis.filter.mylowercasefilter.type=lowercase
index.search.elasticsearch.create.ext.index.analysis.filter.mylowercasefilter.language=greek
index.search.elasticsearch.create.ext.index.analysis.tokenizer.mytokenizer.type=whitespace
index.search.elasticsearch.create.ext.index.analysis.tokenizer.mytokenizer.max_token_length=255
```

and I was able to open a graph using that file without exceptions:

``` groovy
gremlin> g = TitanFactory.open('1114.properties')
==>standardtitangraph[inmemory:[127.0.0.1]]
```

But I wasn't sure exactly how to exercise the custom analyzer, so I stopped there.

**Comment by dalaro** [comment]
`index.<name>.conf-file` also seems okay.

I tried this properties file:

1114.3.properties:

``` ini
storage.backend=berkeleyje
storage.directory=db
index.search.elasticsearch.interface=NODE
index.search.conf-file=1114.es.yaml
```

1114.es.yaml:

``` yaml
node.data: true
node.client: false
node.local: true
```

Ran the same commands as in my previous comment, same result.

**Comment by dalaro** [comment]
To summarize:

I reproduced the `TitanFactory.Builder`-based exceptions.  I have a new test to cover this and an associated fix forthcoming.

I was unable to reproduce problems with `conf-file` or embedding ES `ext` options in the Titan properties file.

**Comment by Alan47** [comment]
Thanks for looking into this. It is possible that some of the bugs are not reproducible anymore due to the latest developments. The report reflected the issues I was facing at that time.
