### ISSUE TITLE
Invalid fetch result after updating node's property(0.5.4)

### ISSUE THREAD

**Issue by eyal33** [thinkaurelius/titan#1115]
Hi,

I am creating a vertex with the following properties :
   contractor String
   isabstract  Boolean
   name        String

On each property we built index of type CompositeIndex.

I am making a query with the properties name & contractor and get the vertex back. 

Now, I am changing the value of one of the properties, contractor for example, from "contractor1" to "contractor2". (commit after update)
Then, I am looking for name=X & contract=contractor1 and I am getting 1 result.
In the result I get the new value "contractor2" under contract property. 
However, I expected for empty result since "contractor1" value no more exist.

(When I am looking for name=X & contract=contractor2 , I am getting the update vertex as expected.)

Observations:
    - When omitting the index, the problem is not reproduced.
    - Checked on String and Boolean properties.

Reproduced on :
     Titan:  titan 0.5.4
     Backend: cassandra/inmemory

Thanks,
Eyal

**Comment by mbroecheler** [comment]
Do you have caching enabled? Is it reproducible without caching?

**Comment by eyal33** [comment]
Hi,
The cache was enabled.
As much as I remember, we disabled the cache and restart the application.
It also reproduced.

When there is no index on the property, it is not reproduced.
Moreover, on 5.5.0-SNAPSHOT it is not reproduced.

Regards,
Eyal
בתאריך 25 באוג 2015 21:54, "Matthias Broecheler" notifications@github.com
כתב:

**Comment by mbroecheler** [comment]
Ah, then this is the same as the other indexing bug that we fixed for 0.5.5.

**Comment by eyal33** [comment]
Since 0.5.5 is a SNAPSHOT version, is there a chance to get a patch for
0.5.4 ?
Any other suggestions ?

Thanks,
Eyal
בתאריך 25 באוג 2015 22:46, "Matthias Broecheler" notifications@github.com
כתב:

**Comment by mbroecheler** [comment]
We will be releasing 0.5.5 soon - that is a minor (patch) release.

**Comment by eyal33** [comment]
Great.
Do you have any estimation when it will be released?
Where will I be able to find the new release? Titan site?

Thanks a lot,
Eyal
בתאריך 26 באוג 2015 03:46, "Matthias Broecheler" notifications@github.com
כתב:

**Comment by eyal33** [comment]
Hi,
I understood that version 1.0 is also going to be released. Do you have any
estimation for that?

Thanks,
Eyal
בתאריך 26 באוג 2015 10:01, "Eyal Sofer" eyali.sofer@gmail.com כתב:

**Comment by mbroecheler** [comment]
They are probably going to be released around the same time. In September. 0.5.5 might be a little later.

**Comment by eyal33** [comment]
Thanks a lot.

Eyal
בתאריך 27 באוג 2015 01:46, "Matthias Broecheler" notifications@github.com
כתב:

**Comment by eyal33** [comment]
Hi Matthias,

We saw titan 1.0.0 was released. We saw it works only with Java 8.
Does titan 1.0.0 is BC with cassandra storage which was used by titan 0.5.4
?

Is titan 0.5.5 going to be released soon ?

Thanks a lot,
Eyal

2015-08-27 1:46 GMT+03:00 Matthias Broecheler notifications@github.com:
