### ISSUE TITLE
slf4j version conflicting for libthrift using slf4j 1.5.8 and gremlin core using slf4j 1.7.2

### ISSUE THREAD

**Issue by parvbhullar** [thinkaurelius/titan#1118]
Is there any fix for that.

**Comment by dalaro** [comment]
I don't see exactly what's wrong or needs to be done here.

Titan doesn't control the slf4j version for libthrift or gremlin-core.  In the titan09 branch, the root pom.xml has a `<dependencyManagement>` stanza that sets the slf4j version to 1.7.5, but that only applies for testing and zip-assembly.   The slf4j version used by downstream projects that depend on Titan through maven is out of our direct control... half the dependency graph points to slf4j, so Maven's version resolution algorithm goes to work.

Please reopen if there's a specific exception falling out of this, or if there's a specific slf4j API version besides 1.7.5 that we should set in Titan's `<dependencyManagement>` for some reason (and why).  Thanks.
