### ISSUE TITLE
Improve usability and functionality around BulkLoaderVertexProgram

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1119]

**Comment by spmallette** [comment]
:+1: - would like to rewrite the "powers of ten" posts with @dkuppitz .  when tp3 releases (and titan) bulkloading/data migration will be a top question on the mailing list. what needs to be done with this one?

**Comment by dkuppitz** [comment]
The last time @dalaro and I looked into it, the loader job went to 100% and then .... nothing else happened. No errors, it just sits there forever. @okram's assumption:

> I suspect its a transaction issue. not a TP3 issue

And, although it went to 100%, nothing was ever loaded into Titan.

**Comment by dkuppitz** [comment]
I think this can be closed, since BLVP is included (and documented) in Titan 1.0. Further changes/optimizations will be discussed in [TINKERPOP3-319](https://issues.apache.org/jira/browse/TINKERPOP3-319).
