### ISSUE TITLE
Wrong results in queries. Properties displayed are not the properties of the vertex

### ISSUE THREAD

**Issue by jal06** [thinkaurelius/titan#112]
Hello,

I am using titan with rexster and Cassandra :
- titan 0.1.0
- rexster 2.1.0
- cassandra 1.1.5 (1 single node in my VM)

When using gremlin with the graph of the Gods, everything is working corectly (I do the requests described in the Getting started page).

When I use gremlin with my data, the results of requests look wrong.
Example : I load a small graph (5 vertex and 4 edges) : you will find below the graph in xml format, and its configuration in rexster.xml.The main difference I see between the graph of the gods and my graph : in my graph, all the vertices do not have the same properties (for example the property legacymodificationdate is defined in only 1 vertex). Is it allowed that all vertices do not have the same properties ?

Using gremlin, I set the storage properties of the graph and I load it :

confcass = new BaseConfiguration();
confcass.setProperty("storage.backend","cassandra");
confcass.setProperty("storage.hostname","localhost");
confcass.setProperty("port",9160);
confcass.setProperty("storage.keyspace","titan");
g = TitanFactory.open(confcass);

g.createKeyIndex('name', Vertex.class)
g.loadGraphML('../../wshared/data/creds/creds2.xml')

Then I query some properties of some vertex in the graph. Results look wrong.

gremlin> msisdn = g.V('name', '336803134278').next()
==>v[16]
gremlin> msisdn.map
==>{name=336803134278, legacymodificationdate=MSISDN}

I was expecting that legacymodificationdate = 2005051614342 and that type = MSISDN, so for me this result is wrong.

Another query :
gremlin> ia = g.V('name', '386653723').next()  
==>v[4]
gremlin> ia.map
==>{name=386653723, legacymodificationdate=IA}

I was expecting type = IA and no legacymodificationdate for this vertex.

The configuration of the graph in rexster is as below :
        <graph>
            <graph-name>titan</graph-name>
            <graph-type>com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration</graph-type>
            <graph-location>db/titan</graph-location>
            <graph-read-only>false</graph-read-only>
            <properties>
            <storage.backend>cassandra</storage.backend>
            <storage.hostname>127.0.0.1</storage.hostname>
            <storage.port>9160</storage.port>
            <storage.keyspace>titan</storage.keyspace>
            </properties>
            <extensions>
            <allows>
                <allow>tp:gremlin</allow>
            </allows>
            </extensions>
       </graph>

Below is the xml file of the graph :
<?xml version="1.0" ?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns">
    <key id="name" for="node" attr.name="name" attr.type="string"></key>
    <key id="type" for="node" attr.name="type" attr.type="string"></key>
    <key id="type" for="node" attr.name="userlevel" attr.type="string"></key>
    <key id="type" for="node" attr.name="mergestatus" attr.type="string"></key>
    <key id="type" for="node" attr.name="mergeusertype" attr.type="string"></key>
    <key id="type" for="node" attr.name="isnew" attr.type="string"></key>
    <key id="type" for="node" attr.name="legacymodificationdate" attr.type="string"></key>
    <key id="time" for="edge" attr.name="time" attr.type="int"></key>
        <graph id="G" edgedefault="directed">
        <node id="1003">
            <data key="name">386653723</data>
            <data key="type">IA</data>
        </node>
        <node id="1004">
            <data key="name">335747055871</data>
            <data key="type">NDRTC</data>
        </node>
        <node id="1005">
            <data key="name">9rV3jV3mwMnHIRDqqIVsMCErPLGMgYXwVIoRdX1c7RN</data>
            <data key="type">ISE</data>
            <data key="userlevel">2</data>
            <data key="mergestatus">5</data>
            <data key="mergeusertype">0</data>
            <data key="isnew">1</data>
        </node>
        <node id="1006">
            <data key="name">336803134278</data>
            <data key="type">MSISDN</data>
            <data key="legacymodificationdate">2005051614342</data>
        </node>
        <node id="1007">
            <data key="name">CugaC5li5uhgoEucTvmDUYIc7qbJEtg08mNFwHUzwxX</data>
            <data key="type">ISE</data>
            <data key="userlevel">1</data>
            <data key="mergestatus">2</data>
            <data key="mergeusertype">2</data>
            <data key="isnew">1</data>
        </node>
        <edge id="1023" source="1003" target="1004" label="linkedto"></edge>
        <edge id="1024" source="1003" target="1005" label="linkedto"></edge>
        <edge id="1025" source="1005" target="1006" label="linkedto"></edge>
        <edge id="1026" source="1003" target="1007" label="linkedto"></edge>
    </graph>
</graphml>

I am newbie with titan, so maybe I did something wrong ?

I have also tried to remove thedescription of the keys userlevel, mergestatus, mergeusertype, isnew and legacymodificationdate. In this case, the results are correct except that the legacymodificationdate is not displayed.

Regards.
Jean Armel

**Comment by mbroecheler** [comment]
Why do you think those results are wrong?

gremlin> msisdn = g.V('name', '336803134278').next()
==>v[16]
gremlin> msisdn.map
==>{name=336803134278, legacymodificationdate=MSISDN}

When you retrieve a vertex with that name you would expect that vertex to
have that name and not some other id as you said.
It sounds like the xml file might contain data different from what you
expect?

On Tue, Nov 6, 2012 at 3:01 AM, jal06 notifications@github.com wrote:

> Hello,
> 
> I am using titan with rexster and Cassandra :
> - titan 0.1.0
> - rexster 2.1.0
> - cassandra 1.1.5 (1 single node in my VM)
> 
> When using gremlin with the graph of the Gods, everything is working
> corectly (I do the requests described in the Getting started page).
> 
> When I use gremlin with my data, the results of requests look wrong.
> Example : I load a small graph (5 vertex and 4 edges) : you will find
> below the graph in xml format, and its configuration in rexster.xml.The
> main difference I see between the graph of the gods and my graph : in my
> graph, all the vertices do not have the same properties (for example the
> property legacymodificationdate is defined in only 1 vertex). Is it allowed
> that all vertices do not have the same properties ?
> 
> Using gremlin, I set the storage properties of the graph and I load it :
> 
> confcass = new BaseConfiguration();
> confcass.setProperty("storage.backend","cassandra");
> confcass.setProperty("storage.hostname","localhost");
> confcass.setProperty("port",9160);
> confcass.setProperty("storage.keyspace","titan");
> g = TitanFactory.open(confcass);
> 
> g.createKeyIndex('name', Vertex.class)
> g.loadGraphML('../../wshared/data/creds/creds2.xml')
> 
> Then I query some properties of some vertex in the graph. Results look
> wrong.
> 
> gremlin> msisdn = g.V('name', '336803134278').next()
> ==>v[16]
> gremlin> msisdn.map
> ==>{name=336803134278, legacymodificationdate=MSISDN}
> 
> I was expecting that legacymodificationdate = 2005051614342 and that type
> = MSISDN, so for me this result is wrong.
> 
> Another query :
> gremlin> ia = g.V('name', '386653723').next()
> 
> ==>v[4]
> gremlin> ia.map
> ==>{name=386653723, legacymodificationdate=IA}
> 
> I was expecting type = IA and no legacymodificationdate for this vertex.
> 
> The configuration of the graph in rexster is as below :
> 
> titan
> com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration
> db/titan
> false
> 
> cassandra
> 127.0.0.1
> 9160
> titan
> 
> tp:gremlin
> 
> Below is the xml file of the graph :
> <?xml version="1.0" ?>
> 
> 386653723
> IA
> 
> 335747055871
> NDRTC
> 
> 9rV3jV3mwMnHIRDqqIVsMCErPLGMgYXwVIoRdX1c7RN
> ISE
> 2
> 5
> 0
> 1
> 
> 336803134278
> MSISDN
> 2005051614342
> 
> CugaC5li5uhgoEucTvmDUYIc7qbJEtg08mNFwHUzwxX
> ISE
> 1
> 2
> 2
> 1
> 
> I am newbie with titan, so maybe I did something wrong ?
> 
> I have also tried to remove thedescription of the keys userlevel,
> mergestatus, mergeusertype, isnew and legacymodificationdate. In this case,
> the results are correct except that the legacymodificationdate is not
> displayed.
> 
> Regards.
> Jean Armel
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/112.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by jal06** [comment]
Yes,

I hava atached the xml file containing my data.
Please, have a look at the data in the xml file : the result should be
legacymodificationdate = 2005051614342 instead of legacymodificationdate =
MSISDN

2012/11/8 Matthias Broecheler notifications@github.com

> Why do you think those results are wrong?
> 
> gremlin> msisdn = g.V('name', '336803134278').next()
> ==>v[16]
> gremlin> msisdn.map
> ==>{name=336803134278, legacymodificationdate=MSISDN}
> 
> When you retrieve a vertex with that name you would expect that vertex to
> have that name and not some other id as you said.
> It sounds like the xml file might contain data different from what you
> expect?
>

**Comment by mbroecheler** [comment]
Hey Jean,

thank you very much for sending this along. I was able to reproduce your problem. However, its not a Titan issue but an issue in the GraphML reader, filed here: https://github.com/tinkerpop/blueprints/issues/326

**Comment by okram** [comment]
@jal06 Your XML is bugged. Use the following correct header.

```
   <key id="name" for="node" attr.name="name" attr.type="string"></key>
<key id="type" for="node" attr.name="type" attr.type="string"></key>
<key id="userlevel" for="node" attr.name="userlevel" attr.type="string"></key>
<key id="mergestatus" for="node" attr.name="mergestatus" attr.type="string"></key>
<key id="mergeusertype" for="node" attr.name="mergeusertype" attr.type="string"></key>
<key id="isnew" for="node" attr.name="isnew" attr.type="string"></key>
<key id="legacymodificationdate" for="node" attr.name="legacymodificationdate" attr.type="string"></key>

{name=386653723, type=IA}
```

   {name=335747055871, type=NDRTC}
   {userlevel=1, name=CugaC5li5uhgoEucTvmDUYIc7qbJEtg08mNFwHUzwxX, mergeusertype=2, isnew=1, type=ISE,   mergestatus=2}
   {userlevel=2, name=9rV3jV3mwMnHIRDqqIVsMCErPLGMgYXwVIoRdX1c7RN, mergeusertype=0, isnew=1, type=ISE,   mergestatus=5}
   {name=336803134278, legacymodificationdate=2005051614342, type=MSISDN}

**Comment by jal06** [comment]
OK Thanks.

Works fine now.
