### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Path calculations are not enabled

### ISSUE THREAD

**Issue by qianghuang84** [thinkaurelius/titan#1123]
Hi, when I ran these commands

[cloudera@quickstart titan-0.5.3-hadoop2]$ bin/gremlin.sh

```
     \,,,/
     (o o)
```

-----oOOo-(_)-oOOo-----
01:24:44 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
gremlin> g = HadoopFactory.open('conf/hadoop/titan-graphson.properties')
gremlin> g.V.as('x').out('father').out('father').linkIn('grandfather','x')

the last command failed and the output is "Caused by: java.lang.IllegalStateException: Path calculations are not enabled",  I don't know how to set path calculation. If any one knows, please tell me. Thanks in advance.

**Comment by pronix** [comment]
add this settings to your properties file 

```
titan.hadoop.pipeline.track-state=true
titan.hadoop.pipeline.track-paths=true
```
