### ISSUE TITLE
Improved Solr Support

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#1126]
The SolrIndex.java code responsible for providing the SolrCloud interface to Titan currently requires a config set name to match a collection name in SolrCloud.  This requires manual creation of many config sets in ZooKeeper before Titan mixed index commands can be issued.

A new config is not be required for every SolrCloud Collection created by Titan.  The same config set can be reused over and over again if the schema, for example, does not need to be different, which is often the case.

In addition, the SYNC state that is checked for in the  waitForRecoveriesToFinish method of the class was a) never really used and b) is no longer supported in Solr 5.2.1 and causes compile errors.
The SYNC code should be removed, allowing Solr 5.2.1 to be supported (currently the latest version of Solr).
http://mail-archives.apache.org/mod_mbox/lucene-solr-user/201410.mbox/%3CCAEvwVFEvCA=5=g7i2HpEtL=51HedoZksKYN+jYierPwWXpZkuA@mail.gmail.com%3E

A new property called 
       index.search.solr.configset
should be supported in the Titan properties file that allows a user to specify the name of a default SolrCloud config set that is reused repeatedly each time a new mixed index (Collection) is created.  This change will allow a user to upload a single config set manually into SolrCloud, and from then on, every time a mixed index statement is encountered, a new Collection is automatically created in Solr with no more manual interventions required.  The advantage of using a property, is that if the property is missing, the behavior of the Solr interface will be as it is today, allowing a different config set per Collection if that is actually needed.

A pull request will be submitted for this Issue shortly that addresses the new property as well as Solr 5.2.1 support and the removal of SYNC.

**Comment by dalaro** [comment]
The linked PR was recently merged.  I think the merge concludes this issue, so I'm closing it.  Please reopen if I missed something.
