### ISSUE TITLE
incorrect command in using-hbase wiki page

### ISSUE THREAD

**Issue by vadasg** [thinkaurelius/titan#113]
In the wiki page

https://github.com/thinkaurelius/titan/wiki/Using-HBase

the section Tips and Tricks for Managing an HBase Cluster has the following lines:

sudo -u hadoop $HBASE_HOME/bin/hbase-daemon.sh stop regionserver
sudo -u hadoop $HBASE_HOME/bin/hbase-daemon.sh stop regionserver

these should read (note the "start" towards the end of the second line)

sudo -u hadoop $HBASE_HOME/bin/hbase-daemon.sh stop regionserver
sudo -u hadoop $HBASE_HOME/bin/hbase-daemon.sh start regionserver

**Comment by okram** [comment]
done. thanks.
