### ISSUE TITLE
Negative Frame Size w/ Cassandra and Thrift

### ISSUE THREAD

**Issue by mypolopony** [thinkaurelius/titan#1159]
I have a functional Cassandra cluster (2.2) that I am trying to allow Titan (1.0) to use. I know that there have been some issues with Thrift, as newer Cassandra versions have depricated it to some degree. 

After double checking the connection settings, I try to initialize thusly:

`g = TitanFactory.build().set("storage.backend", "cassandrathrift").set("storage.hostname", "IP.ADD.RES.S").set("storage.port","9042").open();`

But am met with this error:

`Caused by: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2080374784)!`

The nodetool reveals that Thrift is listening on the Cassandra machine and attempts to connect to the server from other clients are successful.

**Comment by dalaro** [comment]
@mypolopony it looks like you closed the issue a few hours after creating it.  Did you resolve it?

**Comment by mypolopony** [comment]
There was a confusion over the port assignment, and in particular the fact that I had dockerized Cassandra and Titan separately, as opposed to using the combined set of tools that are packaged in the 1.0 release.
