### ISSUE TITLE
Exception when hosting in rexster-server-2.6.0 not able to load com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration

### ISSUE THREAD

**Issue by antonpious** [thinkaurelius/titan#1167]
Have setup rexster-server-2.6.0 and pointed to a Titan 1.0.0-Hadoop 1 instance that runs on a hbase 2 node cluster backend.

I am able to access the graph using titan gremlin shell as well as able to perform graph functions but rexster server is not able to load the graph.

I have copied the jar from lib of titan to the ext folder titan as instructed in 
http://s3.thinkaurelius.com/docs/titan/current/server.html
Section 7.2.2. Downloading Rexster and Titan separately

Can anyone let me know which jar this file is present under? In the previous version the class
com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration is present under the jar titan-rexster-0.4.4.jar
as discussed under
https://groups.google.com/forum/#!msg/aureliusgraphs/SxMW2ae72-0/YV5AggnBsTwJ

**Comment by antonpious** [comment]
Seems this dependency is indeed missed in the distributable for 1.0.0-Hadoop 1. I took the 0.5.4 version of  titan-rexster-0.5.4.jar and dropped it under titan and this started working
http://search.maven.org/#search%7Cga%7C1%7Cfc%3Acom.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration

**Comment by antonpious** [comment]
Is the titan-rexster-0.5.4.jar the right one to use can it connect to the new version of the graph Titan 1.0.0-Hadoop 1

**Comment by antonpious** [comment]
Just realized that titan-rexster is being replace with Gremlin Server and Titan 1.0.0 Hadoop1 is waiting for the actual release which is currently under incubation.
http://tinkerpop.incubator.apache.org/

**Comment by spmallette** [comment]
Just to be clear, TinkerPop released 3.0.0 months ago.  Titan 1.0 ships with Gremlin Server.

**Comment by santhoshtangudu** [comment]
@antonpious , what should I put under titan folder ?

I couldn't understand your last comment. Can you please explain a bit ?
