### ISSUE TITLE
Where to specify the Zookeeper Quorum when its in standalone mode?

### ISSUE THREAD

**Issue by antonpious** [thinkaurelius/titan#1168]
I have setup Titan 1.0.0-hadoop1 with storage backend as two node hbase cluster. In the titan-hbase.properties I have specified the 
storage.backend=hbase
storage.hostname=192.168.0.195,192.168.0.128

I have setup hbase to use a standalone zookeeper at 192.168.0.195 which means that zookeeper is not running on both the nodes but hbase is configured to use a remote zookeeper ensemble.

Now, I am trying to start the titan graph in Cent OS 7

I go to the titan directory in which both my bin as well as my conf directory are on the same level and issue the command
$ bin/gremlin.sh
and on 
gremlin> g = TitanFactory.open('conf/titan-hbase.properties')

When this happens I am finding that Titan wants to connect to both the Zookeeper nodes and I get the following exception
13:43:03 WARN  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper  - Possibly transient ZooKeeper, quorum=192.168.0.128:2181,192.168.0.195:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid

[INFO] ZooKeeper - Initiating client connection, connectString=192.168.0.128:218                            1,192.168.0.195:2181 sessionTimeout=90000 watcher=catalogtracker-on-hconnection-                            0x5d25e6bb, quorum=192.168.0.128:2181,192.168.0.195:2181, baseZNode=/hbase
[INFO] RecoverableZooKeeper - Process identifier=catalogtracker-on-hconnection-0                            x5d25e6bb connecting to ZooKeeper ensemble=192.168.0.128:2181,192.168.0.195:2181
[INFO] ClientCnxn$SendThread - Opening socket connection to server /192.168.0.12                            8:2181
[WARN] ClientCnxn$SendThread - Session 0x0 for server null, unexpected error, cl                            osing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717                            )
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119)

Since I do not have Zookeeper running on both nodes of hbase, where do I specify the zookeeper nodes separately.

The strange thing is when I now execute the following

from the Titan base directory
I do a cd to bin so the current directory is bin

bin$ bash gremlin.sh
and now create the graph
gremlin> g = TitanFactory.open('../conf/titan-hbase.properties')
note the .. to say that conf directory is on top
I get the correct prompt without any warnings
==>standardtitangraph[hbase:[192.168.0.195, 192.168.0.128]]

The other issue is when invoked from the rexster the command that is called seems to be the one that is causing the warning. 

How do I make sure that the one that is working is the default one to initiate?

**Comment by fengkai9** [comment]
change the storage.hostname=192.168.0.195
when titan connect hbase, it will set hbase.zookeeper.quorum=192.168.0.195

**Comment by ghost** [comment]
storage.hostname is misnamed.  It is actually a list of the zookeeper servers in your environment.  Titan can then find HBase via the Zookeeper.  fengkai9 supplied a correct answer.  Is this issue ready to be closed now ?

**Comment by dalaro** [comment]
graben1437 is correct; `storage.hostname` should be a comma-separated list of the zk ensemble hosts.  I'm not really clear on whether fengkai9 resolved the issue with the change in his commen, but it sounds that way to me, so I'm tentatively closing.  Please reopen if there is still an problem.
