### ISSUE TITLE
Using Titan as main Database

### ISSUE THREAD

**Issue by rock59** [thinkaurelius/titan#1171]
I am using Cassandra for main datastore and Neo4J(commiunity version) for graph processing in a small startup company.
I need to distribute graph data and Neo4J enterprise license is very expensive thus I consider using Titan as the main datastore with Cassandra storage backend.
Is Titan stable and can I trust it as an operational database?

**Comment by okram** [comment]
This is not a issue tracker ticket. Please use the public mailing list for questions.

https://groups.google.com/forum/#!forum/aureliusgraphs
