### ISSUE TITLE
TitanGraphIndex no easy way to determine disabled state

### ISSUE THREAD

**Issue by optimuspaul** [thinkaurelius/titan#1175]
awaitGraphIndexStatus appears to be the only way to determine if an index is in the state you want it to be in. But if I don't know what the state is that doesn't seem like a good way to do it. Also calling awaitGraphIndexStatus seems to take forever. I've disabled an index, which took about 30 secs (why would it ever take that long!?!?). Then later I wanted to check if that index was disabled, keep in mind it is already disabled, that call still took 30 seconds (why!?!?!?!). Is it not just a "look at this property or maybe properties and give me a result".  As a general rant, the operational overhead of some of these simple tasks is ridiculous. If removing an index is a complicated task with many steps that need to be done correctly then automate that for me, these hoops are ridiculous.

**Comment by dalaro** [comment]
Do you want to just read index status at the current instant, blocking as little as possible?  If so, then `awaitGraphIndexStatus` is not the only way to do that, and it's an inappropriate tool for the job.

The state in question is defined for (index, property key) pairs.  So, first retrieve a reference to the index from the management system, then iterate over the property keys (or retrieve a specific one if only a specific key matters), then read its status.  Here's a small code snippet showing the gist of it:

https://github.com/thinkaurelius/titan/blob/1.0.0/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/database/management/GraphIndexStatusWatcher.java#L50-L58

That's actually from the guts of the `awaitGraphIndexStatus` impl, but it's written in terms of methods that are part of the public API.

Hope that helps.
