### ISSUE TITLE
Is there a way for Titan to see updated data without .newTransaction()?

### ISSUE THREAD

**Issue by bgdavidx** [thinkaurelius/titan#1186]
I'm currently using Titan in production, however it seems like for Titan to be able to see data (vertices/edges) added to the graph, a new transaction has to be created. Is there a way for the query to see the new data without having to create a new transaction?

The setup is as follows:

16 Nodes writing to Titan (Cassandra, 16 Nodes)
32 Nodes answering queries (this is where I have to use newTransaction() in order for them to see the new data that the 16 nodes writing have inserted into the graph.)

My configuration is as follows:

```
    conf.setProperty("storage.backend","cassandra")
    conf.setProperty("storage.hostname", Config.CASSANDRA_HOSTS)
    conf.setProperty("storage.cassandra.keyspace", Config.KEYSPACE)
    conf.setProperty("storage.buffer-size", 1024 * 128)
    conf.setProperty("graph.unique-instance-id-suffix", RNG.nextInt(Short.MAX_VALUE + 1))
    conf.setProperty("force-index", "true")
```

**Comment by spmallette** [comment]
Just to be clear, you should not ever need to call `.newTransaction` unless you are doing a "threaded transaction" - one that allows multiple threads to act on the _same_ transaction.  

http://tinkerpop.incubator.apache.org/docs/3.0.2-incubating/#_threaded_transactions
http://s3.thinkaurelius.com/docs/titan/1.0.0/tx.html#multi-thread-tx

You can just issue a `rollback()` to start a fresh transaction to ensure that a fresh read transaction is started.  It's fairly typical to do that.  You can turn off caching as well in this case, but you can obviously expect a performance penalty for doing so: http://s3.thinkaurelius.com/docs/titan/1.0.0/caching.html

In the future, please use the mailing list for questions about Titan.  

https://groups.google.com/forum/#!forum/aureliusgraphs

The issue tracker is for "bugs" and such.
