### ISSUE TITLE
Flatten Documentation

### ISSUE THREAD

**Issue by laxatives** [thinkaurelius/titan#1202]
Could you release a version of the documentation on a single page? Its a bit difficult to navigate as is without a time-consuming exhaustive search. Google site: helps, but returns many false positives. IMO a single page with ctrl+f would also greatly increase feature discovery.

**Comment by Airswoop1** [comment]
@laxatives I use a chrome extension that enables me to search through any github repository's entire wiki: https://chrome.google.com/webstore/detail/github-wiki-search/gdifdhnjmjaidbajhapmbcbnoocoeooc?hl=en

This may be of use for you.

**Comment by spmallette** [comment]
careful....Titan doesn't publish to the wiki anymore though.  All the current documentation is in asciidoc and published to html.

**Comment by dalaro** [comment]
Titan is already capable of generating a one-page manual.  I configured that back when we moved to an AsciiDoc + DocBook toolchain.  It still pops out in `titan-doc/target/docs/single/index.html` during the build process, but it's not uploaded anywhere.

My browser has a mini-stroke when opening it (the markup alone is 1.4 MB), but it's still essentially usable.  It would probably be unpleasant if it started showing up in google search hits intended to hit the Titan manual though, so I'm kind of ambivalent about whether to upload it.

**Comment by spmallette** [comment]
ha - tinkerpop's single page reference docs with images and all seems to come in around 16MB - going to choke the life out these browsers - for realz.

**Comment by ghost** [comment]
@laxatives Did the responses here resolve your question ?  Can this issue be closed now ?

**Comment by spmallette** [comment]
i don't think we should upload (mostly for the @dalaro reasoning) - folks can generate locally if needed.
