### ISSUE TITLE
TitanGraph query provides no means for efficient indexed queries using composite indexes

### ISSUE THREAD

**Issue by steowens** [thinkaurelius/titan#1206]
The only way to query for a vertex using the query() function on TitanGraph is to use the .has() constraint.  The .has() constraint does not leverage indexes.  Which seems to translate to the inefficient gremlin query: 

g.V.has("name","marko")

Why is it not possible to do the java equivalent to the gremlin query so that indexes will be used?: 

g.V("my_key", "abc")

**Comment by spmallette** [comment]
If you've gotten the indices set up properly on 'name' then `g.V().has('name','marko') should properly use the indices.  note that in Titan 1.0, there is no such method signature as`g.V("my_key", "abc")`.  Please use the [mailing list](https://groups.google.com/forum/#!forum/aureliusgraphs) for questions about titan usage - thanks.
