### ISSUE TITLE
How can i change the  storage.port ?

### ISSUE THREAD

**Issue by RockyAi125** [thinkaurelius/titan#1234]
My zookeeper port is not  2181 and my hbase verion is 0.94.
i set the "storage.port", but no use.
I alse set the "storage.hbase.ext.hbase.zookeeper.property.clientPort" parameter , but it seems not support that. 
Titan 's version is 0.4.4.
pls help.

**Comment by ghost** [comment]
Hi Rocky,

Version 0.4.4 is very old.  Is there a reason you cannot upgrade to at least Titan 0.5.4 ?
Anyway, this is the way I specify ports in my titan properties file:

storage.hostname=11.115.323.48:2181

Have you tried this yet ?

**Comment by RockyAi125** [comment]
Hi,graben,
Thank you for your reply.
My hbase version is 0.94, there is some problem using Titan0.5.4 to connect.
But we are considering to upgrade the hbase.

storage.hostname=11.115.323.48:2181
That works!Thanks!
I also tried this parameter ,
storage.hbase-config.hbase.zookeeper.property.clientPort. It works too.

**Comment by ghost** [comment]
Great Rocky.   Glad it is working for you.
Do you think we can now close this Issue/Jira ?
