### ISSUE TITLE
Tinkerpop version: Gremlin-Server HTTP Basic Auth

### ISSUE THREAD

**Issue by tspecht** [thinkaurelius/titan#1235]
Hi everyone,

I want to use gremlin-server together with HTTP Basic Auth. This became available in version 3.0.1-incubating of Tinkerpop as far as I can see. Can you tell me which version is by default bundled with Titan, and if its below that one, how I could upgrade the gremlin-server version?

**Comment by spmallette** [comment]
Titan 1.0.0 uses TinkerPop 3.0.1-incubating:

https://github.com/thinkaurelius/titan/blob/1.0.0/pom.xml#L62

In the future please use the mailing list for questions on usage - https://groups.google.com/forum/#!forum/aureliusgraphs
