### ISSUE TITLE
Titan Guava Version Discussion (and StopWatch exceptions)

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#1236]
Opening this issue to capture an ongoing discussion around the Guava version and StopWatch exceptions that are occurring with Titan 1.1.0/TP3 when using HBase 1.1.x on Hadoop 2.7.1.

The conversation started in a pull request #1216  but was moved here as more appropriate.
(https://github.com/thinkaurelius/titan/pull/1216)

The current version of Guava in Titan is 18.0.   Even the latest versions of HBase are still using version 12.0.  (BTW, a JIRA was opened against HBase to fix this, but we should not hold our breath on when it gets done).  The way StopWatch is constructed changed, which can cause the following problem:

Caused by: java.lang.IllegalAccessError: tried to access method  com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator  at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:596) at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:580) at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:559)

The problem occurred while following the bulk loading steps in Chapter 32 of the Titan 1.0 documentation.

The problem was produced in two separate environments simultaneously.  One environment was an IBM Open Platform environment running HBase 1.1.1 and Hadoop 2.7.1 installed with Ambari and the other was a HDP 2.3.0.0-2557 cluster installed with Ambari.  In both cases when the problem was reproduced, Spark was running as a stand alone cluster on the same nodes used by hdfs and hbase.
In other words, Spark was not managed by Yarn in the initial tests.

It would seem this is classpath related, but there are other factors involved too, such as, perhaps, timing.

The StopWatch exception in my tests was intermittent.
The 
graph.compute(SparkGraphComputer).program(blvp).submit().get()
line in Chapter 32 could be issued one moment and the exception would occur, and could be issued a second time (same Gremlin shell, same classpath, same everything) and the problem would not occur and the graph would be loaded.  This intermittent pattern was repeatable, if not precisely predictable.

In tests yesterday, I configured Spark with a specific classpath (rather than just pointing it to a directory of jars) and was unable to get the Stop Watch exception to occur after 10 tries.  I also varied the number of Spark workers in the stand alone cluster from 1 to 2, including 1 remote worker, with no impact on the results.  I will post the config I used (which worked).  

I do not have a specific configuration right now that consistently reproduces the exception.

**Comment by ghost** [comment]
Here are details for what appears to be a "working" environment (i.e. I can't get the StopWatch exception to happen - although it happened in this same cluster with different Titan versions, classpaths etc. in the past)

Spark is configured across 3 nodes running in standalone mode.
The master and 1 worker are running on node 2.  1 worker is on node 3.  1 worker is on node 4.
The Spark console shows all of the workers correctly registered, etc.

HDP 2.3.0 (as mentioned above) is running on a 5 node cluster:
node 1 runs just the ambari server
nodes 2-5 run hdfs, hbase, zoo, etc.
Spark is not controlled by Ambari/Yarn on this particular cluster.

The current version (as of yesterday) titan11 is used - with only an adjustment to the plugins.txt file to automatically install Spark and Giraph (although only the Spark one is needed).  See pull request https://github.com/thinkaurelius/titan/pull/1230

Titan was built using:
mvn clean install -DskipTests=true -Dgpg.skip=true -Paurelius-release

The resulting titan-1.1.0-SNAPSHOT-hadoop2.zip from the build is copied into a directory named "junk" directly underneath the titan build (level in the directory tree with titan-all, etc).  The zip is unzipped.  The titan-hadoop.properties in ./junk/titan-1.1.0-SNAPSHOT-hadoop2/conf is edited to connect with the zookeeper cluster and to configure the titan table name in hbase.  The hadoop-load.properties file is edited to point to the spark master rather than "local":  spark://machine.name.here.com:7077

The Spark cluster is stopped.  A spark-env.sh file is created under ./spark-1.5.1/conf and a specific classpath is configured for bulk loading with Titan:

TITANLIB=/home/graphie/titan1.1.0.master/titan/junk/titan-1.1.0-SNAPSHOT-hadoop2/lib
SPARK_CLASSPATH=$TITANLIB/jersey-server-1.9.jar:$TITANLIB/hbase-protocol-0.98.2-hadoop2.jar:$TITANLIB/titan-core-1.1.0-SNAPSHOT.jar:$TITANLIB/guava-18.0.jar:$TITANLIB/gremlin-core-3.1.0-incubating.jar:$TITANLIB/hadoop-gremlin-3.1.0-incubating.jar:$TITANLIB/gremlin-shaded-3.1.0-incubating.jar:$TITANLIB/javatuples-1.2.jar:$TITANLIB/titan-hbase-1.1.0-SNAPSHOT.jar:$TITANLIB/hbase-client-0.98.2-hadoop2.jar:$TITANLIB/hbase-common-0.98.2-hadoop2.jar:$TITANLIB/htrace-core-2.04.jar:$TITANLIB/reflections-0.9.9-RC1.jar:$TITANLIB/hppc-0.7.1.jar:$TITANLIB/high-scale-lib-1.1.2.jar
HADOOP_CONF_DIR=/usr/hdp/2.3.0.0-2557/hadoop/conf

The Spark master and slaves are restarted and the logs checked to verify the classpath.  NOTE that Spark claims to APPEND SPARK_CLASSPATH - but it appears to PREPEND it to the classpath.

Next I export HADOOP_GREMLIN_LIBS:
HADOOP_GREMLIN_LIBS is set to: /home/graphie/titan1.1.0.master/titan/junk/titan-1.1.0-SNAPSHOT-hadoop2/lib

Next I use hbase shell to verify that the "titan" table doesn't exist, and if it does, I disable and drop it.

Next I start gremlin.sh:
Change directories to the ./junk/titan-1.1.0-SNAPSHOT-hadoop2 directory and issue the command:
bin/gremlin.sh

Then I start pasting the commands from Chapter 32 of the Titan 1.0 documentation into the gremlin shell - making changes for the fact that the example shows Cassandra and I am using HBase:

gremlin> :load data/grateful-dead-titan-schema.groovy
==>true
==>true
gremlin> graph = TitanFactory.open('conf/titan-hbase.properties')
==>standardtitangraph[hbase:[10.124.234.93:2181]]
gremlin> defineGratefulDeadSchema(graph)
==>null
gremlin> graph.close()
==>null
gremlin> hdfs.copyFromLocal('data/grateful-dead.kryo','data/grateful-dead.kryo')
==>null
gremlin> graph = GraphFactory.open('./conf/hadoop-graph/hadoop-load.properties')
==>hadoopgraph[gryoinputformat->nulloutputformat]
gremlin> blvp = BulkLoaderVertexProgram.build().writeGraph('conf/titan-hbase.properties').create(graph)
==>BulkLoaderVertexProgram[bulkLoader=IncrementalBulkLoader,vertexIdProperty=bulkLoader.vertex.id,userSuppliedIds=false,keepOriginalIds=true,batchSize=0]
gremlin> graph.compute(SparkGraphComputer).program(blvp).submit().get()
11:56:31 WARN  org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer  - class org.apache.hadoop.mapreduce.lib.output.NullOutputFormat does not implement PersistResultGraphAware and thus, persistence options are unknown -- assuming all options are possible
==>result[hadoopgraph[gryoinputformat->nulloutputformat],memory[size:0]]
gremlin> g=graph.traversal()
==>graphtraversalsource[hadoopgraph[gryoinputformat->nulloutputformat], standard]
gremlin> g.V().count()
==>808

During loading, the Spark console indicates that the loading job is running and using 24 cores - which is the correct number given the number of workers and the # cores available to the VMs in this configuration.  Loading doesn't seem to be any faster with fewer or more cores...but the Spark console changes.

I repeatedly issue the 
graph.compute(SparkGraphComputer).program(blvp).submit().get()
command, which is when the StopWatch error has occurred in the past, but each load appears to complete successfully at the moment.

That's most of the detail.  If I get an environment where the StopWatch problem "re-appears" (I think timing has something to do with it) then I will add that information.

**Comment by ghost** [comment]
Linking in another "Issue/Feature" on this topic from Dan.
https://github.com/thinkaurelius/titan/issues/1139

**Comment by ghost** [comment]
I was able to solve my Stopwatch issues without more shading.  I moved the StopWatch file in the build from the hbase section to the titan core section, bumped the guava version of Titan down to 16 (correct move...no reason to be at 18 right now - that is more advanced that Spark, HBase, Cassandra or anything else).  I am going to close this issue because I think I know what to do to solve the Stopwatch issue and have it in my forked copy.  Let me know if anyone ever reads this and is interested in a pull request that matches what I did.

**Comment by majic31** [comment]
Execuse me, I try to follow your step to "mvn install", but after installing, titan-dist/titan-dist-hadoop-2/target is empty, and I can't get titan-1.1.0-SNAPSHOT-hadoop2.zip(titan-1.1.0-SNAPSHOT-hadoop1.zip is ok)
1)Titan version is 1.0, which is fetched from git,
2)mvn command is: mvn clean install -DskipTests=true -Dgpg.skip=true -Phadoop2 -Paurelius-release
Does some configuration should be added when run mvn?

Best regards
