### ISSUE TITLE
how to bulkload data to titan? 

### ISSUE THREAD

**Issue by wangweislk** [thinkaurelius/titan#1239]
Titan officials only configuration options and didn't see the specific Bulkload case, may I ask how to operate specific

**Comment by ghost** [comment]
Have you looked at Chapter 32 of the most recent Titan documentation ?
http://s3.thinkaurelius.com/docs/titan/1.0.0/titan-hadoop-tp3.html
If you look at those instructions, it shows how to use the BulkLoaderVertexProgram
which uses Spark to load data into a Titan graph.

**Comment by okram** [comment]
The Titan issue tracker is not a question and answer forum. Please use the mailing list for for questions.
