### ISSUE TITLE
Store information about Titan version in backend

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#124]
This makes it easier to upgrade and reason about the state of the database.

**Comment by spmallette** [comment]
Could this be implemented through this issue in blueprints in some way?  Some manner of "system" property maybe?

https://github.com/tinkerpop/blueprints/issues/237

just something to consider....

**Comment by mbroecheler** [comment]
Didn't know about that issue. Could be. But I think there needs to be
something native in Titan which i can refer to when writing upgrade scripts
and the like - simply for error checking purposes.

On Fri, Dec 21, 2012 at 4:37 AM, stephen mallette
notifications@github.comwrote:

> Could this be implemented through this issue in blueprints in some way?
> Some manner of "system" property maybe?
> 
> tinkerpop/blueprints#237https://github.com/tinkerpop/blueprints/issues/237
> 
> just something to consider....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/124#issuecomment-11611425.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by xedin** [comment]
@mbroecheler Can I take this one?

**Comment by xedin** [comment]
@mbroecheler Code is pushed to titan/issue_124 branch and ready for review, I have added getLastSeenTitanVersion, setTitanVersionToLatest methods in StoreManager, so it would be convenient to do upgrades by checking latest version - doing required migration - reseting that version to the latest.
