### ISSUE TITLE
How to retrieve already built graph from Cassandra using Gremlin or Java for GraphOfTheGodsFactory.java?

### ISSUE THREAD

**Issue by laxpatil** [thinkaurelius/titan#1245]
I have a query regarding the code GraphOfTheGodsFactory.java. The code creates a graph and stores and commits in Cassandra. 

How to retrieve the already built graph in Cassandra later either from Java or Gremlin? How does the code look like? I searched on whole Titan website no where it is mentioned how to retrieve already stored database.

**Comment by okram** [comment]
This is an issue tracker, not a support forum. Please use the mailing list.
