### ISSUE TITLE
Index and storage inconsistencies

### ISSUE THREAD

**Issue by esatsuta** [thinkaurelius/titan#1256]
When removing a bunch of vertices using hadoop, and something goes wrong (storage exception, unexpected termination, etc), it's possible that standard index will become inconsistent with existing vertices, e.g. vertex already removed, while it's s till present in the index.
As a result, querying such index will return 'empty' vertex: {label: "_default", ID: 33146368} which could not be used nor removed from the index.

How to remove such index entry? Or rebuild the index so it contains only valid entries?

**Comment by spmallette** [comment]
The issue tracker isn't for usage questions - please ask such questions on the mailing list:

https://groups.google.com/forum/#!forum/aureliusgraphs

In the meantime, you might want to read about re-indexing procedures here:

http://s3.thinkaurelius.com/docs/titan/1.0.0/index-admin.html
