### ISSUE TITLE
Add LOCAL_ONE as Cassandra consistency level option.

### ISSUE THREAD

**Issue by twilmes** [thinkaurelius/titan#1257]
The possible Cassandra consistency levels are missing LOCAL_ONE as an option.

https://github.com/thinkaurelius/titan/blob/titan10/titan-cassandra/src/main/java/com/thinkaurelius/titan/diskstorage/cassandra/CLevel.java

**Comment by ghost** [comment]
Pull request 1258 submitted to fix this.

**Comment by spmallette** [comment]
#1258 merged
