### ISSUE TITLE
Gremlin Server and Cassandra

### ISSUE THREAD

**Issue by mvbaffa** [thinkaurelius/titan#1259]
I am starting to work with Titan and I am using cassandra as backend store.

When I start titan.sh cassandra and elasticsearch were started but the gremlin server did not.

I was looking at titan.sh and I have seen that it start gremlin server with conf/gremlin-server/gremlin-server.yaml. The problem is that the gremlin-server.yaml is configured as this:
graphs: {
  graph: conf/gremlin-server/titan-berkeleyje-server.properties}

Using BerkeleyDb. I have not seen the cassandra.yaml for Gremlin Server.

How can I configure the it for Cassandra ?

Thanks

**Comment by Astn** [comment]
Are you looking for this?
https://github.com/thinkaurelius/titan/blob/titan11/titan-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml

**Comment by spmallette** [comment]
Please post usage questions on the mailing list:

https://groups.google.com/d/msg/aureliusgraphs/fQABVr6wgxY/MyVe2V12CQAJ

**Comment by mvbaffa** [comment]
Thanks Austin
