### ISSUE TITLE
TitanDB and Spark

### ISSUE THREAD

**Issue by mvbaffa** [thinkaurelius/titan#1260]
Hi,

What is reallly the interface between Spark and TitanDB ?

I could not find any reference to spark in TitanDB. How can they fit together specially the ML library of Spark.

Thanks

**Comment by spmallette** [comment]
Usage questions should be posted to the mailing list - which I think you already did:

https://groups.google.com/d/msg/aureliusgraphs/fQABVr6wgxY/MyVe2V12CQAJ

I'm not sure what else you are looking for in terms of the "interface between Spark and Titan.  TinkerPop provides a general purpose query language in Gremlin for traversing large scale graphs over spark.  You don't directly use Titan with GraphX or anything like that.
