### ISSUE TITLE
can we export graph from Spark GraphX to titan Database??

### ISSUE THREAD

**Issue by javajpn** [thinkaurelius/titan#1262]
I am checking the feasibility of Exporting graph from Spark GraphX to a file and reading in the Titan graph database.

**_Used below code to construct graph in Spark GraphX and writing graph to a json file :**_                     

```
**val conf = new SparkConf()
val sc = new SparkContext(conf.setAppName("========= GraphXTest ======="))

// Create an RDD for the vertices
val users: RDD[(VertexId, (String, String))] = sc.parallelize(Array(
                                                (3L, ("rxin", "student")),
                                                (7L, ("jgonzal", "postdoc")),
                                                (5L, ("franklin", "prof"))
                                                ))
  // Create an RDD for edges                                                
 val relationships: RDD[Edge[String]] = sc.parallelize(Array(
                                            Edge(3L, 7L, "collab"),
                                            Edge(5L, 3L, "advisor")
                                            ))
 // Build the initial Graph                                         
 val graph = Graph(users, relationships)
 graph.vertices.saveAsTextFile("D://Spark-GraphX-vertices.json")**
```

While running the above code it creates folder with the name that I mentioned D://Spark-GraphX-vertices.json and few other files inside that. But those files does not contain any data.

is it possible to export Graph from Spark GraphX to Titan Database ??

**Comment by technotrance** [comment]
Chech the repositories i contribute to for the graph otherwise you need to star a relevant programme

**Comment by spmallette** [comment]
The issue tracker is not for usage questions.  Please post your question to the mailing list:

https://groups.google.com/forum/#!forum/aureliusgraphs
