### ISSUE TITLE
Self looping -- in edge count off after transaction committed. (but good when out edges are counted)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#127]
gremlin> g = TitanFactory.open('/tmp/blah2')
==>titangraph[local:/tmp/blah2]
gremlin> v = g.addVertex()
==>v[4]
gremlin> g.addEdge(v,v,'self')
==>e[11:4:36028797018963982][4-self->4]
gremlin> v.inE.count()
==>1
gremlin> v.outE.count()
==>1
gremlin> g.stopTransaction(SUCCESS)
==>null
gremlin> v = g.getVertex(4)
==>v[4]
gremlin> v.inE.count()
==>0
gremlin> v.outE.count()
==>1
gremlin> v.inE.count() 
==>1
//////////// THE PROBLEM IS EVEN MORE NEFARIOUS IF YOU TRY AND GRAB THE ADJACENT VERTEX
gremlin> g.stopTransaction(SUCCESS)
==>null
gremlin> v = g.getVertex(4)  
==>v[4]
gremlin> v.in.count()
==>0
gremlin> v.out.count()
==>1
gremlin> v.in.count() 
==>0
gremlin> v.inE.count()
==>0

However, note that this seems to only happen with 'self loops'. See the code fragment below:

gremlin> g = TitanFactory.open('/tmp/blah3')
==>titangraph[local:/tmp/blah3]
gremlin> v = g.addVertex()
==>v[4]
gremlin> u = g.addVertex()
==>v[8]
gremlin> g.addEdge(u,v,'knows')
==>e[13:8:36028797018963982][8-knows->4]
gremlin> u.outE.count()
==>1
gremlin> u.inE.count()
==>0
gremlin> v.inE.count()
==>1
gremlin> v.outE.count()
==>0
gremlin> g.stopTransaction(SUCCESS)
==>null
gremlin> u = g.getVertex(8)  
==>v[8]
gremlin> v = g.getVertex(4)
==>v[4]
gremlin> v.inE.count()
==>1
gremlin> u.inE.count()
==>0
gremlin> u.outE.count()
==>1
gremlin> v.outE.count()
==>0

**Comment by okram** [comment]
It might be good to also have a transaction test in Blueprints transactional test suite that validates this behavior.

**Comment by mbroecheler** [comment]
I will fix the bug. Can you add the test to blueprints?

**Comment by okram** [comment]
Done. A validating test has been added to Blueprints TransactionalGraphTestSuite.

Pushed to Blueprints 2.3.0-SNAPSHOT and deployed to SonaType repo.

```
https://github.com/tinkerpop/blueprints/blob/master/blueprints-test/src/main/java/com/tinkerpop/blueprints/TransactionalGraphTestSuite.java#L81
```

Marko.
