### ISSUE TITLE
Pin guava version to 18

### ISSUE THREAD

**Issue by sayrer** [thinkaurelius/titan#1278]
The guava dependency in titan-core/pom.xml should be pinned to version 18. Not doing this can cause problems when users have other versions of guava available.

**Comment by fcalderonnearsoft** [comment]
Hi @sayrer I just commit that change. Cheers

https://github.com/thinkaurelius/titan/pull/1282

**Comment by spmallette** [comment]
See  #1139 - this will be solved with shading.
