### ISSUE TITLE
Add support fo Cassandra 1.2.0

### ISSUE THREAD

**Issue by devsprint** [thinkaurelius/titan#128]
Hi,

a new improved version of Cassandra 1.2.0 is available. I have tested to see if there if it can be used as embedded or just as a storage. Both of the tests failed do to changes in cassandra configuration file (cassandra.yaml) and thrift interface (I guess).

Can this request be added to next release?

Thanks,
Gabi

**Comment by mbroecheler** [comment]
Thanks, we will have a look at this.

**Comment by xedin** [comment]
Cassandra 1.2.0 is merged into master. Closing this issue.
