### ISSUE TITLE
Error on executing scripts on remote server using Gremlin shell

### ISSUE THREAD

**Issue by anindya-albeado** [thinkaurelius/titan#1289]
I am working on Mac OS X el capitan. I am using the titan-1.0.0-hadoop1 distribution of the Titan server.
I have started the Titan server using titan.sh start but using the HttpChannelizer instead of WebsocketChannelizer.

I have created a graph programmatically and I can enumerate the vertices and edges programmatically as well.

When I connect to the server from Gremlin console using :remote command the connect goes through successfully.

But even executing something as simple as :> 1+1 returns an error saying "Host did not respond in a timely fashion - check the server status and submit again.
Display stack trace? [yN] n"

Where am I going wrong ? Thanks in advance.

**Comment by spmallette** [comment]
`:remote` command does not work over REST (i.e. `HttpChannelizer`).  convert back to `WebSocketsChannelizer` and it should work.

in the future please use the mailing list for these kinds of "usage" questions:

https://groups.google.com/forum/#!forum/aureliusgraphs
