### ISSUE TITLE
Vizuealization for Titan v.1.x

### ISSUE THREAD

**Issue by martinstepanov1** [thinkaurelius/titan#1301]
What are prefered ways to visualize titan graph for administration purposes in version 1.0 and newer? Rexter seems to be no longer part of titan distribution.

**Comment by xmen4u** [comment]
Great question! would love to know as well.

**Comment by boliza** [comment]
see doc in  tinkerpop http://tinkerpop.apache.org/docs/3.1.2-SNAPSHOT/reference/#gremlin-plugins
just see the topic Gephi Plugin

**Comment by spmallette** [comment]
As @boliza mentioned we would recommend the gephi plugin. Titan 1.0.x is bound to TinkerPop 3.0.x so the instructions to follow would be here: http://tinkerpop.apache.org/docs/3.0.2-incubating/#gephi-plugin

Also, in the future, please us the mailing list for usage questions: https://groups.google.com/forum/#!forum/aureliusgraphs

**Comment by Rahamathulla** [comment]
hi

we have been using Titan 0.5 version in our project. Whats the way to visualize the graph data. Please help.
