### ISSUE TITLE
how to batch loading in titan 1.0.0

### ISSUE THREAD

**Issue by longhaidadi** [thinkaurelius/titan#1307]
hi, in titan 1.0.0 Api. titanGraph does not implement form TransactionalGraph in blueprints package , I not know how to use batchGraph APi.  so

**Comment by spmallette** [comment]
Titan 1.0 supports TinkerPop 3.x and `BatchGraph` isn't supported in TinkerPop 3.x for bulk loading. you bulk load through BLVP in TinkerPop 3.x:

http://s3.thinkaurelius.com/docs/titan/1.0.0/titan-hadoop-tp3.html
https://github.com/dkuppitz/openflights

In the future, please use the mailing list for "usage questions": https://groups.google.com/forum/#!forum/aureliusgraphs thanks
