### ISSUE TITLE
Load Data into titanDB using Spark

### ISSUE THREAD

**Issue by jason1607** [thinkaurelius/titan#1314]
I want to load data into titanDB using Spark. I searched about it, all i understand is we can traverse graph using SparkGraphComputer but it read the data from the graph but i want to do the opposite of it i.e. i want to write or load data into graph using Spark

**Comment by spmallette** [comment]
You should be looking at the various BLVP (BulkLoaderVertexProgram) examples out there:

https://github.com/dkuppitz/openflights
http://s3.thinkaurelius.com/docs/titan/1.0.0/titan-hadoop-tp3.html
https://groups.google.com/forum/#!msg/gremlin-users/AetuGcLiBxo/KW966WAyAQAJ

In the future, please use the titan mailing list for "usage" questions:

https://groups.google.com/forum/#!forum/aureliusgraphs
