### ISSUE TITLE
README has redirect loop to titan homepage

### ISSUE THREAD

**Issue by mikebrules** [thinkaurelius/titan#1316]
Just so you know, the link to the homepage on the README is a redirect loop for

http://titan.thinkaurelius.com/

Thanks

**Comment by matthiasg** [comment]
still happening sadly .. just wanted to read up on titan .. but i am not sure whether a project that doesnt fix a simple thing like this for 4 days is still active. is titan reliable ? are there enough people in the community behind it ?

update:typo

**Comment by joshsh** [comment]
Yep, I'm concerned about exactly that perception.  I don't know what the holdup is, but this is definitely on the radar for fixing.

**Comment by spmallette** [comment]
we're aware of the issue and as of friday, someone was looking into it. sorta surprised that it is still a problem as of this morning. Note that the docs are still available via direct link:

http://s3.thinkaurelius.com/docs/titan/1.0.0/

**Comment by spmallette** [comment]
The DNS issue appears to have been resolved sometime yesterday:

http://titan.thinkaurelius.com/
