### ISSUE TITLE
How to get vertex from vertex property

### ISSUE THREAD

**Issue by alexingcool** [thinkaurelius/titan#1317]
SQL exists primary key, so I want to keep some property unique in titan. But I get a problem, how can I get the vertex from graph, using codes below?
graph.traversal().V().has("plazaid", Long.valueOf(replaceNullAsZero(items[1]))).next()
if it not exists, I have to catch NoSuchElementException. if it exists, use vertex id to get the vertex and add multi edges.
hope some body give me a better way

**Comment by dkuppitz** [comment]
You can use `tryNext().orElse(...)`. See: http://tinkerpop.apache.org/javadocs/3.0.1-incubating/full/org/apache/tinkerpop/gremlin/process/traversal/Traversal.html#tryNext--

Next time please use the [mailing list](https://groups.google.com/forum/#!forum/gremlin-users) for questions.
