### ISSUE TITLE
Method "awaitGraphIndexStatus" does not exist, but is mentioned in documentation 

### ISSUE THREAD

**Issue by joachimbutz** [thinkaurelius/titan#1324]
I think, this is an issue in documentation - in the source code example in http://s3.thinkaurelius.com/docs/titan/1.0.0/indexes.html#index-mixed the method awaitGraphIndexStatus is used. But the class TitanManagement does not have this method anymore.

**Comment by dkuppitz** [comment]
`awaitGraphIndexStatus`  is a `ManagementSystem` method.

See: http://titan.thinkaurelius.com/javadoc/current/com/thinkaurelius/titan/graphdb/database/management/ManagementSystem.html#awaitGraphIndexStatus-com.thinkaurelius.titan.core.TitanGraph-java.lang.String-

The linked example is totally fine. The only thing that seems to confuse people is that you need to do an explicit cast when you're writing Java code:

```
ManagementSystem mgmt = (ManagementSystem) graph.openManagement();
```
