### ISSUE TITLE
GeoshapeTest->testGeoJsonSerialization() line 225

### ISSUE THREAD

**Issue by gabrielcc2** [thinkaurelius/titan#1326]
Hi,

I was trying to build the project, at it's current state, with all tests, and I got an error in the titan-test project, in the GeoshapeTest->testGeoJsonSerialization(), line 225, saying that the result is a Box, and it's not equal to the Polygon passed as string.

Not being too familiar with the code, I don't know if it's a config error on my side. In any case, I changed "Polygon" to "Box" and the test passed so I could move on the the build. 

I hope that pointing this out can be helpful.

Best,

Gabriel.

**Comment by pluradj** [comment]
This is already fixed on the `titan11` branch. If you're building from source, you should go with that branch.

https://github.com/thinkaurelius/titan/commit/5fd9001d34ddb7b97660e5bf02712f3b8a97d150

**Comment by gabrielcc2** [comment]
Good to know. Thanks :+1:

**Comment by technotrance** [comment]
Do you have a micro emmitting array for the uhf adaptor programme in the module for test
