### ISSUE TITLE
Titan project is dead?

### ISSUE THREAD

**Issue by xdev-developer** [thinkaurelius/titan#1328]
Last repository update is 7 months ago, so reasonable question - project is dead?

**Comment by spmallette** [comment]
Developing is happening on titan11 branch not master: 

https://github.com/thinkaurelius/titan/tree/titan11

and there is some effort to get titan working on TinkerPop 3.2.0:

https://github.com/thinkaurelius/titan/pull/1312

development has slowed, but not "dead". Please use the mailing list for these kinds of question in the future:

https://groups.google.com/forum/#!forum/aureliusgraphs

**Comment by xdev-developer** [comment]
Got it, thanks! and sorry...

**Comment by pluradj** [comment]
How about making `titan11` the default branch in GitHub instead of `titan10`?

**Comment by spmallette** [comment]
yeah - i don't see why we couldn't do that. i'll double check about that

**Comment by manigandham** [comment]
@xdev-developer

TitanDB is retired, there is a new project called **JanusGraph** which is now part of the Linux foundation. It starts with the foundations of TitanDB and has more interest and backing then before.

http://janusgraph.org/

https://opensource.googleblog.com/2017/01/janusgraph-connects-past-and-future-of-titan.html
