### ISSUE TITLE
Running Titan on Hadoop 2 and using SparkGraphComputer

### ISSUE THREAD

**Issue by zachkirsch** [thinkaurelius/titan#1329]
Hello,

I have been trying to get this to work for a few days, and I'm submitting this as a last resort.

I currently have a functioning cluster that has Spark 1.6.1, Hadoop 2.4, and YARN installed. (It was deployed via Microsoft Azure).

My goal set spark.master to be yarn-client, and successfully execute queries through the gremlin shell. For example, I would like the following to work:

(1) Download Titan
(2) Change conf/hadoop-graph/hadoop-script.properties so that spark.master=yarn-client
(3) Run bin/gremlin.sh
(4) Execute these commands in the Gremlin console

```
graph = GraphFactory.open('conf/hadoop-graph/hadoop-script.properties')
g = graph.traversal(computer(SparkGraphComputer))
g.V().count()
```

Unfortunately, it does not work. I get the following exception.

```
java.lang.NoSuchMethodError:org.apache.hadoop.conf.Configuration.addDeprecations([Lorg/apache/hadoop/conf/Configuration$DeprecationDelta;)V
java.lang.IllegalStateException: java.lang.NoSuchMethodError:org.apache.hadoop.conf.Configuration.addDeprecations([Lorg/apache/hadoop/conf/Configuration$DeprecationDelta;)V
```

I believe this might be due to versioning issues between titan/gremlin/hadoop. Is there a mistake that I am making in these steps? If not, is there a stable branch that is able to support Hadoop 2?

I would appreciate any help. I can provide any more information that you need.

**Comment by spmallette** [comment]
This question is being handled on the mailing list: 

https://groups.google.com/d/msg/aureliusgraphs/06biFFbS2xc/blNk51pABQAJ

**Comment by technotrance** [comment]
If you agree not to allow third party sharing or distrobutioned to then I will allow a propper access download copy of the entire programme where you can merge your file into and use it as a independant system it will rerectify any damaged or evolving programmes by natural adaption mail back
