### ISSUE TITLE
Local Server Mode with Cassandra

### ISSUE THREAD

**Issue by tuterbatuhan** [thinkaurelius/titan#1331]
Hello, I'm really new with Cassandra and Titan. In chapter 15 of the documentation, to run a local server node with Cassandra there says 

> Download Cassandra, unpack it, and set filesystem paths in conf/cassandra.yaml and conf/log4j-server.properties

The problem is;
In all versions of Cassandra that I downloaded, there exists no cassandra.yaml or log4j-server.properties file inside the conf folder of it. Also, I could not understand what does it mean to "set filesystem path".

Excuse me in advance if I'm being silly.

**Comment by spmallette** [comment]
Please use the mailing list to ask usage questions:

https://groups.google.com/forum/#!forum/aureliusgraphs

As a for a quick answer to your question, i'm not sure why you don't see `cassandra.yaml`. That file should be present in `conf/`.  When you do find it, setting the file system path i assume refers to where you want your data files, log files, etc. to be located on your local file system.
