### ISSUE TITLE
titan remove vertex can not work properly

### ISSUE THREAD

**Issue by zyoo** [thinkaurelius/titan#1333]
Titan version: 0.5.4
action: remove vertex
action operation in gremlin:
g = TitanFacotory.open("titan-hbase-es.properties")
1, id = g.V.has("key", "xxx").iterator().next().id
2, g.v(id).remove()
3, g.commit()
4, g.v(id)
5, g.v(id).label

after the remove operation(1-3), exectue operation(4, 5),I still got the vertex and the vertex's label is "_default".
this is confused. how can I remove the vertex thoroughly. help!!!

**Comment by zyoo** [comment]
I think the problem is existing in the titan 1.0 too.

**Comment by zyoo** [comment]
btw, the remove vertex isRemoved() operation return false

**Comment by zyoo** [comment]
## 1. unset storage.batch-loading with default value: false

conf = new BaseConfiguration();
conf.setProperty("storage.backend", "inmemory")
g = TitanFactory.open(conf)
mgnt = g.getManagementSystem()
mgnt.makeVertexLabel('person').make()
mgnt.makePropertyKey('key').dataType(String.class).make()
mgnt.commit()

person = g.addVertex('person')
person.setProperty('key', '123456')
g.commit()

g.V.has("key", '123456').iterator().next().id
==>256
g.v(256).remove()
==>null
g.commit()
==>null

g.v(256)
==>null

## 2. set storage.batch-loading to true

conf = new BaseConfiguration();
conf.setProperty("storage.backend", "inmemory")
**conf.setProperty("storage.batch-loading", true)**
g = TitanFactory.open(conf)

mgnt = g.getManagementSystem()
mgnt.makeVertexLabel('person').make()
mgnt.makePropertyKey('key').dataType(String.class).make()
mgnt.commit()

person = g.addVertex('person')
person.setProperty('key', '123456')
g.commit()

g.V.has("key", '123456').iterator().next().id
==>256
g.v(256).remove()
==>null
g.commit()
==>null

**g.v(256)
==>v[256]
g.v(256).label
==>_default
g.v(256).isRemoved()
==>false**

**Comment by zyoo** [comment]
@spmallette

**Comment by spmallette** [comment]
I'm not sure what this is exactly but definitely looks like a bug of some sort. Using cassandra on the titan11 branch:

```
gremlin> conf = new BaseConfiguration();
==>org.apache.commons.configuration.BaseConfiguration@4cc65c2
gremlin> conf.setProperty("storage.backend", "cassandra")
==>null
gremlin> conf.setProperty("storage.batch-loading", true)
==>null
gremlin> graph = TitanFactory.open(conf)
==>standardtitangraph[cassandra:[127.0.0.1]]
gremlin> person = graph.addVertex(label, 'person','k','123456')
==>v[4248]
gremlin> graph.tx().commit()
==>null
gremlin> g = graph.traversal();
==>graphtraversalsource[standardtitangraph[cassandra:[127.0.0.1]], standard]
gremlin> g.V().has("k", '123456').iterator().next().id()
==>4248
gremlin> g.V().has("k", '123456').drop()
gremlin> g.V().has("k", '123456')
gremlin> graph.vertices(4248)
gremlin> g.tx().commit()
==>null
gremlin> graph.vertices(4248)
==>v[4248]
gremlin> g.V().count()
==>0
gremlin> graph.vertices()
```

**Comment by spmallette** [comment]
Had a quick discussion with @dkuppitz - this might not really be a "bug" but the behavior is strange. of course, with `storage.batch-loading` enabled you can expect strange to a certain degree as titan has to turn off a lot of "checks" to ensure loading performance. you really shouldn't use `storage.batch-loading` when doing graph element removal unless you really know what the consequence are of doing so and have a really good reason. This setting is intended for fast insertion of data and as a final resort for dealing with far-flung situations where you need constraints turned off when doing data manipulations. If you fit the latter then I think you just have to be aware of what the peculiarities are when using Titan this way.

**Comment by zyoo** [comment]
In my situation, I use batch-loading to insert and delete batch data,so if I turn off batch-loading, the performance is too bad to accept. we have billions record...

**Comment by zyoo** [comment]
If I insert a batch data in the wrong way, so I can only swap the titan table when the batch-loading is off. This does not make sense...

**Comment by zyoo** [comment]
BTW, the issue 1334 is a more stranger problem...

**Comment by spmallette** [comment]
Well - again - deleting data is not an expected use case for batch-loading, so i'm not completely surprised that there's some strangeness. If you are using batch-loading in this unintended way, then I could maybe see how #1334 could show itself - again, using batch-loading turns off many internal constraints in Titan, so with those checks unavailable, Titan allows you to "do bad things" to yourself.

**Comment by zyoo** [comment]
the delete is seem to be success when I reopen the titan instance with the batch-loading off, it is strange.BTW, how I should to delete batch data? just turn off the batch-loading? or in some other more ?trikcy way?

**Comment by zyoo** [comment]
[#comment](https://github.com/thinkaurelius/titan/issues/1333#issuecomment-235474178), like the comment describe, if I turn the batch-loading off, then deleting data should return nomarl ? or just turn batch-loading off, when I read data from titan.

**Comment by dkuppitz** [comment]
Deletes will eventually succeed with `batch-loading` enabled. However, you can't trust the results from read operations. Titan won't send any read requests to Cassandra, instead it will simply return a fake vertex, assuming that you know what you're doing and the vertex actually exists. `batch-loading` is, as the name implies, made for loading, not for reading.

Why would Titan return a fake vertex? See:

```
g.v(1).addEdge("link", g.v(2))
```

Without `batch-loading` enabled this query would first execute two reads, to verify that vertex `1` and `2` actually exist. An exception would be thrown in case any of the vertices doesn't exist. Next it would send the write requests to create the edge. With `batch-loading` enabled on the other hand Titan assumes that you know that vertex `1` and `2` already exist and thus it will skip the read request. The fake vertices will then only hold the ids, since theyy are required for the edge write requests.

HTH

**Comment by zyoo** [comment]
@spmallette @dkuppitz Thanks! I get it, I will test the problem in the way you suggest!

**Comment by spmallette** [comment]
I presume that the @dkuppitz explanation has settled this issue - closing.

**Comment by Kashyap01** [comment]
We got same issue in JanusGraph as well.
