### ISSUE TITLE
How to redirect titian's log?

### ISSUE THREAD

**Issue by liuyihan** [thinkaurelius/titan#1336]
I have a question about how to redirect titan's log?
I try to redirect log like this,but have no use.

```
BaseConfiguration baseConfiguration = new BaseConfiguration();
baseConfiguration.setProperty("storage.backend", "hbase");
baseConfiguration.setProperty("storage.hostname", HostName);
baseConfiguration.setProperty("log4j.appender.stdout", "org.apache.log4j.ConsoleAppender");
baseConfiguration.setProperty("log4j.appender.stdout.Target", "System.out");
baseConfiguration.setProperty("log4j.appender.stdout.layout", "org.apache.log4j.PatternLayout");
baseConfiguration.setProperty("log4j.appender.stdout.layout.ConversionPattern", "%d{ABSOLUTE} %5p %c{1}:%L - %m%n");
baseConfiguration.setProperty("log4j.rootLogger", "warn, stdout"); baseConfiguration.setProperty("log4j.logger.com.thinkaurelius.titan", "WARN");
```

**Comment by pluradj** [comment]
In the future, please use the [Titan mailing list](https://groups.google.com/forum/#!forum/aureliusgraphs) for questions like this. The issue tracker is used for bugs.

Logging is done with [Log4j](http://logging.apache.org/log4j/1.2/manual.html). Refer to the `$TITAN_HOME/conf/log4j-console.properties` for the configuration. It is used by `$TITAN_HOME/bin/gremlin.sh` by passing the configuration as a property when starting the console via `-Dlog4j.configuration=conf/log4j-console.properties`.
