### ISSUE TITLE
Titan Server gremlin.sh graph initialisation

### ISSUE THREAD

**Issue by abruski** [thinkaurelius/titan#1346]
I have configured my Titan db to run with Berkeley Lucene. When I run the server, be it with gremlin-server.sh or titan.sh -v start, I get all the proper messages
`1230 [main] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  - Graph [graph] was successfully configured via [conf/titan-berkeleyje-lucene.properties].`
`2601 [main] INFO  org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor  - Initialized gremlin-groovy ScriptEngine with scripts/empty-sample.groovy`
`2609 [main] INFO  org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - A GraphTraversalSource is now bound to [g] with graphtraversalsource[standardtitangraph[berkeleyje:../db/berkeley], standard]
`
When I connect to the server instance with
 `gremlin> :remote connect tinkerpop.server ../conf/remote.yaml`
I get
`==>Connected - localhost/127.0.0.1:8182`
`gremlin> g.V()`
`No such property: g for class: groovysh_evaluate`

**Comment by spmallette** [comment]
You are evaluating `g.V()` locally not remotely and therefore "g" is not available. Issue your command with the `:>` to submit the traversal remotely:

``` text
gremlin> :> g.V()
```

In the future please use the mailing list for usage questions and not the issue tracker: https://groups.google.com/forum/#!forum/aureliusgraphs
