### ISSUE TITLE
Make JavaDoc exclusions works.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#135]
```
              <excludePackageNames>
                 com.thinkaurelius.titan.diskstorage;com.thinkaurelius.titan.graphdb;com.thinkaurelius.titan.tinkerpop;com.thinkaurelius.titan.util;
                </excludePackageNames>
```

In the root Titan directory, you create the aggregate JavaDoc with:
   mvn javadoc:aggregate

The titan-all distribution.xml then grabs that for its distribution.zip.

Problem, the name exclusions don't seem to be considered by the plugin' :(

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/155

**Comment by mbroecheler** [comment]
merged
