### ISSUE TITLE
Is TitanDB dead?

### ISSUE THREAD

**Issue by vladaionescu** [thinkaurelius/titan#1360]
I noticed that [the documentation](http://s3.thinkaurelius.com/docs/titan/1.0.0/index.html) and [home page](http://titandb.io/) of Titan now redirect to a closed, enterprise-only version provided by DataStax. Also, there haven't been commits to this repo since June. Am I correct to assume that the open-source version of Titan is no longer being maintained?

With both the author of Titan and the author of Gremlin now being employees of DataStax it looks like there's little interest in maintaining a free and open community for Graph databases in general, let alone Titan. This kind of monopoly is what kills innovation and has historically killed great products like CouchDB/CouchBase.

What's going on?

**Comment by vladaionescu** [comment]
Update from mailing list:

> Our mistake.  We were taking down the old Aurelius corporate site which contained very outdated information on a now defunct company and the documentation ended up going away with it.  The pages http://s3.thinkaurelius.com/docs/titan/1.0.0/  and http://titan.thinkaurelius.com should no longer re-direct to the DataStax Graph landing page.  Sorry. 
> 
> cheers

**Comment by manigandham** [comment]
This was previously asked in #1328 

The `titan11` branch is the latest. It would help if the project switched to that so that people can at least see commits from this year by default.

**Comment by mamoit** [comment]
`titan11` may be the latest, but it looks pretty stale.

**Comment by manigandham** [comment]
@vlad-alexandru-ionescu @mamoit 

TitanDB is retired, there is a new project called **JanusGraph** which is now part of the Linux foundation. It starts with the foundations of TitanDB and has more interest and backing then before.

http://janusgraph.org/

https://opensource.googleblog.com/2017/01/janusgraph-connects-past-and-future-of-titan.html

**Comment by suesunss** [comment]
Thanks for having JanusGraph!
