### ISSUE TITLE
Support java.util.Date in Cassandra storage

### ISSUE THREAD

**Issue by wsalembi** [thinkaurelius/titan#137]
Is this a bug or a bad configuration on my part? My dates are not stored wekk in Titan/Cassandra. I always get currentDate() back from the database.

```
   @Test
public void testDate() throws ParseException {
    Configuration conf = new BaseConfiguration();
    conf.setProperty("storage.backend", "cassandra");
    conf.setProperty("storage.hostname", "127.0.0.1");
    TitanGraph g = TitanFactory.open(conf);

    g.makeType().name("birthday").dataType(Date.class).makePropertyKey();

    Vertex v = g.addVertex(null);
    Date date = new SimpleDateFormat("ddMMyyyy").parse("28101978");
    v.setProperty("birthday", date);
    System.out.println(date); // prints Sat Oct 28 00:00:00 CET 1978

    g.stopTransaction(Conclusion.SUCCESS);

    v = g.getVertex(v);
    System.out.println(v.getProperty("birthday")); // prints Wed Jan 16 18:49:44 CET 2013
}
```

**Comment by mbroecheler** [comment]
I was playing around with this a bit today. I can confirm that I am seeing the same behavior. Essentially, the deserialized date is always today's date & time. There must be something strage happening during the serialization process which I haven't been able to figure out yet.

In the meantime, I figured out a workaround: Use Calendar instead. I.e. set the datatype to GregorianCalendar.class
and then 

``` java
Date date = new SimpleDateFormat("ddMMyyyy").parse("28101978");
Calendar c = Calendar.getInstance();
c.setTime(date);
v.setProperty("birthday",c);
```

That works for me.

**Comment by vikraman** [comment]
I can reproduce this. It is probably due to [this issue](https://groups.google.com/forum/?fromgroups=#!topic/kryo-users/kZacb0ikW98) with kryo and Date.

**Comment by wsalembi** [comment]
Are all property values serialized with kryo? Are primitives and simple types like String and Date not converted to native cassandra types? Would an index on Date be possible?

**Comment by vikraman** [comment]
I see serializers for Double, Float, Integer and Long in [com/thinkaurelius/titan/graphdb/database/serialize/attribute](https://github.com/thinkaurelius/titan/tree/master/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/database/serialize/attribute). The rest are done using kryo I guess? There's nothing in titan-cassandra.

**Comment by mbroecheler** [comment]
Serialization is not backend specific. For everything that is not specifically registered, Titan uses Kryo's standard Field serializer which has an issue with Date as explained in the link above (thanks for posting that here).
Bottom line: We need to add a custom serializer for Date to Titan. I will also look at https://github.com/magro/kryo-serializers (thanks for that as well) and some of the other serializers it provides. However, I think we want a serializer that writes a ms since epoch UTC timestamp so that this can be used by vertex centric indices directly.

In the meantime, you can:
1) Use Calendar as explained above
2) Register a custom serializer for Date as explained in https://github.com/thinkaurelius/titan/wiki/Datatype-and-Attribute-Serializer-Configuration
3) wait until this is fixed

**Comment by vikraman** [comment]
I wrote a [custom serializer](https://gist.github.com/vikraman/4756717) that uses epoch for the time being,

**Comment by rsiemens77** [comment]
Kryo has a DateSerializer which does use long epoch serialization:
http://code.google.com/p/kryo/source/browse/trunk/src/com/esotericsoftware/kryo/serialize/DateSerializer.java?r=109

Just configure to use it with the below adapter:

attributes.attribute# = java.util.Date
attributes.serializer# = your.package.KryoDateSerializer

public class KryoDateSerializer implements AttributeSerializer<Date>
{
private final static DateSerializer sz = new DateSerializer();

@Override public Date read( ByteBuffer byteBuffer ) { return sz.readObjectData( byteBuffer, Date.class ); }

@Override public void writeObjectData( ByteBuffer byteBuffer, Date date ) { sz.writeObjectData( byteBuffer, date ); }

}

**Comment by mbroecheler** [comment]
A special DateSerializer has been added to the list of default serializers.
