### ISSUE TITLE
Can't add a Vertex with properties - titan-0.5.4-hadoop2

### ISSUE THREAD

**Issue by feloc50** [thinkaurelius/titan#1386]
Hi there is anyone who can explain me why i can't add a vertex with properties this way??

![error](https://user-images.githubusercontent.com/27733603/31554904-7c4669b6-b015-11e7-900d-8c7f69b13c00.png)

Thx.

**Comment by spmallette** [comment]
you're using Gremlin 3.x syntax for `addVertex()` with a Gremlin 2.x console. upgrade your console with the latest version from http://tinkerpop.apache.org/downloads.html
