### ISSUE TITLE
Provide a "local" cassandra.yaml file with the distribution.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#139]
Given that 

  storage.backend=embeddedcassandra

requires a cassandra.yaml file, it would be good to distribute a version of this file with Titan. (perhaps in config/)

**Comment by okram** [comment]
NOTE: config/ of cassandra and hbase are not included int the titan-all distribution.

**Comment by xedin** [comment]
Pull request is at https://github.com/thinkaurelius/titan/pull/150

**Comment by mbroecheler** [comment]
merged pull
