### ISSUE TITLE
Provide a rexster.xml with the distribution.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#142]
Like providing a base cassandra.yaml, provide a rexster.xml.

**Comment by okram** [comment]
How I do this now with client:
- go to Rexster source and get rexster.xml
- edit it to remove all <graph>s I don't need.
- add in information from Titan wiki.

Having a base rexster.xml that works with Titan is much eaiser for users.

**Comment by okram** [comment]
Perhaps provide three <graph> examples -- for BerekeleyDB, Cassandra, and HBAse. --- maybe have Cassandra and HBase  commented out so just dumping in the base rexster.xml will make a BerekeleyDB Titan.

**Comment by vadasg** [comment]
I haven't yet done anything with Rexter (so I don't know whether I understand the situation), but this seems like a natural addition to GraphCluster -- have a whirr.instance-template=rexter that when used in conjunction with Titan/X will generate the correct rexter.xml during deployment.  If you have specific requirements please comment on GraphCluster Issue #17:

https://github.com/thinkaurelius/graphcluster/issues/17

thanks, Vadas

**Comment by okram** [comment]
Done. 

@spmallette  can you look at:
   https://github.com/thinkaurelius/titan/tree/master/config
...and if you concur, please close this ticket.

Also, if there are XML comments you want to add that will be helpful to users, please do so. Thanks.

**Comment by spmallette** [comment]
Modified the rexster.xml to have just bare minimum.  Wiki could use some work.  Also not sure if the packaging is right for the distribution.  Some more work for me to do here.

**Comment by spmallette** [comment]
titan wiki updated a bit. config directory is showing up in the distribution.  this one is done
