### ISSUE TITLE
Better error handling around property key/edge label.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#146]
We have:
    g.createKeyIndex('keyword',Vertex.class)

We then do:
  g.addEdge(a,b,'keyword') 
  g.addVertex([keyword:'Coral Reef'])

Database is no happy in terms of g.V('keyword','Coral Reef'). ... I don't have a stack trace because this was discovered via Rexster. ... Perhaps there is a good exception. ?? Just a note as I'm sitting here with client.

**Comment by mbroecheler** [comment]
The issue is that both labels and keys are types in Titan and you cannot have a label and a key with the same name. That causes a name collision in types. That's why this throws an exception.
