### ISSUE TITLE
Edges holding onto stale references of endpoints

### ISSUE THREAD

**Issue by zmaril** [thinkaurelius/titan#148]
See [this issue in Hermes for motivation](https://github.com/gameclosure/hermes/issues/32). Whenever an edge gets printed out at the REPL outside of a transaction, it seems to be complaining about accessing an element outside of it's transaction. My guess is that it is calling toString on a stale node.

**Comment by okram** [comment]
It would be nice if the toString() could exist outside of the transaction.  ?

**Comment by zmaril** [comment]
Stack trace:

```
Backtrace:
  0: TitanException.java:53 com.thinkaurelius.titan.core.TitanException.transactionNotOpenException
  1: SimpleAtomicQuery.java:51 com.thinkaurelius.titan.graphdb.query.SimpleAtomicQuery.<init>
  2: SimpleAtomicQuery.java:64 com.thinkaurelius.titan.graphdb.query.SimpleAtomicQuery.<init>
  3: QueryUtil.java:17 com.thinkaurelius.titan.graphdb.query.QueryUtil.queryHiddenFunctionalProperty
  4: PersistVertexTitanType.java:28 com.thinkaurelius.titan.graphdb.types.vertices.PersistVertexTitanType.getName
  5: SimpleTitanEdge.java:61 com.thinkaurelius.titan.graphdb.relations.SimpleTitanEdge.getLabel
  6: StringFactory.java:34 com.tinkerpop.blueprints.util.StringFactory.edgeString
  7: SimpleTitanEdge.java:56 com.thinkaurelius.titan.graphdb.relations.SimpleTitanEdge.toString
```

(There is more but it is just clojure calling toString)

So it looks like [StringFactory](https://github.com/tinkerpop/blueprints/blob/master/blueprints-core/src/main/java/com/tinkerpop/blueprints/util/StringFactory.java) is getting used [here](https://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/relations/SimpleTitanEdge.java#L57). I'm not sure how this should be handled though. I know in Hermes we could probably wrap this up in a new class and override toString so that it wraps the call in a transaction, but I'm not sure what y'all want to do for Titan.

**Comment by mbroecheler** [comment]
the issue is not so much with a stale vertex but with the edge label. In
order to print it out, it needs to be retrieved first if it isn't cached
locally. if that happens outside the scope of a transaction it throws the
exception you are seeing.
I will take a look at refactoring this so a toString() will always work.

On Mon, Jan 28, 2013 at 4:59 PM, Zack Maril notifications@github.comwrote:

> Stack trace:
> 
> Backtrace:
>   0: TitanException.java:53 com.thinkaurelius.titan.core.TitanException.transactionNotOpenException
>   1: SimpleAtomicQuery.java:51 com.thinkaurelius.titan.graphdb.query.SimpleAtomicQuery.<init>
>   2: SimpleAtomicQuery.java:64 com.thinkaurelius.titan.graphdb.query.SimpleAtomicQuery.<init>
>   3: QueryUtil.java:17 com.thinkaurelius.titan.graphdb.query.QueryUtil.queryHiddenFunctionalProperty
>   4: PersistVertexTitanType.java:28 com.thinkaurelius.titan.graphdb.types.vertices.PersistVertexTitanType.getName
>   5: SimpleTitanEdge.java:61 com.thinkaurelius.titan.graphdb.relations.SimpleTitanEdge.getLabel
>   6: StringFactory.java:34 com.tinkerpop.blueprints.util.StringFactory.edgeString
>   7: SimpleTitanEdge.java:56 com.thinkaurelius.titan.graphdb.relations.SimpleTitanEdge.toString
> 
> (There is more but it is just clojure calling toString)
> 
> So it looks like StringFactoryhttps://github.com/tinkerpop/blueprints/blob/master/blueprints-core/src/main/java/com/tinkerpop/blueprints/util/StringFactory.javais getting used
> herehttps://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/relations/SimpleTitanEdge.java#L57.
> I'm not sure how this should be handled though. I know in Hermes we could
> probably wrap this up in a new class and override toString so that it wraps
> the call in a transaction, but I'm not sure what y'all want to do for
> Titan.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/148#issuecomment-12814840.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by zmaril** [comment]
Great If you have too much on your plate and the refactoring is straightforward, shoot me an email and I will do what I can.

**Comment by mbroecheler** [comment]
This should now longer be an issue as a consequence of https://github.com/thinkaurelius/titan/issues/143
