### ISSUE TITLE
Make each child project have its own distribution.zip

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#149]
We currenlty have it such that Titan-All provides the gremlin.sh and distribution.

It would be good to have each project have its own packaged distribution so that we can have (on the downloads page):

  titan-all-0.3.0.zip
  titan-cassandra-0.3.0.zip
  titan-hbase-0.3.0.zip
  titan-berkeleydb-0.3.0.zip

Each has a bin/gremlin.sh and respective README.txt..

**Comment by xedin** [comment]
Pull request at https://github.com/thinkaurelius/titan/pull/164

**Comment by xedin** [comment]
Merged.
