### ISSUE TITLE
Exception at g.shutdown()

### ISSUE THREAD

**Issue by protheusfr** [thinkaurelius/titan#152]
Hello I get the following exception each time I call a graph.shutdown()

152325 [main] ERROR com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool

Everything all work fine before this shutdown.

**Comment by mbroecheler** [comment]
Which version of Titan is this?
Note that the error is a result of some pooling error inside Astyanax. I
filed a bug report with them a while ago and they closed it. Newer versions
of Titan should not experience this any more. Also note that this is non
criticial. No data is lost and the error can simply be ignored as I don't
know of any implications on the database or the data within.

On Wed, Feb 6, 2013 at 3:24 AM, protheusfr notifications@github.com wrote:

> Hello I get the following exception each time I call a graph.shutdown()
> 
> 152325 [main] ERROR
> com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager -
> com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/152.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by protheusfr** [comment]
0.2.0 with maven bundled astyanax-1.0.6 library.

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/157
