### ISSUE TITLE
Murmur3Partitioner

### ISSUE THREAD

**Issue by kanle485** [thinkaurelius/titan#153]
I have the following error when trying to run with cassandra version 1.2
Unsupported partitioner: org.apache.cassandra.dht.Murmur3Partitioner

When will it be supported? Until then how can i proceed? Because i have a cluster running cassandra1.2.

**Comment by michaelklishin** [comment]
I confirm that Titan currently does not work with Cassandra 1.2 because of this issue.

**Comment by mbroecheler** [comment]
Please read this thread on the mailing list:
https://groups.google.com/forum/?fromgroups=#!topic/aureliusgraphs/ET05rQ2sBiY

In short, the next version of Titan will support the new partitioner. Until then, you can set RandomPartitioner in the yaml file which should also work.
