### ISSUE TITLE
Document Titan's Architecture/Internals

### ISSUE THREAD

**Issue by espeed** [thinkaurelius/titan#158]
A document detailing Titan's architecture/internals will help new devs get up to speed fast on the design philosophy and enable them to quickly build an accurate mental model for how things fit together.

**Comment by okram** [comment]
This would be good on the Wiki so its editable and contained with the documentation. Perhaps a whole section on Titan Internals:

```
* Titan Internals
** Big Table Mapping
** Vertex-Centric Indices
** …
```

**Comment by boneill42** [comment]
+1, i'd love to see it.

**Comment by michaelklishin** [comment]
I'm curious what's the current policy on wiki editing permissions?

**Comment by okram** [comment]
As it stands you have to be a contributor to Titan repo to have the ability to edit the wiki.

Why? Do you want to write up about Titan internals? If so, I can give you write access.

**Comment by mbroecheler** [comment]
include the DelftSWA project results
