### ISSUE TITLE
better type checking 

### ISSUE THREAD

**Issue by connectdotz** [thinkaurelius/titan#161]
Regarding gremlin id property filtering issue, see discussion: https://groups.google.com/forum/#!topic/aureliusgraphs/qyh236qem8I

**Comment by mbroecheler** [comment]
@okram I don't think this is a titan issue since v.has('id',4) is translated to v.getId().equals(4), by gremlin, right?
So, gremlin needs to be more lenient about the comparison.

**Comment by okram** [comment]
No. If the provided value to getVertex() is an int, TitanGraph.getVertex()
should make it a long. See Neo4jGraph.getVertex() to see how I do it there.
This makes the developer's life a bit easier.

http://markorodriguez.com

**Comment by mbroecheler** [comment]
Titan does that (see below). I don't think that's the issue here - I think its filtering (has) not retrieval (getVertex) that is the issue here.

``` java
    @Override
    public Vertex getVertex(final Object id) {
        if (null == id)
            throw ExceptionFactory.vertexIdCanNotBeNull();
        if (id instanceof Vertex) //allows vertices to be "re-attached" to the current transaction
            return getVertex(((Vertex) id).getId());

        final long longId;
        if (id instanceof Long) {
            longId = (Long) id;
        } else if (id instanceof Number) {
            longId = ((Number) id).longValue();
        } else {
            try {
                longId = Long.valueOf(id.toString()).longValue();
            } catch (NumberFormatException e) {
                return null;
            }
        }
        if (longId <= 0)
            return null;
        else
            return getVertex(longId);
    }
```

**Comment by okram** [comment]
Will not fix. If you have a long and you compare it against another type, that is just Java's "style." We are not going to change the Number semantics of Java. For getVertex(Object) we provide some nice helpers, but beyond that, once the ID object is returned, its all Java comparison.
