### ISSUE TITLE
Make titan.sh play nicely with backend monitoring options

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#163]
https://groups.google.com/forum/?hl=en&fromgroups=#!searchin/aureliusgraphs/biswas/aureliusgraphs/t8enj0-KkJs/Kpcd1V_wd7QJ

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/185.

**Comment by xedin** [comment]
Merged.
