### ISSUE TITLE
TitanGraph.getVertices() and TitanGraph.getEdges()

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#166]
The feature for Titan/Cassandra (all adaptors) and Titan/HBase. Already implemented for Titan/BerekelyDB.

**Comment by mbroecheler** [comment]
All that is needed is implementing getKeys() [https://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/diskstorage/keycolumnvalue/KeyColumnValueStore.java#L114] in the respective storage adapters. BerkeleyDB already has an implementation of that method which you can check out. However, BerkeleyDb's implementation is complicated by the fact that we need to keep track of the iterator in the enclosing transaction to close it. For non-transactional backends (Cassandra / Hbase) that would not be necessary. However, for those systems there is no "iterator" model so there needs to be some logic around keeping track of where you are in the key ring.

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/171

**Comment by xedin** [comment]
Merged.
