### ISSUE TITLE
Support Cassandra frame.size setting in Titan client. 

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#167]
E.g.

conf = new BaseConfiguration() 
conf.setProperty('storage.backend', 'cassandrathrift')
conf.setProperty('storage.hostname', 'cassandra-test-01')  
conf.setProperty('cassandra.thirft.frame.size', '1000000')  
g = TitanFactory.open(conf)

**Comment by okram** [comment]
Of course make the "cassandra.thrift.fame.size" name whatever is appropriate. Coordinate with @mbroecheler about naming convention.

**Comment by xedin** [comment]
Pull request is at https://github.com/thinkaurelius/titan/pull/168, I named those options storage.cassandra.thrift.{frame_size_mb, max_message_size_mb} for compatibility with Cassandra's I/O Format.

**Comment by xedin** [comment]
Merged.
