### ISSUE TITLE
Nicer project names in pom.xml for ElasticSearch and Lucene.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#173]
[INFO] Titan-ElasticSearch: Full text indexing support
[INFO] Titan-Lucene: Full-text search support

Should be:

[INFO] Titan-ElasticSearch: Full-Text Indexing Support
[INFO] Titan-Lucene: Full-Text Indexing Support

.. in short, like the other projects, consistent captilization.

Also, is it _just_ Full-Text? Perhaps:

[INFO] Titan-ElasticSearch: Distributed Graph Indexing
[INFO] Titan-Lucene: Local Graph Indexing Support

..or somethig.

**Comment by xedin** [comment]
This one goes to Matthias, super easy to fix in pom.

**Comment by okram** [comment]
fixed.
