### ISSUE TITLE
Embed HttpRexsterServer

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#176]
Get this:

https://github.com/tinkerpop/rexster/blob/master/rexster-server/src/main/java/com/tinkerpop/rexster/server/HttpRexsterServer.java

into Titan Server.  Embeds just like RexProRexsterServer and will give Titan Server REST capability for those who want it.  

Dog House could be deployed with Titan Server, but it will complicate packaging.  Better to just have it disabled (see https://github.com/tinkerpop/rexster/wiki/Rexster-Configuration for how to turn that off).

**Comment by spmallette** [comment]
I have it embedded but still needs more work.  Forgot that we auto-configured "graph" and therefore have no way to configure extensions and such.  Need to work that in there still.

**Comment by spmallette** [comment]
HTTP/REST Server is now fully embedded with the capability to deploy extensions.  Pretty cool...just drop your kibble into Titan Server path and it exposes it.  You only need specific configuration in the rexster.xml if your extension requires it (like Frames Kibble).  Most should just drop in and go.....

Wiki page for Titan Server has been updated.

**Comment by mbroecheler** [comment]
great, thanks Stephen!

On Tue, Mar 26, 2013 at 2:28 PM, stephen mallette
notifications@github.comwrote:

> HTTP/REST Server is now fully embedded with the capability to deploy
> extensions. Pretty cool...just drop your kibble into Titan Server path and
> it exposes it. You only need specific configuration in the rexster.xml if
> your extension requires it (like Frames Kibble). Most should just drop in
> and go.....
> 
> Wiki page for Titan Server has been updated.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/176#issuecomment-15489768
> .

## 

Matthias Broecheler
http://www.matthiasb.com
