### ISSUE TITLE
Make sure Titan 0.2.1 and Titan 0.3.0 work with IdGraph in TinkerPop 2.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#179]
...necessary before release as many users are counting on this functioning.

@joshsh

**Comment by okram** [comment]
This does not work on indexing-branch.

gremlin> IdGraph.class
==>class com.tinkerpop.blueprints.util.wrappers.id.IdGraph
gremlin> g = TitanFactory.open('/tmp/test')
13/03/26 09:34:22 INFO idassigner.VertexIDAssigner: Partition IDs? [false], Local Partitions? [false]
==>titangraph[local:/tmp/test]
gremlin> g = new IdGraph(g)
Cannot add an index to an already existing property key: __id
Display stack trace? [yN] y
java.lang.UnsupportedOperationException: Cannot add an index to an already existing property key: __id
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.createKeyIndex(TitanBlueprintsTransaction.java:180)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.createKeyIndex(TitanBlueprintsGraph.java:117)
    at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.createIndices(IdGraph.java:412)
    at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.<init>(IdGraph.java:82)
    at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.<init>(IdGraph.java:56)

**Comment by mbroecheler** [comment]
That suggests that the id property is used before it is indexed which is a
no go in titan. Is that possible, @joshsh ?

**Comment by joshsh** [comment]
Are you wrapping an existing graph with IdGraph?  One which has previously been wrapped with IdGraph?  If you look at the IdGraph constructor, it creates the indices in advance of allowing you to create any vertices or edges, i.e. use the "__id" property.

**Comment by okram** [comment]
We got it working Josh. If you are going to use __id as a key for both Vertex and Edge in Titan, you need to declare it first.

   gremlin> g.makeType().name('__id').unique(OUT).indexed(Vertex.class).indexed(Edge.class).dataType(String.class).makePropertyKey()
   ==>v[36028797018964170]
   gremlin> g = new IdGraph(g)
   ==>idgraph[titangraph[local:/tmp/test]]
   gremlin> g.addVertex("marko")
   ==>v[marko]
   gremlin> g.addVertex("matthias")
   ==>v[matthias]
   gremlin> g.v("marko")
   ==>v[marko]
   gremlin>

-OR- 

If you only want it for Vertices, then your cool method works:

   g = new IdGraph(g,true,false)

... BTW: IdGraph is awesome. Thanks.

**Comment by okram** [comment]
https://github.com/thinkaurelius/titan/wiki/Advanced-Blueprints

**Comment by joshsh** [comment]
Cool.  As an observation on the above, it appears that if you support both vertex __id and edge __id in Titan, you also need to know in advance the type of your ids.  Mixing and matching ids of different types would be pretty unusual in Blueprints (and impossible in Titan anyway...?), but you never know.

**Comment by okram** [comment]
Yes. You will need to know the types. You can put Object.class, but that is inefficient.
