### ISSUE TITLE
[Indexing branch] INFO Log when starting up BerkeleyDB

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#188]
gremlin> g = TitanFactory.open('/tmp/test')
   13/03/26 09:32:15 INFO idassigner.VertexIDAssigner: Partition IDs? [false], Local     Partitions? [false]
   ==>titangraph[local:/tmp/test]
   gremlin>

**Comment by okram** [comment]
This is showing up in Faunus now too -- so its not specific to BerkeleyDB.

13/03/26 09:52:03 INFO idassigner.VertexIDAssigner: Partition IDs? [false], Local Partitions? [false]

Should this message simply not be DEBUG message?

**Comment by mbroecheler** [comment]
I would like this to be a info because this is very useful information for
reports and such. But I agree that its not pretty in gremlin. Is there a
way to Greene a gremlin specific log4j file?

**Comment by mbroecheler** [comment]
changed to debug
