### ISSUE TITLE
Gremlin Configuration Helpers

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#19]
Provide some helpers (mostly for Gremlin) to generate the BaseConfiguration object.  It gets a bit tedious typing this:

``` text
Configuration conf = new BaseConfiguration();
conf.setProperty("storage.backend","cassandra");
conf.setProperty("storage.hostname","127.0.0.1");
```

Perhaps, just having something that could generate different BaseConfiguration objects with all the defaults for each of the different modes of operation for Titan.  Or, maybe a 'create' method on TitanFactory in addition to 'open' ("create" in the sense of creating a configuration and opening the graph...might not be the right word) :

``` text
TitanGraph g = TitanFactory.create(Mode.CASSANDRA_LOCAL_SERVER)
```

kind of reminds me of the TinkerGraphFactory.createTinkerGraph() method that spins up the toy graph to play with.

**Comment by mbroecheler** [comment]
Should this be in Titan core or in the titan gremlin shell?

**Comment by spmallette** [comment]
I would think it would be most useful in the shell where you are just typing the same commands over and over again.  Not sure how much additional value it would add to connecting to titan otherwise.  I suppose that if was just in the shell then new methods on TitanFactory wouldn't be the way to go.  Conceptually, it would be the same thing though...

**Comment by okram** [comment]
This will go into Gremlin shell. In the package com.thinkaurelius.titan.tinkerpop.gremlin.... I'll handle it, but if people have good ideas for good helper methods, I'm all ears.

Marko.

http://markorodriguez.com

**Comment by mbroecheler** [comment]
Maybe extend the TitanFactory class in Gremlin?

On Fri, Jun 8, 2012 at 6:44 AM, Marko A. Rodriguez <
reply@reply.github.com

> wrote:
> 
> This will go into Gremlin shell. In the package
> com.thinkaurelius.titan.tinkerpop.gremlin.... I'll handle it, but if people
> have good ideas for good helper methods, I'm all ears.
> 
> Marko.
> 
> http://markorodriguez.com
> 
> On Jun 7, 2012, at 8:30 PM, Matthias Broecheler wrote:
> 
> > Should this be in Titan core or in the titan gremlin shell?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/thinkaurelius/titan/issues/19#issuecomment-6193148
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/19#issuecomment-6203041

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by okram** [comment]
Done.
