### ISSUE TITLE
.hasIndex takes two arguments

### ISSUE THREAD

**Issue by zmaril** [thinkaurelius/titan#198]
https://github.com/thinkaurelius/titan/wiki/Type-Definition-Overview

The documentation shows that the function takes no arguments, while the javadocs says it takes two.

**Comment by zmaril** [comment]
Actually, the javadocs look odd as well. 

http://thinkaurelius.github.com/titan/javadoc/current/com/thinkaurelius/titan/core/TitanKey.html

hasIndex is now in in TitanKey. It looks like it should be in TypeMaker based on the arguments and description string.

**Comment by zmaril** [comment]
Whoops. Never mind. Didn't understand that the string was supposed to be something like "search" instead of the name. That makes more sense. What's the default index name then? Like if I only called indexed when creating the type without the string "search" as the first argument?

**Comment by mbroecheler** [comment]
"standard"

On Sun, Mar 31, 2013 at 3:01 PM, Citizen notifications@github.com wrote:

> Whoops. Never mind. Didn't understand that the string was supposed to be
> something like "search" instead of the name. That makes more sense. What's
> the default index name then? Like if I only called indexed when creating
> the type without the string "search" as the first argument?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/198#issuecomment-15698760
> .

## 

Matthias Broecheler
http://www.matthiasb.com
