### ISSUE TITLE
Persistit Backend

### ISSUE THREAD

**Issue by bdeggleston** [thinkaurelius/titan#199]
The new b/e is coming along, though I have some questions. I thought it would be best to open a dedicated issue here than ask questions on the mailing list.

**Comment by bdeggleston** [comment]
I'm getting this error intermittently in the concurrentReadWriteOnSingleTransaction test: "Relation already existed on some vertices but not on others". @mbroecheler, I remember you making a comment about the likely cause of this somewhere a few months ago, but I can't find it. Anyway, I wanted to check if you knew of a common cause of this before diving in.

**Comment by bdeggleston** [comment]
Also, I've been talking with the guys at akiban, and there is in fact a way to have transactions that aren't bound to a single thread. They've been very helpful.

https://groups.google.com/a/akiban.com/forum/#!topic/akiban-user/IqMQqDr9QDA

**Comment by mbroecheler** [comment]
@bdeggleston: Great to hear that this is coming along. Looking forward to giving it a spin. 
Do you get that exception with Titan 0.3.0? Try to implement the adapter against that version. The diskstorage package got cleaned up a bit.

**Comment by dalaro** [comment]
This exception string is no longer in Titan master.  It was refactored out of existence months ago:

```
dalaro@bluebox:~/tinkerelius/titan[52]$ git log -n1 -S'Relation already existed'
commit d5662482340f61d370cde27fece75d7ecb6b16e4
Author: Matthias Broecheler
Date:   Mon Feb 25 00:58:42 2013 -0800

    Intermediate commit on indexing and complete refactor
```

d5662482340f61d370cde27fece75d7ecb6b16e4 deletes the method that used to throw this exception, along with its enclosing class, and replaces it with substantially different code.  I'm not sure whether this exception has a direct equivalent anymore.  Maybe something thrown from `ElementLifeCycle#update()`?  Regardless, I haven't seen any exceptions when running titan-persistit tests locally on the persitit-to-master branch (#276).

**Comment by bdeggleston** [comment]
yeah, I developed the persistit backend against titan 0.2.x, then ported it to 0.3.x. We're using 0.2.1 here, so I was able to give it some real world use, and look for any problems not exposed by the unit tests

**Comment by mbroecheler** [comment]
To clarify on the "Relation already existed" exception: With the major
refactoring of Titan, this exception is no longer applicable nor does it
have an equivalent in Titan 0.3.x.

On Thu, Jun 20, 2013 at 9:35 AM, Blake Eggleston
notifications@github.comwrote:

> yeah, I developed the persistit backend against titan 0.2.x, then ported
> it to 0.3.x. We're using 0.2.1 here, so I was able to give it some real
> world use, and look for any problems not exposed by the unit tests
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/199#issuecomment-19765149
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
closed with https://github.com/thinkaurelius/titan/pull/275
