### ISSUE TITLE
Import UniquenessConstraint on Titan/Gremlin

### ISSUE THREAD

**Issue by renatogp** [thinkaurelius/titan#203]
It would be great to have UniquenessConstraint automatically imported into Gremlin sessions, as suggested by @okram on https://groups.google.com/d/msg/aureliusgraphs/R3LbPEs9RzA/PMTGvOokHrMJ

**Comment by okram** [comment]
gremlin> LOCK
==>LOCK
gremlin> NO_LOCK
==>NO_LOCK
gremlin> NO_LOCK.class
==>class com.thinkaurelius.titan.core.TypeMaker$UniquenessConsistency
gremlin> LOCK.class
==>class com.thinkaurelius.titan.core.TypeMaker$UniquenessConsistency

**Comment by renatogp** [comment]
Thanks!
