### ISSUE TITLE
IO Packages

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#21]
Since @g.V@ and @g.E@ don't behave the in titan the way they do in other blueprints implementation the gremlin options to saveGraphML, saveGraphSON and saveGML won't work right as the IO writers won't be able to simply iterate all vertices and edges for output.  

I suspect that's not a huge deal considering that no one would be dumping billions or vertices/edges to these file formats, however, it's worth documenting or otherwise warning users of the limitation somehow.

**Comment by okram** [comment]
Oh yea --- huh. 

Matthias, is it at all possible for g.V/E to work?

Marko.

**Comment by mbroecheler** [comment]
Well, it is technically possible, but it won't work for any use case that one might need Titan for. I did document this limitation in the wiki. I will add that this limitation also applies to all functionality that relies on vertex iteration.

My 2 cents: Global graph operations, including exports, should be handled through Faunus. We should get Faunus into shape asap after the Titan release to cover that functionality hole. I feel like adding @g.V@ functionality now is like adding a bandage that won't last long. We should see the pain of not having it as a motivation to get Faunus in shape ;-)

**Comment by okram** [comment]
Coo'.

And yea Stephen -- geez.

Marko.
