### ISSUE TITLE
Vertices Not Deleting Fully

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#212]
Vertices only partially deleting under certain conditions.  First reported here:

https://groups.google.com/forum/#!topic/gremlin-users/m5RjyS97iNA

To recreate:
- Start Titan Server:

``` text
bin/titan.sh config/titan-server-rexster.xml config/titan-server-cassandra.properties`
```
- Start gremlin and connect to titan server and add a few vertices: 

``` text
gremlin> g = TitanFactory.open('bin/cassandra.local')
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.addVertex([name:'allen'])
==>v[4]
gremlin> g.addVertex([name:'rick'])
==>v[8]
gremlin> g.addVertex([name:'sandy'])
==>v[12]
gremlin> g.commit()
==>null
gremlin> g.V
==>v[4]
==>v[8]
==>v[12]
```
- You should be able to curl that out via REST:

``` text
curl http://localhost:8182/graphs/graph/vertices
{"version":"2.3.0","results":[{"name":"allen","_id":4,"_type":"vertex"},{"name":"rick","_id":8,"_type":"vertex"},{"name":"sandy","_id":12,"_type":"vertex"}],"totalSize":3,"queryTime":270.671319}
```
- You should be able to remove all those vertices via REST:

``` text
curl "http://localhost:8182/graphs/graph/tp/gremlin?script=g.V.remove();g.commit()"
{"results":null,"success":true,"version":"2.3.0","queryTime":843.982107}
```
- But they are still there...sort of.  They are listed but have no properties:

``` text
curl http://localhost:8182/graphs/graph/vertices{"version":"2.3.0","results":[{"_id":4,"_type":"vertex"},{"_id":8,"_type":"vertex"},{"_id":12,"_type":"vertex"}],"totalSize":3,"queryTime":26.497273}
```
- So check in Gremlin REPL and see what it says:

``` text
gremlin> g.V
gremlin> 
```

Apparently they were deleted.
- It must be a problem with Rexster.  Maybe a lurking cache somewhere in memory.  Perhaps some trick of multithreading.  So...restart Titan Server and try to grab the data again:

``` text
gremlin> g = TitanFactory.open('bin/cassandra.local')
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.V
gremlin> 
```

Gremlin is good...what about REST:

``` text
curl http://localhost:8182/graphs/graph/vertices
{"version":"2.3.0","results":[{"_id":4,"_type":"vertex"},{"_id":8,"_type":"vertex"},{"_id":12,"_type":"vertex"}],"totalSize":3,"queryTime":231.322573}
```

Still showing those "empty" vertices.  What about Rexster Console:

``` text
rexster[groovy]> g = rexster.getGraph('graph')
==>titangraph[embeddedcassandra:null]
rexster[groovy]> g.V
==>v[4]
==>v[8]
==>v[12]
rexster[groovy]> g.V.map
==>{}
==>{}
==>{}
```

Same problem.  The fact that restarting Titan Server doesn't fix the problem seems to indicated that Rexster is not the problem as it maintains no state itself between stop/start. The fact that Gremlin REPL is working properly seems to indicate that the problem is not in Titan as we're removing layers from the stack and simplifying.

**Comment by xedin** [comment]
This is the problem with range ghosts (http://wiki.apache.org/cassandra/DistributedDeletes), as if you login to cassandra CLI and list edgestore you will see following (after removing vertices using rexster):

[default@titan] list edgestore;
Using default limit of 100
Using default column limit of 100
RowKey: 0000000000000008
RowKey: 0000000000000010
RowKey: 0000000000000018
.....

Those are just "empty" keys left there after removal have happened (refer to aforementioned dock for explanation why). In the latest 1.2 release internal API that used to check for those types of columns was slightly changed that is what caused embedded Cassandra implementation for getKeys(StorageTransaction) to misbehave while all other implementations returned correct "empty" result.

Pull request with fix is at https://github.com/thinkaurelius/titan/pull/218

**Comment by spmallette** [comment]
nice pavel...thanks

**Comment by xedin** [comment]
All tests passed (+ manually checked), merged and closing.
