### ISSUE TITLE
deleted vertices can still be loaded from a separate transaction with getVertices

### ISSUE THREAD

**Issue by bdeggleston** [thinkaurelius/titan#213]
I've created a test case that reproduces

https://gist.github.com/bdeggleston/5320684

this may be the same issue reported here:
https://github.com/thinkaurelius/titan/issues/212

**Comment by mbroecheler** [comment]
I added a test case and it looks like its related to #212 as you suggested. We have disabled vertex iteration when using BoP with embedded cassandra for now and are looking into possible ways to make it work.

**Comment by mbroecheler** [comment]
I have added the test case to the Titan test suite and its passing now after fixing #258.
