### ISSUE TITLE
GraphSON reader assume particular order of JSON fields and exits upon errors

### ISSUE THREAD

**Issue by voxsup** [thinkaurelius/titan#223]
in the example of loading an entire graph from graphSON (https://github.com/tinkerpop/blueprints/wiki/GraphSON-Reader-and-Writer-Library), why is it necessary to place the JSON elements in a particular order (specifically, the "edges":[...] list comes before "vertices":[....] list)? i generated a JSON file programmatically and the program puts the edges list before vertices and then the import does work.

gremlin> g.loadGraphSON('/files2/tmp/graph/test.json')
Given element was not created in this baseGraph

the load command exits upon reaching an edge whose end vertices are not specified (seems simply because the vertices list is placed after edges....)

also is it possible to 'continue-on-errors'?

**Comment by spmallette** [comment]
This is a blueprints issue and exist as such over in blueprints:

https://github.com/tinkerpop/blueprints/issues/386
