### ISSUE TITLE
Expand Documentation on Type Definitions

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#224]
The [Type Definition Overview](https://github.com/thinkaurelius/titan/wiki/Type-Definition-Overview) wiki page requires more clarity I think.  Specifically, greater explanation on:
- the concept of Unique Types
- the use of indexed

**Comment by zmaril** [comment]
Agreed. Getting Titanium up and running with types was not all that straightforward. I'm writing the documentation for Titanium currently and I saved types for last out of fear. The "unique via direction" idea doesn't intuitively make sense to me yet.

**Comment by wsalembi** [comment]
Agreed. I got an exception while creating an elastic search index on a property key: "Only standard index is allowed on non-unique property keys". The point was my index was not intended to be a 'unique' index. Till the point I understood that unique(OUT) means singlevalue and unique(IN) means unique across all vertices. Very confusing.

**Comment by rustyrazorblade** [comment]
Personally I think using unique(IN) and unique(OUT) is a strange choice.  functional(false) was also weird, but at least didn't use the same term to mean two totally different things.  unique is a term used frequently in other databases to indicate that the value is unique in the entire dataset, so at least that was consistent terminology.  unique(OUT) is extremely unintuitive that there's a single value of a given key in a vertex.  

I'm guessing this is a direct result of how properties are actually stored as vertices?  I don't feel that the terms that you expose to people should be a reflection of the implementation, as it results in you needing to change your terminology every time the implementation changes.

On the thunderdome side, we decided to use the same terminology as titan for creating a spec so people wouldn't need to learn something totally new on top of titan, but now we need to maintain a different spec parser on every version bumb.  We'll probably end up either dropping the current system or writing a totally new DSL to avoid people having to totally change their spec every time they upgrade titan versions.

See here: https://github.com/StartTheShift/thunderdome/wiki/Spec-Files

**Comment by bytor99999** [comment]
Not sure if this has been addressed. But the Schema definition documentation is extremely confusing. I mean in general I understand the code, but what are we actually defining here. I can't even figure out how to start to define my Vertices. Is schema definition just about properties, or just about edges, or defining everything. Also when should this code to define the schema be run? Each time you start up your application? Just one big confusing documentation. 

Thanks

**Comment by spmallette** [comment]
>  what are we actually defining here. I can't even figure out how to start to define my Vertices

You are defining all the property keys (for a vertex or edge) and edge labels you intend to use in your graph, with their explicit data types and constraints.  The best practice is to define "everything" and to do so prior to first usage in your graph (e.g. via Element.setProperty), lest the type be defined by default Type Maker:

https://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/blueprints/BlueprintsDefaultTypeMaker.java

I think it's smart to set the `autotype` property to `none` to disable this feature, which prevents accidental type creation.

**Comment by bytor99999** [comment]
Thanks Stephen, those are the details that I would love to see added to the documentation. I feel it just goes into those little details that those that already knows how it works takes for granted, but those that are new, really would need that information to get going.

Thanks again

Mark
