### ISSUE TITLE
There are two versions of Groovy in the distribution. Make it one.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#23]
groovy-all-1.8.5.jar
groovy-1.8.6.jar

Why is this? Also, see if you can get rid of all the GMaven depedencies (though they are tiny so its not too big a deal).

**Comment by mbroecheler** [comment]
Titan has no groovy dependencies directly, but only through gremlin. Could
it be possible that gremlin has those two dependencies somehow?

On Thu, Jun 14, 2012 at 7:24 AM, Marko A. Rodriguez <
reply@reply.github.com

> wrote:
> 
> groovy-all-1.8.5.jar
> groovy-1.8.6.jar
> 
> Why is this? Also, see if you can get rid of all the GMaven depedencies
> (though they are tiny so its not too big a deal).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/23

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by okram** [comment]
This was due to a GMaven inclusion which was confusing because GMaven is a plugin, howver, I fixed this in Gremlin and now it rippled down and fixed this in Titan. Done.
