### ISSUE TITLE
Make documentation around ES indexing more explcit.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#230]
These would be good points to include in the ElasticSearch (? or index in general) documentation in Titan.
- full-text clips out stop words (english language)
- full-text removes punctuation
- all words in ES are toLowerCase()
- dashes (-) are considered spaces.
- only tokenized searches, not multiple tokens.

What is geo indexing all about?
- a diagram perhaps demonstrating a circle intersecting points

Perhaps some good, explicit references to the ES documentation could be good, but nice to have it written in our documentaiton if its < 1 page.

**Comment by mbroecheler** [comment]
https://github.com/thinkaurelius/titan/wiki/Indexing-Backend-Overview
