### ISSUE TITLE
ByteBuffer.duplicate in Cassandra adapters

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#239]
Check which of the defensive copies are actually necessary.

**Comment by dalaro** [comment]
I deleted the remaining explicit ByteBuffer.duplicate(...) calls in the Astyanax and Thrift Cassadra KCVS classes in 8774c847c7b50c8338cc0bfe946f40681a8884d3.  I'm reasonably -- though not absolutely -- confident that the deletions are safe.  The complete Titan test suite passes on my box.

Though I deleted ByteBuffer.duplicate(...) call sites in the Cassandra KCVS classes, invocations remain inside StaticBuffer.asByteBuffer() calls.  These SB -> BB duplicates could be characterized as defensive copies, but trying to avoid them would arguably defeat the point of StaticBuffer, so I'm leaving them untouched.
