### ISSUE TITLE
Implement data grid KeyValueStore

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#243]
together with a KCVStore adapter that groups the entire adjacency list of a vertex into one value. This will be an in-memory version of Titan.

Which one should we support as our initial implementation for a data grid?

**Comment by espeed** [comment]
Galaxy 1.0  :-) http://puniverse.github.com/galaxy/

http://paralleluniverse.co/docs/galaxy-1.0-SNAPSHOT.zip

Getting Started
http://puniverse.github.io/galaxy/start/getting-started.html

The Performance Of Distributed Data-Structures Running On A "Cache-Coherent" In-Memory Data Grid
http://highscalability.com/blog/2012/8/20/the-performance-of-distributed-data-structures-running-on-a.html

On Distributed Memory Systems
http://blog.paralleluniverse.co/post/26909672264/on-distributed-memory 
https://news.ycombinator.com/item?id=4224637

A New Approach to Databases and Data Processing — Simulating 10Ks of Spaceships on My Laptop
http://blog.paralleluniverse.co/post/44146699200/spaceships
https://news.ycombinator.com/item?id=5293619

**Comment by mbroecheler** [comment]
Its LGPL :-(

On Fri, Apr 26, 2013 at 5:09 PM, James Thornton notifications@github.comwrote:

> Galaxy 1.0 :-) http://puniverse.github.com/galaxy/
> 
> http://paralleluniverse.co/docs/galaxy-1.0-SNAPSHOT.zip
> 
> Getting Started
> http://puniverse.github.io/galaxy/start/getting-started.html
> 
> The Performance Of Distributed Data-Structures Running On A
> "Cache-Coherent" In-Memory Data Grid
> 
> http://highscalability.com/blog/2012/8/20/the-performance-of-distributed-data-structures-running-on-a.html
> 
> On Distributed Memory Systems
> http://blog.paralleluniverse.co/post/26909672264/on-distributed-memory
> https://news.ycombinator.com/item?id=4224637
> 
> A New Approach to Databases and Data Processing — Simulating 10Ks of
> Spaceships on My Laptop
> http://blog.paralleluniverse.co/post/44146699200/spaceships
> https://news.ycombinator.com/item?id=5293619
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/243#issuecomment-17106701
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by zmaril** [comment]
Pinging @pron @eitan101 , you might be interested in this issue.

**Comment by pron** [comment]
@mbroecheler Is there a problem with LGPL?

**Comment by espeed** [comment]
Previous discussions on Titan and Galaxy.... 

B+ Tree implementation in Galaxy
https://github.com/puniverse/galaxy/issues/9

B+ Tree
https://groups.google.com/d/topic/galaxy-user/3XD72zxdKyk/discussion

**Comment by mbroecheler** [comment]
@pron: I don't have any personal problems with LGPL. Its been my impression
from interactions on the mailing list that folks get confused by non
Apache2 licenses which slows adoption. We are looking into different
alternatives including Hazelcast and EhCache (both Apache2).

That said, I am personally interested in seeing how Galaxy performs on
graph work loads compared to other systems like the ones mentioned above.

On Sat, Apr 27, 2013 at 12:19 PM, pron notifications@github.com wrote:

> @mbroecheler https://github.com/mbroecheler Is there a problem with
> LGPL?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/243#issuecomment-17121685
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by pron** [comment]
@mbroecheler Interesting. We'll take a look at that (the licensing). Also,there are some changes coming very soon that will promote Galaxy to a  beta status.

**Comment by mbroecheler** [comment]
@pron: Great, looking forward to it.

On Sat, Apr 27, 2013 at 1:29 PM, pron notifications@github.com wrote:

> @mbroecheler https://github.com/mbroecheler Interesting. We'll take a
> look at that (the licensing). Also,there are some changes coming very soon
> that will promote Galaxy to a beta status.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/243#issuecomment-17122835
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
Implemented CacheStore and CacheStoreAdapter with an initial (experimental) implementation based on Hazelcast. Merged into mater.

**Comment by espeed** [comment]
FYI: [Infinispan](http://infinispan.org/) is now Apache 2.0: 

http://infinispan.blogspot.com/2013/05/infinispan-to-adopt-apache-software.html
