### ISSUE TITLE
ElasticSearch chaining has() does not work -- Titan 0.3.0 and ES 0.20.06 

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#252]
Without ElasticSearch, has() chaining works perfect. See below.

``` text
gremlin> g = TitanFactory.open('bin/cassandra.local')
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.makeType().name('service').indexed(Vertex.class).unique(OUT).dataType(String.class).makePropertyKey()
==>v[36028797018963978]
gremlin> v = g.addVertex([service:'computers',name:'marko'])
==>v[4]
gremlin> g.query().has('service','computers').vertices()
==>v[4]
gremlin> g.query().has('service','computers').has('name','marko').vertices()
==>v[4]
gremlin> g.commit()
==>null
gremlin> g.query().has('service','computers').has('name','marko').vertices()
==>v[4]
```

With ElasticSearch has() chaining does not work correctly. .................

NOTE: I can NOT reproduce it on the small scale. I can only reproduce it in a semi-production data set.

I can demonstrate on the large scale:

g.query().has('service','computers').has('name','marko').vertices() is an empty iterable.
g.query().has('service','computers').vertices()._().has('name','marko') returns the 1 vertex.

...apologies that I don't have a perfect clean-cut test case. Hopefully there is an "ah. I know why." Else, if someone else can identify the problem simply, please comment on this ticket.

**Comment by mbroecheler** [comment]
Which of these property keys are indexed? Just "service"?

**Comment by okram** [comment]
Yes. Just 'service'.

**Comment by okram** [comment]
Using the latest Titan 0.3.1-SNAPSHOT, the problem does not happen for _the same_ query above. I don't know what is different now save ElasticSearch bump and Titan bump. Either way, I can't reproduce it anymore.
