### ISSUE TITLE
KryoException: Buffer underflow

### ISSUE THREAD

**Issue by zachkinstner** [thinkaurelius/titan#259]
RexConnectServer query:

``` json
{
  "reqId":"8f24b5f1-4b15-4b8f-a8e9-a1f80a496d9a",
  "cmdList":[{
    "cmd":"query",
    "args":["g.V('A_AId',_P0);","{\"_P0\":40}"]
  }]
}
```

Returned the following RexProException message:

> An error occurred while processing the script for language [groovy]. All transactions across all graphs in the session have been concluded with failure: javax.script.ScriptException: com.esotericsoftware.kryo.KryoException: Buffer underflow.\nSerialization trace:\nname (com.thinkaurelius.titan.graphdb.types.StandardKeyDefinition)","cmdList":[]}

I'm using Rexster 2.4.0-SNAPSHOT and Titan 0.3.1-SNAPSHOT.  The Rexster build is more recent, but the Titan build is older, around the time of the #222 fix (https://github.com/thinkaurelius/titan/commit/33a560db97bf3187ac45d1fe4fdf2e6b817bec40).

This seems to happen only when I'm executing several commands in parallel. I don't currently have any good way to consistently reproduce it.

**Comment by mbroecheler** [comment]
Hey Zach,

I have seen this exception before and made a change to EdgeSerializer a few
commits ago. Titan now reliably passes the concurrency tests. Could you try
with the head of the titan03 branch and see if it comes up again? I am not
100% confident that I have fixed this problem completely.

Best,
Matthias

On Sat, May 4, 2013 at 8:17 AM, Zach Kinstner notifications@github.comwrote:

> RexConnectServer query:
> 
> {
>   "reqId":"8f24b5f1-4b15-4b8f-a8e9-a1f80a496d9a",
>   "cmdList":[{
>     "cmd":"query",
>     "args":["g.V('A_AId',_P0);","{\"_P0\":40}"]
>   }]}
> 
> Returned the following RexProException message:
> 
> An error occurred while processing the script for language [groovy]. All
> transactions across all graphs in the session have been concluded with
> failure: javax.script.ScriptException:
> com.esotericsoftware.kryo.KryoException: Buffer underflow.\nSerialization
> trace:\nname
> (com.thinkaurelius.titan.graphdb.types.StandardKeyDefinition)","cmdList":[]}
> 
> I'm using Rexster 2.4.0-SNAPSHOT and Titan 0.3.1-SNAPSHOT. The Rexster
> build is more recent, but the Titan build is older, around the time of the
> #222 https://github.com/thinkaurelius/titan/issues/222 fix (33a560dhttps://github.com/thinkaurelius/titan/commit/33a560db97bf3187ac45d1fe4fdf2e6b817bec40
> ).
> 
> This seems to happen only when I'm executing several commands in parallel.
> I don't currently have any good way to consistently reproduce it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/259
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by zachkinstner** [comment]
It's looking good so far with the latest Titan build -- I think it's safe to close this ticket. Thanks!
