### ISSUE TITLE
Document & monitor diskstorage.locking.consistentkey package

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#261]
- Explaining how locking is achieved. Use comments written in #69 as a starting point
- JavaDoc for classes
- Add monitoring hocks

**Comment by dalaro** [comment]
Monitoring hooks now has its own issue: #268 

In db73354894a076eeadbe6a361745e3c9c8592dc7 and a few smaller subsequent commits, I fleshed out and updated the Javadocs for diskstorage.locking.consistentkey.  I also added a package-info.java file in titan-core/.../diskstorage/locking/consistentkey that briefly describes how to use the locking code from a client perspective and how the locking protocol works internally, including a discussion of the lockstore data format and timing constraints.
