### ISSUE TITLE
Warn: you are using a buggy JRE and cassandra issue

### ISSUE THREAD

**Issue by vallettea** [thinkaurelius/titan#262]
when launching a titan cassandra server I get the following warning:

13/05/06 16:36:33 WARN service.CacheService: MemoryMeter uninitialized (jamm not specified as java agent); KeyCache size in JVM Heap will not be calculated accurately. Usually this means cassandra-env.sh disabled jamm because you are using a buggy JRE; upgrade to the Sun JRE instead

but:
MacAV:~ vallette$ java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06-451-10M4406)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01-451, mixed mode)

so I guess the warning is linked to this cassandra bug:
https://issues.apache.org/jira/browse/CASSANDRA-2787

**Comment by zachkinstner** [comment]
See [these notes](https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#removing-jamm-warning-messages) to resolve this warning:

> Cassandra uses a Java agent called MemoryMeter which allows it to measure the actual memory use of an object, including JVM overhead. To use JAMM (Java Agent for Memory Measurements), the path to the JAMM jar must be specific in the Java javaagent parameter when launching the JVM.

**Comment by vallettea** [comment]
thanks
