### ISSUE TITLE
Question on Graph Initialization

### ISSUE THREAD

**Issue by neilchaudhuri** [thinkaurelius/titan#265]
I have been told that a Titan graph can be built by simply "pointing to data in Hadoop." Regardless of the lack of precision of that statement, I do not see any evidence in the documentation that indicates that a Titan graph can be initialized with data in HDFS or Hive. Rather, the only way I have found is to construct a graph "manually" (with the TItanGraph API) and have Titan store the data in the configured backend.

Is this correct? Or is there in fact a way to "point" Titan to a set of data to build the graph?

Thanks.

**Comment by okram** [comment]
Please see Faunus (http://faunus.thinkaurelius.com). Faunus provides tools for importing/exporting graphs to/from Hadoop.

https://github.com/thinkaurelius/faunus/wiki/Titan-Format

**Comment by mbroecheler** [comment]
Also, please use our mailing list aureliusgraphs@googlegroups.com for
questions.

On Mon, May 6, 2013 at 3:38 PM, Marko A. Rodriguez <notifications@github.com

> wrote:
> 
> Please see Faunus (http://faunus.thinkaurelius.com). Faunus provides
> tools for importing/exporting graphs to/from Hadoop.
> 
> https://github.com/thinkaurelius/faunus/wiki/Titan-Format
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/265#issuecomment-17512771
> .

## 

Matthias Broecheler
http://www.matthiasb.com
