### ISSUE TITLE
GraphConfigurationContainer - Could not load graph

### ISSUE THREAD

**Issue by zachkinstner** [thinkaurelius/titan#267]
Setup:
- Rexster 2.4.0
- Titan 0.3.1 (from [this commit](https://github.com/thinkaurelius/titan/commit/e8280480d0830cfb3db4288d8f0dba8ca1a4c037))
- Embedded Cassandra
- 3-node cluster
- Replication factor = 3

Every time I start up Rexster (roughly simultaneously on all nodes), at least one (usually the first) node gives me the following warning. The problem goes away once I restart Rexster on the node with the failure.

```
[WARN] GraphConfigurationContainer - Could not load graph Fabric. Please check the XML configuration.
[WARN] GraphConfigurationContainer - GraphConfiguration could not be found or otherwise instantiated: [com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration]. Ensure that it is in Rexster's path.
[WARN] GraphConfigurationContainer - Could not initialize backend
```

**Comment by zachkinstner** [comment]
This seems related to #236.

**Comment by spmallette** [comment]
are you saying that you are running titan.sh (embedded cassandra) and then trying to connect to it from a different rexster instance?

**Comment by zachkinstner** [comment]
I'm not sure if I understand what you're asking... here are some more details:

I don't currently work directly with Titan or `titan.sh`. Titan+EmbeddedCassandra starts up automatically when I start Rexster with `rexster.sh -s`.  At that point, I can use Rexster REST or RexPro/RexConnect to communicate with the graph.

Here's the graph portion of my `rexster.xml` configuration:

``` xml
        <graph>
            <graph-name>Fabric</graph-name>
            <graph-type>com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration</graph-type>
            <graph-location>data/Fabric</graph-location>
            <graph-read-only>false</graph-read-only>
            <properties>
                <storage.keyspace>fabric</storage.keyspace>
                <storage.backend>embeddedcassandra</storage.backend>
                <storage.cassandra-config-dir>file:///root/fabric/dsc-cassandra-1.2.2/conf/cassandra.yaml</storage.cassandra-config-dir>
                <storage.replication-factor>3</storage.replication-factor>
                <buffer-size>1024</buffer-size>
            </properties>
            <extensions>
                <allows>
                    <allow>tp:gremlin</allow>
                </allows>
            </extensions>
        </graph>
```

**Comment by zachkinstner** [comment]
The `graph-location` tag seems out-of-place here. I'll remove that and see what happens.

**Comment by spmallette** [comment]
ah...i see.  that's basically what i was asking. i don't believe that this is a supported configuration option.  i don't think you can start an embedded cassandra inside of a rexster container.  any reason you are not using Titan Server (titan.sh -https://github.com/thinkaurelius/titan/wiki/Titan-Server) which basically runs titan+cassandra+rexster in the same jvm (which appears to be what you are trying to do)?

**Comment by zachkinstner** [comment]
Removing `graph-location` didn't help.  I'm finding that the failures sometimes occur on more than just the first-started node, and sometimes take more than one Rexster restart to resolve.

Regarding my configuration, I'm using the [Titan Embedded Mode](https://github.com/thinkaurelius/titan/wiki/Using-Cassandra#titan-embedded-mode) approach:

> When running a cluster with Titan and Cassandra embedded, it is advisable to expose Titan through the Rexster server so that applications can remotely connect to the Titan graph database and execute queries. To make this setup easy and simple, Titan comes packaged with Titan Server.

Regarding the part about Titan Server, does this mean I should stop using Rexster Server and use Titan Server instead?

**Comment by zachkinstner** [comment]
> any reason you are not using Titan Server

No reasons anymore :smile:.  I didn't realize that the Rexster/RexPro functionality is already included within Titan Server.

**Comment by spmallette** [comment]
yes...you get all the same benefit of rexster (except dog house).  you can still deploy extensions, connect via rexster console, do REST, do rexpro.
