### ISSUE TITLE
Index query fails

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#279]
Index queries fail when you use at least two equality filter conditions for two indexed properties. Problem is described [here](https://groups.google.com/forum/#!topic/aureliusgraphs/sXjw-JTwHsY) and [here](https://groups.google.com/forum/#!topic/aureliusgraphs/VPx0-K5W5gw). Additionally I just wanted to mention, that it works, when you only have one equality filter:

```
gremlin> g.query().has('job',EQUAL,'fur').has('filepath',NOT_EQUAL,'/foo/bar.txt').vertices()
==>v[80]
==>v[72]
==>v[76]
gremlin> g.query().has('job',EQUAL,'fur').has('filepath',EQUAL,'/foo/bar.txt').vertices()
Could not call index
```

**Comment by zachkinstner** [comment]
I just experienced this issue with a query in this format (using Gremlin 2.4.0-SNAPSHOT):

``` java
g.V("name", "zach").has("x", Tokens.T.eq, "y")
```

**Comment by dalaro** [comment]
I'm copying @dkuppitz's Gremlin script from the list to this issue because the script is so handy.

```
g = TitanFactory.open('bin/inmemory.local')

g.makeType().name('job').dataType(String.class).indexed(Vertex.class).unique(OUT).makePropertyKey()
g.makeType().name('filepath').dataType(String.class).indexed(Vertex.class).unique(OUT).makePropertyKey()
g.commit()

jobs =  ["far","fer","fir","for","fur"]
paths = ["/foo/bar.txt","/bar/foo.txt","/foo/bah.txt","/foo/baz.txt"]

jobs.each {
  job = it
    paths.each {
      g.addVertex('job':job,'filepath':it)
  }
}; g.commit()

g.query().has('job','fur').has('filepath','/foo/bah.txt').vertices()
(Exception follows)
```

Thanks, Daniel!

**Comment by dalaro** [comment]
I've attempted to patch this in fa5c1bffdf26f12b6f9c5330ea445c2d30b8a801 on titan03.  Please consider my changes experimental and potentially broken until Matthias reviews them.  He's much more familiar with this part of Titan than I am.  The changes needed seemed simple, which is partly why I'm concerned that I might be breaking some state invariant out of ignorance.

Given that disclaimer, I now get the following query results on @dkuppitz's test graph:

```
gremlin> g.query().has('job','fur').vertices()._().map()
==>{filepath=/foo/bar.txt, job=fur}
==>{filepath=/foo/baz.txt, job=fur}
==>{filepath=/foo/bah.txt, job=fur}
==>{filepath=/bar/foo.txt, job=fur}
gremlin> g.query().has('filepath','/foo/bah.txt').vertices()._().map()
==>{filepath=/foo/bah.txt, job=fur}
==>{filepath=/foo/bah.txt, job=far}
==>{filepath=/foo/bah.txt, job=fer}
==>{filepath=/foo/bah.txt, job=fir}
==>{filepath=/foo/bah.txt, job=for}
gremlin> g.query().has('job','fur').has('filepath','/foo/bah.txt').vertices()._().map()
==>{filepath=/foo/bah.txt, job=fur}
```

I'm running the full test suite on my box now.

**Comment by dalaro** [comment]
Following up on my last comment: the test suite did pass on my box.  I'd still consider my commit experimental and potentially broken until it's reviewed, though.
