### ISSUE TITLE
Change scope of log4j in pom.xml's

### ISSUE THREAD

**Issue by gjdev** [thinkaurelius/titan#280]
Please mark the dependencies log4j and slf4j-log4j12 as scope=provided or with optional=true in the pom.xml's. That would make it easier for projects that depend on titan to use another logging implementation over slf4j.

**Comment by dalaro** [comment]
Optional sounds good.  I think we want scope=runtime or at least scope=test rather than scope=provided, since we do use log4j output when debugging failing tests.  What do you think?

I can make this change in Titan, but some of Titan's dependencies still have non-optional compile-scoped dependencies on log4j.  I think both Rexster (depended on by titan-core) and Cassandra are in that category.

**Comment by gjdev** [comment]
Scope = runtime wouldn't help, the jars would remain transitive dependencies for dependent projects. Scope = test is what the slf4j faq suggest, so that's probably best. Scope = provided jars are available on the test-classpath, so you will still have log4j when debugging failing tests.

You're right about rexster directly depending on log4j (but shouldn't rexster be an optional dependency of titan-core?). In the case of Cassandra it actually looks like an unnecessary dependency that could be excluded: Cassandra uses slf4j in code.

**Comment by dalaro** [comment]
> Scope = runtime wouldn't help, the jars would remain transitive dependencies for dependent projects.

We agree on optional=true.  Won't that kill dependency transitivity regardless of scope?  That's how I interpreted the [Maven docs on optional](http://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#How_do_optional_dependencies_work).  I think scope=test and scope=runtime will probably be practically indistinguishable for Titan, but I wonder if I've misunderstood something now...

**Comment by gjdev** [comment]
Yes if optional=true and scope=runtime, that should work. With scope=test you don't need to set optional. The scope setting might affect how distributions are build, so you may want to double-check that a distribution build still includes the log4j bindings.
