### ISSUE TITLE
AbstractElement.equals

### ISSUE THREAD

**Issue by gmcfall** [thinkaurelius/titan#286]
Sometimes, the following class cast exception occurs...

java.lang.ClassCastException: com.thinkaurelius.titan.graphdb.types.system.SystemKey cannot be cast to com.thinkaurelius.titan.graphdb.internal.AbstractElement
    at com.thinkaurelius.titan.graphdb.internal.AbstractElement.equals(AbstractElement.java:40)

Here's the source code...

 public boolean equals(Object other) {
        if (this==other) return true;
        else if (other==null) return false;
        if (((this instanceof TitanVertex) && (other instanceof TitanVertex)) ||
                ((this instanceof TitanEdge) && (other instanceof TitanEdge)))
            return getID()==((AbstractElement)other).getID();
        else return false;
    }

Notice that "other" is being cast as an (AbstractElement) without first checking to see if it is an instance of AbstractElement.  This unsafe cast should be fixed.

**Comment by dalaro** [comment]
I patched titan03 to remove the unchecked cast.  The new equals() should be safe to call on objects of any type.  However, I wonder if comparing SystemKey to AbstractElement subclasses could be indicative of a failed assumption somewhere else in the Titan source.  Would you please paste the full exception stacktrace?
