### ISSUE TITLE
Why does this warning message happen twice? (During vertex iteration with no indices)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#288]
``` text
gremlin> g = TitanFactory.open('bin/cassandra.local')
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.addVertex([name:'marko'])
==>v[4]
gremlin> g.V('name','marko')
13/05/22 18:32:26 WARN transaction.StandardTitanTx: Query requires iterating over all vertices [(v[36028797018963978]=marko)]. For better performance, use indexes
13/05/22 18:32:26 WARN transaction.StandardTitanTx: Query requires iterating over all vertices [(v[36028797018963978]=marko)]. For better performance, use indexes
==>v[4]
gremlin>
```

**Comment by okram** [comment]
This is Titan 0.3.1.

**Comment by dalaro** [comment]
Titan's `QueryProcessor` iterator appears to precompute the first `next()` result during construction.  Two such iterators are instantiated in the constructor for `GremlinPipeline`:

```
public GremlinPipeline(final Object starts, final boolean doQueryOptimization) {
    super(new StartPipe(starts));
    this.doQueryOptimization = doQueryOptimization;
    FluentUtility.setStarts(this, starts);
}
```

The first is instantiated inside the `StartPipe` constructor (first line of GP constructor).  The second is instantiated inside `FluentUtility.setStarts(...)` (last line of GP constructor).  Each iterator precomputes a result, generating the warning you showed in the Gremlin output twice.

I don't understand why both `GremlinPipeline` and its `StartPipe` need separate iterators over `starts`.  Can you help me understand why that is?

It seems that deduplicating this warning might involve some combination of altering Titan's `QueryProcessor#getUnwrappedIterator()` to stop eager precomputation of `next()` values and/or altering `GremlinPipeline` to use only a single `starts` iterator (if the latter is even possible).

By the way, I could easily have made a mistake in that analysis.  The stacktrace for this warning is 73 frames deep and touches Pipes and Gremlin code that I've never looked at before.

**Comment by okram** [comment]
I fixed the double .iterator() call in Gremlin.
