### ISSUE TITLE
ThreadedTransactionalGraph and Type Maker

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#289]
Is there a possible problem when introducing a new property key via a `TransactionalGraph` spawned from `newTransaction()`?  I tried to recreate the problem (something I've experienced while writing unit tests) in the Gremlin REPL, but couldn't.  I've been seeing this issue with BerkeleyDB, but perhaps it is possible to recreate it with the other backends.

Here's a rough synopsis of what I see happening:
1. Start with a brand new empty graph
2. Two or more threads call `newTransaction()` (think a REST based server like Rexster receiving multiple requests each processing in its own thread)
3. Each thread has a lot of small bits of work to do so it sometimes delegates that to some other threads.  The thread handling the requests and the other threads it spawns add vertices/edges, set properties, etc.
4. Very quickly I see "java.lang.IllegalArgumentException: The given value is already used as a property and the property key is defined as in-unique"...which is interesting because no types have been defined.

I've found that the only workaround to this problem is to initialize all the property keys ahead of time before any other processing begins...something like follows:

``` text
tg.makeType().name("name").dataType(String.class).unique(Direction.OUT, TypeMaker.UniquenessConsistency.NO_LOCK).makePropertyKey()
```

If I do that for every property key I intend to use, then everything works properly.

**Comment by dalaro** [comment]
[TransactionTitanGraphTestSuite](https://github.com/thinkaurelius/titan/blob/master/titan-test/src/main/java/com/thinkaurelius/titan/blueprints/TransactionalTitanGraphTestSuite.java) also does what you did.  That contains a comment reading "Need to define types before hand to avoid deadlock in transactions" underneath which it makes a bunch of property keys and then starts a bunch of threads that use the property keys.

Maybe we should synchronize this for protection against concurrent access.

**Comment by dalaro** [comment]
Are you passing TypeMaker between threads?  Or does each thread get its own TypeMaker by calling tg.makeType()?

**Comment by spmallette** [comment]
Using `synchronize` sounds like the right way to go.  regarding:

> Are you passing TypeMaker between threads? Or does each thread get its own TypeMaker by calling tg.makeType()?

I'm not passing TypeMaker explicitly.  I only included that line of code to show what i do in a single thread prior to starting the application touching the fresh graph.  In doing that, things work fine. 

My guess from following the Titan code (which I still don't know very well) is that the default TypeMaker gets called when `setProperty` is called:

https://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/vertices/AbstractVertex.java#L209

If the key passed in does not exist then it is created with some defaults by that type maker.  I'm further guessing that if two threads try to create that type at the same time you get the error I end up seeing.

**Comment by okram** [comment]
We had a big time sync that I believe is related to this problem.

We were bulk loading data into Titan/HBase with Faunus. We accidently forgot to add one of the property keys as a type. The property key was "value". The data loaded correctly, but when we did this in Titan/Gremlin terminal we got this weird behavior.

``` text
gremlin> g = TitanFactory.open('bin/hbase.local')
gremlin> g.v(4).value
==>null
gremlin> g.v(4).map
==>{value="22344224", amount=0}
gremlin> g.v(4).value
==>22344224
```

We were like "bawaaah?" ... After realized we forgot to add "value" to our Schema.groovy file, we reparsed and it worked correctly. Note we could not reproduce the behavior when I added data to Titan/HBase from the Gremlin terminal. I believe its cause of the single threaded nature of my test. With parallel writing from Faunus (and not type defined), the behavior is readily realized.

Anywho, if anything, this is a heads up to anyone that sees this.

**Comment by mbroecheler** [comment]
@okram: Did you have batch loading enabled when you were loading the data. That would explain the weirdness you were seeing. With batch loading enabled, existing types would get silently overwritten (since locking is disabled - that's why you weren't seeing the exception that Stephen got) and the database ended up in an inconsistent state.

I think what we should do is this:
Whenever batch-loading is enabled, Titan automatically disables automatic creation of types. That is, if you forget to pre-define a type prior to batch loading you would get an exception.
WDYT?

**Comment by okram** [comment]
> @okram: Did you have batch loading enabled when you were loading the data. That would explain the weirdness you were seeing. With batch loading enabled, existing types would get silently overwritten (since locking is disabled - that's why you weren't seeing the exception that Stephen got) and the database ended up in an inconsistent state.
> 
> Yes. Faunus does the batch-loading=true.
> 
> I think what we should do is this:
> Whenever batch-loading is enabled, Titan automatically disables automatic creation of types. That is, if you forget to pre-define a type prior to batch loading you would get an exception.
> WDYT?

That makes sense. SchemaInferencer does that job in Faunus so that makes sense to me.

**Comment by spmallette** [comment]
Lost a lot of time on this issue again.  I should have recognized the problem, but I didn't make the connection immediately.  This issue does not seem to occur just with `TransactionalGraph`.  It was the source of this problem as well where i don't think @zcox was using `TransactionalGraph` at all:

https://groups.google.com/forum/#!topic/aureliusgraphs/BeGJ6k6saMs

**Comment by mbroecheler** [comment]
I have implemented a check that disables automatic creation of types when @batch-loading@ is enabled. AFAIK, this problem arises when multiple threads operate on a graph and attempt to automatically create a new type (label or key) that hasn't been defined up front. Normally, this would cause locking exceptions, however when batch-loading is enabled no exceptions are thrown and things get overwritten which causes havoc.
@spmallette  can you verify that this solves the issue for you as well? Thanks!

**Comment by spmallette** [comment]
In a way, automatic type creation is a good and bad thing.  it's good because new users have no clue what's going on with types so it gets them started, but it's bad because you almost never want automatic types happening in production. I know there's a configuration one can set that controls automatic type creation, but usually by that point you've learned too late the importance of types and production is full of auto-typed stuff.

That aside, disabling automatic type creation on `batch-loading` should fix a percentage of the problems (it would NOT have saved us from the time spent digging into this problem, that prompted this issue), but I think that a majority of people will still struggle here.  If you don't follow the convention of creating types first (for example, having a Schema class that can init all the types and having that Schema class execute on test creation) then this failure will still be a plague.  

Is synchronization out of the question for this somehow?

**Comment by mbroecheler** [comment]
@spmallette Can you elaborate a little more on why this wouldn't solve the issue you were seeing. In the ticket description, the seen exception was a conflict due to in-uniqueness. This is interesting, because the default type maker never creates in-unique property keys. Might it have been a conflict on out-uniqueness? I see that in your key definition you are setting UniquenessConsistency to NO_LOCK which would solve the concurrent property modification problem.

**Comment by spmallette** [comment]
if i understood the change you made properly, you made it so that batch-loading does not use automatic type creation.  when the error occurred, I wasn't batch-loading, so i assume the error would still have been present.  

i'm not sure you're reading my issue right.  looking back at what i wrote on it, i was just trying to say that defining the types in a single thread, up front (before loading data of any sort) prevents the problem (the fact that the example code for the type maker used NO_LOCK really wasn't relevant to the problem, because the error occurred on type creation and not on insertion of new data).  I think creating types up front in a single thread is the right convention that people should follow, but this convention isn't enforced by titan by default, so i think people will still be surprised by the error when it pops up.  

does that help clarify?

**Comment by mbroecheler** [comment]
Aaaaah, now I got you. You got the error because multiple threads were automatically defining the same types and hence you got an in-unique exception since type names are always unique. Gotcha.

There is nothing we can do about that, since Titan is definitely right in throwing that exception. Synchronizing won't help either, because the transaction won't announce the new type until commit. So, the best thing we can do it document this clearly. And write better tutorials.

**Comment by spmallette** [comment]
you got it.  my initial description of the problem was somewhat a few steps away from where i ultimately realized the problem was.  if synchronization won't help, the we'll have to rely on documentation like you say.  if folks follow the proper conventions they shouldn't have problems.

**Comment by mbroecheler** [comment]
Exactly. The good thing about your scenario is that you got the exception
at the right point and it did not impact or corrupt the graph in any way.
That was the scary part about having batch-loading enabled - then the
problem does not appear when the types are automatically defined but later
when you read data.

On Fri, Sep 27, 2013 at 11:14 AM, stephen mallette <notifications@github.com

> wrote:
> 
> you got it. my initial description of the problem was somewhat a few steps
> away from where i ultimately realized the problem was. if synchronization
> won't help, the we'll have to rely on documentation like you say. if folks
> follow the proper conventions they shouldn't have problems.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/289#issuecomment-25265394
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by zcox** [comment]
+1 for clearly documenting this behavior (multiple threads concurrently trying to create default types) as well as the best practice (define all types up-front single-threaded). 

Even with the above, this will still happen. Any way to provide a more descriptive message in the exception when this does occur? I think that would really help new users diagnose things.
