### ISSUE TITLE
Make graph.getVertices() an UnsupportedOperationException.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#29]
This distinction between "get all vertices in transaction" and "get all vertices in graph" seems to be confusing people. Best to simply throw an unsupported operation exception to make things clear.

**Comment by diegovar** [comment]
What would be the way of getting a graph given a property value if there is an index on that property? Doing
g.getVertices("name", "hercules") returns an empty list from Java code

**Comment by okram** [comment]
If you have created a key index of "name" on Vertex.class, then g.getVertices("name","hercules") will return all vertices that have a name property of "hercules."

**Comment by diegovar** [comment]
I am running titan on top of Cassandra locally.
In the gremlin prompt I can run
g.V('name','hercules').name
Which correctly returns "hercules". However, from Scala code I run

```
val conf = new BaseConfiguration()
conf.setProperty("storage.backend","cassandra")
conf.setProperty("storage.hostname","127.0.0.1")
val g = TitanFactory.open(conf)
assert(g.getVertices.asScala.size > 0)
assert(g.getVertices("name", "jupiter").asScala.size > 0)
```

And the first assert fails. I have also tried creating a Transaction via g.startTransaction and doing the operation on the transaction, but that fails as well.

**Comment by okram** [comment]
g.getVertices() is only respective of the currently transaction (which is different than g.getVertices(key,value)). To reduce confusion, this ticket will NOT make g.getVetices() a legal operation.

Regarding your getVertices(key, value) problem -- this is not the appropriate ticket as this is with respect to graph.getVertices().

Please provide another ticket with appropriate steps to reproduce your problem. Also, please do not include Scala code -- raw Java or Gremlin/Groovy.

Thanks,
Marko.
