### ISSUE TITLE
[URGENT] update to 0.3.1 failed - waiting for id renewal

### ISSUE THREAD

**Issue by advancedlogic** [thinkaurelius/titan#291]
it's one day and a half I am literally fighting with titan 0.3.1
I have updated ElasticSearch to version 0.90.0 and titan to 0.3.1 using maven.
I already set ids.block-size to 250000 but nothing changed.
I tried using Cassandra 1.2.2 as suggested (I was using the last version 1.2.5) but nothing changed.  What am I doing wrong?
Below the exceptions

26:35 [main] INFO  org.elasticsearch.plugins  - [Shamrock] loaded [], sites []
26:35 [main] DEBUG org.elasticsearch.common.compress.lzf  - using [UnsafeChunkDecoder] decoder
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [generic], type [cached], keep_alive [30s]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [index], type [fixed], size [8], queue_size [null], reject_policy [abort], queue_type [linked]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [bulk], type [fixed], size [8], queue_size [null], reject_policy [abort], queue_type [linked]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [get], type [fixed], size [8], queue_size [null], reject_policy [abort], queue_type [linked]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [search], type [fixed], size [16], queue_size [1k], reject_policy [abort], queue_type [linked]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [percolate], type [fixed], size [8], queue_size [null], reject_policy [abort], queue_type [linked]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [management], type [scaling], min [1], size [5], keep_alive [5m]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [flush], type [scaling], min [1], size [4], keep_alive [5m]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [merge], type [scaling], min [1], size [4], keep_alive [5m]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [refresh], type [scaling], min [1], size [4], keep_alive [5m]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [warmer], type [scaling], min [1], size [4], keep_alive [5m]
26:36 [main] DEBUG org.elasticsearch.threadpool  - [Shamrock] creating thread_pool [snapshot], type [scaling], min [1], size [4], keep_alive [5m]
26:36 [main] DEBUG org.elasticsearch.transport.netty  - [Shamrock] using worker_count[16], port[9300-9400], bind_host[null], publish_host[null], compress[false], connect_timeout[30s], connections_per_node[2/6/1], receive_predictor[512kb->512kb]
26:36 [main] DEBUG org.elasticsearch.client.transport  - [Shamrock] node_sampler_interval[5s]
26:36 [elasticsearch[Shamrock][transport_client_worker][T#1]{New I/O worker #1}] DEBUG netty.channel.socket.nio.SelectorUtil  - Using select timeout of 500
26:36 [elasticsearch[Shamrock][transport_client_worker][T#1]{New I/O worker #1}] DEBUG netty.channel.socket.nio.SelectorUtil  - Epoll-bug workaround enabled = false
26:36 [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex  - Configured remote host: 127.0.0.1 : 9300
26:36 [main] DEBUG org.elasticsearch.client.transport  - [Shamrock] adding address [[#transport#-1][inet[/127.0.0.1:9300]]]
26:36 [elasticsearch[Shamrock][management][T#1]] DEBUG org.elasticsearch.transport.netty  - [Shamrock] connected to node [[#transport#-1][inet[/127.0.0.1:9300]]]
26:36 [main] DEBUG org.elasticsearch.transport.netty  - [Shamrock] connected to node [[Diablo][F_ytw5fSS-eYBQepVcqlnw][inet[/xxx.yyy.zzz.kkk:9300]]]
27:06 [main] DEBUG com.thinkaurelius.titan.diskstorage.common.DistributedStoreManager  - Set rid: 0x7f0000013230303331406c6f63616c686f73742e6c6f63616c646f6d61696e
27:06 [main] DEBUG com.thinkaurelius.titan.diskstorage.common.DistributedStoreManager  - Set rid: 0x7f0000013230303331406c6f63616c686f73742e6c6f63616c646f6d61696e
27:06 [main] DEBUG com.thinkaurelius.titan.diskstorage.locking.consistentkey.LocalLockMediators  - Local lock mediator instantiated for namespace astyanax[xxxxxxx@127.0.0.1:9160]:edgestore
27:06 [main] DEBUG com.thinkaurelius.titan.diskstorage.locking.consistentkey.LocalLockMediators  - Local lock mediator instantiated for namespace astyanax[xxxxxxx@127.0.0.1:9160]:vertexindex
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner  - Partition IDs? [false], Local Partitions? [false]
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.query.QueryProcessor  - Optimized query [[v[-2]](OUT,null,[com.thinkaurelius.titan.graphdb.types.system.SystemKey@1ddaf92])-():false:PROPERTY] into 0 subqueries
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.query.QueryProcessor  - Optimized query [[v[-2]](OUT,null,[com.thinkaurelius.titan.graphdb.types.system.SystemKey@1ddaf92])-():true:PROPERTY] into 1 subqueries
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.query.TitanGraphQueryBuilder  - Best index for query [[(com.thinkaurelius.titan.graphdb.types.system.SystemKey@1ddaf92=score)]:VERTEX]: standard
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.query.QueryProcessor  - Optimized query [[(com.thinkaurelius.titan.graphdb.types.system.SystemKey@1ddaf92=score)]:VERTEX] into 1 subqueries
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Answering query [[(com.thinkaurelius.titan.graphdb.types.system.SystemKey@1ddaf92=score)]:VERTEX] with index standard
27:06 [main] DEBUG com.thinkaurelius.titan.diskstorage.keycolumnvalue.CachedKeyColumnValueStore  - Cache Retrieval on vertexindex. Attempts: 0 | Misses: 0
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Starting id block renewal thread upon 0
27:06 [main] DEBUG com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [0 ms]
27:07 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [1000 ms]
27:08 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [2001 ms]
27:09 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [3001 ms]
27:10 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [4001 ms]
27:11 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [5002 ms]
27:12 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [6002 ms]
27:13 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [7002 ms]
27:14 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [8003 ms]
27:15 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [9003 ms]
27:16 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [10003 ms]
27:17 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [11003 ms]
27:18 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [12004 ms]
27:19 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [13004 ms]
27:20 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [14005 ms]
27:21 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [15005 ms]
27:22 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [16005 ms]
27:23 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [17006 ms]
27:24 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [18006 ms]
27:25 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [19007 ms]
27:26 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [20007 ms]
27:27 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [21007 ms]
27:28 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [22008 ms]
27:29 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [23008 ms]
27:30 [main] WARN  com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Waiting for id renewal thread on partition 2 [24008 ms]
Exception in thread "Thread-2" java.lang.IllegalArgumentException: timeout value is negative
    at java.lang.Thread.sleep(Native Method)
    at com.netflix.astyanax.retry.SleepingRetryPolicy.allowRetry(SleepingRetryPolicy.java:39)
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:267)
    at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1.execute(ThriftColumnFamilyQueryImpl.java:175)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:117)
    at com.thinkaurelius.titan.diskstorage.idmanagement.ConsistentKeyIDManager.getCurrentID(ConsistentKeyIDManager.java:83)
    at com.thinkaurelius.titan.diskstorage.idmanagement.ConsistentKeyIDManager.getIDBlock(ConsistentKeyIDManager.java:109)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.renewBuffer(StandardIDPool.java:110)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.access$100(StandardIDPool.java:14)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool$IDBlockThread.run(StandardIDPool.java:171)

.....
....
....

And when the titan try to create a new Vertex or test if it exists:

Uncaught exception
java.lang.IllegalArgumentException: -1
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:87)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:133)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:264)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:156)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:188)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addPropertyInternal(StandardTitanTx.java:404)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.setProperty(StandardTitanTx.java:435)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addProperty(StandardTitanTx.java:379)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.addProperty(AbstractVertex.java:198)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:256)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addVertex(TitanBlueprintsTransaction.java:54)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addVertex(TitanBlueprintsGraph.java:133)
    at org.octopus.store.Titan.getOrCreateVertexFromOctoNode(Titan.java:200)
    at org.octopus.store.Titan.connect(Titan.java:50)
    at org.octopus.processors.TitanStorer.process(TitanStorer.java:80)
    at org.octopus.engine.Cruncher.run(Cruncher.java:41)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

**Comment by dalaro** [comment]
The commit I pushed is for the negative sleep time exception in your log dump, but that seems like a peripheral concern here.  The main concern is why Titan is taking 25+ seconds to get an ID allocation from Cassandra.

Can you describe a bit more about your deployment?  Is it an upgrade from, for instance, 0.3.0 and some other Cassandra version?  Or is it a new installation of Titan 0.3.1?  Is the Cassandra ring all up and can you connect to the Cassandra cluster from the machine running Titan?  Is this failure is reproducible?  What steps does the Titan client take to induce it?

**Comment by advancedlogic** [comment]
Thanks for your kind reply. I was able to fix it a couple of hour ago and now it's under test.
There was a Cassandra wrong settings in cassandra.yaml and some maven library intellij did not import correctly :( … 
in any case it has been really hard to find out the reason. A lot of debugging inside your code (very nice code in any case :) ) …
At the end I tried first running embedded cassandra and it worked, then I decided to use you cassandra.yaml file (I just changed the RPC setting from sync to hahs).
Still having problem with locks on vertices but I still have to test the multithread transactions features.
Very good library indeed.

**Comment by dalaro** [comment]
Glad the config issue is resolved.

Regarding that "problem with locks on vertices" -- this sounds alarming and is unfortunately vague.  If you'd like to discuss it further, then please open another ticket about the problem with additional details and/or stacktraces.  Thanks.
