### ISSUE TITLE
Per transaction configuration of LockMode for Berkeley

### ISSUE THREAD

**Issue by gjdev** [thinkaurelius/titan#293]
Currently when using the Berkeley backend, it is not possible to have concurrent transactions that do mutations on the same data, without getting PermanentStorageException (caused by sleepycat LockTimeOutException). That's because in the typical read-modify-write logic imposed by Titan, the concurrent transaction will deadlock when they try to promote their locks from READ to WRITE. (Which will lead to LockTimeoutException for all but one of the concurrent transactions).

The way to prevent these timeout exceptions is to use LockMode.RMW in transactions that mutate data. It's currently impossible to configure that with Titan.

This is request is related to #71.

**Comment by dalaro** [comment]
cc2b3a5bf6edc5599a506f9eda5e01018466b9a6 on titan05 adds a `storage.lock-mode` option that accepts any of the BDB LockMode enum values (DEFAULT, READ_UNCOMMITTED, READ_COMMITTED, RMW).

Similar to #71, the option can be set two ways:

In the transaction configuration, e.g. `g.buildTransaction().setCustomOption("storage.lock-mode", "RMW").start()`.

In the graph configuration, e.g. `storage.lock-mode=RMW` in titan's properties file, which becomes the default LockMode for all transactions that don't specify their own LockMode as shown above.
