### ISSUE TITLE
Text.CONTAINS is token based

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#296]
In some other trials, I found an interesting result: a partial-text search works (case-sensitive) if the property is not indexed:

g.makeType().dataType(String.class).name("test").unique(OUT).makePropertyKey();
g.addVertex([test: "Elastic"]);
g.query().has("test", com.thinkaurelius.titan.core.attribute.Text.CONTAINS, "E").vertices(); //works
g.query().has("test", com.thinkaurelius.titan.core.attribute.Text.CONTAINS, "e").vertices(); //no results

Since it isn't indexed, this creates the following Titan warnings:

13/05/19 13:54:57 WARN transaction.StandardTitanTx: Query requires iterating over all vertices [(v[36028797018963978]CONTAINSE)]. For better performance, use indexes
13/05/19 13:57:08 WARN transaction.StandardTitanTx: Query requires iterating over all vertices [(v[36028797018963978]CONTAINSe)]. For better performance, use indexes

**Comment by zachkinstner** [comment]
Thanks Matthias -- from [this discussion](https://groups.google.com/forum/?fromgroups#!topic/aureliusgraphs/0ZQLoYtjC0g).

**Comment by mbroecheler** [comment]
Fixed in https://github.com/thinkaurelius/titan/commit/cfecb0c85cf2539eb2bc01c90a83e7f3572d57d6
All Text.\* predicates now tokenize first.
