### ISSUE TITLE
Provide HadoopGraph implementation...

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#3]
Per this issue:
  https://github.com/tinkerpop/blueprints/issues/247

This way other packages such as Faunus can deal with a HadoopGraph and not need to write one off Reader/Writer solutions as any graph that implements HadoopGraph will provide appropriate implementations.

**Comment by mbroecheler** [comment]
This is a feature request, right?

**Comment by okram** [comment]
this was just a note from back in the day. sorry -- i will formulate it better.

http://markorodriguez.com

**Comment by okram** [comment]
Closing. Will open when better articulated.
