### ISSUE TITLE
Querying Titan using Labels

### ISSUE THREAD

**Issue by dbxfb** [thinkaurelius/titan#30]
Hi,

I would be interested in querying Titan for an Iterable(TitanEdge) using a TitanLabel as argument (finding all edges with the given type).

As I could not find a way to do it: is there currently any way to do it, and if not can it be done ? 
they way I understand things, Titan should be indexing my edge labels and thus doing TitanLabel queries should be feasible)

Thanks !

**Comment by mbroecheler** [comment]
Hey Dan,

Titan does not currently support global edge retrievals but only vertex centric edge retrievals. So, given a vertex you can retrieve all of its edges for a particular label, for instance.

**Comment by dbxfb** [comment]
All right, thanks for the quick answer.
