### ISSUE TITLE
Problem with limit in Query API

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#305]
The problem is in the last query:

```
gremlin> g = TitanFactory.open('bin/inmemory.local')
==>titangraph[inmemory:null]
gremlin> g.makeType().name('vt').dataType(String.class).unique(OUT).indexed(Vertex.class).makePropertyKey()
==>v[36028797018963978]
gremlin> g.makeType().name('firstname').dataType(String.class).unique(OUT).makePropertyKey()
==>v[36028797018963986]
gremlin> g.commit()
==>null
gremlin> alice = g.addVertex(['vt':'user','firstname':'Alice'])
==>v[4]
gremlin> bob = g.addVertex(['vt':'user','firstname':'Bob'])
==>v[8]
gremlin> g.commit()
==>null
gremlin> g.query().has('vt','user').vertices()
==>v[4]
==>v[8]
gremlin> g.query().has('vt','user').has('firstname','Alice').vertices()
==>v[4]
gremlin> g.query().has('vt','user').has('firstname','Bob').vertices()
==>v[8]
gremlin> g.query().has('vt','user').has('firstname','Alice').limit(1).vertices()
==>v[4]
gremlin> g.query().has('vt','user').has('firstname','Bob').limit(1).vertices()
gremlin>
```

I suspect the set of users is limited without taking firstname into account.

**Comment by dalaro** [comment]
I didn't account for limits in fa5c1bffdf26f12b6f9c5330ea445c2d30b8a801 when working on #279.  As @dkuppitz inferred, the limit on graph queries is being erroneously applied to the index fetch without consideration for the additional unindexed conditions.

I wrote a unit test based on the gremlin script.  It failed as expected.  I then changed the graph query processor.  It now hits the backend with Query.NO_LIMIT when a query needs "filtering" (i.e. when a graph query's constraints cannot be completely satisfied using only an index retrieval).  If a query does not need filtering then we still hit the backend with the query limit.  After this test, the test passed when I tried it with BDB.

I'm running the full suite and plan on pushing to master shortly, assuming it passes.
