### ISSUE TITLE
getPropertyKey and getEdgeLabel should throw exceptions

### ISSUE THREAD

**Issue by dbxfb** [thinkaurelius/titan#31]
Hello !

I noticed that when doing

<pre>tx.getPropertyKey("someKey");</pre>

or

<pre>tx.getEdgeLabel("someLabel");</pre>

Instead of getting an <pre>IllegalArgumentException</pre> just like the documentation says, Titan silently creates the given type name and returns it.
This caused me a bit of trouble : albeit this was my bad for using getX()instead of getType(),
I think Titan should have angrily thrown exceptions at my face :D

Thanks,
Dan

**Comment by mbroecheler** [comment]
Hey Dan,
thanks for pointing out the inconsistency. whether or not titan throws an
exception in such a situation is actually configurable. I will document
this better.
Thanks,
Matthias
On Jun 27, 2012 7:22 AM, "Dan Forest-Barbier" <
reply@reply.github.com>
wrote:

**Comment by mbroecheler** [comment]
Hey Dan,

I have been going back and forth on how to approach this. Finally, the behavior will stay the same, i.e. types will be automatically created by default. This is what users of Blueprints would expect. However, for increased type safety you can set _autotype=none_ in the configuration which will throw exceptions like you expected. Hope this is a good compromise.

**Comment by dbxfb** [comment]
Sounds fine to me, thanks for taking this into account!
