### ISSUE TITLE
Titan cluster set up in embedded cassandra mode

### ISSUE THREAD

**Issue by akumarb2010** [thinkaurelius/titan#318]
Is there any documentation for setting up Titan Cluster with embedded Cassandra?

Is there any user mailing list for Titan?

And also I want to understand, how the graph partitioning(sharding) will be happen, in cluster mode? Is there any architecture documentation for this? I started going through source code, but it is taking time to understand.

**Comment by mbroecheler** [comment]
Please read the documentation in the wiki and use the mailinglist aureliusgraphs@googlegroups.com for questions.
