### ISSUE TITLE
Could we have the possibility to retry a failed transaction?

### ISSUE THREAD

**Issue by dbxfb** [thinkaurelius/titan#32]
Hi :)

Currently, when a transaction throws on commit/stopTransaction because of a locking error, everything gets destroyed and if I want to try again later I have to redo all of my previous computations in a new transaction... 

Would it be possible to have a tryCommitting method, or some way to backup the changes so that we can retry committing a changeset to Titan?
(I could do it manually... but it pretty much ruins everything and isn't very maintainable)

Thanks in advance,
Dan

**Comment by mbroecheler** [comment]
That's a good idea for an enhancement. If I understand you correctly, there would be two parameters: numRetries and waitTime, such that if Titan fails in committing a transaction, it will wait for waitTime milliseconds and then retry committing the transaction. It will do so numRetries times and only fail if all of these attempts fail.

Does that sound good?

**Comment by dbxfb** [comment]
Yep, that's exactly the feature I'd like to see :)

Maybe there could be a way to manually do it, by having "commit()" return a boolean (commited / failed) — but it could be an open door to leaks / beginner errors...
