### ISSUE TITLE
potential race in ES query over recently-committed vertex properties

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#320]
Jon Smoot reported this issue in the aureliusgraphs thread [elasticsearch queries stoped working after commit (from a Java app)](https://groups.google.com/d/msg/aureliusgraphs/nCIKkwiif-M/Hs_P-kQiIC4J).  Thanks, Jon!

I played around with this example locally in Java and Gremlin (except I inserted a g.commit() right after creating types).  It seems to be a race condition.  If I insert a `Thread.sleep(1000L)` between the final commit and query, then I get the expected vertex.  No sleep, no vertex.

The remainder of this issue is a verbatim copy of Jon's message.

Environment:
Titan 0.31, Embedded Cassandra, Embedded ElasticSearch

Performing the same Query before commit works, after commit returns nothing (but an INFO message from elasticsearch)

Java Code:

```
// Base config for embedded Cassandra, embedded ElasticSearch

        Configuration conf = new BaseConfiguration();
        conf.setProperty("storage.backend","embeddedcassandra");
        conf.setProperty("storage.cassandra-config-dir","file:///C:/ws/titan-all-0.3.1/config/cassandra.yaml");
        conf.setProperty("storage.index.search.backend","elasticsearch");
        conf.setProperty("storage.index.search.directory","/tmp/elasticsearch");
        conf.setProperty("storage.index.search.client-only",false);
        conf.setProperty("storage.index.search.local-mode",true);
        TitanGraph g = TitanFactory.open(conf);

// Create ES indexed type
        g.makeType().name("es_type").dataType(String.class).indexed("search", Vertex.class).unique(Direction.OUT).makePropertyKey();
        g.makeType().name("std_type").dataType(String.class).indexed("standard", Vertex.class).unique(Direction.OUT).makePropertyKey();
        Vertex v = g.addVertex(null);
        v.setProperty("es_type", "full text indexed message");
        v.setProperty("std_type", "standard indexed text");

// Pre commit everything works!
        System.out.println(" --- pre commit ---");
        Iterable<Vertex> vertices = g.query().has("es_type", Text.CONTAINS, "text").vertices();
        if (vertices != null){
            for (Vertex tmp : vertices){
                System.out.println(tmp.getProperty("es_type"));
            }
        }

// Do commit
        g.commit();

//Post commit - no results

        System.out.println(" --- post commit ---");
        vertices = g.query().has("es_type", Text.CONTAINS, "text").vertices();
        if (vertices != null){
            for (Vertex tmp : vertices){
                System.out.println(tmp.getProperty("es_type"));
            }
        }
```

Console output:

```
 --- pre commit ---
full text indexed message
 --- post commit ---
24910 [elasticsearch[Zero-G][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata  - [Zero-G] [titan] update_mapping [vertex] (dynamic)
```

**Comment by mbroecheler** [comment]
Is there anything we can do about that? I mean, it has to be expected that results added to elasticsearch are not immediately available (the same might even hold for Cassandra in a distributed environment).

**Comment by dalaro** [comment]
I thought about two potential options, but I don't really like either.

It's extraordinarily costly and doesn't scale, but there's  the `refresh` option for ES's bulk/update/index ops.  That would guarantee subsequent searchability.  But I don't have a reasonable use case for that.  If someone can show that exposing `refresh` solves an actual application problem with lots of property reads and nearly no writes, then I would be interested.

Alternatively, we could copy property writes in a hazelcast distributed map with entry ttls set to, say, 2 \* ES's index.refresh_interval.  Any such caching approach would inevitably be best-effort.  I think there's no hard limit on ES's actual refresh intervals, so we can't guarantee property search hits after committing a tx with ES updates, no matter the cache ttl.  Without that guarantee I don't think it's valuable.  The engineering complexity would make the query path even more elaborate.  And it would slow otherwise fast ES index hits to the speed of a hazelcast distributed map, even if we did both in parallel.  The best it could do, performance-wise, is make ES hits only very slightly slower.  This idea sucks on multiple levels.

I still don't like how `tx.commit()` is quietly asynchronous with respect to ES-indexed properties, but I also don't see anything we can do about it.
