### ISSUE TITLE
Problem connecting to external ElasticSearch cluster (which has two sets of public&private IPs)

### ISSUE THREAD

**Issue by yvesx** [thinkaurelius/titan#321]
I searched my error and couldnt find much either in titan or elasticsearch repo...
(in Using-Elastic-Search, this is mentioned `Also ensure that the machine running Titan can connect to the Elasticsearch instances over the network if the machines are physically separated.`)
So this is my setup. I have Titan on top of 10 non-embedded Cassandra node.

I also have 4 ES nodes (say ES-1,ES-2,ES-3,ES-4) that are in another network. The 4 ES nodes are connected with private IPs. For any of the Cassandra nodes to talk to ES nodes, it has to be done over public network.

So I have the following issue when enabling ES search...
The symptom looks like Titan cannot connect to ES nodes. but pls see my curl statements, the 4 ES nodes are reachable at port9200 (which is the one I use, not the default 9300)

My question is this: I have to provide Titan with ES nodes' public IPs b/c ES and Titan are on different networks. Does this mean ES-1 will try to talk to ES-2 using the same public IP provided to Titan? ES-1 should use the private network to talke to ES-2 not the public IPs provided to Titan. In my setting ES-1 cannot reach ES-2 over the public IPs on purpose.

I hope my question is clear. Please Let me know if this is entirely an ElasticSearch issue.
thank you very much.
I tried this in Gremlin shell.

```
backend: elasticsearch
hostname: [222.111.12.75:9200, 222.111.12.76:9200, 222.111.12.87:9200, 222.111.12.88:9200]
client-only: true

13/07/12 14:44:48 INFO elasticsearch.plugins: [Red Lotus] loaded [], sites []
13/07/12 14:44:49 INFO es.ElasticSearchIndex: Configured remote host: 222.111.12.75 : 9200
13/07/12 14:44:54 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-1][inet[/222.111.12.75:9200]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.75:9200]][cluster/state] request_id [0] timed out after [5001ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
13/07/12 14:44:54 INFO es.ElasticSearchIndex: Configured remote host: 222.111.12.76 : 9200
13/07/12 14:44:59 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-1][inet[/222.111.12.75:9200]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.75:9200]][cluster/state] request_id [1] timed out after [5000ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
13/07/12 14:45:04 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-1][inet[/222.111.12.75:9200]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.75:9200]][cluster/state] request_id [2] timed out after [5000ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
13/07/12 14:45:04 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-2][inet[/222.111.12.76:9200]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.76:9200]][cluster/state] request_id [3] timed out after [5001ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
13/07/12 14:45:04 INFO es.ElasticSearchIndex: Configured remote host: 222.111.12.87 : 9200
[download@social2 bin]$ 
[download@social2 bin]$ 
[download@social2 bin]$ curl 222.111.12.75:9200
{
  "ok" : true,
  "status" : 200,
  "name" : "es-1.incincinc.com",
  "version" : {
    "number" : "0.90.0",
    "snapshot_build" : false
  },
  "tagline" : "You Know, for Search"
}[download@social2 bin]$ curl 222.111.12.76:9200
{
  "ok" : true,
  "status" : 200,
  "name" : "es-2.incincinc.com",
  "version" : {
    "number" : "0.90.0",
    "snapshot_build" : false
  },
  "tagline" : "You Know, for Search"
}[download@social2 bin]$ curl 222.111.12.87:9200
{
  "ok" : true,
  "status" : 200,
  "name" : "es-3.incincinc.com",
  "version" : {
    "number" : "0.90.0",
    "snapshot_build" : false
  },
  "tagline" : "You Know, for Search"
}[download@social2 bin]$ curl 222.111.12.88:9200
{
  "ok" : true,
  "status" : 200,
  "name" : "es-4.incincinc.com",
  "version" : {
    "number" : "0.90.0",
    "snapshot_build" : false
  },
  "tagline" : "You Know, for Search"
}[download@social2 bin]$ 
```

**Comment by mbroecheler** [comment]
This seems to be an issue with the elastic search client not being able to
connect to the elastic search servers at the ips that you configured.
Note, that Cassandra is not talking to elasticsearch - only titan is.
Hence, the Titan instance (in this case the gremlin shell where you were
running this) must be able to physically connect to the ES servers.

On Fri, Jul 12, 2013 at 1:09 PM, yvesx notifications@github.com wrote:

> I searched my error and couldnt find much either in titan or elasticsearch
> repo...
> (in Using-Elastic-Search, this is mentioned Also ensure that the machine
> running Titan can connect to the Elasticsearch instances over the network
> if the machines are physically separated.)
> So this is my setup. I have Titan on top of 10 non-embedded Cassandra node.
> 
> I also have 4 ES nodes (say ES-1,ES-2,ES-3,ES-4) that are in another
> network. The 4 ES nodes are connected with private IPs. For any of the
> Cassandra nodes to talk to ES nodes, it has to be done over public network.
> 
> So I have the following issue when enabling ES search...
> The symptom looks like Titan cannot connect to ES nodes. but pls see my
> curl statements, the 4 ES nodes are reachable at port9200 (which is the one
> I use, not the default 9300)
> 
> My question is this: I have to provide Titan with ES nodes' public IPs b/c
> ES and Titan are on different networks. Does this mean ES-1 will try to
> talk to ES-2 using the same public IP provided to Titan? ES-1 should use
> the private network to talke to ES-2 not the public IPs provided to Titan.
> In my setting ES-1 cannot reach ES-2 over the public IPs on purpose.
> 
> I hope my question is clear. Please Let me know if this is entirely an
> ElasticSearch issue.
> thank you very much.
> I tried this in Gremlin shell.
> 
> backend: elasticsearch
> hostname: [222.111.12.75:9200, 222.111.12.76:9200, 222.111.12.87:9200, 222.111.12.88:9200]
> client-only: true
> 
> 13/07/12 14:44:48 INFO elasticsearch.plugins: [Red Lotus] loaded [], sites []
> 13/07/12 14:44:49 INFO es.ElasticSearchIndex: Configured remote host: 222.111.12.75 : 9200
> 13/07/12 14:44:54 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-1][inet[/222.111.12.75:9200]], disconnecting...
> org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.75:9200]][cluster/state] request_id [0] timed out after [5001ms]
>     at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>     at java.lang.Thread.run(Thread.java:679)
> 13/07/12 14:44:54 INFO es.ElasticSearchIndex: Configured remote host: 222.111.12.76 : 9200
> 13/07/12 14:44:59 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-1][inet[/222.111.12.75:9200]], disconnecting...
> org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.75:9200]][cluster/state] request_id [1] timed out after [5000ms]
>     at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>     at java.lang.Thread.run(Thread.java:679)
> 13/07/12 14:45:04 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-1][inet[/222.111.12.75:9200]], disconnecting...
> org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.75:9200]][cluster/state] request_id [2] timed out after [5000ms]
>     at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>     at java.lang.Thread.run(Thread.java:679)
> 13/07/12 14:45:04 INFO client.transport: [Red Lotus] failed to get local cluster state for [#transport#-2][inet[/222.111.12.76:9200]], disconnecting...
> org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/222.111.12.76:9200]][cluster/state] request_id [3] timed out after [5001ms]
>     at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:342)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>     at java.lang.Thread.run(Thread.java:679)
> 13/07/12 14:45:04 INFO es.ElasticSearchIndex: Configured remote host: 222.111.12.87 : 9200
> [download@social2 bin]$
> [download@social2 bin]$
> [download@social2 bin]$ curl 222.111.12.75:9200
> {
>   "ok" : true,
>   "status" : 200,
>   "name" : "es-1.incincinc.com",
>   "version" : {
>     "number" : "0.90.0",
>     "snapshot_build" : false
>   },
>   "tagline" : "You Know, for Search"
> }[download@social2 bin]$ curl 222.111.12.76:9200
> {
>   "ok" : true,
>   "status" : 200,
>   "name" : "es-2.incincinc.com",
>   "version" : {
>     "number" : "0.90.0",
>     "snapshot_build" : false
>   },
>   "tagline" : "You Know, for Search"
> }[download@social2 bin]$ curl 222.111.12.87:9200
> {
>   "ok" : true,
>   "status" : 200,
>   "name" : "es-3.incincinc.com",
>   "version" : {
>     "number" : "0.90.0",
>     "snapshot_build" : false
>   },
>   "tagline" : "You Know, for Search"
> }[download@social2 bin]$ curl 222.111.12.88:9200
> {
>   "ok" : true,
>   "status" : 200,
>   "name" : "es-4.incincinc.com",
>   "version" : {
>     "number" : "0.90.0",
>     "snapshot_build" : false
>   },
>   "tagline" : "You Know, for Search"
> }[download@social2 bin]$
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/321
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by yvesx** [comment]
Thanks. So I tried to run the Titan instance on the same private network as ES nodes. Yes, Titan indeed detects ES nodes. I guess Titan interacts with ES through means other than ES's HTTP interface (this would explain why simply enable port9200 in the firewall does not do the trick). However, I have not tested if Titan can connect to remote Cassandra nodes.

So if anyone, like me, is running ES and Cassandra on two separate private networks, I would love to hear about how the his/her Titan instance is set up.

I'll update here if I can connect to Cassandra nodes from my Titan instance, which is running with ES nodes. In any case, running Cassandra and ES from the same network should be easier to work with.
