### ISSUE TITLE
Multithread transaction update

### ISSUE THREAD

**Issue by gorgia** [thinkaurelius/titan#322]
I have the usual problem of retrieving a vertex, update a property, save it back to the graph.
Since I have a massive and continuous amount  of data I would like to multithread this job. Is that possible within a TitanTransaction?
I have read https://github.com/thinkaurelius/titan/wiki/Multi-Threaded-Transactions and tried that configuration but it leads to this error: https://github.com/thinkaurelius/titan/issues/279
with this kind of instruction tx.getEdges("eid", eid).iterator().next();
Maybe, due to the huge traffic, the mechanism is failing, thus saving (despite my all effort) two identical edges in the same transaction and making the iterator.next() fail.
I have tried to use more transaction at once but I ended with a clear PermanentLockException.
Is there any chance to update a vertex, which can be in the graph and in the transaction, concurrently?

**Comment by mbroecheler** [comment]
Can you please post your question to the mailinglist instead of using the issue tracker:
aureliusgraphs@googlegroups.com
Thanks
