### ISSUE TITLE
Titan cluster set up in embedded cassandra mode

### ISSUE THREAD

**Issue by akumarb2010** [thinkaurelius/titan#330]
Hi,

I have created titan(embedded cassandra) cluster of size 4, and by using rexster-console I pointed to one of the node and created on graph as below:

1) rexster-console.bat -rh 192.168.23.78
        (l_(l
(_______( 0 0
(        (-Y-) <woof>
l l-----l l
l l,,   l l,,
opening session [192.168.23.78:8184]
?h for help

rexster[groovy]> g=rexster.getGraph("graph")
==>titangraph[embeddedcassandra:null]
rexster[groovy]> n=g.addVertex(null)
==>v[4]
rexster[groovy]> n.setProperty('name','newvertex')
==>null
rexster[groovy]> n.setProperty('type','vertex')
==>null

And tried rexster-console connected to another node and tried to access same graph, but we are unable to access it.
2) rexster[groovy]> g=rexster.getGraph("graph")
==>titangraph[embeddedcassandra:null]
rexster[groovy]> g.v(4).name
==>An error occurred while processing the script for language [groovy]. All tran
sactions across all graphs in the session have been concluded with failure: java
.util.concurrent.ExecutionException: javax.script.ScriptException: javax.script.
ScriptException: java.lang.NullPointerException: Cannot get property 'name' on n
ull object
rexster[groovy]> g.V
rexster[groovy]> g.V.next()
==>An error occurred while processing the script for language [groovy]. All tran
sactions across all graphs in the session have been concluded with failure: java
.util.concurrent.ExecutionException: javax.script.ScriptException: javax.script.
ScriptException: java.util.NoSuchElementException

Can anyone please clarify my below doubts?
1) Why I am unable to access the same graph from another node in the cluster?
2) How exactly graph data will be stored on backend like on cassandra/hbase?
3) Is there any web UI for titan to see the nodes in the cluster?
4) How to give the names for the graph, If we want to create multiple graphs?
5) How can we do bulkload on titan? As of now we are trying to create the graph using MR job, Is this the correct way? In my application I might need to create 30Billion vertices, So what is the best way for loading?

**Comment by spmallette** [comment]
You should likely take these question to the mailing list, but just a quick observation: 

I don't see where you actually `commit()` your transaction on the first node.  As long as you have that transaction open you won't see that v[4] anywhere, even if you started a new Rexster Console on the same Titan Server instance.

**Comment by spmallette** [comment]
Ah...i see that you did that already.

**Comment by jann2005** [comment]
Dear akumarb2010 ,

Need help to set up clustered environment. Can you please setup steps from dev perspective, what configuration you had done to set up 4 node titan-cassandra cluster.

your help is appreciated. Thanks!
