### ISSUE TITLE
Problems using elasticsearch

### ISSUE THREAD

**Issue by richtera** [thinkaurelius/titan#331]
It seems that the pom file has a dependency to lucene 4.1 through titan-lucene but the version of elastic search the server depends on requires lucene 4.2. Changing the pom file in titan-lucene to require 4.2 seems to fix the issue.

**Comment by dalaro** [comment]
I fixed this a little while ago in master after enabling maven-enforcer-plugin's DependencyConvergence feature.  According to the output of mvn dependency:tree -Dverbose=true, all Lucene artifact dependencies are currently at version 4.2.1.  This change will be part of the 0.4.0 release.

In the future, if ES and titan-lucene disagree on the version of Lucene to use, then the enforcer plugin will generate a Maven build error.  At that point the developer has to intervene by modifying the lucene.version property in titan-lucene/pom.xml or adding a transitive exclusion to titan-es's dependency on ES.  This should prevent us from accidentally falling back into this broken state in the future.
