### ISSUE TITLE
Index query fails

### ISSUE THREAD

**Issue by vallettea** [thinkaurelius/titan#333]
index query fails with this query:

```
g.query().has("coords", WITHIN, Geoshape.circle(42.4049187, -124.4161254, 50)).vertices()
```

com.thinkaurelius.titan.core.TitanException: Could not call index

I think this issue is different from issue 279 (https://github.com/thinkaurelius/titan/issues/279)

**Comment by mbroecheler** [comment]
Please post the full stack trace. Judging from your email, this seems to be a Lucene problem.

**Comment by vallettea** [comment]
I think this was due to my server running titan 3.0.0 and the code querying using titan 3.0.1 dependency.
thx
