### ISSUE TITLE
Elastic search runs fine but starts an unknown greedy process

### ISSUE THREAD

**Issue by vallettea** [thinkaurelius/titan#336]
hello,

I'm running titan with cassandra and elastic search. I had no problem before I added elasticsearch.
Here is my .properties to start my titan server:

```
storage.backend=embeddedcassandra
storage.cassandra-config-dir=config/cassandra.yaml

storage.index.search.backend=elasticsearch
storage.index.search.hostname=127.0.0.01
storage.index.search.client-only=true
```

Then I interact via scala using something like this:

```
 trait TitanProvider {
  val conf = new org.apache.commons.configuration.BaseConfiguration()
  conf.setProperty("storage.backend", "cassandra")
  conf.setProperty("storage.hostname", "127.0.0.1")
  conf.setProperty("storage.index.search.backend", "elasticsearch")
  conf.setProperty("storage.index.search.client-only", true)
  conf.setProperty("storage.index.search.hostname", "127.0.0.1")
  val g = TitanFactory.open(conf)
  println("Opened graph")
 }

 object QueryTitan extends App with TitanProvider {
    // using elastic search's full text search
    val element = g.query().has("tags", CONTAINS, "millo").vertices()
 }
```

My query works fine but after i get:

```
   ...
   v[36136]
    [success] Total time: 91 s, completed Jul 29, 2013 11:54:12 AM
    1. Waiting for source changes... (press enter to interrupt)
    39674 [elasticsearch[Master Pandemonium][generic][T#5]] INFO  org.elasticsearch.client.transport  - [Master Pandemonium] failed to get local cluster state for [Neptune][VGIp2tfpRRyeW-ciGLjnQA][inet[/10.0.2.15:9301]], disconnecting...
    org.elasticsearch.transport.NodeDisconnectedException: [Neptune][inet[/10.0.2.15:9301]][cluster/state] disconnected
    39674 [elasticsearch[Master Pandemonium][generic][T#7]] INFO  org.elasticsearch.client.transport  - [Master Pandemonium] failed to get local cluster state for [#transport#-1][inet[/127.0.0.1:9300]], disconnecting...
    org.elasticsearch.transport.NodeDisconnectedException: [][inet[/127.0.0.1:9300]][cluster/state] disconnected
    39692 [elasticsearch[Master Pandemonium][generic][T#6]] INFO  org.elasticsearch.client.transport  - [Master Pandemonium] failed to get local cluster state for [Space Turnip][XgAKAgp3SsuHhBCxN7valg][inet[/10.0.2.15:9300]], disconnecting...
    org.elasticsearch.transport.NodeDisconnectedException: [Space Turnip][inet[/10.0.2.15:9300]][cluster/state] disconnected
```

then my processors are used both to 100% until I kill the java process.

**Comment by mbroecheler** [comment]
From your configuration it seems that you are running ES in its own
processes. Is it only that process that causes the problems?

On Mon, Jul 29, 2013 at 5:07 AM, Alexandre Vallette <
notifications@github.com> wrote:

> hello,
> 
> I'm running titan with cassandra and elastic search. I had no problem
> before I added elasticsearch.
> Here is my .properties to start my titan server:
> 
> storage.backend=embeddedcassandra
> storage.cassandra-config-dir=config/cassandra.yaml
> 
> storage.index.search.backend=elasticsearch
> storage.index.search.hostname=127.0.0.01
> storage.index.search.client-only=true
> 
> Then I interact via scala using something like this:
> 
>  trait TitanProvider {
>   val conf = new org.apache.commons.configuration.BaseConfiguration()
>   conf.setProperty("storage.backend", "cassandra")
>   conf.setProperty("storage.hostname", "127.0.0.1")
>   conf.setProperty("storage.index.search.backend", "elasticsearch")
>   conf.setProperty("storage.index.search.client-only", true)
>   conf.setProperty("storage.index.search.hostname", "127.0.0.1")
>   val g = TitanFactory.open(conf)
>   println("Opened graph")
>  }
> 
>  object QueryTitan extends App with TitanProvider {
>     // using elastic search's full text search
>     val element = g.query().has("tags", CONTAINS, "millo").vertices()
>  }
> 
> My query works fine but after i get:
> 
>    ...
>    v[36136]
>     [success] Total time: 91 s, completed Jul 29, 2013 11:54:12 AM
>     1. Waiting for source changes... (press enter to interrupt)
>     39674 [elasticsearch[Master Pandemonium][generic][T#5]] INFO  org.elasticsearch.client.transport  - [Master Pandemonium] failed to get local cluster state for [Neptune][VGIp2tfpRRyeW-ciGLjnQA][inet[/10.0.2.15:9301]], disconnecting...
>     org.elasticsearch.transport.NodeDisconnectedException: [Neptune][inet[/10.0.2.15:9301]][cluster/state] disconnected
>     39674 [elasticsearch[Master Pandemonium][generic][T#7]] INFO  org.elasticsearch.client.transport  - [Master Pandemonium] failed to get local cluster state for [#transport#-1][inet[/127.0.0.1:9300]], disconnecting...
>     org.elasticsearch.transport.NodeDisconnectedException: [][inet[/127.0.0.1:9300]][cluster/state] disconnected
>     39692 [elasticsearch[Master Pandemonium][generic][T#6]] INFO  org.elasticsearch.client.transport  - [Master Pandemonium] failed to get local cluster state for [Space Turnip][XgAKAgp3SsuHhBCxN7valg][inet[/10.0.2.15:9300]], disconnecting...
>     org.elasticsearch.transport.NodeDisconnectedException: [Space Turnip][inet[/10.0.2.15:9300]][cluster/state] disconnected
> 
> then my processors are used both to 100% until I kill the java process.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/336
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by vallettea** [comment]
yes when I do not use elastic search (either remotely or embedded) I have no problem.

**Comment by mbroecheler** [comment]
This seems to be an elastic search specific issue then. Please file it with
the Elasticsearch project.

On Mon, Jul 29, 2013 at 11:43 PM, Alexandre Vallette <
notifications@github.com> wrote:

> yes when I do not use elastic search (either remotely or embedded) I have
> no problem.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/336#issuecomment-21772474
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by vallettea** [comment]
no because I've tested my elastic search nodes and they are running nicely. Doon't you think it can be a problem of connection between elastic search and titan?

**Comment by mbroecheler** [comment]
It could be, but we are connecting with ElasticSearch through their normal
java API. There is nothing "special" that Titan does when connecting to ES.
It might be that a particular query is extremely expensive and causes ES to
get into this state?

On Mon, Jul 29, 2013 at 11:55 PM, Alexandre Vallette <
notifications@github.com> wrote:

> no because I've tested my elastic search nodes and they are running
> nicely. Doon't you think it can be a problem of connection between elastic
> search and titan?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/336#issuecomment-21772876
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by vallettea** [comment]
yes you are right I don't think it a titan problem anymore. I think it is a problem of sbt (scala built tool) when you use the mode

```
 sbt clean "~run"
```

but the simple

```
 sbt clean run
```

does not reproduce the problem.
Apologies for the inconvenience and many thanks for your great work.

**Comment by vallettea** [comment]
I think the problems comes from the fact that when you make a simple run at the end all the connections to whatever services are closed. But with the "~run" option, the JVM is left hot, connection opened and only modified files are recompiled. So I think this problem is due to the fact titan does not closes ES normally.

**Comment by mbroecheler** [comment]
Titan closes both the ES client and node (if it exists) upon database shutdown. Are you sure you are calling graph.shutdown() after you are done with it? Otherwise I suppose the client and open connections could linger around.

**Comment by mbroecheler** [comment]
Pending further notice moved to 0.4.1.
