### ISSUE TITLE
Can we safely exclude JRuby from HBase? -- Its ~14 megs.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#34]
mvn dependency:tree

+- org.apache.hbase:hbase:jar:0.92.1:compile
[INFO] |  +- org.jruby:jruby-complete:jar:1.6.5:compile

That would help reduce the size of Titan.

**Comment by dalaro** [comment]
igrepping a HBase distro (incl source) for jruby brings up docs and scripts.  It _seems_ like JRuby is only used to run the Ruby-language "hbase shell" and some admin scripts (e.g. <code>bin/graceful_stop.sh</code>).  I'm not completely certain that JRuby is just a shell dependency within HBase, it just looks that way on brief inspection.

The use of JRuby in the shell is discussed at length on the HBase wiki, but I couldn't find anything definitive about JRuby on the server.

I pushed an pom.xml exclusion stanza to the titan0.1 branch.  The regular "mvn test" suite passes with the exclusion.  I'd still rather not roll this into the master until we've had a chance to play with the dev branch for a while.

**Comment by jramsdale** [comment]
It seems like the better solution (or possibly additional solution) is to turn Titan into a multi-module build. The core should be split from the various implementations since most users will not want the dependencies and transitive dependencies for a data store they have no intention of using.

The question then becomes: do users of the HBase data store still require the Jruby dependencies? There might not be a reason to exclude them if so.

**Comment by mbroecheler** [comment]
While multi-module builds are the more sophisticated approach to handling the multiple dependencies, it will add too much overhead for just the two different dependencies (cassandra / hbase) at the moment. We will revisit this issue later.

**Comment by okram** [comment]
Thing to consider:
- How are you going to meet the 30 meg .zip limit with Apache Central Repo?

**Comment by jramsdale** [comment]
I find multi-module builds to be almost no overhead over single-module builds.

Are you using the Maven Release Plugin?

I would be willing to help with this if you'd like.

**Comment by mbroecheler** [comment]
I have to disclose that I am not a mvn expert. If you have an easy way to
accomplish this, then please show me how. Thanks a lot!

**Comment by okram** [comment]
Please try and emulate the TinkerPop style of multi-modules. (e.g. https://github.com/tinkerpop/blueprints ).. Unless you have a really cool way I don't know about.

**Comment by DanielThomas** [comment]
The Tinkerpop style is what you find on most projects. The only way I'd recommend you diverge is the module directory naming: 'project-module' gets tiresome on the command line - for example, blueprints-core would instead be 'core'. It remains 'blueprints-core' in the pom and therefore generated artifacts, only the module definition differs.

You might want to consider a dedicated parent pom (titan-parent) which allows you to keep the root pom to basic version and module definition. A "company pom" is also a great way of standardizing certain configurations across all projects (which is what you're doing in part with the Sonatype POM). Best examples of this structure are Sonatypes own projects - check out Nexus.

You could also avoid the need for the 'comprehensive' test designation by using the Failsafe plugin. It's designed to run integration tests during the verify phase. The default convention is to name texts *IT, but you can use the standard inclusion/exclusion rules that Surefire supports. Also great for separately measuring IT code coverage separately using Jacoco and Sonar - in fact, I can't recommend Sonar highly enough. The trending and test covage stuff alone is worth it, let alone the static analysis and review functionality.

**Comment by jramsdale** [comment]
Yeah, I would do it the same as Blueprints. I was the contributor of the Sonatype OSS Maven changes so have experience with Blueprints. I strongly prefer artifactIds match directory names--it prevents confusion and most folks have command-line completion anyway. I also prefer having a prefixed artifact names in the fashion of Spring and Blueprints. I've finished much of the restructuring today and that's how I've done it (with a parent pom).

Introducing the Failsafe plugin and other improvements are good ideas, but probably are better left for a different commit so this one can focus solely on a restructuring. Can this issue be reopened or should a more general one be created for introducing a decomposed multi-module build?

**Comment by mbroecheler** [comment]
This issue is now addressed by #61

**Comment by jramsdale** [comment]
I have to confess, issue 61 is only a partial step. It doesn't change the overall size of the distribution--it just isolates the impact. There would still need to be research into whether JRuby is a required dependency. Apologies for waylaying the original conversation. I don't know HBase well, but I expect @dalaro is correct about it not being required. I would suggest reopening this and if @dalaro's patch works then close again. I purposely tried not to change dependencies in issue 61, so can't say I've dealt with the issue there.

**Comment by mbroecheler** [comment]
Yes, Dan already excluded jruby in the titan0.1 branch pom, hence I
consider this issue closed. The reason I reopened it was for the pom
refactoring that you suggested. But that is in #61.

On Thu, Aug 23, 2012 at 9:10 PM, jramsdale notifications@github.com wrote:

> I have to confess, issue 61 is only a partial step. It doesn't change the
> overall size of the distribution--it just isolates the impact. There would
> still need to be research into whether JRuby is a required dependency.
> Apologies for waylaying the original conversation. I don't know HBase well,
> but I expect @dalaro https://github.com/dalaro is correct about it not
> being required. I would suggest reopening this and if @dalarohttps://github.com/dalaro's
> patch works then close again. I purposely tried not to change dependencies
> in issue 61, so can't say I've dealt with the issue there.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/34#issuecomment-7991714.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by jramsdale** [comment]
Ok. What's the plan to reconcile titan0.1 and master? (See other thread on
the subject...) Would like to know next steps to take.

-jeff
