### ISSUE TITLE
Reindexing elements using Titan/Faunus (global graph indices)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#341]
This is possible with Faunus quite simply.

```
g.V.each { v ->
  v.getPropertyKeys().each {
     v.setProperty(it,v.getProperty(it));
  }
}
```

If Titan allows us to define an index "after the fact," then once that is done, then for all elements, the above Faunus job is kicked off. Read the property and set the property.

**Comment by dkuppitz** [comment]
Just wanted to mention a short version:

```
g.V.sideEffect('{ ElementHelper.copyProperties(it, it) }')
```

What about properties that are not out-unique? Trying to call setProperty will fail, right?

**Comment by ppeddi** [comment]
Would this be fixed in 0.5? We are waiting for this fix (critical for us since we need the ability to add indexes after the data is populated).

Thanks

**Comment by mbroecheler** [comment]
Yes this will be part of the 0.5 release and is availble on M2. Documentation is forthcoming.

**Comment by mbroecheler** [comment]
This has been implemented and documented.
