### ISSUE TITLE
Titan 'autotype' map implementation incorrect according to documentation

### ISSUE THREAD

**Issue by mphuff** [thinkaurelius/titan#346]
We have started using Titan 0.3.1 (and recently upgraded to 0.3.2) and discovered that the 'autotype' according to Titan's documentation is inconsistent with what is actually implemented.

In the documentation, the valid values are "none" or "blueprints". However, looking into the com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration class, here is the actual implementation:

```
public static final String AUTO_TYPE_DEFAULT = "../../titan-core/src/test/java/com/thinkaurelius/titan/blueprints";

private static final Map<String, DefaultTypeMaker> preregisteredAutoType = new HashMap<String, DefaultTypeMaker>() {{
    put("none", DisableDefaultTypeMaker.INSTANCE);
    put("../../titan-core/src/test/java/com/thinkaurelius/titan/blueprints", BlueprintsDefaultTypeMaker.INSTANCE);
}};
```

Of course, for those of us who have made due with this inconsistency, changing this property back to what it should be is going to be a breaking change. The fact that this property got updated in a release should be called out in release notes when this is released.

Micah

**Comment by mbroecheler** [comment]
Oh no, this must have happened during refactoring. This configuration option is completely non-sensical.

**Comment by mphuff** [comment]
Thank you for submitting the patch @mbroecheler!
