### ISSUE TITLE
Embedded Database

### ISSUE THREAD

**Issue by sirinath** [thinkaurelius/titan#353]
Hi,

Can you add the ability to work with an embedded instance without having to use HBase, Cassandra, etc.

Suminda

**Comment by espeed** [comment]
You can use BDB: https://github.com/thinkaurelius/titan/wiki/Using-BerkeleyDB

**Comment by sirinath** [comment]
I was thinking something like MapDB. This perhaps would be much faster. Also may be easy to get up and running if you are just dealing with small amount of data.

**Comment by mbroecheler** [comment]
Yes, a MapDB storage adapter would be splendid indeed.
