### ISSUE TITLE
Solr As Full-Text Index for Titan

### ISSUE THREAD

**Issue by jholmberg-cni** [thinkaurelius/titan#356]
Hi There,
I'm currently working on a fork of Titan where I'm attempting to add support for Solr 4.4.0. We're already using Solr in production with other parts of our technology stack, and we'd like to contribute Solr support back to the titan project as a pull request if that turns out to be helpful. 

I'm getting most of the assertions to pass in IndexProviderTest.singleStore() but I've run into a little snag on the line of code in that says:

``` java
result = tx.query(new IndexQuery(store, KeyAnd.of(KeyAtom.of("text", Text.CONTAINS, "world"), KeyAtom.of("weight", Cmp.GREATER_THAN,6.0))));
            assertEquals(2,result.size());
            assertEquals("doc1",result.get(0));
```

I was thinking the results should also include doc3 as it was modified to have its text say: "Bob owns the world".

If that's not correct, let me know so I can get my logic fixed in the SolrSearchIndex class that I'm building.

Thanks!
-Jared

**Comment by jholmberg-cni** [comment]
Figured it out. The SolrSearchIndex class I'm writing didn't properly handle the mutation to remove the weight field and its value from doc3.  Fixed it and test is now passing on that assertion.

**Comment by vantonio** [comment]
Good to know another index provider coming, thanks and hope to see your work real soon!

**Comment by dalaro** [comment]
Hi Jared, looking forward to the PR.  Please ping if other implementation obstacles come up.
