### ISSUE TITLE
Label / Tags on Vertices | Sub Labels / inter label relationships

### ISSUE THREAD

**Issue by sirinath** [thinkaurelius/titan#357]
Hi,

Can you consider ability to add Label / Tags on Vertices also. 

Also sub labelling / additional qualification to label. E.g. 1) A related / cousin B. The relationship cousin is contained within related also. 2) A related / cousin / Classmate B. here being a classmate has no hierarchical relationship like before. These can be modelled as 3 edges but in this case the affinity in related and cousin is not captured. In which case being a cousin would imply being related.

Suminda

**Comment by sirinath** [comment]
Perhaps ability to model Label and Properties which have relationships as other graphs would perhaps be the solution?

**Comment by sirinath** [comment]
Perhaps capture meta data in 1 graph as edges and vertices in another graph.

**Comment by sirinath** [comment]
Perhaps objects as properties would solve this. These could be part for more than 1 graph.

**Comment by mbroecheler** [comment]
Hey Sirinath,

the feature you are describing can be useful in some applications, in particular, those that have "ontological" or "taxonomic" labels. I'd encourage whoever is interested in such an extension to Titan to write a wrapper around TitanGraph (similarly to the wrappers that Blueprints provides) that adds these features as we intent to keep Titan as lean as possible.
Concretely,

### Labels on Vertices

Create vertices for each vertex label (e.g. "person", "product", etc) and then link an "instance" vertex to the label vertex by way of a **unidirected** edge.

### Label Hierarchy

Note, that labels and keys in Titan are themselves vertices in the graph. As such, you can add edges between these types to encode additional relationships (such as subsumption) and then treat them accordingly.

**Comment by sirinath** [comment]
Perhaps you can provide the wrapper for ontological / taxonomic labels and data. We might want to attache just more than a label.

Also perhaps reference to other graphs / sub graphs.

Also graph reference is also a feature that is nice to have. Perhaps as a thin wrapper on top of the core api.

**Comment by sirinath** [comment]
Should I opening a new enhancement request for graph / sub graph references to make this part clear?

**Comment by mbroecheler** [comment]
I think the mailing list is a better place to discuss general feature requests. The issue tracker is resolved for concrete issues or enhancements.

Also, if this is something you need, it might be quickest to take a crack at this yourself, then open source the repo and invite other to contribute. There are more important things we need to address in Titan first.
