### ISSUE TITLE
Null Edge Properties Added After Commit

### ISSUE THREAD

**Issue by zachkinstner** [thinkaurelius/titan#358]
I have noticed that Titan is adding additional null properties to edges after committing the transaction. I think this is related to the property being an edge primary key, and _not_ being set by `addEdge()`. Here is an example scenario:

``` java
myProp = g.makeType().dataType(Integer.class).name("MyProp").unique(OUT).indexed(Vertex.class).makePropertyKey(); 
g.makeType().name("MyEdge").primaryKey(myProp).unique(OUT).makeEdgeLabel();
a = g.addVertex();
b = g.addVertex();
e = g.addEdge(a,b,"MyEdge",[:]);
```

Result before commit:

``` json
{"_type":"edge","_inV":"8","_id":"j-4-2F0LaTPQAS","_label":"MyEdge","_outV":"4"}]
```

After commit, the `MyProp` property is present:

``` json
{"_properties":{"MyProp":null},"_type":"edge","_inV":"8","_id":"j-4-2F0LaTPQAS","_label":"MyEdge","_outV":"4"}
```

Is this the expected behavior?

Side note: this (after commit) returns an empty result:

``` java
g.e("j-4-2F0LaTPQAS").has("MyProp");
```

**Comment by zachkinstner** [comment]
This also occurs when I replace `primaryKey` with `signature` during edge-label creation.

**Comment by mbroecheler** [comment]
No, this is not expected behavior. It occurs because Titan will automatically add all primary key and signature keys to the list of keys on the edge which results in this behavior.
