### ISSUE TITLE
Rexster-Server 2.4 has issue with "isRDFModel" in REST service

### ISSUE THREAD

**Issue by bhvette** [thinkaurelius/titan#365]
I'm trying to use Rexster-Server 2.4.0, with Cassandra as a backend.  I can get it up, and connect with Rexster-Console, including adding data.  But when I try to use the REST interface (curl http://mymachine:8182/graphs/titan) Rexster throws a "java.lang.NoSuchFieldError: isRDFModel"

Suggestions as to how I can make this work?  This same error is thrown if you try to use doghouse to view the nodes and edges.

**Comment by spmallette** [comment]
Not sure what version of Titan you are using, but I don't think Titan 0.3.x is completely compatible with Rexster/TinkerPop 2.4.0.  That is likely your problem.  Try to downgrade to Rexster 2.3.0 or try the Titan 0.4.0-SNAPSHOT with Rexster 2.4.0.  Please reopen if you find other problems.

**Comment by bytor99999** [comment]
I was just about to open an issue myself on this. Funny that it was 8 hours apart.

I get a compile time error showing in my IDE for line 32 of TitanFeatures class 

features.isRDFModel = false;

I am trying to use IdGraph to set my Vertex ids to a user-defined id. 

Thanks, I will try to downgrade our TinkerPop Blueprints to 2.3.0 and see what happens.

**Comment by bhvette** [comment]
I'm using the libraries from the Titan 0.3.2 Complete. I already tried the downgrade to Rexster 2.3, so I'll try an upgrade to Titan 0.4-SNAPSHOT

**Comment by bytor99999** [comment]
Yes, switching to 2.3.0 of TinkerPop does the trick for that compile time error, but now I can't use the FramedGraphFactory in Frames. :(

Oh, well, I guess we can't have IdGraph. (Un-related to the actual issue)

The issue won't show anymore, but at a trade-off of some nice new features in 2.4.0

Thanks

Mark

**Comment by bhvette** [comment]
I had to go back to Rexster 2.2, but I can now get the REST interface to work.

**Comment by spmallette** [comment]
@bhvette, fwiw, you should not have had to go all the way back to 2.2.0.  2.3.0 should have done the trick as @bytor99999 reported.
