### ISSUE TITLE
Make cassandra transaction timestamp directly settable

### ISSUE THREAD

**Issue by gwhitehawk** [thinkaurelius/titan#367]
Atm, transaction timestamps are assigned to current time in (Cassandra)StoreManager.mutateMany method. Support making them settable via transaction configuration. I'm working on this, a patch should be ready within a few days.

**Comment by gwhitehawk** [comment]
Related to this pull request: https://github.com/thinkaurelius/titan/pull/369

**Comment by mbroecheler** [comment]
#369 was merged which closes this ticket.
