### ISSUE TITLE
ElasticSearch index query stopped working when combined with standard index

### ISSUE THREAD

**Issue by JonSmoot** [thinkaurelius/titan#373]
Mixing two indices in a single query, one an elasticsearch index and a second titan index produces unexpected results (or to be more exact, seems like the query behaves as a standard index and not using elastic search)
See this thread for more details:
https://groups.google.com/forum/#!topic/gremlin-users/h-wW8UIFIf0

How to reproduce:
environment: titan 0.3.2, java 1.7.0_02-b13

create a couple of indexes:

g = GraphOfTheGodsFactory.create('/tmp/titan')
g.makeType().name("simpleindex").dataType(String.class).indexed(Vertex.class).unique(Direction.OUT).makePropertyKey();
g.makeType().name("fulltextindex").dataType(String.class).indexed("search", Vertex.class).unique(Direction.OUT).makePropertyKey();
g.commit()
v = g.addVertex()
v.setProperty("simpleindex", "George")
v.setProperty("fulltextindex", "George Washington was the first President of the United States")
g.commit()

Querying each index by itself produces the expected results (i.e. the 'fulltextindex' field can be queried with various upper case, lower case combinations)

g.query().has('simpleindex', 'George').vertices()._().simpleindex // prints George
g.query().has('fulltextindex', Text.CONTAINS, 'washington').vertices()._().simpleindex // prints George
g.query().has('fulltextindex', Text.CONTAINS, 'WaShInGtOn').vertices()._().simpleindex // prints George

but when you mix the two, only exact case works (which means, IMHO, that although we do not see any warning, it is not being treated as an elastic search index but rather as a built in one)

g.query().has('fulltextindex', Text.CONTAINS, 'Washington').has('simpleindex', 'George').vertices()._().simpleindex // prints George 
g.query().has('fulltextindex', Text.CONTAINS, 'washington').has('simpleindex', 'George').vertices()._().simpleindex // no results

The result disappears just by changing Washington to washington.

Side note, I believe that while this uses the standard index (which means iterating over all vertices), it doesn't show the expected warning (transaction.StandardTitanTx: Query requires iterating over all vertices...) due to another (or related) bug, agian more details on this assumption in the thread mentioned above

**Comment by JonSmoot** [comment]
Wouldn't this simply hide the problem instead of fixing it (the code above will "work", but will not use elasticsearch index (although one is defined) therefore performing full graph scan)?

**Comment by mbroecheler** [comment]
No, it will use an index. It uses the standard index defined via "simpleindex" since this is the faster of the two indexes.
In the future, we will work on making the query optimizer smarter about which indexes to use and how.
However, this should not result in a full table scan for any of your queries.
