### ISSUE TITLE
Add the ability to register a new index provider in com.thinkaurelius.titan.diskstorage.Backend

### ISSUE THREAD

**Issue by GeorgeVorobiov** [thinkaurelius/titan#384]
I'm working on adding a custom index provider to support our solr instance instead of the ones provided out of the box. It would be nice if we had an API to make it easy.
Currently I've found the only method that does it:

```
public static final void registerShorthands(Properties props, String prefix, Map<String,String> shorthands) {
    for (String key : props.stringPropertyNames()) {
        if (key.toLowerCase().startsWith(prefix)) {
            String shorthand = key.substring(prefix.length()).toLowerCase();
            String clazz = props.getProperty(key);
            shorthands.put(shorthand,clazz);
            log.debug("Registering shorthand [{}] for [{}]",shorthand,clazz);
        }
    }
}
```

but the problem is that we need to put a new mapping into the following private Map object inside the Backend class:

```
private static final Map<String, String> REGISTERED_INDEX_PROVIDERS = new HashMap<String, String>() {{
    put("lucene","com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex");
    put("elasticsearch","com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex");
    put("es","com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex");
}};
```

But in order to change this Map, I need to be able to pass it in. 
I was able to work around this issue by including my own titan.properties file and relying on it being found by classloader first, before the one included with the titan jar, based on this static loading code in the same class:

```
static {
    Properties props;

    try {
        props = new Properties();
        InputStream in = TitanFactory.class.getClassLoader().getResourceAsStream(TitanConstants.TITAN_PROPERTIES_FILE);
        if (in!=null && in.available()>0) {
            props.load(in);
        }
    } catch (IOException e) {
        throw new AssertionError(e);
    }
    registerShorthands(props,"storage.",REGISTERED_STORAGE_MANAGERS);
    registerShorthands(props,"index.",REGISTERED_INDEX_PROVIDERS);
}
```

But this seems to be a hack more than a real solution. 
What I'd like to have is just a method that adds a mapping to the REGISTERED_INDEX_PROVIDERS map (and possibly the other one while we are at it).

**Comment by GeorgeVorobiov** [comment]
So something like: 

public static final void registerIndexShorthand(String shorthand, String clazz) {
        shorthands.put(shorthand,clazz);
        log.debug("Registering index shorthand [{}] for [{}]",shorthand,clazz);
}

**Comment by mbroecheler** [comment]
If this method was available, then you would have to have a custom build of Titan which registers your particular shorthand which seems cumbersome or run some custom code prior to initializing Titan.
You can simply use the entire class name in your configuration file:
@storage.index.search.backend=name.for.your.IndexProvider@

Wouldn't that do it?

**Comment by GeorgeVorobiov** [comment]
Thanks a lot. I was under the impression that you have to use a shorthand, but using a fully qualified class name works fine. 
I consider the issue resolved.
