### ISSUE TITLE
Add ability to define properties as indexed, but not stored in Titan vertex

### ISSUE THREAD

**Issue by kunklejr** [thinkaurelius/titan#385]
Titan provides the ability to use Lucene or Elastic Search to "full text index" a property as well as save it to the storage backend. It would be nice to allow a property to be indexed but not stored in the Titan vertex for cases where the data is very large and you'd still like to be able to use its value in a graph query. Currently we need to maintain a separate Elastic Search index for large properties and attempt to merge search results with Titan queries.

**Comment by mbroecheler** [comment]
@kunklejr Are you saying that you have vertex properties that are too large to be stored in Titan? How large are they and what is the exception that you are seeing?

**Comment by kunklejr** [comment]
I'm primarily thinking about the backend storage engine used by Titan, specifically HBase. In their FAQ they suggest storing data in HDFS and "pointers" in HBase for anything over 10MB (http://wiki.apache.org/hadoop/Hbase/FAQ_Design#A3). In my case I'm storing text extracted from any number of documents (Word, Excel, HTML, PDF, etc.) where I don't control the size.

**Comment by kunklejr** [comment]
Even if the data isn't huge, it's a problem when querying. Imagine you have vertices with a text field that is 1MB and your query returns 100 vertices. There's currently no way to prevent 100MB worth of data from being returned from that query.

**Comment by espeed** [comment]
Separating ElasticSearch from Titan and replacing it with a Kafka connector would simplify the code and provide more flexibility in choosing what to store where, and it would make it easy to run custom ElasticSearch configurations (see https://github.com/thinkaurelius/titan/issues/399).

**Comment by mbroecheler** [comment]
I think you are better off storing this data outside of Titan. From an architectural perspective, its important that Titan has one "authoritative" data source which is always the storage backend. The indexing backends are purely used for indexing and not data storage. If we had some data stored in the storage backend and some in the indexing backend, we would make Titan's architecture way more complicated.

If you are storing such large amounts of data, you are probably better off with an ES cluster optimized for such large items or connect to some file storage solution which has streaming support.

**Comment by pellyadolfo** [comment]
> > If you are storing such large amounts of data, you are probably better off with an ES cluster optimized for such 
> > large items or connect to some file storage solution which has streaming support.

I am also having this use case and I agree that is better using an ES cluster for this large data..... but how do you keep integrity for this external data with a Titan graph on Titan searches?

+1 for giving a thought to this configuration

Update: I added this thread on Gremlin forum on the possibility of a NoSQL Distributed Query Engine
https://groups.google.com/forum/?hl=en-GB#!topic/gremlin-users/3yTfaEe5D_8
