### ISSUE TITLE
Limit applied client side for HBase storage adapter

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#4]
Although getSlice applies columnStart and columnEnd filtering server-side, the total column count limit is only applied client-side.  This limit is obviously better applied server-side.  However, this might require deploying a Filter class to the HBase server(s), which makes deployment more annoying for prospective users.

**Comment by crisweber** [comment]
I had not seen this issue and so I've submitted a new pull request with same subject with the nice #42.

**Comment by mbroecheler** [comment]
Addressed in #42
