### ISSUE TITLE
Efficiency problems with Cassandra backend

### ISSUE THREAD

**Issue by dbxfb** [thinkaurelius/titan#41]
Hello there,

I'm guessing this is a known issue, but still:

When using Cassandra through Thrift, there is a serialization/deserialization of each mutation,
and the current version of the Cassandra backend creates a huge batchmutation with everything;
which means that when I create 100k edges, there will be 100k mutations serialized in one go, eating lots of ram on both sides (client while serialization, and server while deserializing), taking long to process on the Cassandra side (possibly reaching internal query timeout) and adding latency.

I think there should be a limit (possibly a configurable one) to the number of mutations per Cassandra batch.

Thanks,
Dan

**Comment by mbroecheler** [comment]
Check out buffer-size:
https://github.com/thinkaurelius/titan/wiki/Graph-Configuration

On Thu, Jul 19, 2012 at 8:42 AM, Dan Forest-Barbier <
reply@reply.github.com

> wrote:
> 
> Hello there,
> 
> I'm guessing this is a known issue, but still:
> 
> When using Cassandra through Thrift, there is a
> serialization/deserialization of each mutation,
> and the current version of the Cassandra backend creates a huge
> batchmutation with everything;
> which means that when I create 100k edges, there will be 100k mutations
> serialized in one go, eating lots of ram on both sides (client while
> serialization, and server while deserializing).
> 
> I think there should be a limit (possibly a configurable one) to the
> number of mutations per Cassandra batch.
> 
> Thanks,
> Dan
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/41

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by dbxfb** [comment]
Right !
Sorry for the false issue, it seems I didn't look at the right places in the source.
