### ISSUE TITLE
ElasticSearch index query condition not being analyzed for Text.CONTAINS

### ISSUE THREAD

**Issue by akeffalas** [thinkaurelius/titan#410]
When I create an indexed, unique property key of type String for a vertex and create a vertex containing that property with a value of "test-me", I'm unable to have a query for "test-me" return that vertex.

Example code:

```
static final String VERTEX_PROPERTY = "testname";

Configuration conf = new BaseConfiguration();
conf.setProperty("storage.backend","berkeleyje");
conf.setProperty("storage.directory","/tmp/titan_test");

conf.setProperty("storage.index.search.backend", "elasticsearch");
conf.setProperty("storage.index.search.hostname", "localhost");
conf.setProperty("storage.index.search.client-only", "true");

TitanGraph graph = TitanFactory.open(conf);
graph.makeType().name(VERTEX_PROPERTY).dataType(String.class).vertexUnique(Direction.OUT, TypeMaker.UniquenessConsistency.NO_LOCK).indexed("search", Vertex.class).makePropertyKey();
graph.commit();

Vertex test = graph.addVertex(null);
test.setProperty(VERTEX_PROPERTY, "test-me");
graph.commit();

TitanGraphQuery query = graph.query();
query.has(VERTEX_PROPERTY, Text.CONTAINS, "test-me");
for(final Vertex v : query.vertices()) {
    System.out.println(v.getProperty(VERTEX_PROPERTY));  // displays no results
}
```

If I were to tokenize the search query beforehand, the vertex is returned.

```
query.has(VERTEX_PROPERTY, Text.CONTAINS, "test").has(VERTEX_PROPERTY, Text.CONTAINS, "me");  // Returns the one vertex, as expected
```

However, I shouldn't have to know how to tokenize my query beforehand.

After looking at ElasticSearchIndex's query method it appears that the query being issued is: "1cCONTAINStest-me".  The '1c' corresponds to the Base 62 value of the serialized long value of 'testname' (I believe?).  The query method appears to build a query using "match_all" with a "term" filter, which in ElasticSearch looks like this:

```
{
     "query": {
        "match_all": { }
     },
     "filter":{
               "term":{
                  "1c":"test-me"
              }
     }
}
```

This returns no results.

As mentioned in the term filter documentation, http://www.elasticsearch.org/guide/reference/query-dsl/term-filter/, the term being searched for is not analyzed.  From what I can tell, when creating the 'titan' index no mappings are defined; therefore, String fields are analyzed with Lucene's StandardAnalyzer by default at index time (which would strip out the '-' in my case).  Therefore, the terms exist in the underlying Lucene index used by ElasticSearch via Titan as tokenized terms from this analyzer which is not being used at query time.

To verify, I ran a filter that does analyze the search query:

```
{
     "query": {
        "match_all": { }
     },
     "filter" : {
            "query" : { 
                "query_string" : { 
                    "query" : "test-me"
                }
            }
    }
}
```

This returns the one vertex that I expect.

I believe this issue relates to #296, but I wasn't sure.

Can someone confirm what I'm seeing or am I doing something wrong?  I'd prefer to not have to tokenize my query string and add multiple 'has' clauses.

**Comment by mbroecheler** [comment]
@akeffalas Yes, as documented here you currently have to tokenize the query string:
https://github.com/thinkaurelius/titan/wiki/Indexing-Backend-Overview
