### ISSUE TITLE
Investigate connection issues with Astyanax on AWS

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#414]
sometimes it does not seem to connect. Why and what can we do about that?

**Comment by dalaro** [comment]
Are there particular cases we should focus on?

I saw http://stackoverflow.com/questions/16536871/noavailablehostsexception-while-starting-titan-with-cassandra/19283015, but that's on 0.3.0.

We know 0.3.1 had a crippling Astyanax bug: https://groups.google.com/forum/#!msg/aureliusgraphs/RQIQqaoURd4/IVwQ-9uXveoJ.

But those are both previous versions.

**Comment by mbroecheler** [comment]
I filed this bug for future investigation. Let's see if this issue remains
with Titan 0.4.0.

On Thu, Oct 10, 2013 at 2:38 AM, Dan LaRocque notifications@github.comwrote:

> Are there particular cases we should focus on?
> 
> I saw
> http://stackoverflow.com/questions/16536871/noavailablehostsexception-while-starting-titan-with-cassandra/19283015,
> but that's on 0.3.0.
> 
> We know 0.3.1 had a crippling Astyanax bug:
> https://groups.google.com/forum/#!msg/aureliusgraphs/RQIQqaoURd4/IVwQ-9uXveoJ
> .
> 
> But those are both previous versions.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/414#issuecomment-26040288
> .

## 

Matthias Broecheler
http://www.matthiasb.com
