### ISSUE TITLE
Maven repo doesn't seem to contain titan-rexster

### ISSUE THREAD

**Issue by richtera** [thinkaurelius/titan#415]
The titan-rexster project seems to contain a refactor of the rexster specific classes but it's not pointed to by the parent pom file and doesn't seem to be included in the maven repo.

**Comment by richtera** [comment]
Building this project with it's associated pom file and using it does work, so the code is correct and working. It's just the pom file is not linked.

**Comment by dalaro** [comment]
Whoops, forgot to `git add pom.xml` in d01dd628c52af6458a0a0bebc4bb00969cd3b909.  Push inbound...

**Comment by richtera** [comment]
Would you be able to make an official compile so that the titan-rexster resources end up in the maven repo?

**Comment by dalaro** [comment]
I deployed a 0.4.0-SNAPSHOT to Sonatype.  Is that what you were looking for?  This module won't appear in Maven Central until the 0.4.0 release.

**Comment by richtera** [comment]
Yes that's what I was looking for, thank you.

Sent from my iPhone

On Oct 10, 2013, at 11:18 PM, Dan LaRocque notifications@github.com wrote:

I deployed a 0.4.0-SNAPSHOT to Sonatype. Is that what you were looking for?
This module won't appear in Maven Central until the 0.4.0 release.

—
Reply to this email directly or view it on
GitHubhttps://github.com/thinkaurelius/titan/issues/415#issuecomment-26111406
.
