### ISSUE TITLE
Improve Cassandra embedded

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#417]
By doing a small change in CassandraEmbeddedKeyColumnValueStore.java#L341, you should have a performance improvement, unless read slices are very small.
This change consists in using cf.getSortedColumns() and, avoid calling cf.getColumn(col)

Why ?
ColumnFamily inherits AbstractColumnContainer, which has a ISortedColumns member.
This interface has multiple implementation. One of them is ArrayBackedSortedColumns
From documentation, it says : "This implementation makes sense when the main operations performed are iterating over the map and adding columns (especially if insertion is in sorted order)"

When reading from Cassandra, this implementation is used because:

reads are done in order using an iterator merging memtables & sstables,
thus insert are done in order,
then serialization is done by iterating over the collection.
In this case, because Cassandra is embedded, there is no serialization involved and the structure is used directly.
When calling "cf.getColumn(col)" there is a binary search involved for each call which is less efficient than iterating over the collection.

**Comment by mpouttuclarke** [comment]
FYI: I have published my load test package for Titan / Cassandra embedded under github.  This link may be of intrest :)
https://github.com/mpouttuclarke/titan-loadtest/wiki/Embedded-Cassandra-Considerations

**Comment by mbroecheler** [comment]
Awesome, thanks @mpouttuclarke.
You might be interested to know that we have been doing a ton of optimizations on the in-memory data structures of Titan that should greatly reduce the number of objects being created for common types of queries. That should help keep GC under control. This work is currently in the infinispan branch and will be merged hopefully soon.
