### ISSUE TITLE
[Titan04/SNAPSHOT] Hazelcast not found

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#419]
From the git pull titan$ directory, Hazelcast doesn't load. Note that Cassandra works just fine.

```
titan$ git pull
titan$ mvn clean install -Dmaven.test.skip=true
titan$ bin/gremlin.sh
...
gremlin> g = TitanFactory.open('conf/titan-hazelcast.properties')
Could not find implementation class: com.thinkaurelius.titan.diskstorage.hazelcast.HazelcastCacheStoreManager
Display stack trace? [yN]
```

**Comment by dalaro** [comment]
I forgot to add HC to the dependency set of the "all" distro.  I reproduced the error locally before my commit and it was disappeared after, so I think this should work as expected now.
