### ISSUE TITLE
master branch (0.4.0) build fails.

### ISSUE THREAD

**Issue by haebin** [thinkaurelius/titan#421]
Yes, I only have jdk6 installed, so I changed compiler.target  from 1.6 to 1.7 in root pom.xml.

And I hit the following error.

[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project titan-core: Compilation failure
/home1/irteam/apps/titan-all-0.4.0/titan-core/src/main/java/com/thinkaurelius/titan/core/TitanVertexQuery.java:[16,7] types com.tinkerpop.blueprints.VertexQuery and com.thinkaurelius.titan.core.BaseVertexQuery are incompatible; both define limit(int), but with unrelated return types

The following tip didn't help either. 
https://github.com/thinkaurelius/titan/issues/411

And I tried to build against tinkerpop 2.5.0-SNAPSHOT and 2.3.0 but it didn't help either.

What am I doing wrong?

**Comment by haebin** [comment]
https://groups.google.com/forum/#!msg/aureliusgraphs/1K85lxdtGl0/FvZ-e4zALVEJ

Sorry for cross posting. This is for the other folks.

**Comment by dalaro** [comment]
Titan's current master can be compiled for the Java 1.6 runtime, but due to this multiple inheritance limitation in JDK 6, we can only do it using the JDK 7 compiler.
