### ISSUE TITLE
Titan source hierarchy pattern (and its ramifications to documentation)

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#431]
The current source heirarchy is:

titan-all
titan-berkeleyje
titan-cassandra
titan-core
titan-dist
titan-es
titan-hazelcast
titan-hbase
titan-lucene
titan-persistit
titan-rexster
titan-site
titan-test

Source and documentation might be best understood categorized as:

titan-core
titan-test
storage
.    titan-berkeleyje
.    titan-cassandra
.    titan-hazelcast
.    titan-hbase
.    titan-persistit
indices
.    titan-es
.    titan-lucene
docs
.    titan-site
dists
.    titan-all
.    titan-dist
.    titan-rexster

This way the pattern of what Titan is starts to become more obvious to people:

```
      storage backend + indexing systems
```

**Comment by spmallette** [comment]
:+1:

**Comment by mbroecheler** [comment]
Is this a recommendation for the code layout?

**Comment by mbroecheler** [comment]
Titan 05 docs are almost completely restructured.
