### ISSUE TITLE
Rexster server now very hard to start

### ISSUE THREAD

**Issue by poelzi** [thinkaurelius/titan#436]
With the bin/titan.sh wrapper script gone, it is very hard to get the rexster server started.
This is definitively a step in the wrong direction.

**Comment by poelzi** [comment]
ok, titan-server-*.zip is the way to go. titan-all is kinda misleading :-)

**Comment by mbroecheler** [comment]
Yes, we tried to pull things apart a little bit so that we don't have all
of the Rexster dependencies in the raw distributions.
We are still experimenting with our distribution strategy. There are lots
of components now and things are getting a little out of hand.
Feedback is welcome.

On Thu, Oct 17, 2013 at 5:41 PM, Daniel Poelzleithner <
notifications@github.com> wrote:

> ok, titan-server-*.zip is the way to go. titan-all is kinda misleading :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/436#issuecomment-26564801
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by topiaruss** [comment]
For our internal projects, I'm experimenting with Docker deployment. I'm certain that Docker is taking off like a rocket.

I suspect you could increase the titan user base by providing approved image Docker images, in the Docker index.  There are a few already appearing.

Best,

--r

On 18 Oct 2013, at 04:25, Matthias Broecheler notifications@github.com wrote:

> Yes, we tried to pull things apart a little bit so that we don't have all 
> of the Rexster dependencies in the raw distributions. 
> We are still experimenting with our distribution strategy. There are lots 
> of components now and things are getting a little out of hand. 
> Feedback is welcome. 
> 
> On Thu, Oct 17, 2013 at 5:41 PM, Daniel Poelzleithner < 
> notifications@github.com> wrote: 
> 
> > ok, titan-server-*.zip is the way to go. titan-all is kinda misleading :-) 
> > 
> > — 
> > Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/436#issuecomment-26564801 
> > . 
> 
> ## 
> 
> Matthias Broecheler 
> http://www.matthiasb.com
> —
> Reply to this email directly or view it on GitHub.

Russ Ferriday -- Software and Systems Architect/Developer
CEO Topia Systems Ltd.
russf@topia.com  --  +44 7429 518822  --  www.topia.com
