### ISSUE TITLE
Make usage CachedKeyColumnValueStore configurable

### ISSUE THREAD

**Issue by mpouttuclarke** [thinkaurelius/titan#440]
I have found that commenting out this line of code improves bulk load performance:

com.thinkaurelius.titan.diskstorage.Backend[titan3]:
156        //Enable cache
157        store = new CachedKeyColumnValueStore(store);

There may be other places where cache is not appropriate as well, or where we need to tune the cache size.

**Comment by mbroecheler** [comment]
Excellent observation. Yes, it indeed does not make sense to check mutations for cachable items on bulk loading. My suggestion would be to disable the CacheStore when batch-loading=true. Would that work for you?

**Comment by mbroecheler** [comment]
Wait, unless <code>query.isStatic() && !query.hasLimit()</code> is true, CachedKeyColumnValueStore will pass method calls right through and should have no impact on performance. This line is only ever true for Titan internal queries which are rare.
It might be that the default cache size is too large and hence a lot of memory ends up being consumed. I reduced it to 1000 in 9692b2e0e968267fb95f33b411508d21d0fce9e9
Does that solve the problem?

**Comment by mpouttuclarke** [comment]
Both of these would work.  Also, for reads it would be nice to configure the cache size via a property.

**Comment by mpouttuclarke** [comment]
@mbroecheler: For now I am performance testing with a custom build with that line commented.  I have also added a number of .clear() calls on collections used during the commit process to free up memory for the concurrent GC process.  I now have embedded cassandra completely stabilized with absolutely consistent performance and no heap pressure.  Will be publishing results soon :)

**Comment by mbroecheler** [comment]
@mpouttuclarke: Great, looking forward to it! Did you need to touch things in core? We are doing a pretty massive performance oriented refactoring of core that improves in-transaction performance by a lot. That would go nicely with you Cassandra embedded improvements.

**Comment by mpouttuclarke** [comment]
@mbroecheler : Some of the other changes I made were previous to tuning the cassandra.yaml and -XX settings to prevent heap pressure created by Cassandra.  i.e. I know turning off the cache made a difference but some of my other changes may not have...

**Comment by mpouttuclarke** [comment]
@mbroecheler : I can merge any of my other changes which made improvements in performance, do you guys prefer patch file, pull, or just direct merge?  Any of the changes I make for Cassandra embedded should also carry over to data grid as well, since grids like to operate in the same JVM.  I have also built a distributed performance test project for embedded Cassandra as well...

**Comment by mbroecheler** [comment]
A pull request would be fantastic. Thank you!

On Fri, Oct 25, 2013 at 9:18 AM, Matt Pouttu-Clarke <
notifications@github.com> wrote:

> @mbroecheler https://github.com/mbroecheler : I can merge any of my
> other changes which made improvements in performance, do you guys prefer
> patch file, pull, or just direct merge? Any of the changes I make for
> Cassandra embedded should also carry over to data grid as well, since grids
> like to operate in the same JVM. I have also built a distributed
> performance test project for embedded Cassandra as well...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/440#issuecomment-27105668
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
In Titan 0.5 this no longer exists and has been replaced by an explicit schema cache.
