### ISSUE TITLE
Cannot query g.V('primaryKey', byteArray) because byte[] is converted to List<Byte> via groovy(?).

### ISSUE THREAD

**Issue by haebin** [thinkaurelius/titan#443]
https://groups.google.com/forum/#!topic/aureliusgraphs/IBA4ocY-M5M

> g.makeKey('compId').dataType(byte[].class).indexed(Vertex.class).unique().single().make(); // OK
> bytes = java.nio.ByteBuffer.allocate(16).putLong(g.V('oid','objectX').next().ID).putLong(g.V('oid','objectY').next().ID).array(); // OK
> g.addVertex([compId:bytes]); // OK
> ==>v[24]
> java.nio.ByteBuffer.wrap(g.v(24).compId).getLong(0) // OK 
> java.nio.ByteBuffer.wrap(g.v(24).compId).getLong(8) // OK
> g.V('compId',bytes); // NOK --> everything else works just fine, but this does not work.
> g.V('compId',g.v(24).compId); // NOK

**Comment by mbroecheler** [comment]
I think this is mostly an artifact of groovy's automatic type conversion,
no? Are you seeing the same issue when using the raw Java API?

On Tue, Oct 22, 2013 at 4:39 AM, Frederick Haebin Na <
notifications@github.com> wrote:

> https://groups.google.com/forum/#!topic/aureliusgraphs/IBA4ocY-M5M
> 
> g.makeKey('compId').dataType(byte[].class).indexed(Vertex.class).unique().single().make();
> // OK
> bytes =
> java.nio.ByteBuffer.allocate(16).putLong(g.V('oid','objectX').next().ID).putLong(g.V('oid','objectY').next().ID).array();
> // OK
> g.addVertex([compId:bytes]); // OK
> ==>v[24]
> java.nio.ByteBuffer.wrap(g.v(24).compId).getLong(0) // OK
> java.nio.ByteBuffer.wrap(g.v(24).compId).getLong(8) // OK
> g.V('compId',bytes); // NOK --> everything else works just fine, but this
> does not work.
> g.V('compId',g.v(24).compId); // NOK
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/443
> .

## 

Matthias Broecheler
http://www.matthiasb.com
