### ISSUE TITLE
ID Pool concurrency issues

### ISSUE THREAD

**Issue by janarthanamr** [thinkaurelius/titan#446]
Currently, ID Pool results in generating overlapping id ranges in the following scenario:
1. There are multiple threads
2. Each thread deal with its own instance of graph object

This is because the rid field used to uniquely identify the id pool claim is unique only per jvm. Its not unique per thread. In case two threads from the same jvm writes a claim on same id block, then we will end up with both of them acquiring the same id block. This will lead to data being lost/overwritten during such scenarios.

**Comment by mbroecheler** [comment]
For such cases, it is required to configure a unique machine prefix.
This is documented here:
https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#multiple-titan-instances-on-one-machine

On Tue, Oct 22, 2013 at 10:12 PM, janarthanamr notifications@github.comwrote:

> Currently, ID Pool results in generating overlapping id ranges in the
> following scenario:
> 1. There are multiple threads
> 2. Each thread deal with its own instance of graph object
> 
> This is because the rid field used to uniquely identify the id pool claim
> is unique only per jvm. Its not unique per thread. In case two threads from
> the same jvm writes a claim on same id block, then we will end up with both
> of them acquiring the same id block. This will lead to data being
> lost/overwritten during such scenarios.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/446
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by janarthanamr** [comment]
Yes, the configuration parameter 'storage.machine-id' will avoid this issue.However, if they are using threads, then this has to be dynamically set in the code to be unique. If they don't configure this right, this might lead to data corruption and there is currently no way for Titan to warn the user that this is mandatory in the given setting.

Given all this, and its fairly easy to fix this to be our default behavior, do we need to leave this to our users?

**Comment by mbroecheler** [comment]
Ah, I see where you are coming from.

On Wed, Oct 23, 2013 at 9:43 AM, janarthanamr notifications@github.comwrote:

> Yes, the configuration parameter 'storage.machine-id' will avoid this
> issue.However, if they are using threads, then this has to be dynamically
> set in the code to be unique. If they don't configure this right, this
> might lead to data corruption and there is currently no way for Titan to
> warn the user that this is mandatory in the given setting.
> 
> Given all this, and its fairly easy to fix this to be our default
> behavior, do we need to leave this to our users?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/446#issuecomment-26921488
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
Making the ID Allocator a singleton is not a good approach imho because then they couldn't be individually configured per Graph instance. Rather, I think we should implement that checks that if two (or more) id allocators are running in the same jvm that the rid is properly specified.

**Comment by mbroecheler** [comment]
Fixed with merge
