### ISSUE TITLE
Persistit cleanup

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#448]
When gremlin is shut down without shutting down the graph, this error appears and the shell hangs:

[CLEANUP_MANAGER] WARNING Transaction abandoned Transaction_100000003 depth=1 status=<ts=17,896 tc=ABORTED mvv=0> owner=main

**Comment by brianin3d** [comment]
Heh... thanks for the tip about shutting down the graph!

**Comment by dalaro** [comment]
I see a hang on quit without the transaction warning when opening an empty graph:

```
gremlin> g = TitanFactory.open('conf/titan-persistit.properties')
==>titangraph[persistit:/home/dalaro/tinkerelius/titan/conf/../db/persistit]
gremlin> quit
(... non-daemon threads keep VM alive ...)
```

When I take a thread dump from the VM, I see about a half-dozen non-daemon threads waiting in Persistit code.

I'm reluctant to try to force the daemon bit on these threads.

Maybe we could change the behavior of quit.  Start a daemon thread, pass gremlin session from main to daemon thread, let the main thread die.  The daemon thread sleeps briefly.  If VM is still alive when it wakes up, it asks whether the user wants to force quit (System.exit()) or return to the shell using the session passed from the main thread (start a new non-daemon thread -- "main jr.").  User can return to shell if they forgot to g.shutdown() and care about the data or force quit if they don't.

Just ruminating... there may be some technical obstacle that I'm missing...

**Comment by ghost** [comment]
Recommend closing >> Persistit related issues.
