### ISSUE TITLE
CassandraEmbedded Hangs on exiting Gremlin REPL

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#449]
```
gremlin> g.shutdown()
==>null
gremlin> exit

```

Just sitting there... been over 1 minute thus far.

**Comment by okram** [comment]
The same hang also happens with Titan/Infinispan.

**Comment by dkuppitz** [comment]
It happens with any backend and even with Neo4J.

**Comment by mbroecheler** [comment]
Is it a general Gremlin REPL problem?

On Wed, Nov 6, 2013 at 9:11 PM, Daniel Kuppitz notifications@github.comwrote:

> It happens with any backend and even with Neo4J.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/449#issuecomment-27938306
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by dkuppitz** [comment]
All you need to do to reproduce it is: open a connection to any transactional graph and then try to exit the REPL. Makes no difference whether you call shutdown() or not. I've had this problem 1 time in my Java app, but I cannot guarantee that it wasn't a bug in my application, since it never happened again. However, this behaviour is always reproducable in the REPL (at least I wasn't able to close the REPL without CTRL+C since the Titan 0.4.0 release).

**Comment by dkuppitz** [comment]
Seems like g.shutdown() simply doesn't work. Just recognized that when I tried to shutdown a Titan/EmbeddedCassandra graph in one screen session and open another in a second screen session. The result was a port conflict. That means the first connection was still open.

**Comment by mbroecheler** [comment]
That would be strange. We have about a gazillion unit tests that use
g.shutdown(). There must be some strage interaction. Maybe a transaction is
still open but not thread bound?

On Thu, Nov 7, 2013 at 5:33 PM, Daniel Kuppitz notifications@github.comwrote:

> Seems like g.shutdown() simply doesn't work. Just recognized that when I
> tried to shutdown a Titan/EmbeddedCassandra graph in one screen session and
> open another in a second screen session. The result was a port conflict.
> That means the first connection was still open.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/449#issuecomment-28024108
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by topiaruss** [comment]
Which OS's are each of you using?
There have been various issues over the years with ports remaining in TIME_WAIT, after being closed, therefore preventing a new bind. OS and version dependent, of course.
I'll give you this old link to get you started:
http://hea-www.harvard.edu/~fine/Tech/addrinuse.html  
You might want to spend 20 mins checking out this aspect of things, before suspecting code that apparently works fine on some platforms. 

$netstat -an will tell you the state of a port.

Best,
--r

On 8 Nov 2013, at 02:47, Matthias Broecheler notifications@github.com wrote:

> That would be strange. We have about a gazillion unit tests that use 
> g.shutdown(). There must be some strage interaction. Maybe a transaction is 
> still open but not thread bound? 
> 
> On Thu, Nov 7, 2013 at 5:33 PM, Daniel Kuppitz notifications@github.comwrote: 
> 
> > Seems like g.shutdown() simply doesn't work. Just recognized that when I 
> > tried to shutdown a Titan/EmbeddedCassandra graph in one screen session and 
> > open another in a second screen session. The result was a port conflict. 
> > That means the first connection was still open. 
> > 
> > — 
> > Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/449#issuecomment-28024108 
> > . 
> 
> ## 
> 
> Matthias Broecheler 
> http://www.matthiasb.com
> —
> Reply to this email directly or view it on GitHub.

Russ Ferriday -- Software and Systems Architect/Developer
CEO Topia Systems Ltd.
russf@topia.com  --  +44 7429 518822

**Comment by dalaro** [comment]
Daniel, are you running `g.newTransaction()` to force a hang?  I have to do this.  If I just open a graph and call `g.shutdown()` and then exit, the REPL exits as intended.

I attached to the VM and took thread dumps after calling `g.newTransaction(); g.shutdown(); exit`.  The main thread is already dead.  The VM is being kept alive by ConcurrentLRUCache$CleanupThreads.  Each Transaction starts one of these internally to manage its vertex cache.  These threads have `isDaemon=false` and therefore prevent the VM from dying even after the main thread dies.  When I set `isDaemon=true` on the CleanupThreads, the VM exits as expected.

This is kind of a fix, but it raises three concerns:
- It would be cleaner to call `rollback()` on all outstanding transactions during graph `shutdown()`.  For instance, if an open tx held locks in a distributed backend, then `rollback()` would release them if possible.  Letting the VM die this way does not release them.  However, this means the graph has to know all of its outstanding transactions all of the time, and I don't think it tracks that right now.
- This could not possibly be the cause of the problem in Neo4j.
- Spawning one background thread per tx just for cache cleanup is probably not great for scaling OLTPish flurry-of-tiny-transactions workloads.  These threads spend most of their time asleep in `this.wait()`.  Perhaps the one-thread-per-tx model could be replaced by a thread-pool-backed Executor and one-runnable-per-tx without reducing performance.

I don't think this is related to TIME_WAIT.  Were a socket held in TIME_WAIT by the kernel, then I would expect the JVM to exit but encounter BindExceptions when restarted immediately thereafter as it attempts to listen on the TIME_WAIT'd socket.  I haven't seen that happen or seen it mentioned, but please let me know if I'm mistaken.

**Comment by dalaro** [comment]
Oh, I should add about embedded cassandra: `g.shutdown()` makes no attempt to kill the Cassandra daemon.  The unit tests share a single embedded Cassandra daemon but each class uses a different keyspace.  So it's not surprising that you got port conflicts when shutting down an embedded cassandra db but not killing the VM.

**Comment by topiaruss** [comment]
Makes sense.
In this case, please ignore my earlier uninformed comment.
Best,
--r
On 8 Nov 2013, at 18:14, Dan LaRocque notifications@github.com wrote:

> Oh, I should add about embedded cassandra: g.shutdown() makes no attempt to kill the Cassandra daemon. The unit tests share a single embedded Cassandra daemon but each class uses a different keyspace. So it's not surprising that you got port conflicts when shutting down an embedded cassandra db but not killing the VM.
> 
> —
> Reply to this email directly or view it on GitHub.

Russ Ferriday -- Software and Systems Architect/Developer
CEO Topia Systems Ltd.
russf@topia.com  --  +44 7429 518822  --  www.topia.com

**Comment by dkuppitz** [comment]
No, I don't have to do anything to force a hang. Just to show that it's not only Cassandra/Embedded:

```
[ec2-user@ip-10-236-139-214 titan]$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
gremlin> g = TitanFactory.open("conf/titan-hazelcastcache.properties")
Nov 08, 2013 6:59:29 PM com.hazelcast.config.ClasspathXmlConfig
INFO: Configuring Hazelcast from 'hazelcast.xml'.
Nov 08, 2013 6:59:29 PM com.hazelcast.instance.DefaultAddressPicker
INFO: Prefer IPv4 stack is true.
Nov 08, 2013 6:59:29 PM com.hazelcast.instance.DefaultAddressPicker
INFO: Picked Address[10.236.139.214]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Nov 08, 2013 6:59:29 PM com.hazelcast.system
INFO: [10.236.139.214]:5701 [dev] Hazelcast Community Edition 3.0.2 (20130906) starting at Address[10.236.139.214]:5701
Nov 08, 2013 6:59:29 PM com.hazelcast.system
INFO: [10.236.139.214]:5701 [dev] Copyright (C) 2008-2013 Hazelcast.com
Nov 08, 2013 6:59:29 PM com.hazelcast.core.LifecycleService
INFO: [10.236.139.214]:5701 [dev] Address[10.236.139.214]:5701 is STARTING
Nov 08, 2013 6:59:29 PM com.hazelcast.instance.Node
WARNING: [10.236.139.214]:5701 [dev] No join method is enabled! Starting standalone.
Nov 08, 2013 6:59:29 PM com.hazelcast.core.LifecycleService
INFO: [10.236.139.214]:5701 [dev] Address[10.236.139.214]:5701 is STARTED
WARN  com.thinkaurelius.titan.diskstorage.hazelcast.AbstractHazelcastStoreManager  - Hazelcast does not support multiple transactions per thread
==>titangraph[hazelcastcache:/home/ec2-user/titan/conf/../db]
gremlin> g.shutdown()
==>null
gremlin> exit
```

..hanging.

**Comment by dkuppitz** [comment]
Correction for one of my last comments: Neo4J only hangs when you've actually used it / executed some queries. Simply opening a connection, calling `shutdown()` and then `exit` works as expected.

**Comment by dalaro** [comment]
Thanks.  Your example led me to another separate root cause in HC.  Creating a HazelcastInstance starts a bunch of non-daemon threads.  Calling `HazelcastInstance#getLifecycleService()#shutdown()` in the store's `close()` stops those threads and allows the REPL to exit.

I also found a way to shutdown embedded Cassandra.  I'm refcounting Titan's uses of the embedded Cassandra instance by incrementing a counter in CassandraDaemonWrapper#start and decrementing in #stop.  When the counter decrements to zero, the instance is terminated.  Calling `CassandraDaemon.stop(null)`, despite the suggestive name, is insufficient.  It leaves some non-daemon threads running.  Additionally calling `MessagingService.instance().shutdown()` and `CommitLog.instance.shutdownBlocking()` kills these remaining threads.  However, one background thread, PERIODIC-COMMIT-LOG-SYNCER, only stops after waiting up to commitlog_sync_period_in_ms, 10 sec by default.  I think most developers are not going to wait five seconds (mean) before hitting ctrl+c.  So the termination code in CassandraDaemonWrapper forces an immediate commitlog flush via `CommitLog.instance.sync()` .  It then locates the PERIODIC-COMMIT-LOG-SYNCER thread by name via a recursive ThreadGroup traversal starting from the VM's root ThreadGroup.  Interrupting this thread allows the REPL to exit immediately.  Just prior to interrupt, the code also sets an UncaughtExceptionHandler on the thread that will swallow the ensuing InterruptedException and suppress a spurious stacktrace.  This stuff would have been a little too scary for me to consider back in 0.3.x, but now that embedded is going unsupported, I'm willing to try these sorts of shenanigans in the interest of easier hacking.

**Comment by dalaro** [comment]
Collected relevant changes (all on infinispan branch):
- f645e3f3afdef3b9bfdb8dd55c832dba0a6da500 - mark LRU cache cleaner threads as daemon threads
- 0b9f48f468e43a06e28d88c8dc745c40c31a14a9 - fire a Hazelcast lifecycle shutdown event on manager close
- 896fc61259515284638f0e425699e699c7498db0 - embedded Cassandra refcounting and quick shutdown
- c6814f4466ecff679ed718379990a2dc7200c7fd - Hazelcast bugfix: let the close and clearStorage methods on HZ stores fail gracefully when their manager has already been shutdown

My changes increased test walltime from about 38 minutes on my machine to 39.  I think the new IDAllocationTest may be consuming a lot of mostly idle walltime.
