### ISSUE TITLE
Performance of Hbase backend

### ISSUE THREAD

**Issue by white127** [thinkaurelius/titan#451]
Hi, all:

I try to use Hbase backend, the database contains more the 10 million vertexs and edges, the performance is not good, especially when getting properties of vertex, some times this operation consumes more the 100ms(even 500ms).
Can somebody give a help. And is there any extra infomations you needed?

**Comment by mbroecheler** [comment]
Please use the mailing list aureliusgraphs@googlegroups.com for questions.
