### ISSUE TITLE
Best Practice for Unique Id's

### ISSUE THREAD

**Issue by realdoug** [thinkaurelius/titan#456]
I am relatively new to Titan, and I noticed that when I did an update on an Edge (via Rexster), the edge was actually deleted and rebuilt with my new parameters, thus creating a new value in the "_id"

Can I rely on the "_id" field to act as a unique identifier the way I would in a traditional relational database (for both edges and vertices)?  If not what is a best practice for achieving this functionality?

Thanks!

**Comment by mbroecheler** [comment]
Hi Doug,

please use our mailing list for questions: aureliusgraphs@googlegroups.com
We use this issue tracker for issues only.
Thanks,
Matthias

On Fri, Nov 1, 2013 at 11:13 AM, Doug Friedman notifications@github.comwrote:

> I am relatively new to Titan, and I noticed that when I did an update on
> an Edge (via Rexster), the edge was actually deleted and rebuilt with my
> new parameters, thus creating a new value in the "_id"
> 
> Can I rely on the "_id" field to act as a unique identifier the way I
> would in a traditional relational database (for both edges and vertices)?
> If not what is a best practice for achieving this functionality?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/456
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by realdoug** [comment]
Sure thing sorry bout that!
