### ISSUE TITLE
Titan-Server-0.4.0 fails to launch on fresh install

### ISSUE THREAD

**Issue by kevinschumacher** [thinkaurelius/titan#462]
On a fresh installation of Titan-Server-0.4.0, "titan.sh start" fails to start Rexster. It appears that the jars for Rexster are corrupt. 

$ unzip titan-server-0.4.0.zip
$ cd titan-server-0.4.0/bin
$ ./titan.sh start &> titan.start.log
...
$ ./titan.sh stop &> titan.stop.log

In the start log:
Error: Could not find or load main class com.tinkerpop.rexster.Application

In the stop log:
Titan + Rexster (com.tinkerpop.rexster.Application) not found in the java process table

**Comment by dalaro** [comment]
I can't reproduce this locally.  Do you still have the zipfile that produced the corrupted jars?  If so, then could you please paste a sha1sum or md5sum or verify the GPG signature?

**Comment by kevinschumacher** [comment]
Dan - 

I mispoke about the JARs being corrupt. I thought I had fixed the issue by replacing them with the JARs from the Rexster distribution, but that's not the case (the JARs for Rexster match what is provided in the Rexster server and console distributions, see below.) 

I've pasted MD5 of the titan-server-0.4.0.zip below. For more context, I am running a fresh install of Ubuntu Precise 12.04 with Oracle/Sun Java 1.7.0_45. It's not a permissions problem, as I tried running as root and had similar issues. 

I was curious about the Rexster JARs and compared them, but they check out. 
91907815e77d681ed9a404fb7d124e76  titan-server-0.4.0.zip

74c74ac90798eaeac7fe24b442ab7c3e  rexster-console-2.4.0/lib/rexster-core-2.4.0.jar
74c74ac90798eaeac7fe24b442ab7c3e  rexster-server-2.4.0/lib/rexster-core-2.4.0.jar
74c74ac90798eaeac7fe24b442ab7c3e  titan-server-0.4.0/lib/rexster-core-2.4.0.jar

41e29b98b70033314cb66307884e6659  rexster-console-2.4.0/lib/rexster-protocol-2.4.0.jar
41e29b98b70033314cb66307884e6659  rexster-server-2.4.0/lib/rexster-protocol-2.4.0.jar
41e29b98b70033314cb66307884e6659  titan-server-0.4.0/lib/rexster-protocol-2.4.0.jar

b1f92287af60b4d11ba63d8797db4264  rexster-server-2.4.0/lib/rexster-server-2.4.0.jar
b1f92287af60b4d11ba63d8797db4264  titan-server-0.4.0/lib/rexster-server-2.4.0.jar

fcfd1999e3f914d66863dc1ea439517a  rexster-console-2.4.0/lib/rexster-console-2.4.0.jar
fcfd1999e3f914d66863dc1ea439517a  titan-server-0.4.0/lib/rexster-console-2.4.0.jar

Attached are the complete logs of startup/shutdown as well. Are there additional dependencies? The documentation doesn't spell it out. 

$ ./titan.sh start &> titan.start.log

Starting Cassandra...
xss =  -Dtitan.logdir=/home/USERNAME/titan-server-0.4.0/log -ea -javaagent:/home/USERNAME/titan-server-0.4.0/lib/jamm-0.2.5.jar -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms1001M -Xmx1001M -Xmn100M -XX:+HeapDumpOnOutOfMemoryError -Xss256k
Starting Titan + Rexster...
 INFO 10:31:52,081 Logging initialized
 INFO 10:31:52,104 JVM vendor/version: Java HotSpot(TM) 64-Bit Server VM/1.7.0_45
 INFO 10:31:52,104 Heap size: 1039138816/1040187392
 INFO 10:31:52,104 Classpath: /home/USERNAME/titan-server-0.4.0/conf:/home/USERNAME/titan-server-0.4.0/build/classes/main:/home/USERNAME/titan-server-0.4.0/build/classes/thrift:/home/USERNAME/titan-server-0.4.0/lib/activation-1.1.jar:/home/USERNAME/titan-server-0.4.0/lib/akiban-persistit-3.3.0.jar:/home/USERNAME/titan-server-0.4.0/lib/ant-1.8.3.jar:/home/USERNAME/titan-server-0.4.0/lib/ant-launcher-1.8.3.jar:/home/USERNAME/titan-server-0.4.0/lib/antlr-2.7.7.jar:/home/USERNAME/titan-server-0.4.0/lib/antlr-3.2.jar:/home/USERNAME/titan-server-0.4.0/lib/antlr-runtime-3.2.jar:/home/USERNAME/titan-server-0.4.0/lib/asm-3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/asm-analysis-3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/asm-commons-3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/asm-tree-3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/asm-util-3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/astyanax-cassandra-1.56.37.jar:/home/USERNAME/titan-server-0.4.0/lib/astyanax-core-1.56.37.jar:/home/USERNAME/titan-server-0.4.0/lib/astyanax-recipes-1.56.37.jar:/home/USERNAME/titan-server-0.4.0/lib/astyanax-thrift-1.56.37.jar:/home/USERNAME/titan-server-0.4.0/lib/avro-1.4.0-cassandra-1.jar:/home/USERNAME/titan-server-0.4.0/lib/avro-ipc-1.5.3.jar:/home/USERNAME/titan-server-0.4.0/lib/blueprints-core-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/cassandra-all-1.2.2.jar:/home/USERNAME/titan-server-0.4.0/lib/cassandra-thrift-1.2.2.jar:/home/USERNAME/titan-server-0.4.0/lib/colt-1.2.0.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-beanutils-1.7.0.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-beanutils-core-1.7.0.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-cli-1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-codec-1.7.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-collections-3.2.1.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-configuration-1.6.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-digester-1.8.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-el-1.0.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-httpclient-3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-io-2.1.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-lang-2.5.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-logging-1.1.1.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-math-2.2.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-net-1.4.1.jar:/home/USERNAME/titan-server-0.4.0/lib/commons-pool-1.6.jar:/home/USERNAME/titan-server-0.4.0/lib/compress-lzf-0.8.4.jar:/home/USERNAME/titan-server-0.4.0/lib/concurrent-1.3.4.jar:/home/USERNAME/titan-server-0.4.0/lib/concurrentlinkedhashmap-lru-1.3.jar:/home/USERNAME/titan-server-0.4.0/lib/core-3.1.1.jar:/home/USERNAME/titan-server-0.4.0/lib/elasticsearch-0.90.5.jar:/home/USERNAME/titan-server-0.4.0/lib/frames-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/gmbal-3.2.0-b003.jar:/home/USERNAME/titan-server-0.4.0/lib/gmetric4j-1.0.3.jar:/home/USERNAME/titan-server-0.4.0/lib/gremlin-groovy-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/gremlin-java-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-core-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-framework-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-http-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-http-server-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-http-servlet-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-portunif-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/grizzly-rcm-2.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/groovy-1.8.9.jar:/home/USERNAME/titan-server-0.4.0/lib/guava-14.0.1.jar:/home/USERNAME/titan-server-0.4.0/lib/hadoop-core-1.0.4.jar:/home/USERNAME/titan-server-0.4.0/lib/hazelcast-all-3.0.2.jar:/home/USERNAME/titan-server-0.4.0/lib/hbase-0.94.7.jar:/home/USERNAME/titan-server-0.4.0/lib/high-scale-lib-1.1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/hppc-0.4.2.jar:/home/USERNAME/titan-server-0.4.0/lib/hsqldb-1.8.0.10.jar:/home/USERNAME/titan-server-0.4.0/lib/httpclient-4.0.1.jar:/home/USERNAME/titan-server-0.4.0/lib/httpcore-4.0.1.jar:/home/USERNAME/titan-server-0.4.0/lib/ivy-2.3.0.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-annotations-2.1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-core-2.1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-core-asl-1.9.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-databind-2.1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-datatype-json-org-2.1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-jaxrs-1.9.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-mapper-asl-1.9.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jackson-xc-1.9.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jamm-0.2.5.jar:/home/USERNAME/titan-server-0.4.0/lib/jamon-runtime-2.3.1.jar:/home/USERNAME/titan-server-0.4.0/lib/jansi-1.5.jar:/home/USERNAME/titan-server-0.4.0/lib/jasper-compiler-5.5.23.jar:/home/USERNAME/titan-server-0.4.0/lib/jasper-runtime-5.5.23.jar:/home/USERNAME/titan-server-0.4.0/lib/javassist-3.18.0-GA.jar:/home/USERNAME/titan-server-0.4.0/lib/javax.servlet-api-3.0.1.jar:/home/USERNAME/titan-server-0.4.0/lib/jaxb-api-2.2.2.jar:/home/USERNAME/titan-server-0.4.0/lib/jaxb-impl-2.2.3-1.jar:/home/USERNAME/titan-server-0.4.0/lib/jbcrypt-0.3m.jar:/home/USERNAME/titan-server-0.4.0/lib/je-5.0.73.jar:/home/USERNAME/titan-server-0.4.0/lib/jersey-core-1.17.jar:/home/USERNAME/titan-server-0.4.0/lib/jersey-grizzly2-1.17.jar:/home/USERNAME/titan-server-0.4.0/lib/jersey-json-1.17.jar:/home/USERNAME/titan-server-0.4.0/lib/jersey-server-1.17.jar:/home/USERNAME/titan-server-0.4.0/lib/jersey-servlet-1.17.jar:/home/USERNAME/titan-server-0.4.0/lib/jets3t-0.7.1.jar:/home/USERNAME/titan-server-0.4.0/lib/jettison-1.3.3.jar:/home/USERNAME/titan-server-0.4.0/lib/jetty-6.1.26.jar:/home/USERNAME/titan-server-0.4.0/lib/jetty-util-6.1.26.jar:/home/USERNAME/titan-server-0.4.0/lib/jline-1.0.jar:/home/USERNAME/titan-server-0.4.0/lib/jna-3.2.7.jar:/home/USERNAME/titan-server-0.4.0/lib/joda-time-1.6.2.jar:/home/USERNAME/titan-server-0.4.0/lib/json-20090211.jar:/home/USERNAME/titan-server-0.4.0/lib/json-simple-1.1.jar:/home/USERNAME/titan-server-0.4.0/lib/jsp-2.1-6.1.14.jar:/home/USERNAME/titan-server-0.4.0/lib/jsp-api-2.1-6.1.14.jar:/home/USERNAME/titan-server-0.4.0/lib/jsr305-1.3.9.jar:/home/USERNAME/titan-server-0.4.0/lib/junit-benchmarks-0.7.0.jar:/home/USERNAME/titan-server-0.4.0/lib/kfs-0.3.jar:/home/USERNAME/titan-server-0.4.0/lib/kryo-2.21-shaded.jar:/home/USERNAME/titan-server-0.4.0/lib/libthrift-0.7.0.jar:/home/USERNAME/titan-server-0.4.0/lib/log4j-1.2.16.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-analyzers-common-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-codecs-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-core-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-grouping-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-highlighter-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-join-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-memory-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-misc-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-queries-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-queryparser-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-sandbox-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-spatial-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lucene-suggest-4.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/lz4-1.1.0.jar:/home/USERNAME/titan-server-0.4.0/lib/management-api-3.0.0-b012.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-annotation-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-core-2.1.2.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-core-3.0.0-BETA3.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-ganglia-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-graphite-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-healthchecks-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-jersey-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-json-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-jvm-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/metrics-servlets-3.0.0.jar:/home/USERNAME/titan-server-0.4.0/lib/msgpack-0.6.5.jar:/home/USERNAME/titan-server-0.4.0/lib/netty-3.2.7.Final.jar:/home/USERNAME/titan-server-0.4.0/lib/oncrpc-1.0.7.jar:/home/USERNAME/titan-server-0.4.0/lib/org.apache.servicemix.bundles.commons-csv-1.0-r706900_3.jar:/home/USERNAME/titan-server-0.4.0/lib/oro-2.0.8.jar:/home/USERNAME/titan-server-0.4.0/lib/pfl-asm-1.0.0-b001.jar:/home/USERNAME/titan-server-0.4.0/lib/pfl-basic-1.0.0-b001.jar:/home/USERNAME/titan-server-0.4.0/lib/pfl-basic-tools-1.0.0-b001.jar:/home/USERNAME/titan-server-0.4.0/lib/pfl-tf-1.0.0-b001.jar:/home/USERNAME/titan-server-0.4.0/lib/pfl-tf-tools-1.0.0-b001.jar:/home/USERNAME/titan-server-0.4.0/lib/pipes-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/protobuf-java-2.4.0a.jar:/home/USERNAME/titan-server-0.4.0/lib/randomizedtesting-runner-2.0.8.jar:/home/USERNAME/titan-server-0.4.0/lib/rexster-console-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/rexster-core-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/rexster-protocol-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/rexster-server-2.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/servlet-api-2.5-6.1.14.jar:/home/USERNAME/titan-server-0.4.0/lib/servlet-api-2.5.jar:/home/USERNAME/titan-server-0.4.0/lib/slf4j-api-1.7.5.jar:/home/USERNAME/titan-server-0.4.0/lib/slf4j-log4j12-1.7.5.jar:/home/USERNAME/titan-server-0.4.0/lib/snakeyaml-1.6.jar:/home/USERNAME/titan-server-0.4.0/lib/snappy-java-1.0.5-M3.jar:/home/USERNAME/titan-server-0.4.0/lib/snaptree-0.1.jar:/home/USERNAME/titan-server-0.4.0/lib/spatial4j-0.3.jar:/home/USERNAME/titan-server-0.4.0/lib/stax-api-1.0.1.jar:/home/USERNAME/titan-server-0.4.0/lib/stringtemplate-3.2.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-berkeleyje-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-cassandra-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-core-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-es-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-hazelcast-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-hbase-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-lucene-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-persistit-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/titan-rexster-0.4.0.jar:/home/USERNAME/titan-server-0.4.0/lib/uuid-3.2.jar:/home/USERNAME/titan-server-0.4.0/lib/velocity-1.7.jar:/home/USERNAME/titan-server-0.4.0/lib/xmlenc-0.52.jar:/home/USERNAME/titan-server-0.4.0/lib/zookeeper-3.4.5.jar:/home/USERNAME/titan-server-0.4.0/lib/jamm-0.2.5.jar
 WARN 10:31:52,183 Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
 INFO 10:31:52,198 Loading settings from file:/home/USERNAME/titan-server-0.4.0/conf/cassandra.yaml
 INFO 10:31:52,729 DiskAccessMode 'auto' determined to be mmap, indexAccessMode is mmap
 INFO 10:31:52,729 disk_failure_policy is stop
 INFO 10:31:52,736 Global memtable threshold is enabled at 330MB
 INFO 10:31:53,384 Initializing key cache with capacity of 49 MBs.
 INFO 10:31:53,397 Scheduling key cache save to each 14400 seconds (going to save all keys).
 INFO 10:31:53,398 Initializing row cache with capacity of 0 MBs and provider org.apache.cassandra.cache.SerializingCacheProvider
 INFO 10:31:53,406 Scheduling row cache save to each 0 seconds (going to save all keys).
 INFO 10:31:53,645 Opening db/cassandra/data/system/schema_keyspaces/system-schema_keyspaces-ib-6 (317 bytes)
 INFO 10:31:53,716 Opening db/cassandra/data/system/schema_keyspaces/system-schema_keyspaces-ib-7 (220 bytes)
 INFO 10:31:53,746 Opening db/cassandra/data/system/schema_columnfamilies/system-schema_columnfamilies-ib-15 (7113 bytes)
 INFO 10:31:53,754 Opening db/cassandra/data/system/schema_columnfamilies/system-schema_columnfamilies-ib-16 (4536 bytes)
 INFO 10:31:53,763 Opening db/cassandra/data/system/schema_columns/system-schema_columns-ib-7 (3773 bytes)
 INFO 10:31:53,765 Opening db/cassandra/data/system/schema_columns/system-schema_columns-ib-6 (3901 bytes)
 INFO 10:31:53,791 Opening db/cassandra/data/system/local/system-local-ib-28 (120 bytes)
 INFO 10:31:53,793 Opening db/cassandra/data/system/local/system-local-ib-29 (110 bytes)
 INFO 10:31:53,795 Opening db/cassandra/data/system/local/system-local-ib-27 (500 bytes)
 INFO 10:31:54,446 Opening db/cassandra/data/titan/titan_ids/titan-titan_ids-ib-1 (170 bytes)
 INFO 10:31:54,536 Opening db/cassandra/data/titan/system_properties/titan-system_properties-ib-1 (64 bytes)
 INFO 10:31:54,553 Opening db/cassandra/data/system_auth/users/system_auth-users-ib-1 (64 bytes)
 INFO 10:31:54,617 completed pre-loading (6 keys) key cache.
 INFO 10:31:54,650 Replaying db/cassandra/commitlog/CommitLog-2-1383664789357.log, db/cassandra/commitlog/CommitLog-2-1383664789358.log, db/cassandra/commitlog/CommitLog-2-1383664789359.log, db/cassandra/commitlog/CommitLog-2-1383664789360.log, db/cassandra/commitlog/CommitLog-2-1383664789361.log, db/cassandra/commitlog/CommitLog-2-1383664789362.log, db/cassandra/commitlog/CommitLog-2-1383664789363.log
 INFO 10:31:54,686 Replaying db/cassandra/commitlog/CommitLog-2-1383664789357.log
 INFO 10:31:54,811 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789357.log
 INFO 10:31:54,812 Replaying db/cassandra/commitlog/CommitLog-2-1383664789358.log
 INFO 10:31:54,812 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789358.log
 INFO 10:31:54,812 Replaying db/cassandra/commitlog/CommitLog-2-1383664789359.log
 INFO 10:31:54,854 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789359.log
 INFO 10:31:54,854 Replaying db/cassandra/commitlog/CommitLog-2-1383664789360.log
 INFO 10:31:54,888 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789360.log
 INFO 10:31:54,890 Replaying db/cassandra/commitlog/CommitLog-2-1383664789361.log
 INFO 10:31:54,919 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789361.log
 INFO 10:31:54,919 Replaying db/cassandra/commitlog/CommitLog-2-1383664789362.log
 INFO 10:31:54,935 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789362.log
 INFO 10:31:54,936 Replaying db/cassandra/commitlog/CommitLog-2-1383664789363.log
 INFO 10:31:54,939 Finished reading db/cassandra/commitlog/CommitLog-2-1383664789363.log
 INFO 10:31:54,954 Enqueuing flush of Memtable-local@106358232(52/52 serialized/live bytes, 2 ops)
 INFO 10:31:54,962 Writing Memtable-local@106358232(52/52 serialized/live bytes, 2 ops)
 INFO 10:31:54,975 Enqueuing flush of Memtable-schema_keyspaces@1208820522(251/251 serialized/live bytes, 8 ops)
 INFO 10:31:54,982 Enqueuing flush of Memtable-schema_columns@1906891332(21903/21903 serialized/live bytes, 332 ops)
 INFO 10:31:54,982 Enqueuing flush of Memtable-schema_columnfamilies@76669096(21969/21969 serialized/live bytes, 359 ops)
 INFO 10:31:55,035 Completed flushing db/cassandra/data/system/local/system-local-ib-30-Data.db (84 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=142)
 INFO 10:31:55,078 Writing Memtable-schema_keyspaces@1208820522(251/251 serialized/live bytes, 8 ops)
 INFO 10:31:55,097 Completed flushing db/cassandra/data/system/schema_keyspaces/system-schema_keyspaces-ib-8-Data.db (221 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=142)
 INFO 10:31:55,098 Writing Memtable-schema_columns@1906891332(21903/21903 serialized/live bytes, 332 ops)
 INFO 10:31:55,144 Completed flushing db/cassandra/data/system/schema_columns/system-schema_columns-ib-8-Data.db (3771 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=142)
 INFO 10:31:55,144 Writing Memtable-schema_columnfamilies@76669096(21969/21969 serialized/live bytes, 359 ops)
 INFO 10:31:55,173 Completed flushing db/cassandra/data/system/schema_columnfamilies/system-schema_columnfamilies-ib-17-Data.db (4535 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=142)
 INFO 10:31:55,174 Log replay complete, 12 replayed mutations
ERROR 10:31:55,178 Exception in thread Thread[COMMIT-LOG-ALLOCATOR,5,main]
FSWriteError in db/cassandra/commitlog/CommitLog-2-1383665514388.log
    at org.apache.cassandra.db.commitlog.CommitLogSegment.<init>(CommitLogSegment.java:132)
    at org.apache.cassandra.db.commitlog.CommitLogAllocator$3.run(CommitLogAllocator.java:196)
    at org.apache.cassandra.db.commitlog.CommitLogAllocator$1.runMayThrow(CommitLogAllocator.java:94)
    at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: db/cassandra/commitlog/CommitLog-2-1383665514388.log (Permission denied)
    at java.io.RandomAccessFile.open(Native Method)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
    at org.apache.cassandra.db.commitlog.CommitLogSegment.<init>(CommitLogSegment.java:116)
    ... 4 more
 INFO 10:31:55,501 Cassandra version: 1.2.2
 INFO 10:31:55,501 Thrift API version: 19.35.0
 INFO 10:31:55,501 CQL supported versions: 2.0.0,3.0.1 (default: 3.0.1)
 INFO 10:31:55,550 Loading persisted ring state
 INFO 10:31:55,556 Starting up server gossip
 INFO 10:31:55,593 Enqueuing flush of Memtable-local@128705692(251/251 serialized/live bytes, 9 ops)
 INFO 10:31:55,593 Writing Memtable-local@128705692(251/251 serialized/live bytes, 9 ops)
 INFO 10:31:55,610 Completed flushing db/cassandra/data/system/local/system-local-ib-31-Data.db (238 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=50385)
 INFO 10:31:55,714 Compacting [SSTableReader(path='db/cassandra/data/system/local/system-local-ib-30-Data.db'), SSTableReader(path='db/cassandra/data/system/local/system-local-ib-31-Data.db'), SSTableReader(path='db/cassandra/data/system/local/system-local-ib-29-Data.db'), SSTableReader(path='db/cassandra/data/system/local/system-local-ib-28-Data.db'), SSTableReader(path='db/cassandra/data/system/local/system-local-ib-27-Data.db')]
 INFO 10:31:55,842 Starting Messaging Service on port 7000
 INFO 10:31:55,851 Compacted 5 sstables to [db/cassandra/data/system/local/system-local-ib-32,].  1,052 bytes to 494 (~46% of original) in 136ms = 0.003464MB/s.  5 total rows, 1 unique.  Row merge counts were {1:0, 2:0, 3:0, 4:0, 5:1, }
 INFO 10:31:55,944 Using saved token [-2700724245002588400]
 INFO 10:31:55,953 Enqueuing flush of Memtable-local@1215713589(84/84 serialized/live bytes, 4 ops)
 INFO 10:31:55,953 Writing Memtable-local@1215713589(84/84 serialized/live bytes, 4 ops)
 INFO 10:31:55,971 Completed flushing db/cassandra/data/system/local/system-local-ib-33-Data.db (120 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=50660)
 INFO 10:31:55,979 Enqueuing flush of Memtable-local@1263451227(51/51 serialized/live bytes, 2 ops)
 INFO 10:31:55,980 Writing Memtable-local@1263451227(51/51 serialized/live bytes, 2 ops)
 INFO 10:31:56,000 Completed flushing db/cassandra/data/system/local/system-local-ib-34-Data.db (110 bytes) for commitlog position ReplayPosition(segmentId=1383665514387, position=50835)
 INFO 10:31:56,018 Node localhost/127.0.0.1 state jump to normal
 INFO 10:31:56,026 Startup completed! Now serving reads.
Processes forked.  Setup may take some time.
Run ./rexster-console.sh to connect.
Error: Could not find or load main class com.tinkerpop.rexster.Application

$ ./titan.sh stop &> titan.stop.log

Titan + Rexster (com.tinkerpop.rexster.Application) not found in the java process table
Killing Cassandra (pid 3750)...

**Comment by dalaro** [comment]
Ah, I read right past the issue in the first message.  This is a known path bug in 0.4.0's titan.sh.  It's fixed in master and will be fixed in 0.4.1.

For now, cd to the root of the extracted distribution and run bin/titan.sh instead of cding into bin and running ./titan.sh.  Silly, I know, but a fix is coming.

**Comment by puneetar** [comment]
Hi Dalaro,

I am a student and doing a benchmark analysis over titan_cassadra and Neo4j.

I am facing the same Issue #462  in titan-server-0.4.1.
I am using ubuntu 12.04 LTS

pld4@pld4-virtual-machine:~/titan-server-0.4.1$ sudo ./bin/titan.sh -c cassandra-es start
Starting Cassandra...
Started Cassandra.  Thrift service is alive.
Forking Titan + Rexster...
Forked Titan + Rexster.
Rexster may need a few more seconds to finish bootstrapping.
Run ./bin/rexster-console.sh to connect.

pld4@pld4-virtual-machine:~/titan-server-0.4.1$ sudo ./bin/titan.sh -c cassandra-es stop
./bin/titan.sh: line 59: jps: command not found
Titan + Rexster (com.tinkerpop.rexster.Application) not found in the java process table
./bin/titan.sh: line 59: jps: command not found
Cassandra (org.apache.cassandra.service.CassandraDaemon) not found in the java process table

When I do a ps -ef | grep titan .. the titan server is still running, Moreover, it is only happening in few machines and I am using the same distribution on all machines

Kindly, help me on this. Am I doing something wrong ?

**Comment by puneetar** [comment]
Apologies Dalaro, it is not at all related to issue #462.

I found the problem and the solution for it.

The titan.sh script tries to use "jps" which was not available in the default path i.e. /usr/bin/
Actually I installed sun-jdk7_45, so it was installed in usr/lib/jvm. Therefore the titan script was not able to find it.

So did the following fix in titan.sh:
ORIGINAL:
 local p=`jps -l | grep "$2" | awk '{print $1}'`

UPDATE:
 local p=`${JAVA_HOME}/bin/jps -l | grep "$2" | awk '{print $1}'`

And it worked like a charm.

**Comment by oren** [comment]
I use ubuntu 15.04 and I couldn't run `bin/titan.sh -c cassandra-es status` until I changed the line to it's original version - local p=jps -l | grep "$2" | awk '{print $1}'
