### ISSUE TITLE
Detect token ring bounds over localhost connection

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#465]
for both Cassandra and Hbase when a local connection is made to the storage backend and the keys are kept in sorted order (always true for Hbase).
In order word, extends this feature from CassandraEmbedded to CassandraThrift and HBase so we can read local partitions and effectively partition the graph.

**Comment by xedin** [comment]
This has already been merged into titan05 (at least Cassandra side of things).

**Comment by mbroecheler** [comment]
fixed in titan05
