### ISSUE TITLE
Bug RexsterClient traversal

### ISSUE THREAD

**Issue by dirkweissenborn** [thinkaurelius/titan#471]
I am querying the graph through rexpro with many queries (only reading, no writing) and mysteriously at some point the results of one query change (becoming wrong results). I try to verify the problem in gremlin and I cannot reproduce the problem. I know which queries were issued prior to the problem:

```
g.v(2152).transform{[ it.outE('hmod -> induce:VB -> pobj').count(), it.depth, it.totalDepth ]}.next()                                                                        --> gives right result
g.v(35416).inE.filter{!notAllowed.contains(it.label)}.transform{[it.label,it.outV.next().ui,it.outV.next().text]}
g.v(35416).outE.filter{!notAllowed.contains(it.label)}.transform{[it.label,it.inV.next().ui,it.inV.next().text]}
g.v(2152).transform{[ it.outE('hmod -> induce:VB -> pobj').count(), it.depth, it.totalDepth ]}.next()                                                                        --> gives wrong result     
```

If I issue those queries before I run my loop (in which I do some traversing), it works. Inside the loop, after some traversing it doesn't anymore.

I cannot figure out what the problem is, but it is very weird and seems to only happen to edges with this label.

**Comment by mbroecheler** [comment]
@D9891 according to the mails on the mailing list this does not occur through the gremlin shell but only when you run those queries in Rexster, is that correct? Would you mind verifying this so we know that we can isolate the bug to Rexster?
Thank you.

**Comment by dirkweissenborn** [comment]
This is correct, but I am not sure this is a rexster bug though. I mean, I cannot run the same algorithm in a simple gremlin console, that's why I could not replicate the problem with gremlin, but that does not mean, that the bug is actually coming from rexster. I have the feeling it has something to do with titan, but of course I am not the expert here. It also only happens with one particular type of label which is very strange.

**Comment by spmallette** [comment]
On the surface, the queries themselves don't seem to contain anything that would make me think anything would be wrong.  Btw, interesting edge label names: `hmod -> induce:VB -> pobj`....never seen that before.  Is there more information in the mailing list on the exact nature of what's wrong in your results?  Could you please supply a link to the post if so?

**Comment by dirkweissenborn** [comment]
Sorry, that is all I got. I really tried to get to the surface of that problem, but since it is not reproducible out of the context it occurs in I don't have anything else. I just ignore the issue for now, because it only happened for this specific edge or label. FYI, the edge label name is simply a dependency path from dependency trees (which are linguistic constructs).

**Comment by mbroecheler** [comment]
@D9891 why can you not run the algorithm in Gremlin? It has the same expressive power as Rexster.

**Comment by dirkweissenborn** [comment]
Because I have more than one graph which I query simultaneously. After each query I need to combine the results of this query from each graph, then I take these results and issue a new query to all graphs and so on. I would have to rewrite my whole code (which is written in scala) to groovy to let it run only on one graph using gremlin.

**Comment by mbroecheler** [comment]
Interesting setup. Is there way you can isolate this error you are seeing? It is very hard for us to debug something sitting at the very top of the stack when we don't know what the data and program looks like. Thank you.

**Comment by dirkweissenborn** [comment]
That is the same problem I had. I tried to reproduce the problem by finding out which queries were being issued prior to that problem and applying those to the graph where the change happened. Unfortunately this did not reproduce the error and I am kind of stuck. However, I will try to figure out a way to see what's really going on. It might be related to some elusive graph inconsistencies I reported in #476.

**Comment by dirkweissenborn** [comment]
Could there be a problem if I create a lot of edges with a lot of different labels? I changed my implementation now, such that I rather create a property for the dependency path instead of using the dependency path as a label. Does this effect performance in some way? Maybe this might also solve the problem.

**Comment by mbroecheler** [comment]
Titan should be able to support lots of different labels. What can cause a
problem is if those labels are created while storage.batch-loading is
enabled. In that case, you can have weird race conditions that can cause
edges to seamingly disappear.

On Tue, Nov 12, 2013 at 8:11 AM, D9891 notifications@github.com wrote:

> Could there be a problem if I create a lot of edges with a lot of
> different labels? I changed my implementation now, such that I rather
> create a property for the dependency path instead of using the dependency
> path as a label. Does this effect performance in some way? Maybe this might
> also solve the problem.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/471#issuecomment-28306682
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
Are you still seeing this issue?

**Comment by dirkweissenborn** [comment]
I am handling ui -> id mapping now locally, because like this I can iterate through the graph with my stored ids and I know which uis were already added. This was a fix from my side. When I see it again, I will report updates, but it is very unlikely now, because I handle uniqueness also on my side.
