### ISSUE TITLE
Provide a TitanRowCacheProvider for use with Cassandra

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#475]
```
TitanRowCacheProvider implements org.apache.cassandra.cache.IRowCacheProvider.
```

From the DataStax documentation:

```
row_cache_provider

(Default: SerializingCacheProvider) Specifies what kind of implementation to use for the row cache.

SerializingCacheProvider: Serializes the contents of the row and stores it in native memory, that is, off the JVM Heap. Serialized rows take significantly less memory than live rows in the JVM, so you can cache more rows in a given memory footprint. Storing the cache off-heap means you can use smaller heap sizes, which reduces the impact of garbage collection pauses. It is valid to specify the fully-qualified class name to a class that implements org.apache.cassandra.cache.IRowCacheProvider.
ConcurrentLinkedHashCacheProvider: Rows are cached using the JVM heap, providing the same row cache behavior as Cassandra versions prior to 0.8.
The SerializingCacheProvider is 5 to 10 times more memory-efficient than ConcurrentLinkedHashCacheProvider for applications that are not blob-intensive. However, SerializingCacheProvider may perform worse in update-heavy workload situations because it invalidates cached rows on update instead of updating them in place as ConcurrentLinkedHashCacheProvider does.
```

@dkuppitz  and I have played with both SerializingCacheProvider (default and off-heap) and ConcurrentLinkedHashCacheProvider (on-heap). They perform (t = System.currentTimeMillis()) about the same (ConcurrentLinkedHashCacheProvider is ~10-20% faster). However, I'm wondering if Titan could have its own specific implementation of a IRowCacheProvider that more easily (less CPU) moves from Cassandra's cache to Titan's TX Java objects, then the cache would be more effective.

This would (of course) be Titan/Cassandra specific, but a nice addition/boon for using Titan/Cassandra.

Note that by default Titan has row-caching off for edgestore.

**Comment by mbroecheler** [comment]
If we put it on heap, we will suffer from the same deficiencies that ConcurrentLinkedHashCacheProvider has: much higher memory footprint which further compounds the issue that a lot of data is held on heap and hence under the control of the GC.
If we put it off heap, then the performance will be identical to if maybe marginally better than the current SerializingCacheProvider which does not justify the development cost.
