### ISSUE TITLE
[Enhancement] Streaming Transactions for BDB

### ISSUE THREAD

**Issue by dirkweissenborn** [thinkaurelius/titan#480]
It would be very nice to have streaming transactions for BDB, to make global graph operations faster (e.g. iterating over all vertices).

**Comment by mbroecheler** [comment]
So, you are finding that having transactions enabled and doing a g.V is too expensive, right?
I think this is related to #71.

**Comment by dirkweissenborn** [comment]
Yes, it takes ages for reasonably large graphs (some millions of vertices). Does the number of edges effect g.V?

**Comment by mbroecheler** [comment]
Yes, for BDB it does. g.V requires a full table scan. There is no optimization for this query yet.
If this is a read only graph, why not disable transactions?

**Comment by dirkweissenborn** [comment]
I do disable them. Still it is very slow!

**Comment by mbroecheler** [comment]
Ok, thanks. Can you post the query you are executing with g.V.... so I can take a look at the runtimes?

**Comment by mbroecheler** [comment]
This has been addressed by the Fulgora streaming component
