### ISSUE TITLE
Annoying warnings when using BatchGraph

### ISSUE THREAD

**Issue by dirkweissenborn** [thinkaurelius/titan#481]
```
val bGraph = new BatchGraph(graph, VertexIDType.STRING, 1000000)

bGraph.addVertex(someUI,'ui',someUI)
```

always gives me the warning:

Provided vertex id [someUI] is not supported by Titan and hence ignored

However, when using BatchGraph someUI has to be provided for addVertex, such that BatchGraph remembers the mappings from my uis to titan ids.

**Comment by mbroecheler** [comment]
The warning has been disabled and changed to an info statement.
