### ISSUE TITLE
Question about SetProperty

### ISSUE THREAD

**Issue by virgil0** [thinkaurelius/titan#482]
Hi there, I got a problem when I try to use rexster server.
I am using titan-server-0.4.0. Created a graph through gremlin.sh.
Then I add the graph to db. and add a rexster.xml.
rexster.xml:
<?xml version="1.0" encoding="UTF-8"?>
<rexster>
    <http>
        <server-port>8182</server-port>
        <server-host>0.0.0.0</server-host>
        <base-uri>http://localhost</base-uri>
        <web-root>public</web-root>
        <character-set>UTF-8</character-set>
        <enable-jmx>false</enable-jmx>
        <enable-doghouse>true</enable-doghouse>
        <max-post-size>2097152</max-post-size>
        <max-header-size>8192</max-header-size>
        <upload-timeout-millis>30000</upload-timeout-millis>
        <thread-pool>
            <worker>
                <core-size>8</core-size>
                <max-size>8</max-size>
            </worker>
            <kernal>
                <core-size>4</core-size>
                <max-size>4</max-size>
            </kernal>
        </thread-pool>
        <io-strategy>leader-follower</io-strategy>
    </http>
    <rexpro>
        <server-port>8184</server-port>
        <server-host>0.0.0.0</server-host>
        <session-max-idle>1790000</session-max-idle>
        <session-check-interval>3000000</session-check-interval>
        <connection-max-idle>180000</connection-max-idle>
        <connection-check-interval>3000000</connection-check-interval>
        <enable-jmx>false</enable-jmx>
        <thread-pool>
            <worker>
                <core-size>8</core-size>
                <max-size>8</max-size>
            </worker>
            <kernal>
                <core-size>4</core-size>
                <max-size>4</max-size>
            </kernal>
        </thread-pool>
        <io-strategy>leader-follower</io-strategy>
    </rexpro>
    <shutdown-port>8183</shutdown-port>
    <shutdown-host>127.0.0.1</shutdown-host>
    <script-engines>
        <script-engine>
            <name>gremlin-groovy</name>
            <reset-threshold>-1</reset-threshold>
            <init-scripts>config/init.groovy</init-scripts>
            <imports>com.tinkerpop.rexster.client._</imports>
            <static-imports>java.lang.Math.PI</static-imports>
        </script-engine>
    </script-engines>
    <security>
        <authentication>
            <type>none</type>
            <configuration>
                <users>
                    <user>
                        <username>rexster</username>
                        <password>rexster</password>
                    </user>
                </users>
            </configuration>
        </authentication>
    </security>
    <metrics>
        <reporter>
            <type>jmx</type>
        </reporter>
        <reporter>
            <type>http</type>
        </reporter>
        <reporter>
            <type>console</type>
            <properties>
                <rates-time-unit>SECONDS</rates-time-unit>
                <duration-time-unit>SECONDS</duration-time-unit>
                <report-period>10</report-period>
                <report-time-unit>MINUTES</report-time-unit>
                <includes>http.rest._</includes>
                <excludes>http.rest.*.delete</excludes>
            </properties>
        </reporter>
    </metrics>
    <graphs>
        <graph>
          <graph-name>rGraph</graph-name>
          <graph-type>com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration</graph-type>
          <graph-location>db/rGraph</graph-location>
          <graph-read-only>false</graph-read-only>
          <properties>
                <storage.backend>local</storage.backend>
                <storage.buffer-size>100</storage.buffer-size>
          </properties>
          <extensions>
            <allows>
              <allow>tp:gremlin</allow>
            </allows>
          </extensions>
        </graph>
    </graphs>
</rexster>

Then I start the server using "bin/rexster.sh -s rexster.xml".
The problem is I can add vertex through code like:
RexsterGraph rgraph = new RexsterGraph("http://ur.lti.cs.cmu.edu:8182/graphs/rGraph");
 Vertex a = rgraph.addVertex(null);
    a.setProperty("name", "juno");
It's ok to add vertex but when i try to setProperty it says that
 Server returned HTTP response code: 500 for URL: http://localhost:8182/graphs/rGraph/vertices/4

Any ideas?

Thank you!

**Comment by mbroecheler** [comment]
@virgil0 : Please use our public mailing list aureliusgraphs@googlegroups.com for questions. Thank you.
