### ISSUE TITLE
Consider switching persistence times milliseconds

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#483]
From @xedin: all of the standard tools are at micros granularity so if only titan writes to that would be all fine because longs would be the same bit size but non of the standard tools would be able to override the data

**Comment by dalaro** [comment]
From Pavel's comment I think the title of this ticket should be "...times to microseconds".  Yeah?

I'm aware of Guava Ticker and considering replacing TimestampProvider with it, but I don't like that it exposes systemTicker().

**Comment by dalaro** [comment]
Actually, I'm definitely not going to extend Ticker now that I see the javadoc saying it's used only for nanotime and we're moving towards micros or millis.  That's a time unit conversion error waiting to happen.

**Comment by dalaro** [comment]
Summary: I added an experimental "timestamps" config option to choose between milliseconds, microseconds, or nanoseconds timestamps throughout the diskstorage layer.  It defaults to microseconds.

Discussion:

I refactored core's existing `TimestampProvider` interface and implemented it in a new `Timestamps` enum with values `MILLI`, `MICRO`, and `NANO`.  This is essentially Titan's supported subset of `TimeUnit`, plus a helper method for sleep-until-timestamp logic needed in several places.  (At millisecond resolution, some of the Cassandra tests are capable of completing colliding writes inside 1 ms and triggering a test failure)

ConsistentKeyLocker, ConsistentKeyIDManager, HBase, and Cassandra in titan05 HEAD use a `TimestampProvider` implementation whenever the tx config lacks a manually-specified timestamp value.  The impl is controlled by the graph config option "timestamps".  This is defined in GraphDatabaseConfiguration in the Titan namespace with type `ConfigOption<Timestamps>` and Type.FIXED.  It defaults to `MICRO`.

I might remove the option and hardcode the effective value.  However, flexibility to centrally change Titan's timestamp resolution may be useful as we integrate new store/index/msgbroker services, so we should retain the plumbing even if the user-facing option goes away.  If we do expose this as a config option, then I want to expand test coverage on the non-default timestamp resolutions.

I think the only component that still uses a hardcoded timestamp unit is KCVSConfiguration.  This uses the config option's default value.  It seems possible to make KCVSConfiguration use a localconfig value for timestamp units, but refactoring it to do so seemed kind of tricky for questionable payoff.

The ID manager also still uses currentTimeMillis in column values, though the HBase version/Cassandra write timestamp is now dictated by the config option.

Commits:

0c9e1e80068e5724af428f773600806d733be398
efe3e65ab6c651a00efbbc48d9501e7be64111b1
6b55174bb2f7559ef47696222adf5f65f61b58f5
f0d41c6743a3514966326d90e9b1234c5d58e16e
837d05077f634cfea64495f0ae1d83f01d715a57
851790ea09b19fb839568d036ff7da5744767b58
8919c7edd0b762e7749becf0672695e21d5b10fe
2a718b846a771f20711041bc87aceaf502c20ae3

**Comment by dalaro** [comment]
The default in titan05 is now microseconds both Cassandra and HBase.  These timestamps are computed by System.currentTimeMillis() \* 1000 and so they effectively only have millisecond resolution even though the units are microseconds.  Both the HBase and Cassandra backends block, if necessary, after completing a write until the timestamp changes.  But we could go back to the elaborate function-of-nanotime-and-currentTimeMillis dance that we had at nanosecond resolution but truncate by three orders of magnitude if necessary.
