### ISSUE TITLE
drop indices (and/or types) on a per-connection basis

### ISSUE THREAD

**Issue by pellyadolfo** [thinkaurelius/titan#488]
I have a graph which takes several hours in being populated with metadata. In order to fine tune performance by setting the right indices it seems that indices already created can not be dropped. So, no other option than start again, setup a new brand graph and repopulate it again (hours between tests of the indices configuration).

It would be hepful (but do not know if feasible) the possibility of dropping indices (maybe on a per-connection basis or something as indices with per-connection lifecycle) or just a mechanism for dropping indices.

The issue was opened here https://groups.google.com/forum/#!topic/aureliusgraphs/5L0oN4zv48Y

**Comment by mbroecheler** [comment]
It will be possible to drop mixed/ES based indexes in Titan 0.5. However, composite indexes cannot be entirely dropped yet, only disabled. Hence, this ticket will survive into titan 0.6

**Comment by dalaro** [comment]
@mbroecheler is documentation (and perhaps additional testing) the only remaining task in this issue?

ManagmentSystem.updateIndex's `REMOVE_INDEX` case seems to have logic for removing all but mixed graph indices, for which an exception directs the user to drop the index manually in the backend:

``` java
case REMOVE_INDEX:
    if (index instanceof RelationTypeIndex) {
        builder = graph.getBackend().buildEdgeScanJob();
    } else {
        TitanGraphIndex gindex = (TitanGraphIndex)index;
        if (gindex.isMixedIndex())
            throw new UnsupportedOperationException("External mixed indexes must be removed in the indexing system directly.");
        builder = graph.getBackend().buildGraphIndexScanJob();
    }
    builder.setFinishJob(indexId.getIndexJobFinisher());
    builder.setJobId(indexId);
    builder.setJob(new IndexRemoveJob(graph,indexId.indexName,indexId.relationTypeName));
    try {
        future = builder.execute();
    } catch (BackendException e) { throw new TitanException(e); }
    break;
```

For large composite indices, there are two helper methods on `MapReduceReindexJobs` that spin up an index removal scanjob:
- `hbaseRemove`
- `cassandraRemove`

**Comment by mbroecheler** [comment]
Yes, it is my understanding that the implementation is complete (modulo bugs).

**Comment by dalaro** [comment]
I wrote docs for this today in a local branch.  The gremlin.sh-pastable sample code snippet that I wrote to remove a composite graph index on BDB executes without errors and seems innocuous enough up through the steps required to disable the index and await its state change to `DISABLED`.  An IndexRemoveJob on it then runs but doesn't appear to do anything: ScanMetrics show 0 for both FAILURE and SUCCESS.  Attaching with a debugger shows that `workerIterationStart` is invoked, but `process` is not.  I think I found one issue.  IndexRemoveJob's `keyFilter` was choking on some buffer underruns on short graphindex keys -- not sure if that if that itself is indicative of an error, but I thought it should be tolerated, and so tweaked it in 98f864b40c1970dce3f8a82e3fd16180343a50fd.  Still not getting into `process`.  Going to take a closer look.

**Comment by dalaro** [comment]
Matthias fixed a subtle related issue with IndexRemoveJob's slice bounds in a457c6bc3a440d72e045436f8be7a93948568f2e.  I also reworked the API around this in #1040.  The documentation for dropping indexes (and reindexing) went in as PR #1047.
