### ISSUE TITLE
unique() locks all vertex properties

### ISSUE THREAD

**Issue by ilyakard** [thinkaurelius/titan#489]
We've been having some issues with concurrency and locking in titan 0.4.1. We are using a rexpro connection and cassandra-thrift to connect our rails application to titan. Multiple user accounts log in at once. On login we update a few properties on the User vertex with type definitions like this:

``` java
g.makeKey("last_sign_in_ip").dataType(String.class).single(UniquenessConsistency.NO_LOCK).make()
```

This property is not modified (but is read):

``` java
g.makeKey("login").dataType(String.class).single(UniquenessConsistency.NO_LOCK).unique().indexed(Vertex.class).make()
```

The gremlin command that we are using to update the user properties:

``` java
v = g.v(id); 
params.each { v.setProperty(it.key, it.value) }
```

``` ruby
bindings: {
  :id=>5440, 
  :params=>{
    :last_sign_in_at=>1384861765, 
    :current_sign_in_at=>1384861765, 
    :last_sign_in_ip=>"127.0.0.1", 
    :current_sign_in_ip=>"127.0.0.1", 
    :sign_in_count=>1, 
    :updated_at=>1384861765
}}
```

All of the above is being done in one transaction, which is committed at the end of the http session. Removing the `unique()` from the login type definition makes the locking problem go away. Running with batch loading on makes it go away. We didn't have this problem in 0.3.2. 

Is this expected behaviour or should we be acquiring locks on the vertex properties that are modified only?

Thanks!

**Comment by mbroecheler** [comment]
Could you do me a favor and check whether setting "fast-property=false" in
the configuration file changes anything?

On Tue, Nov 19, 2013 at 5:46 AM, Ilya notifications@github.com wrote:

> We've been having some issues with concurrency and locking in titan 0.4.1.
> We are using a rexpro connection and cassandra-thrift to connect our rails
> application to titan. Multiple user accounts log in at once. On login we
> update a few properties on the User vertex with type definitions like this:
> 
> g.makeKey("last_sign_in_ip").dataType(String.class).single(UniquenessConsistency.NO_LOCK).make()
> 
> This property is not modified (but is read):
> 
> g.makeKey("login").dataType(String.class).single(UniquenessConsistency.NO_LOCK).unique().indexed(Vertex.class).make()
> 
> The gremlin command that we are using to update the user properties:
> 
> v = g.v(id); params.each { v.setProperty(it.key, it.value) }
> 
> bindings: {
>   :id=>5440,
>   :params=>{
>     :last_sign_in_at=>1384861765,
>     :current_sign_in_at=>1384861765,
>     :last_sign_in_ip=>"127.0.0.1",
>     :current_sign_in_ip=>"127.0.0.1",
>     :sign_in_count=>1,
>     :updated_at=>1384861765}}
> 
> All of the above is being done in one transaction, which is committed at
> the end of the http session. Removing the unique() from the login type
> definition makes the locking problem go away. Running with batch loading on
> makes it go away. We didn't have this problem in 0.3.2.
> 
> Is this expected behaviour or should we be acquiring locks on the vertex
> properties that are modified only?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/489
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by ilyakard** [comment]
`fast-property=false` has fixed it, and has made the other (read-only) traversals in our performance test faster. There were other vertices with unique properties being traversed.

Thanks Matthias!

**Comment by mbroecheler** [comment]
Thanks @ilyakardailsky, this pointed me to a bug in the retrieval of Titan's types in the sense that it did not utilize the cache correctly. If you pull the current master and enable `fast-property=true` you should see the same if not faster performance, because this setting will retrieve all properties with one Cassandra call when you are updating a bunch of properties.

However, I could not determine how this could have impacted locking. What locking exceptions are you seeing when fast-property is enabled? Could you send me the stack trace?

Thanks,
Matthias

**Comment by ilyakard** [comment]
Repeated our concurrency tests and everything looks good with the official 0.4.1 release. The exceptions we were getting were the Cassandra thread blocks that Lars wrote to you about on the mailing list: https://groups.google.com/d/msg/aureliusgraphs/qfC97cM83rw/i5e7CssQM_EJ
These are now gone, not sure after which commit, perhaps the above fast-property fix. Also had a >50% performance boost after enabling the db cache, new release looks fantastic!
