### ISSUE TITLE
Typo is Exception -- g.V and g.E.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#494]
Please see the two global scan queries below:

```
gremlin> g.V.count()
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>809
gremlin> g.E.count()
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>8049
```

The second one should read:

```
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all edges [()]. For better performance, use indexes
```

While you may be getting all edges by scanning all vertices and emitting v.outE, perhaps for cleanliness, its good to say "iterating over all edges"

**Comment by mbroecheler** [comment]
Problem is that g.E calls g.V internally so there is no way for us to
"mask" this warning message.

On Sun, Nov 24, 2013 at 9:27 AM, Marko A. Rodriguez <
notifications@github.com> wrote:

> Please see the two global scan queries below:
> 
> gremlin> g.V.count()
> WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
> ==>809
> gremlin> g.E.count()
> WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
> ==>8049
> 
> The second one should read:
> 
> WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all edges [()]. For better performance, use indexes
> 
> While you may be getting all edges by scanning all vertices and emitting
> v.outE, perhaps for cleanliness, its good to say "iterating over all edges"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/494
> .

## 

Matthias Broecheler
http://www.matthiasb.com
