### ISSUE TITLE
Fulgora and Hazelcast documentation still in Titan main.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#495]
The following two links should be removed from Titan and put into the "experimental" Titan wiki.

https://github.com/thinkaurelius/titan/wiki/Fulgora
https://github.com/thinkaurelius/titan/wiki/Using-Hazelcast

**Comment by mbroecheler** [comment]
I have copied the pages over but not deleted them in the current wiki (you
never know ;-). I removed the reference to those pages.

On Sun, Nov 24, 2013 at 9:51 AM, Marko A. Rodriguez <
notifications@github.com> wrote:

> The following two links should be removed from Titan and put into the
> "experimental" Titan wiki.
> 
> https://github.com/thinkaurelius/titan/wiki/Fulgora
> https://github.com/thinkaurelius/titan/wiki/Using-Hazelcast
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/495
> .

## 

Matthias Broecheler
http://www.matthiasb.com
