### ISSUE TITLE
0.5.0 should remove local: as possibility

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#504]
This "local:conf/titan.properties" as a folder and using BerekelyDB cause more problems then it solves. I think that by 0.5.0 we should have it so that every TitanFactory.open() MUST point to a properties file and if not, it gives a FileNotFoundException, where for local, you have to have a respective properites file.

**Comment by dalaro** [comment]
TitanFactory.open() on titan05 (as of a 0385d74d3f8ebbbfa5887b1a8c7a0aa8d3701645) no longer creates a BDB instance when the argument doesn't exist.  It throws an IllegalArgumentException on mistyped paths now, which I think is an improvement.  I'm not sure what commit made this change.

Incidentally, TitanFactory.open as of the same comimt also rejects arguments like "local:conf/titan.properties" even when conf/titan.properties exists, though it accepts just "conf/titan.properties".

So this is done.  I think.

**Comment by mbroecheler** [comment]
fixed in titan05
