### ISSUE TITLE
Ignore unknown fields in indexQuery

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#507]
`indexQuery()` currently throws an Exception when you use a non existent field/key. ES/Lucene will ignore unkown fields. To get the same result in Titan we could simply ignore/pass-through unknown field names.

Maybe a configuration option would be a good idea. Something like:

```
storage.index.search.ignore-unkown-fields=true
```

with a default value of `false`.

**Comment by mbroecheler** [comment]
The configuration option is called:
<code>
ignore-unknown-index-key=true
</code>
but will likely change in Titan 0.5 since the configuration system is being refactored for that release.
