### ISSUE TITLE
Resource leak when using 0.4.1 + cassandrathrift and iterating over all vertices

### ISSUE THREAD

**Issue by vshchukin** [thinkaurelius/titan#508]
Hello,

I've experienced lockups when using cassandrathrift backend and iterating over all vertices.
Steps to reproduce: 
- using titan-server-0.4.1.zip
- using Rexster config https://github.com/MrKeyholder/random-data/blob/master/titan/rexster-cassandra.xml (the only change from default file is `storage.backend` changed from `cassandra` to `cassandrathrift` )
- run ./bin/titan.sh -c cassandra start
- Open a few times http://localhost:8182/graphs/graph/vertices (20 times should be enough with default connection pool size)
- Web page stops responding
- Not reproducible when using `cassandra` option as backend

Here's thread dump: https://github.com/MrKeyholder/random-data/blob/master/titan/threaddump.txt#L412-479

My guess is that iterators like `AllTokensIterator` and `KeyRangeIterator` in `CassandraThriftKeyColumnValueStore` are not being closed thus connections are not returned to the pool.

Environment:
jdk8
ubuntu 13.10

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/512, problem is related to pool behavior when iterators hold on to connections. Please give it a try.

**Comment by xedin** [comment]
@mbroecheler I'm pretty confident that we can move on and merge this.

**Comment by vshchukin** [comment]
Works OK for me, thanks. Added test in separate pull request.

**Comment by mbroecheler** [comment]
Closed when merged #512
