### ISSUE TITLE
gremlin.sh doesn't parse more than 9 parameters

### ISSUE THREAD

**Issue by tsecheran** [thinkaurelius/titan#510]
If more than 9 parameters passed onto gremlin.sh,  gremlin interprets 10 as ${1}0, so the 10th param would result in "-e0", this is due to this following eval in the parsing block

if [ $# -gt 2 ]; then
    for (( i=3 ; i < $# + 1 ; i++ ))
    do
      eval a=\$$i
      k="$k \"$a\""
    done
  fi

**\* eval a=\${${i}} **\* should fix this issue...

**Comment by dalaro** [comment]
I merged your associated PR (#513) into master.  This part of gremlin.sh looks needlessly byzantine... it seems like the loop and eval block could be replaced with a couple of conditional calls to the `shift` builtin.  Still, your fix looks correct and in testing seems to handle both arguments with internal spaces and positional arguments greater than $9.  Thanks.

**Comment by tsecheran** [comment]
Thanks for the merging the fix.
