### ISSUE TITLE
indexQuery() not supporting terms with underscores

### ISSUE THREAD

**Issue by ilyakard** [thinkaurelius/titan#515]
I have some indexed vertex properties with underscores in the name.

```
rexster[groovy]> g.indexQuery("search", "v.first_name:ilya").vertices()
==>An error occurred while processing the script for language [groovy]. All transactions across all graphs in the session have been concluded with failure: java.util.concurrent.ExecutionException: javax.script.ScriptException: javax.script.ScriptException: java.lang.IllegalArgumentException: Found reference to non-existant property key in query at position [0]: first
```

It seems Titan is breaking up the indexed property key name at the underscore, I believe underscores in the field name should be supported in the Lucene syntax. Escaping it out with \ did not seem to work. Other indexQuery calls are working great with my titan/cassandra/es setup, thanks!

**Comment by mbroecheler** [comment]
You have to escape the entire property name when it contains non-alphabetic characters:

"v.\"first_name\":ilya"

**Comment by dkuppitz** [comment]
Added this information to the according wiki page: https://github.com/thinkaurelius/titan/wiki/Direct-Index-Query

**Comment by ilyakard** [comment]
Ah thanks for clarifying guys.
