### ISSUE TITLE
count() in user defined steps

### ISSUE THREAD

**Issue by carlosalberto** [thinkaurelius/titan#516]
count() -and likely other similar functions- don't work at all in a user defined step. Example:

g.v(1).out.count() -> works, returns the count of outgoing vertices.

Gremlin.defineStep('vouts', [Vertex, Pipe], { _().out.count() }) -> ok
g.v(1).vouts -> FAIL
groovysh_evaluate cannot be cast to com.tinkerpop.blueprints.Vertex
(Huge, not very helpful stacktrace...)

I'm pretty sure there must be a reason to do so (Pipe, Vertex types related), but since nothing more is mentioned in the docs, I'm clueless. Or is that a limitation?

**Comment by spmallette** [comment]
This is really a Gremlin issue and not related to Titan.  `_().out.count()` is iterating the pipeline and returning a count.  You technically don't want to return that numeric value as that closure you are supplying to the `defineStep` should return a `Pipe`.  One way to do that would be to do:

``` text
gremlin> g = TinkerGraphFactory.createTinkerGraph()                                 
==>tinkergraph[vertices:6 edges:6]
gremlin> Gremlin.defineStep('vouts', [Vertex, Pipeline], { _().transform{v->v.out.count()}})
==>null
gremlin> g.v(1).vouts                                                                       
==>3
gremlin> g.V.vouts 
==>0
==>0
==>3
==>1
==>0
==>2
```

In this way, we transform the incoming value to the count.  Now that the closure returns a `Pipe` it's good to go...you can see it this way:

``` text
gremlin> g.v(1).vouts.toString()
==>[GremlinStartPipe, [GremlinStartPipe, TransformFunctionPipe]]
```
