### ISSUE TITLE
Rate Unit of the Sl4j Metrics report is off

### ISSUE THREAD

**Issue by karkumar** [thinkaurelius/titan#517]
I'm currently getting  this output for the timer: 

13:28:09,480 INFO foo: type=TIMER, name=com.thinkaurelius.titan.sys.stores.mutate.time, count=48, min=1.9043409999999998, max=10.187138, mean=2.82683375, stddev=1.5763919352830456, median=2.366405, p75=2.6430339999999997, p95=7.597572049999993, p98=10.187138, p999=10.187138, mean_rate=10.187138, m1=0.9160719857693511, m5=1.228691531959396, m15=1.5209966162594168, rate_unit=1.573440286521742, duration_unit=events/second

As you can see the rate_unit is incorrect.  This is caused by a minor bug in the version of the Metrics that titan depends upon. Looks it is fixed the 3.0.1 release. Can titan upgrade to the latest version of metrics?

**Comment by dalaro** [comment]
I reproduced the gibberish rate_unit problem locally on Metrics 3.0.0-BETA3 and checked that upgrading to 3.0.1 fixed it.  The release notes for 3.0.1 look innocuous, so I'm pushing this to master and titan05.

master: a68dce2d22e5c7e2fc307a9e100829c736a45a43
titan05: f56c54c85ee5b465be00afce241de6c0742cce8a
