### ISSUE TITLE
Add integration with Codahale Metrics / Graphite

### ISSUE THREAD

**Issue by mpouttuclarke** [thinkaurelius/titan#521]
It would be very useful for Titan to integrate with these metrics packages:
https://github.com/codahale/metrics 
http://metrics.codahale.com/manual/graphite/

**Comment by dalaro** [comment]
Titan supports Metrics and its standard reporters, including Graphite: https://github.com/thinkaurelius/titan/wiki/Titan-Performance-and-Monitoring

I want to add new measurement points and welcome suggestions about what to monitor.  That's probably a discussion better suited to the aureliusgraphs list than the issue tracker.
