### ISSUE TITLE
More Informative toString for Types

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#525]
Doing a `toString` on a types gives you a vertex `toString` which makes sense because types are defined as vertices:

``` text
gremlin> g = GraphOfTheGodsFactory.create('/tmp/gog')     
==>titangraph[local:/tmp/gog]
gremlin> g.getTypes(TitanKey.class)
==>v[74]
==>v[82]
==>v[90]
==>v[98]
==>v[106]
==>v[114]
```

It would be nicer if Titan would return more meaningful information there about the type itself.

**Comment by okram** [comment]
I concur. To extend, I think that we should blind people to the fact that these are "vertices" (RDF schema style) and simply provide a TitanType.toString() that is cool as Stephen recommends.
