### ISSUE TITLE
Support pre-splitting HBase tables with IDs as rowkeys

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#528]
This would avoid some region split churn during HBase bulk loads.  This can be done manually with an intimate understanding of both Titan and HBase, but let's see if we can reasonably support or automate it.  Implementation notes:
- HBase creates tables with just one region by default: http://hbase.apache.org/book/perf.writing.html#precreate.regions
- configuring filesize threshold that triggers an automatic region split: http://hbase.apache.org/book/important_configurations.html#disable.splitting
- default size is 10 GB: http://hbase.apache.org/book/config.files.html#hbase.hregion.max.filesize
- setting a uniform split at table creation: http://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/HBaseAdmin.html#createTable%28org.apache.hadoop.hbase.HTableDescriptor,%20byte[],%20byte[],%20int%29
- setting split manually via RegionSplitter: http://hbase.apache.org/apidocs/org/apache/hadoop/hbase/util/RegionSplitter.UniformSplit.html

**Comment by dalaro** [comment]
I added two options to the HBase adapter in titan05:
- storage.region-count
- storage.regions-per-server

These option names are liable to change before 0.5 releases.

If region-count is set, then regions-per-server is ignored.  Setting both issues a warning and considers only the former.

Region count, when set, is the total number of regions to create in Titan's table.  This option is only effective when Titan's table doesn't already exist.

Regions per server, when set, is multiplied by the number of HBase servers reported by `ClusterStatus.getServers()` to determine the total region count.  Again, only has an effect when Titan's table doesn't yet exist.

If neither is set, or if we try to talk to ClusterStatus but it generates an exception, then we revert to the old behavior of creating a table without specifying a region count, which allows the implementation to use its own defaults.

Both of these options default unset.  This may change.

Commits:
- eac3ea42b370c379a6358f9160e3f68756eec2a9
- ce8956d714d160d83be52951af38d1f94f6c8c8b

**Comment by figo1885** [comment]
Hi dalaro,
    If set these two configuration, the table in hbase will split into N regions as i seted.
    When i insert Vertices into hbase, is these Vertices equal distribution on these regions? Or it will write to the region by order until reach the filesize threshold?  
    When i am doing the OLAP test , i found in the HBaseBinaryInputFormat, the getSplits method will split the task by region number, so if there are very big regions, it will be very slow. Thank you.
