### ISSUE TITLE
Forward-compatibility with Astyanax RetryPolicy constructors

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#536]
https://groups.google.com/forum/#!topic/aureliusgraphs/YmS-ovoOQHg

BoundedExponentialBackoff (and maybe others?) have undergone constructor signature changes since 1.56.37 that break reflective instantiation of RetryPolicy in AstyanaxStoreManager.  Also consider potential mirror breakage for RetryBackoffStrategy implementations.

**Comment by moczkowski** [comment]
There are more relevant changes in the Astyanax codebase : https://github.com/Netflix/astyanax/pull/465/files which appears to solidify that the API change will be permanent.

**Comment by xedin** [comment]
Pull Request is at https://github.com/thinkaurelius/titan/pull/604
