### ISSUE TITLE
titan 0.3.2 - cannot remove titan key - "Cannot remove vertex since it is still connected"

### ISSUE THREAD

**Issue by eyal33** [thinkaurelius/titan#543]
I am creating a titan key using (using cassandra 2.0.2 & titan 0.3.2):

TitanTransaction tx = graph.newTransaction();
TitanType titanType = tx.makeType().name("mytype3").dataType(Integer.class)
    .group(TypeGroup.DEFAULT_GROUP).unique(Direction.OUT).makePropertyKey();
tx.commit();

When I am trying to remove it I am getting the error :
java.lang.IllegalStateException: Cannot remove vertex since it is still connected
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.remove(AbstractVertex.java:81)
    at com.thinkaurelius.titan.graphdb.vertices.StandardVertex.remove(StandardVertex.java:85)

TitanType titanType2 = graph.getType("mytype3");  
titanType2.remove();

What is the proper to remove a titan key ?

Thanks,
Eyal

**Comment by dkuppitz** [comment]
Types can currently not be changed/removed. See: [Titan Limitations](https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#types-can-not-be-changed-once-created)
Please use our [mailing list](https://groups.google.com/forum/?pli=1#!forum/aureliusgraphs) for questions.

**Comment by eyal33** [comment]
Thanks.
I suggest to add the word remove to the limitation.

Regards,
Eyal
בתאריך 22 בדצמ 2013 14:56, מאת "Daniel Kuppitz" notifications@github.com:
