### ISSUE TITLE
Akiban Persistit Link Broken

### ISSUE THREAD

**Issue by sirinath** [thinkaurelius/titan#546]
The link to above is broken in: http://thinkaurelius.github.io/titan/

**Comment by nathanlws** [comment]
I believe it can now be found at https://github.com/pbeaman/persistit

**Comment by mbroecheler** [comment]
@nathanlws Do you know what the status of the project is?

**Comment by nathanlws** [comment]
I can't speak to any plans but I do know the maintainer still has interest in it.

@pbeaman, can you weigh in any further at this point?
