### ISSUE TITLE
the script "g.makeLabel("about").sortKey(seq).sortOrder(Order.DESC).make();" fail in titan-server-0.4.0, success in titan-server-0.4.1.

### ISSUE THREAD

**Issue by hzlijianjun** [thinkaurelius/titan#549]
execute following script with rexster-console, fail in titan-server-0.4.0
seq = g.makeKey("seq").dataType(Integer.class).indexed(Vertex.class).indexed(Edge.class).make();
g.makeLabel("about").sortKey(seq).sortOrder(Order.DESC).make();

 luckily success in titan-server-0.4.1.

**Comment by mbroecheler** [comment]
yes, this is an issue we fixed for 0.4.1
