### ISSUE TITLE
Have local mode flag take priority in ES

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#552]
Yes, I can see your exercise config would work, however, what I was referring was for the very first embedded ES (which your 2nd ES uses as master to form a dummy ES cluster in a single physical node). The problem is that if you have both the two below in your config (as I did a g = TitanFactory.open('conf/titan-hbase-es.properties') in the gremlin shell)

storage.search.index.hostname = 127.0.0.1
storage.search.index.local-mode = true

This is gonna fail as local-mode is not checked unless the hostname key does not exist, illustrated from the quoted code above. Removing the 'hostname' will work, but as I was saying, it seems to me awkward to have the hostname taking priority of boolean flag local-mode, since according to the doc, it is the flag controls whether to use ES embedded or not, regardless whether you have hostname key there or not.

**Comment by pellyadolfo** [comment]
https://groups.google.com/forum/?hl=en-GB#!topic/aureliusgraphs/qIkVs5TaffY

**Comment by dalaro** [comment]
Now the ES backend checks local mode prior to hostname.  This is changed and tested by the two referenced commits.
