### ISSUE TITLE
Advanced Eventual Consistency Options

### ISSUE THREAD

**Issue by dsiegel** [thinkaurelius/titan#555]
I'd like to use Titan with a Cassandra cluster distributed across multiple data centers. I must use CL_LOCAL_QUORUM for reads/writes. That means I can't use locking anywhere. As much as possible I want to use Cassandra’s write timestamps to resolve consistency issues.

There are three changes to Titan that I am interested in:
1. a “single” option for edges.
2. read access to the Cassandra timestamps for edges and properties.
3. eventually consistent uniqueness constraint option.

Detailed explanation follows.

There are a bunch of scenarios where data can become inconsistent. I can allow things to become inconsistent, but there needs to some way to eventually resolve the inconsistency and a way to hide it until its resolved.

Vertex Properties:  

If a property is written at the same time across two data centers a conflict will occur.

If I configure my property key like so:

tx.makeKey("foo")
            .single(TypeMaker.UniquenessConsistency.NO_LOCK)
            .make();

Cassandra will resolve the conflict for me using the write timestamps. This works for me.

Edges:

If I add an edge with a given label between two vertices twice across the two data centers then I may end up with two edges. Titan doesn't allow me to configure the edge as "single" the same way I can with properties. I need to pick a winning edge myself. I'd rather just leave it up to Cassandra's timestamps.

Edge Properties:

With the current Titan edge system, if I update the same edge property from two different data centers then I end up with two new edges, each with a different value. If I could make the edge "single" like I can with properties, then Cassandra would resolve this using write timestamps.

Luckily, I don't have a use case for multiple properties per edge, which would be harder to resolve.

Property uniqueness constraints:

This case is a real pickle. Say we have a vertex property index:

tx.makeKey("foo")
            .single(TypeMaker.UniquenessConsistency.NO_LOCK)
            .unique(TypeMaker.UniquenessConsistency.NO_LOCK)
            .make();

I could add a new vertex with the same foo property value from both data centers at the same time. I'd end up with two entries in the index. How can I resolve this?

Well, anytime I use this index I can check to see if there are ever more than one vertex returned per index key and merge the vertices before returning them to the user. I need some method to resolve conflicts between the vertices though. Happily, Cassandra provides a write timestamp per column that we can use to pick winners for each property (and edge). It gets trickier if one side of the "split" vertex has been deleted, but I believe this can be resolved using tombstones. When deleting properties or vertices, columns must be overwritten with nulls with a TTL instead of deleted. When repairing a “split” vertex, we can use the write timestamps of any null fields to decide whether the delete won or not.

If I'm over (or under) complicating things, your advice would be appreciated.

Thanks.

**Comment by mbroecheler** [comment]
Great timing. We just put out an RFC that should address some of your comments:
https://groups.google.com/forum/#!topic/aureliusgraphs/MKpsXCp2VXU
Please comment.

**Comment by dsiegel** [comment]
Thanks. The RFC looks very promising. However, it doesn't mention 3 in my list. Are eventually consistent uniqueness constraints just a bridge too far?

**Comment by mbroecheler** [comment]
We are considering surfacing the timestamp of edges / properties as a
special property. However, this might happen in a later release. Will keep
you posted.

On Thu, Jan 16, 2014 at 9:05 AM, David Siegel notifications@github.comwrote:

> Thanks. The RFC looks very promising. However, it doesn't mention 3 in my
> list. Are eventually consistent uniqueness constraints just a bridge too
> far?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/555#issuecomment-32488766
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
1 & 2 are fixed. 3 is likely a NO_FIX
