### ISSUE TITLE
storage.tablename not documented

### ISSUE THREAD

**Issue by mauropirrone** [thinkaurelius/titan#563]
This config property is not documented in this page.

https://github.com/thinkaurelius/titan/wiki/Graph-Configuration

**Comment by mbroecheler** [comment]
This option only applies to Hbase, hence its documented here:
https://github.com/thinkaurelius/titan/wiki/Using-HBase

On Wed, Jan 22, 2014 at 6:59 AM, Mauro Pirrone notifications@github.comwrote:

> This config property is not documented in this page.
> 
> https://github.com/thinkaurelius/titan/wiki/Graph-Configuration
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/563
> .

## 

Matthias Broecheler
http://www.matthiasb.com
