### ISSUE TITLE
Provide indexed search integration with ElastiSearch for geo points within a circle

### ISSUE THREAD

**Issue by zazzcode** [thinkaurelius/titan#568]
ElastiSearch provides support to perform an indexed search for elements that are located within a given radius of a geo-point.

Since this is already built into ElastiSearch, please provide support within Titan to search (using an index) for vertices having a geo-point property that are within a given radius of a geo-point.   Currently (according to the Titan documentation) one can only use an index to search for a given geo-point.

Reference: (http://www.elasticsearch.org/blog/geo-location-and-search/)
https://github.com/thinkaurelius/titan/wiki/Using-Elastic-Search

Would defining new Titan datatype called "geo-point" or "geoPoint" facilitate this integration?

**Comment by mbroecheler** [comment]
If I understand this feature request correctly, this is already supported in Titan with the Geo.WITHIN predicate.
Have a look at:
https://github.com/thinkaurelius/titan/wiki/Indexing-Backend-Overview#querying-an-index

**Comment by BrynCooke** [comment]
As far as I can tell this is supported (0.9-M1)
You can do something like

```
graph.V().has("location", Geo.WITHIN, Geoshape.circle(0.1, 0.1, 16)).next()
```

You need to make sure you use a mixed index

```
TitanManagement mng = graph.openManagement();
PropertyKey location = mng.makePropertyKey("location").dataType(Geoshape.class).make();
mng.buildIndex("byLocation",Vertex.class).addKey(location).buildMixedIndex("search");
mng.commit();
```

Please open if you still think there is an issue.
