### ISSUE TITLE
Remove many-to-one constraint on unidirected edges off of edges

### ISSUE THREAD

**Issue by zazzcode** [thinkaurelius/titan#569]
We would like the ability to create multiple unidirected edges with the same label off of a single edge.   We are using this pattern to model multiple graph-spaces within a single large graph.    

Many-to-many carnality for unidirected edges is allowed from vertices and we feel allowing a many-to-many carnality for unidirected edges off of edges would also be more consistent and increase modeling flexibility.

**Comment by mbroecheler** [comment]
This would greatly complicate the Edge interface and in many cases you would rather want to have multiple edges for each "namespace". Can you describe the use case in a little more detail?

**Comment by zazzcode** [comment]
Hi,  Thank you for replying to my post.  
Based on comments on the Google group we have implemented multiple edges with one unidirected edge off each (as you suggest).

The overall problem I am trying to deal with is providing an efficient means of sub-setting graph elements (both edges and vertices) in a large graph.  The same graph elements can exist in multiple sets.  I call these sets "graph spaces".  

Ideally I would like an efficient mechanism built into Titan and Gremlin to allow assigning elements to spaces and then performing queries within the context of a given space.

Currently, to accomplish this we are creating unidirected edges from edges and from vertices that point to a project vertex (our contextual space).  Then when we query or traverse, we check the unidirected edge to ensure we are staying within the specified space.

The only issue (which is more of a modeling nit) with our current approach is we can not have the same edge label for unidirected edges off edges and off vertices because the carnality is different.

I hope this better explains the problem we are trying to solve.

**Comment by mbroecheler** [comment]
After some discussion of use cases, we decided that in the interest of keeping the user interface simple we will not allow multiple unidirected edges off of a single edge (same for properties).
If this is absolutely required and none of the work around work, then we suggest wrapping Titan Edges such that mulitple unidirected edges are stored as a list of vertex ids and the wrapper converts those to vertices upon request.

**Comment by zazzcode** [comment]
Thanks...  We came up with an alternate design

-Michael
