### ISSUE TITLE
Consider GeoshapeHandler being able to parse a GeoJSON

### ISSUE THREAD

**Issue by erickt** [thinkaurelius/titan#574]
[GeoJSON](http://geojson.org/) is a standardized format that is used by a variety of projects, like MongoDB, PostGIS, and Twitter. I don't think it'll be that hard to add support for it in Titan. The approach I see is that the `GeoshapeHandler.convert` could be modified to check if it was passed a `Map<String, Object>` and check if it conforms to the GeoJSON spec.

If we do go this route, I would also suggest either adding a `Map<String, Object> Geoshap.toGeoJSON()` method so that we can export a vertex to JSON and import it back in without everyone needing to write their own GeoJSON formatters and parsers.

on the `Geoshape` itself so that we c

**Comment by BrynCooke** [comment]
These methods could be added to Geoshape:

```
String toGeoJSON()
static Geoshape fromGeoJSON(String json)
```

One potential issue is that geoJSON doesn't support circles. So what do we do if we are trying to serialize one of these? I would not be keen on an approximation via polygon as accuracy requirements may not be known.

There is a proposal for circles in V 1.1 of the spec
https://github.com/geojson/geojson-spec/wiki/Proposal---Circles-and-Ellipses-Geoms

Are any of the other projects using this?

**Comment by BrynCooke** [comment]
Actually the extra methods are an awful idea. Marshalling belongs in type handlers in gson or the equivalent in Jackson.

**Comment by mbroecheler** [comment]
@BrynCooke Exactly, you can extend the TypeHandler to look at strings and detect the encoding, then try to parse.

**Comment by BrynCooke** [comment]
I've not added a toGeoJSON method as I believe that serialization should be performed by a type serializer.
I think this could be added as part of https://github.com/thinkaurelius/titan/issues/954 and if folks want to reuse it in their own code then they can.
