### ISSUE TITLE
Add API to get multiple vertices in one call

### ISSUE THREAD

**Issue by shaie** [thinkaurelius/titan#575]
A spinoff from here: https://groups.google.com/forum/#!topic/aureliusgraphs/agWHzWY05z0. Would be nice if Titan offered API like TitanMultiVertexQuery to get a group of vertices (by their IDs) in one call, instead of calling g.getVertex() one by one. Something like g.getVertices(id1, id2, id3...). It can either return a List<TitanVertex> in the same order the IDs were given, or return a Map<ID,TitanVertex>.

**Comment by mbroecheler** [comment]
This is implemented as part of TP3 g.V(id1,id2,...)
