### ISSUE TITLE
Avoid the use of null in internal implementations

### ISSUE THREAD

**Issue by DanielThomas** [thinkaurelius/titan#58]
As discussed in issue #57, except where an external API contract requires (Blueprints for instance), consider:
- Using Guava Optional or Objects.firstNonNull to guard against null and establish defined absent or empty collection returns, instead of relying on null. When you require null when reaching those external interfaces with Optional, use http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Optional.html#orNull()
- Use collections that do not allow null keys or values. There's still an opportunity for null to cause problems, given null can mean a non-existent key, a null key with a null value, or a null value with many default Java collections

I have to say though, Titan does an excellent job generally about guarding against undesired state via Preconditions and assertions, but adopting patterns like these gives you those advantages for free, rather than requiring separate checks. See:

http://code.google.com/p/guava-libraries/wiki/UsingAndAvoidingNullExplained

**Comment by DanielThomas** [comment]
This is a good example of a bug that would have been avoided using Optional. IMO, Optional is even safer and less ambiguous than an empty collection in cases like these:

https://github.com/thinkaurelius/titan/commit/72f849f1c3bf20d38ef82c06175318668da779ea

That said, if a collection is returned by a method and an empty collection doesn't introduce ambiguity, I'd prefer that over Optional, but using Collections.empty*. They're static instances and are implemented as a separate class, whereas an empty Guava immutable collections aren't as obviously an explicitly empty collection.

**Comment by mbroecheler** [comment]
Thanks for the pointer. That page was a good read. As I wrote in the in-line comment responding to your comment I think both Optional and empty immutable default collections have their place. The former is more "idiot-proof" but the latter is nicer to handle when you have a lot of default accesses (e.g. contains). 

However, I completely agree on the general point: null should go. I will be looking out for it ;-)

**Comment by DanielThomas** [comment]
Oh, I came across this too. The Guava Immutable\* classes don't allow nulls, so you could use those as safer return collection in certain contexts:

https://plus.google.com/u/0/118010414872916542489/posts/8aY1LxiY15F
