### ISSUE TITLE
titan-rexster-0.4.2.jar missing in lib folder for titan-all build

### ISSUE THREAD

**Issue by Endellur** [thinkaurelius/titan#583]
The instructions on the website to get rexster up and running won't work without it. I downloaded the titan-server package and copied the jar over because I couldn't find it on the website by itself.

**Comment by dalaro** [comment]
Titan 0.5 is slated to release with only one zipfile containing all the storage backends, index backends, rexster bits, titan.sh, gremlin.sh, etc.  I've already unified the confusing plethora of zipfile options into a single package on the 0.5 development branch.  I recognize that it's really confusing that titan-all-0.4.2.zip is a subset of titan-server-0.4.2.zip, but soon that will be a thing of the past.

Related issue: #514
