### ISSUE TITLE
Allow specification of host supplier for AstyanaxStoreManager

### ISSUE THREAD

**Issue by batali** [thinkaurelius/titan#586]
Astyanax contexts implement the DISCOVERY_SERVICE type of node discovery using a "host supplier" (an instance of Supplier<List<Host>>) provided in the context builder.  The supplier's get() method is called periodically and the resulting list of available hosts is stored in the context's connection pool.

Titan currently uses the RingDescribeHostSupplier which doesn't work for multi-region Cassandra clusters (see: http://cassandra-user-incubator-apache-org.3065146.n2.nabble.com/ring-describe-returns-only-public-ips-td7592672.html).

But even if it did, it would seem useful for the Titan Cassandra client to be able to use Eureka or Zookeeper or other discovery systems.

Implementing this change is relatively simple:  the host supplier could be specified in the storageConfig passed to the Backend.  (If unspecified, or null, the host supplier would be created depending on the connection pool type.).  The AstyanaxStoreManager's getContexBuilder method would obtain the host supplier from the Configuration object, and store it in the context builder using the withHostSupplier method.

**Comment by xedin** [comment]
@dalaro I can take this one if you have more important stuff on your plate.

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/624, @mbroecheler please take a look.

**Comment by dalaro** [comment]
Merged #624.

Thanks, Pavel.
