### ISSUE TITLE
Investigate resize cost in VertexCache and alternatives

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#588]
NonBlockingHashMapLong gets into pathologically costly resize behavior under single-threaded access as the absolute size of the map increases.  Measure and compare to implementation alternatives.

**Comment by xedin** [comment]
@dalaro I can take this one if you have more important stuff on your plate.

**Comment by dalaro** [comment]
59ff650bf732a51805409bd577d4cf9da18070dd adds a new option to set the initial size of the NonBlockingHashMapLong instance inside GuavaVertexCache that holds a transaction's uncommitted dirty vertices.  It's named "cache.tx-dirty-size" in an attempt to harmonize with the existing config option named "cache.tx-cache-size".  I'm not married to that name.

The size defaults to 32 with batch-loading disabled and 4096 with batch-loading enabled.  Those defaults seem reasonable, but I haven't tuned them with systematic empirical tests.  At any rate, the user can now override the defaults at both the graph config and transaction config levels by setting the new option, so the defaults don't have to be perfect.
