### ISSUE TITLE
Shutdown hook

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#590]
Register a shutdown hook to ensure Titan is properly shut down when Gremlin exits.

**Comment by xedin** [comment]
@dalaro I can take this one if you have more important stuff on your plate.

**Comment by mbroecheler** [comment]
@xedin @dalaro Great idea. The goal here is to force a proper shutdown of Titan (so that all spawned non-daemon threads get properly shut down) when a user exists the gremlin shell (without g.close()) or hits ctrl-c.

**Comment by xedin** [comment]
@mbroecheler pull is at https://github.com/thinkaurelius/titan/pull/600
