### ISSUE TITLE
NPE accessing Edge with Framed primitive @Property added to interface after edge created

### ISSUE THREAD

**Issue by cmbaron** [thinkaurelius/titan#596]
Not sure if this is a Titan or Blueprints issue, but trying here first.

An edge is created with the following edge frame:

``` java
public interface AttributeRelationMeta extends EdgeFrame {
    @Property("negate")
    public boolean isNegate();
    @Property("negate")
    public void setNegate(boolean negate);
}
```

The Frame is then modified to include an additional property:

``` java
public interface AttributeRelationMeta extends EdgeFrame {
    @Property("negate")
    public boolean isNegate();
    @Property("negate")
    public void setNegate(boolean negate);
    @Property("hidden")
    public boolean isHidden();
    @Property("hidden")
    public void setHidden(boolean hide);
}
```

Attempts to access "isHidden" on an existing edge results in an NPE in the Proxy:
Caused by: java.lang.NullPointerException
        at com.sun.proxy.$Proxy164.isHidden(Unknown Source)

Changing the property to use the boxed Boolean fixes this problem:

``` java
public interface AttributeRelationMeta extends EdgeFrame {
    @Property("negate")
    public boolean isNegate();
    @Property("negate")
    public void setNegate(boolean negate);
    @Property("hidden")
    public Boolean isHidden();
    @Property("hidden")
    public void setHidden(Boolean hide);
}
```

**Comment by okram** [comment]
As I remember, Frames requires that full Java objects be used in the Frame definitions -- i.e. no primitive types.

For example see:

```
https://github.com/tinkerpop/frames/blob/master/src/test/java/com/tinkerpop/frames/domain/classes/Person.java#L24-L28
```

**Comment by cmbaron** [comment]
Thanks Marko.  I looked through the documentation for some reference to primitive semantics, but did not find any.  We'll stick to the boxed types. 

## 

Chris
