### ISSUE TITLE
AbstractVertexCentricQueryBuilder.types(params array) only processes last item in params array

### ISSUE THREAD

**Issue by tmichaud314** [thinkaurelius/titan#599]
Found in 0.4.2 release.

titan-core: AbstractVertexCentricQueryBuilder.types(TitanType... type) always converts only the last item in the array and storing it to the internal "types" array, effectively truncating the first n - 1 items of the array.

**Comment by xedin** [comment]
@mbroecheler are you going take a look at this?

**Comment by mbroecheler** [comment]
fixed in titan05
