### ISSUE TITLE
Fix multi-threaded correctness issues detected by FindBugs

### ISSUE THREAD

**Issue by DanielThomas** [thinkaurelius/titan#60]
See #59. The priorities for these rules are low - I'd consider all violations in MT_CORRECTNESS category critical.

**Comment by dalaro** [comment]
Some of the MT_CORRECTNESS bugs indeed read like they're worth a look, such as "&lt;object&gt; only synchronized &lt;less-than-100&gt;% of the time".

What about "&lt;method&gt; attempts to manually schedule threads by calling method Thread.sleep(long)"?  The explanation link for this bug description is http://findbugs.sourceforge.net/bugDescriptions.html#MDM_THREAD_YIELD, but that anchor doesn't exist.  We could indeed replace all Thread.sleep() calls with ScheduledExecutorService.schedule() calls followed by get() on the associated futures, but this doesn't strike me as necessarily critical.  What's your impression?

**Comment by DanielThomas** [comment]
Yeah, really just concerned with the synchronization issues. That rule came from fb-contrib, the description reads like that they consider it a code smell, rather than any particular problem:

http://fb-contrib.sourceforge.net/bugdescriptions.html

**Comment by mbroecheler** [comment]
I went through the list and tried to address a bunch of the issues in d038bc27ba07a7813e456c76e12995c641ab68d8. I will keep an eye on findbugs moving forward, but for now I hope it covers most of the critical issues. Most of the MT_CORRECTNESS that are left seem to be of the kind Dan mentions above or "sleeps without timeout when calling java.util.concurrent.locks.Lock.lock()"

Reopen if I missed something.
