### ISSUE TITLE
Make vertex IDs always the last sort criteria

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#606]
If you have a non-unique sort key, the sorting of edges with the same value is currently random. Is it possible to make the vertex IDs always the last sort criteria? This can be useful for fast paging.

The following code demonstrates the problem.

**Init sample graph**

```
conf = new BaseConfiguration() {{
  setProperty("storage.backend","inmemory")
}}

g = TitanFactory.open(conf)
w = g.makeKey("weight").dataType(Byte.class).make()
g.makeLabel("links").sortKey(w).make()
g.commit()

root = g.addVertex()
(1..100).each({
  v = g.addVertex()
  root.addEdge("links", v, ["weight":(Byte)(Math.random()*10)])
}); g.commit()
```

**Query first page (10+1 items)**

```
gremlin> root.outE("links")[0..10].map()
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
==>{weight=0}
```

```
gremlin> root.outE("links")[0..10]
==>e[7d-4-1o][4-links->396]
==>e[39-4-1o][4-links->144]
==>e[4b-4-1o][4-links->208]
==>e[7h-4-1o][4-links->400]
==>e[6v-4-1o][4-links->352]
==>e[2r-4-1o][4-links->100]
==>e[6z-4-1o][4-links->356]
==>e[5J-4-1o][4-links->304]
==>e[2H-4-1o][4-links->116]
==>e[6T-4-1o][4-links->376]
==>e[2P-4-1o][4-links->124]
```

Now it's clear that page 2 must start with weight == 0, but since page 1 also starts with 0, that doesn't help much. We need another sort criteria -> vertex ID. Assuming the vertex IDs were sorted, we could now query the next page as follows:

**Query next page**

```
gremlin> root.outE("links").has("weight", T.gte, 0).filter({
gremlin>     it.getVertex(IN).getID() >= 124L
gremlin> })[0..10]
...
```

That is much faster than incrementing the offset in our range query (higher offsets lead to slower queries).

_Next step would be to make the vertex ID accessible in .has()._
_For example:_ `.has("_inV", T.gte, 124L)` and `.has("_outV", T.gte, 124L)`
_...but that's another story._

**Comment by mbroecheler** [comment]
This will be the case in 0.5 with the only difference being that edges will
be sorted by vertex id difference

**Comment by dkuppitz** [comment]
_by vertex id difference_ means something like `edge.inV().id() - edge.outV().id()`? If so, will it be consistent (e.g. always inV - outV) so that negative values are used or will you use the absolute distance?

**Negative values valid: _(preferred)_**

```
gremlin> g.v(3).out()
gremlin> v[1] // distance is -2
gremlin> v[2] // distance is -1
gremlin> v[4] // distance is 1
gremlin> v[5] // distance is 2
```

**Absolute distance: _(useless for the paging approach mentioned above)_**

```
gremlin> g.v(3).out()
gremlin> v[2] // abs. distance is 1
gremlin> v[4] // abs. distance is 1
gremlin> v[1] // abs. distance is 2
gremlin> v[5] // abs. distance is 2
```

**Comment by mbroecheler** [comment]
added in titan05
