### ISSUE TITLE
titan05 branch's titan-hbase does not play nicely with IntelliJ

### ISSUE THREAD

**Issue by erickt** [thinkaurelius/titan#608]
`titan-hbase` in the `titan05` branch appears to be doing some maven tricks in order to support both hbase 0.94 and 0.96. However, this really confuses IntelliJ, because there is no direct dependency in `titan-hbase` on the `hbase` jar for 0.94, or `hbase-server` for 0.96. So it throws errors everywhere when compiling or debugging. Is anyone aware of a way to make IntelliJ Happy?

**Comment by dalaro** [comment]
I refactored titan-hbase in titan05 again.  This time, I'm trying a unified jar that dynamically loads a shim class compiled against 0.94 or 0.96 depending on what's detected at runtime, similar to the way Hive supports multiple Hadoope versions in a single jar.  It currently imports and builds in IDEA 13.1.1 on my machine.

Please reopen if you see a way to make it play nicer with IDEA.  Despite the note about testSourceDirectory in http://wiki.jetbrains.net/intellij/Maven_FAQ, I can't seem to get it to pickup up the HBase submodule tests.
