### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by galan** [thinkaurelius/titan#612]
Question: Is there anywhere a roadmap to see when future versions (such as 0.5.0) will be released?

**Comment by rahst12** [comment]
In NYC they said 0.5.0 will have a the last changes to the underpinnings of the database. (This is important because it was beforehand causing significant / incompatible upgrade issues.)

**Comment by mbroecheler** [comment]
@d8bitr We are keeping track of issues on github. The roadmap itself changes quite rapidly at the moment so we maintain it internally to not cause confusion. But as @rahst12 pointed out, our goal is to remain compatible on the storage backend level which should stabilize things a lot. Hopefully that will work out ;-)

**Comment by l15k4** [comment]
I'm just joining 2 potential sources of revealing the roadmap a bit, even a rough estimate would help :-P  However I fully understand the reasons for keeping it internal. http://goo.gl/ZkJGpE
