### ISSUE TITLE
document reserved names

### ISSUE THREAD

**Issue by p1tz** [thinkaurelius/titan#613]
Hi,

maybee I'm just too stupid to find it, but are there any other reserved names except id and label? is there a wiki page where I can look this up?

Have you considered renaming them to something awkward like _id_ or the like, because id is a very common property?

thank you :)

**Comment by p1tz** [comment]
... like [underscore]id[underscore] ...

**Comment by mbroecheler** [comment]
The reserved names are taken from TinkerPop/Blueprints. @okram @spmallette Is there such a page for TinkerPop?
The reason its not an awkward name is that we want to allow usage in has constraints: has(id,5) for instance.

**Comment by okram** [comment]
id and label are the only reserved names.

**Comment by p1tz** [comment]
thank you for your feedback, though it probably was a dumb question. I found it in the code meanwhile.
