### ISSUE TITLE
cassandrathrift returns broken connections back to the pool.

### ISSUE THREAD

**Issue by xedin** [thinkaurelius/titan#618]
User has reported a problem with cassandrathrift when at least one of the nodes is stopped. https://groups.google.com/forum/#!topic/aureliusgraphs/yzedZ-P5D5k

**Comment by anvie** [comment]
+1

**Comment by xedin** [comment]
Pull is at https://github.com/thinkaurelius/titan/pull/623, @mbroecheler please take a look.

**Comment by dalaro** [comment]
Merged #623.

Thanks, Pavel.
