### ISSUE TITLE
Build fails on JDK 7 on OS X due to no snappyjava in java.library.path

### ISSUE THREAD

**Issue by bobbyno** [thinkaurelius/titan#62]
```
$ mvn -v 
Apache Maven 3.0.4 (r1232337; 2012-01-17 02:44:56-0600)
Maven home: /usr/local/Cellar/maven/3.0.4/libexec
Java version: 1.7.0_06, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_06.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.7.4", arch: "x86_64", family: "mac"

$ mvn clean package
Running com.thinkaurelius.titan.diskstorage.astyanax.InternalAstyanaxKeyColumnValueTest
java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.UnsatisfiedLinkError: no snappyjava in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at org.xerial.snappy.SnappyNativeLoader.loadLibrary(SnappyNativeLoader.java:52)
    ... 25 more
```

Workaround: 
1. Download libsnappyjava.jnilib from [Google Code](http://code.google.com/p/snappy-java/source/browse/src/main/resources/org/xerial/snappy/native/Mac/x86_64/libsnappyjava.jnilib?name=snappy-java-1.0.3.3)
2. Copy to a directory on the java.library.path, e.g. /usr/lib/java/
3. Rename to libsnappyjava.dylib per the [snappy issue](http://code.google.com/p/snappy-java/issues/detail?id=39)
4. `chmod 755 /usr/lib/java/libsnappyjava.dylib`
5. `mvn clean package` should now work
6. ???
7. Profit

**Comment by mbroecheler** [comment]
Thanks for the workaround. Obviously we want this to work out of the box. Is this a known issue in JDK 7 on Mac OS? Does it apply to other operating systems?

**Comment by bobbyno** [comment]
Yes, it's a [known issue](http://code.google.com/p/snappy-java/issues/detail?id=39) involving changes in the naming conventions for shared libraries in JDK 7 on OS X. It doesn't affect other operating systems. 

This issue was accepted as a defect and is scheduled to be included in the 1.0.5 snappy-java release, but there's no indication in that community when that will happen. I've asked the maintainer for an update.

**Comment by xedin** [comment]
added 1.5.0-M3 to the cassandra pom, tests on Mac OS X 10.7.5 with JDK 7 issue was fixed, closing.

**Comment by heyvishy** [comment]
Thanks for this workaround. Although in my case, I skipped step 3 and 4 and it worked fine for me.
I am using Mac OS 10.7.5
