### ISSUE TITLE
Clarify documentation or fix bug on transactional scope

### ISSUE THREAD

**Issue by johnbcoughlin** [thinkaurelius/titan#622]
The documentation at https://github.com/thinkaurelius/titan/wiki/Transaction-Handling seems to indicate that vertices are always transitioned between transactions: 

> Once the transaction is closed, all graph elements associated with that transaction become stale and unavailable. However, Titan will automatically transition vertices and types into the new transactional scope...

This appears to only be true for the "implicit" transaction that is opened whenever we modify the graph. Consider the following, passing, test:

``` java
  @Test
  public void verticesTransitionedAcrossTransactions() {
    TitanTransaction transaction = graph.newTransaction();
    Vertex explicitTransactionVertex = transaction.addVertex(null);
    explicitTransactionVertex.setProperty("value", 0);
    transaction.commit();
    try {
      explicitTransactionVertex.getProperty("value");
      assertThat(false);
    } catch (IllegalStateException e) {
      assertThat(true);
    }
  }
```

Thus, attempting to transition a vertex between explicit TitanTransaction instances will fail.

**Comment by dkuppitz** [comment]
The linked wiki page also states that

> The method `newTransaction` is used to start [multi threaded transactions](https://github.com/thinkaurelius/titan/wiki/Multi-Threaded-Transactions) only. 

And the documentation for multithreaded transactions [states](https://github.com/thinkaurelius/titan/wiki/Multi-Threaded-Transactions#gotcha) that

> When using multi-threaded transactions via `newTransaction` all vertices and edges retrieved or created in the scope of that transaction are **not** available outside the scope of that transaction.
