### ISSUE TITLE
Null pointer on key.getDataType()

### ISSUE THREAD

**Issue by kmccarp** [thinkaurelius/titan#635]
Graph created with Titan 0.4.4, we're getting a NPE on line 262 of `com.thinkaurelias.titan.graphdb.database.EdgeSerializer` (see below for offending line).

```
private static boolean hasGenericDataType(TitanKey key) {
    return key.getDataType().equals(Object.class);
}
```

I'm not sure how, but none of the keys on any of the properties on any of our vertices have a datatype set. Is there something I can do to fix this? When retrieving any property on any vertex, I'm getting this null pointer.

**Comment by mbroecheler** [comment]
Do you get that exception in all cases or just some of them? If the latter, what cases?

**Comment by kmccarp** [comment]
I discovered the error was due to pulling in Kryo 2.23 instead of 2.21 (the version Titan 0.4.4 depends on). Kryo 2.23 was retrieving a null datatype instead of the actual datatype.
