### ISSUE TITLE
Titan doesn't seem to like single node Cassandra w/stacktrace

### ISSUE THREAD

**Issue by awcoding** [thinkaurelius/titan#637]
``` java
public class Titanic {
    TitanGraph graph;
    public Titanic() {
        Configuration conf = new BaseConfiguration();
        conf.setProperty("storage.backend","cassandra");
        conf.setProperty("storage.hostname","192.168.4.26");
        graph = TitanFactory.open(conf);
    }
    public TitanGraph getGraph() {
        return graph;
    }
    public void setGraph(TitanGraph graph) {
        this.graph = graph;
    }

    public static void main(String [] args) {
        Titanic titanic = new Titanic();
        TitanGraph g = titanic.getGraph();

        Vertex juno = g.addVertex(null);
        juno.setProperty("name", "juno");
        Vertex jupiter = g.addVertex(null);
        jupiter.setProperty("name", "jupiter");
        Edge married = g.addEdge(null, juno, jupiter, "married");
        g.commit();
    }
}
```

``` bash
First RUN
===============

Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not successfully complete backend operation due to repeated temporary exceptions after 60000 ms
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:49)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:277)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at my.graph.Titanic.<init>(Titanic.java:18)
    at my.graph.Titanic.main(Titanic.java:28)
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
    ... 7 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
    at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:30)
    at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
    at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:519)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:136)
    ... 11 more


Second RUN
=================


0    [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
14   [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 192.168.1.6
109  [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool
109  [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 192.168.1.6
155  [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 127.0.0.1
156  [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - RemoveHost: 192.168.1.6
375  [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Initiated backend operations thread pool of size 16
40219 [RingDescribeAutoDiscovery] WARN  com.netflix.astyanax.impl.RingDescribeHostSupplier  - Failed to get hosts from titan via ring describe.  Will use previously known ring instead
49060 [main] INFO  com.thinkaurelius.titan.diskstorage.util.BackendOperation  - Temporary storage exception during backend operation. Attempting backoff retry
com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:277)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at my.graph.Titanic.<init>(Titanic.java:18)
    at my.graph.Titanic.main(Titanic.java:28)
Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
    at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:30)
    at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
    at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:519)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:136)
    ... 11 more
60218 [RingDescribeAutoDiscovery] WARN  com.netflix.astyanax.impl.RingDescribeHostSupplier  - Failed to get hosts from titan via ring describe.  Will use previously known ring instead
Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not successfully complete backend operation due to repeated temporary exceptions after 60000 ms
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:49)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:277)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at my.graph.Titanic.<init>(Titanic.java:18)
    at my.graph.Titanic.main(Titanic.java:28)
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
    ... 7 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
    at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:30)
    at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
    at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:519)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:136)
    ... 11 more
```

**Comment by mbroecheler** [comment]
What's your replication factor? On a single instance, it must be configured
to equal 1.

On Fri, May 2, 2014 at 9:13 PM, Alexwhite3000 notifications@github.comwrote:

> public class Titanic {
>     TitanGraph graph;
>     public Titanic() {
>         Configuration conf = new BaseConfiguration();
>         conf.setProperty("storage.backend","cassandra");
>         conf.setProperty("storage.hostname","192.168.4.26");
>         graph = TitanFactory.open(conf);
>     }
>     public TitanGraph getGraph() {
>         return graph;
>     }
>     public void setGraph(TitanGraph graph) {
>         this.graph = graph;
>     }
> 
> ```
> public static void main(String [] args) {
>     Titanic titanic = new Titanic();
>     TitanGraph g = titanic.getGraph();
> 
>     Vertex juno = g.addVertex(null);
>     juno.setProperty("name", "juno");
>     Vertex jupiter = g.addVertex(null);
>     jupiter.setProperty("name", "jupiter");
>     Edge married = g.addEdge(null, juno, jupiter, "married");
>     g.commit();
> }}
> ```
> 
> First RUN===============
> 
> Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not successfully complete backend operation due to repeated temporary exceptions after 60000 ms
>     at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:49)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:277)
>     at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
>     at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
>     at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
>     at my.graph.Titanic.<init>(Titanic.java:18)
>     at my.graph.Titanic.main(Titanic.java:28)
> Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
>     ... 7 more
> Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
>     at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:30)
>     at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
>     at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
>     at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:519)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:136)
>     ... 11 more
> 
> Second RUN=================
> 
> 0    [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
> 14   [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 192.168.1.6
> 109  [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool
> 109  [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 192.168.1.6
> 155  [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 127.0.0.1
> 156  [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - RemoveHost: 192.168.1.6
> 375  [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Initiated backend operations thread pool of size 16
> 40219 [RingDescribeAutoDiscovery] WARN  com.netflix.astyanax.impl.RingDescribeHostSupplier  - Failed to get hosts from titan via ring describe.  Will use previously known ring instead
> 49060 [main] INFO  com.thinkaurelius.titan.diskstorage.util.BackendOperation  - Temporary storage exception during backend operation. Attempting backoff retry
> com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:277)
>     at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
>     at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
>     at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
>     at my.graph.Titanic.<init>(Titanic.java:18)
>     at my.graph.Titanic.main(Titanic.java:28)
> Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
>     at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:30)
>     at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
>     at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
>     at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:519)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:136)
>     ... 11 more
> 60218 [RingDescribeAutoDiscovery] WARN  com.netflix.astyanax.impl.RingDescribeHostSupplier  - Failed to get hosts from titan via ring describe.  Will use previously known ring instead
> Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not successfully complete backend operation due to repeated temporary exceptions after 60000 ms
>     at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:49)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:277)
>     at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1174)
>     at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
>     at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
>     at my.graph.Titanic.<init>(Titanic.java:18)
>     at my.graph.Titanic.main(Titanic.java:28)
> Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
>     ... 7 more
> Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
>     at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:30)
>     at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
>     at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
>     at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:519)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:136)
>     ... 11 more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/637
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by awcoding** [comment]
I let Titan configure the KS,CFs on the first run and I did on the 2nd. Both with RF=1. 
Cassandra v=2.0.6

BTW I use Cassandra/Astyanax daily without any special config. I isolated the case above in it's own proj though so you should be able to replicate the error by just including titan-core and titan-cassandra.

**Comment by xedin** [comment]
So I tried both Titan 0.4.3 and 0.5 with Cassandra 2.0.6 and they both work fine, I tried using ./bin/gremlin.sh but the same exact statements you did. It looks like Astyanax can't get the connection to your machine somehow, can you check server logs maybe they can shed some light?...

**Comment by awcoding** [comment]
Did you try with my  class? My only two pom.xml deps are titan-core and titan-cassandra (tested with both: 0.4.3 or 0.4.4)

Here is the output on the server side: 

``` shell
 INFO [MigrationStage:1] 2014-05-15 13:16:05,801 DefsTables.java (line 341) Loading org.apache.cassandra.config.CFMetaData@2fc1fd9c[cfId=df718c47-b235-3c54-a609-07187692ebe0,ksName=titan,cfName=system_properties,cfType=Standard,comparator=org.apache.cassandra.db.marshal.BytesType,comment=,readRepairChance=0.1,dclocalReadRepairChance=0.0,replicateOnWrite=true,gcGraceSeconds=864000,defaultValidator=org.apache.cassandra.db.marshal.BytesType,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,column_metadata={java.nio.HeapByteBuffer[pos=0 lim=3 cap=3]=ColumnDefinition{name=6b6579, validator=org.apache.cassandra.db.marshal.BytesType, type=PARTITION_KEY, componentIndex=null, indexName=null, indexType=null}, java.nio.HeapByteBuffer[pos=0 lim=5 cap=5]=ColumnDefinition{name=76616c7565, validator=org.apache.cassandra.db.marshal.BytesType, type=COMPACT_VALUE, componentIndex=null, indexName=null, indexType=null}, java.nio.HeapByteBuffer[pos=0 lim=7 cap=7]=ColumnDefinition{name=636f6c756d6e31, validator=org.apache.cassandra.db.marshal.BytesType, type=CLUSTERING_KEY, componentIndex=null, indexName=null, indexType=null}},compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={},compressionOptions={sstable_compression=org.apache.cassandra.io.compress.SnappyCompressor, chunk_length_kb=64},bloomFilterFpChance=<null>,memtable_flush_period_in_ms=0,caching=KEYS_ONLY,defaultTimeToLive=0,speculative_retry=NONE,indexInterval=128,populateIoCacheOnFlush=false,droppedColumns={},triggers={}]
 INFO [MigrationStage:1] 2014-05-15 13:16:05,812 ColumnFamilyStore.java (line 254) Initializing titan.system_properties
 INFO [CompactionExecutor:54] 2014-05-15 13:16:05,959 CompactionTask.java (line 275) Compacted 4 sstables to [/var/lib/cassandra/data/system/schema_columns/system-schema_columns-jb-185,].  9,658 bytes to 9,187 (~95% of original) in 192ms = 0.045632MB/s.  9 total partitions merged to 6.  Partition merge counts were {1:5, 4:1, }

```

I also tried adding:

``` java
        conf.setProperty("storage.port","9160");
        conf.setProperty("storage.keyspace", "titan");
        conf.setProperty("storage.cluster","Test Cluster");
```

But no help there either. Whenever I use astyanax / cassandra in normal operation I usually have to specify the cluster name. According to the wiki there is no obvious way of specifying the cluster name. Could that be it?

Another strange thing is that when I run for the first time, Titan creates it's Keyspace and CF's in the database on it's own, but then fails this simple app. Very odd.

**Comment by awcoding** [comment]
Perhaps if ring describe fails you could use storage.hostname for cassandra operations?

**Comment by xedin** [comment]
Let me try your app.

**Comment by xedin** [comment]
Tried your code with following dependencies version 0.4.4 (titan-core-jre6, titan-cassandra)

```
0    [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
11   [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 17.115.45.8
90   [main] INFO  com.netflix.astyanax.connectionpool.impl.ConnectionPoolMBeanManager  - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool
91   [main] INFO  com.netflix.astyanax.connectionpool.impl.CountingConnectionPoolMonitor  - AddHost: 17.115.45.8
422  [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Initiated backend operations thread pool of size 16
516  [main] INFO  com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoSerializer  - Kryo serializer enabled with utf8: false
transaction committed!
```

What I think is happening in your case is in yaml you have "listen_address" set to localhost or something similar, that would block Astyanax from getting ranges. You can try setting "connection-pool-type" to "ROUND_ROBIN" and see what happens.

**Comment by awcoding** [comment]
I've tried it with both listen_address is set to localhost and the public ip address of the host machine 192.168.4.126. That's not it. 

``` java
        conf.setProperty("connection-pool-type","ROUND_ROBIN");
        conf.setProperty("storage.connection-pool-type","ROUND_ROBIN"); 
```

This is the code we are running in our dev env:

``` java
    public static Keyspace setup(String keyspaceName, String cluster,
            String ipAddressPortString) {
        AstyanaxContext<Keyspace> context = new AstyanaxContext.Builder()
                .forCluster(cluster)
                .forKeyspace(keyspaceName)
                .withAstyanaxConfiguration(new AstyanaxConfigurationImpl().setDiscoveryType(NodeDiscoveryType.NONE))
                .withConnectionPoolConfiguration(new ConnectionPoolConfigurationImpl("MyConnectionPool")
                .setPort(9160)
                .setMaxConnsPerHost(1)
                .setSeeds(ipAddressPortString))
                .withConnectionPoolMonitor(new CountingConnectionPoolMonitor())             
                .buildKeyspace(ThriftFamilyFactory.getInstance());

        context.start();
        Keyspace keyspace = context.getEntity();
        return keyspace;
    }
```

Would you be open to integrating NodeDiscoveryType.NONE with Titan if storage.direct=true?

**Comment by mbroecheler** [comment]
Does that solve the problem for you?

On Thu, May 15, 2014 at 8:11 PM, Alexwhite3000 notifications@github.comwrote:

> I've tried it with both listen_address is set to localhost and the public
> ip address of the host machine 192.168.4.126. That's not it.
> 
> ```
>     conf.setProperty("connection-pool-type","ROUND_ROBIN");
>     conf.setProperty("storage.connection-pool-type","ROUND_ROBIN");
> ```
> 
> This is the code we are running in our dev env:
> 
> ```
> public static Keyspace setup(String keyspaceName, String cluster,
>         String ipAddressPortString) {
>     AstyanaxContext<Keyspace> context = new AstyanaxContext.Builder()
>             .forCluster(cluster)
>             .forKeyspace(keyspaceName)
>             .withAstyanaxConfiguration(new AstyanaxConfigurationImpl().setDiscoveryType(NodeDiscoveryType.NONE))
>             .withConnectionPoolConfiguration(new ConnectionPoolConfigurationImpl("MyConnectionPool")
>             .setPort(9160)
>             .setMaxConnsPerHost(1)
>             .setSeeds(ipAddressPortString))
>             .withConnectionPoolMonitor(new CountingConnectionPoolMonitor())
>             .buildKeyspace(ThriftFamilyFactory.getInstance());
> 
>     context.start();
>     Keyspace keyspace = context.getEntity();
>     return keyspace;
> }
> ```
> 
> Would you be open to integrating NodeDiscoveryType.NONE with Titan if
> storage.direct=true?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/637#issuecomment-43291508
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by awcoding** [comment]
That's from another project. But I think It would work if you integrated it. I guess if you really need me to I can submit a pull req but it might take awhile. Right now, as far as I can tell Titan won't work with Cassandra on a single node.

**Comment by xedin** [comment]
It does work with the single node just fine, also there is no need to change any code for support NodeDiscoveryType.NONE, just set "node-discovery-type" to "NONE" in your properties.

listen_address should be pointing to the accessiable address otherwise Astyanax node discovery won't work.
