### ISSUE TITLE
Add thread-safety and concurrency tests to KeyColumnValueStoreTest

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#644]
also, add a test case to load a non-trivial amount of data and iterate it through. We were seeing a weird Astyanax issue in earlier versions where it would truncate the result set after returning a lot of elements.

**Comment by dalaro** [comment]
Added some simple parallel getSlice and mutate stress tests in d163815083d61e8b455859b1751ec1f5a09b6f9c.
