### ISSUE TITLE
why TitanGraphQuery does not return TitanVertex?

### ISSUE THREAD

**Issue by eparejatobes** [thinkaurelius/titan#646]
I'm having a hard time writing generic code because of this. Why vertices or edges returns the corresponding tinkerpop stuff? Just non-covariant Java generics? Can I safely assume that they're going to be TitanVertex/TitanEdge?

**Comment by okram** [comment]
Yes.These will be TitanVertex/TitanEdge.

Please use our mailing list for questions as this is not a question for a bug tracker.

**Comment by okram** [comment]
Yes.These will be TitanVertex/TitanEdge.

Please use our mailing list for questions as this is not a question for a bug tracker.

**Comment by eparejatobes** [comment]
OK thanks for the quick reply, will do next time
