### ISSUE TITLE
Comparaison strangness

### ISSUE THREAD

**Issue by crakjie** [thinkaurelius/titan#647]
Hello,
I'm using titan 0.4.2 with rexter

I have one vertex with a property witch is an int and witch is equal to 45
So in rexter console when i'm doing this

```
 gremlin> g.V.has('time_before_closing',T.eq,45)
==>v[132]
```

I got a result i'm ok.

when i do this 

```
 gremlin> g.V.has('time_before_closing',T.eq,45.0)
```

I got no result, I'm disappointed but ok.

now when I'm doing this 

```
 gremlin> g.V.has('time_before_closing',T.gt,44.0)
==>v[132]
```

I got a result !!

ps : I'm disappointed because i cannot request integer with double or double with integer

**Comment by mbroecheler** [comment]
Hi Etienne,

can you connect with the Gremlin shell directly against Titan (i.e. no Rexster) and do the same?
Here is what I get on Titan 0.4.2:

``` groovy
gremlin> g = TitanFactory.open('/tmp/titan')
==>titangraph[local:/tmp/titan]
gremlin> tx = g.newTransaction()
==>standardtitantx[null]
gremlin> tx.makeKey('time').dataType(Integer.class).make()
==>time
gremlin> tx.commit()
==>null
gremlin> v = g.addVertex(['time':45])
==>v[4]
gremlin> g.commit()
==>null
gremlin> g.V.has('time',T.eq,45)
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [(time = 45)]. For better performance, use indexes
==>v[4]
gremlin> g.V.has('time',T.eq,45.0)
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [(time = 45)]. For better performance, use indexes
==>v[4]
gremlin> g.V.has('time',T.eq,44.0)
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [(time = 44)]. For better performance, use indexes
gremlin> 
```

Note, that double-to-integer conversion works for me here because I defined the data type of the property explicitly. If you don't do this, then Titan accepts arbitrary values in which case it must compare them at "face-value" and then an integer is different from a double.

**Comment by crakjie** [comment]
Sorry but I'm not able to connect to my database , i tried db db/cassandra db/cassandra/data db/cassandra/data/titan ...
But we use tinkerpop frames and I think it's possible the data type of each property is not set by frames.

**Comment by crakjie** [comment]
Y test with gremlin without rexter ( but with titan 0.4.4 )
And I have exactly the same result with Rexter.
What is exactly face-value ?

**Comment by mbroecheler** [comment]
By "face-value" I mean the actual value that is being represented. Why did you close the issue?

**Comment by crakjie** [comment]
Because if i enderstand what you mean it's not realy a bug , but a problem of configuration ?
