### ISSUE TITLE
Allows specifying keyspace strategy_class and strategy_options

### ISSUE THREAD

**Issue by krm1312** [thinkaurelius/titan#649]
It should be possible to specify the 'NetworkTopology' strategy and further keyspace options besides replication_factor.

In particular, in AstyanaxStoreManager:

```
try {

            Map<String, String> stratops = ImmutableMap.of(
                "replication_factor", String.valueOf(replicationFactor));

            ksDef = cl.makeKeyspaceDefinition()
                    .setName(keySpaceName)
                    .setStrategyClass("org.apache.cassandra.locator.SimpleStrategy")
                    .setStrategyOptions(stratops);
            cl.addKeyspace(ksDef);

            log.debug("Created keyspace {}", keySpaceName);
        } catch (ConnectionException e) {
            log.debug("Failed to create keyspace {}, keySpaceName");
            throw new TemporaryStorageException(e);
        }
```

Would like to be able to create a keyspace as in:

https://github.com/Netflix/astyanax/wiki/Create-keyspace-or-column-family

Second example with NetworkTopologyStrategry and two datacenters.

**Comment by xedin** [comment]
I'm on this, strategy_class is already added, will try to finish up with options over the weekend.

**Comment by xedin** [comment]
@mbroecheler @krm1312  Pull is at https://github.com/thinkaurelius/titan/pull/654 

Only thing is that replication-strategy-options have to be set as an array instead of a map (because of property file support), but normally people do "<DC>", "<factor>" pairs anyway, so it's not a big deal.

**With BaseConfiguration:**

```
conf = new BaseConfiguration();
conf.setProperty("storage.backend","cassandra");
conf.setProperty("storage.hostname","127.0.0.1");
conf.setProperty("storage.replication-strategy-class", "org.apache.cassandra.locator.NetworkTopologyStrategy");
conf.setProperty("storage.replication-strategy-options", ["DC5", "1", "DC1", "2", "DC7", "3"]);
g = TitanFactory.open(conf);
```

**With .properties file:**

```
storage.backend=astyanax
storage.hostname=127.0.0.1
storage.replication-strategy-class=org.apache.cassandra.locator.NetworkTopologyStrategy
storage.replication-strategy-options=DC5,1,DC1,2,DC7,3
```

**Comment by dalaro** [comment]
Thanks Pavel, #654 is merged into titan05.  I like that it works with all of the Cassandra backends.  I expanded one of the new config option doc strings in 3b3d63a3e8ab9d4d70e48ac7347a8b1055423a46, but otherwise I didn't touch anything.
