### ISSUE TITLE
Occasional LuceneIndex.mutate failures

### ISSUE THREAD

**Issue by jsight** [thinkaurelius/titan#656]
I am getting periodic LuceneIndex.mutate failures due to duplicate documents. The stacktrace is:

```
at com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex.mutate(LuceneIndex.java:171)
at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:95)
at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:77)
at com.thinkaurelius.titan.diskstorage.BackendTransaction.commit(BackendTransaction.java:88)
at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$2.call(StandardTitanGraph.java:311)
at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$2.call(StandardTitanGraph.java:241)
at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:62)
at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:320)
at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1018)
at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commit(TitanBlueprintsGraph.java:57)
```

The code in question is:
} else if (hits.scoreDocs.length > 1) {
                        throw new IllegalArgumentException("More than one document found for document id: " + docid);

For some reason, hits.scoreDocs returns two identical documents. I cannot see what scenario would cause the index to get into this state.

**Comment by mbroecheler** [comment]
Yeah, that's interesting. Do you have code that reproduces this?

**Comment by jsight** [comment]
Nothing standalone... the unit test suite for this project fails ~1/3 of the time with this exception:
https://github.com/windup/windup

**Comment by mbroecheler** [comment]
There seems to be a race condition around the creation of documents. If you substitute ES for Lucene, do you still see the error?

**Comment by jsight** [comment]
I tried ElasticSearch, but I do not believe that it would work for our use-case due to the lazy indexing. If we attempt a query before the ElasticSearch refresh interval has occurred, then we will end up with a race condition and potentially an invalid query result.

This actually shows up in some of our unit tests as well. I don't believe there is a way to force immediate indexing with ES, right?

**Comment by mbroecheler** [comment]
regarding lucene:  we are extending our test coverage in the hope to
reproduce this. If you can isolate a test that does this please let us
know. Is this triggered in a multi-threaded test case?

regarding es: you could force a flush after each commit (
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-flush.html)
but that would be expensive. In any case, i was wondering if es would
exhibit the same race condition.

On Thu, Jun 12, 2014 at 10:32 AM, Jesse Sightler notifications@github.com
wrote:

> I tried ElasticSearch, but I do not believe that it would work for our
> use-case due to the lazy indexing. If we attempt a query before the
> ElasticSearch refresh interval has occurred, then we will end up with a
> race condition and potentially an invalid query result.
> 
> This actually shows up in some of our unit tests as well. I don't believe
> there is a way to force immediate indexing with ES, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/656#issuecomment-45922745.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by jsight** [comment]
@mbroecheler - I have tried to isolate a test-case, but this has been completely unsuccessful for me so far. The test-cases that trigger the problem are not multithreaded.

I have spent a lot of time looking into this today, and it really is a bizarre problem. The problem does not happen on every test run, but when it does occur, it always occurs on exactly the same Vertex in our unit test. One-off timing related problems seem unlikely to be so consistent in terms of where they fail, IMO.

I am currently experimenting with a retry mechanism. I think that once the problem occurs once, it will reoccur during the same build periodically.

**Comment by jsight** [comment]
@mbroecheler - I have placed a sample of a detailed log here:
https://raw.githubusercontent.com/jsight/scratchpad/master/build_1.log

This enables the trace statements from LuceneIndex.mutate to be seen.

As you can see, document 2oo appears to only be created once:
Jun 25, 2014 6:17:38 PM com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex mutate
INFO: Creating new document for [2oo]

For some reason, when it is called again a while later multiple docs are found anyway:
INFO: More than one document found for document id [2oo]
Failed to add type (interface org.jboss.windup.rules.apps.java.scan.model.JavaClassModel) to: [isDirectory: false, filePath: /home/jsightler/project/migration/software/windup/tests/core/target/windup3332650931868536265/archives/wicket-core-1.5.10.jar/org/apache/wicket/util/iterator/IteratorFilter.class, type: |FileResource|]
Attempting to add type (interface org.jboss.windup.rules.apps.java.scan.model.JavaClassModel) to: [isDirectory: false, filePath: /home/jsightler/project/migration/software/windup/tests/core/target/windup3332650931868536265/archives/joda-time-2.0.jar/org/joda/time/LocalDateTime$Property.class, type: |FileResource|]

Could it be that lucene is reorganizing under the covers and this is a false result? Maybe both docs are actually identical somehow?

**Comment by jsight** [comment]
@mbroecheler - I have isolated the problem. It appears that in some cases, the search is returning inexact matches, even though this is a StringField. These seem to differ only in case (2Oo vs 2oo).

I have put a patch in my local fork that fixes this:
https://github.com/jsight/titan/commit/5c4ac652287b1e761756db40dfaf73c16c8e1599

Could you look into this (or another similar solution)?

**Comment by mbroecheler** [comment]
@jsight That's an excellent observation. We will take a look at the solution.

**Comment by mbroecheler** [comment]
In Titan 0.5 we are changing the encoding scheme to only use lower-case letter thereby making it case insensitive which should fix this issue.
