### ISSUE TITLE
Wiki : wrong Snappy version ?

### ISSUE THREAD

**Issue by 0xRoch** [thinkaurelius/titan#657]
https://github.com/thinkaurelius/titan/wiki/Titan-Limitations#snappy-14-does-not-work-with-java-17

In the wiki, Snappy 1.4 / 1.5 is mentioned : shouldn't it be Snappy 1.0.4 / 1.0.5 instead ?

http://mvnrepository.com/artifact/org.xerial.snappy/snappy-java

**Comment by dalaro** [comment]
Fixed in d5b091df87122eb9cff31afdeba201f5631cdbca

This bug only affects really old Cassandras at this point, since they've shipped a fixed version since 1.2.6.  I've noted that version and just suggested an upgrade instead of the old surgical fix of dropping in a newer Snappy.
