### ISSUE TITLE
gremlin.bat fails with Titan 0.5 on Windows with "The input line is too long."

### ISSUE THREAD

**Issue by yuriythedev** [thinkaurelius/titan#662]
After I've built Titan 0.5 after sync'ing my local repo today, I was not able to run gremlin.bat
It was failing with :

The input line is too long.
The syntax of the command is incorrect.

My environment is: Windows 8.1 x64

My workaround for the issue was to simply add directories to CLASSPATH like: 
set CLASSPATH=..\lib*;

Instead of looping over all the jar files and adding each jar to the class path explicitly. 

I am not an expert in Java, but possibly it would be worth switching to this, simpler, solution?

**Comment by dalaro** [comment]
Both this gremlin.bat CLASSPATH issue and the HadoopGraph import issue were resolved in 0.5.0.  Setting milestone back from 0.5.1 to 0.5.
