### ISSUE TITLE
Index name setting ignored

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#669]
FROM PABLO: Thank you for your response. I did the change, And I'm seeing in the logs that the xyz index name seems to be applied

14/05/03 14:24:14 INFO diskstorage.Backend: Configuring index [xyz] based on:

However, when I browse indexes in ES http://localhost:9200/all/_mapping  I'm seeing 

{
titan: 
{
vertex: 
{
properties: 
{

and

hits" : [ {
      "_index" : "titan",
      "_type" : "vertex",
      "_id" : "12j6",

I was expecting that the index name = xyz? what I'm doing wrong?

**Comment by dkuppitz** [comment]
I just [verified](https://groups.google.com/d/msg/aureliusgraphs/HF8p4I6d4QI/2YoO0mnXGl0J) that everything's working as expected.
