### ISSUE TITLE
titan 0.5 hbase 0.94 support broken

### ISSUE THREAD

**Issue by michaelhowecisco** [thinkaurelius/titan#672]
titan-hbase-parent module titan-hbase-core has a specific dependency on hbase 0.96.

In titan-hbase-core/pom.xml, the hadoop1 and hadoop2 profiles declare, respectively:
               <hbase.version>${hbase096.version.base}-hadoop1</hbase.version>
               <hbase.version>${hbase096.version.base}-hadoop2</hbase.version>
This <hbase.version> is then used to for other artifacts. 

This dependency appears to break compatibility when running on systems only able to support hbase 0.94.

**Comment by dalaro** [comment]
@michaelhowecisco please share some details about how this is failing, like logs or exception traces (ideally something I can reproduce).

`mvn clean install -DskipTests=true && mvn verify -pl titan-hbase-parent/titan-hbase-094` passes here except HBaseGraphTest.simpleLogTest.  That's currently failing on 0.96 and 0.98 too; it covers the trigger log consumer system and looks unrelated, though I could be mistaken.

The dependencies in titan-hbase-core that you described are all marked `<optional>true</optional>`.  They're not inherited by titan-hbase-094.  The intent was that titan-hbase-core's code should only use parts of the HBase ABI & API that are stable across versions.  In theory, it should be possible to compile it against any one of 0.94, 0.96, or 0.98, and then to link those classfiles against each of those HBase versions safely at runtime.  Are you seeing an IncompatibleClassChange exception?

**Comment by dalaro** [comment]
I still haven't been able to reproduce this; please reopen with additional details
