### ISSUE TITLE
Add HyperDex as a datastore and/or indexing backend

### ISSUE THREAD

**Issue by espeed** [thinkaurelius/titan#673]
HyperDex (http://hyperdex.org) is an open-source (BSD) distributed, consistent, multidimensional datastore that enables multi-property searches and range queries so it can also be used as an indexing backend.

From the paper...

> [HyperDex] provides a unique search primitive that enables queries on secondary  attributes. The key insight behind HyperDex is the concept of hyperspace hashing in which objects with multiple attributes are mapped into a multidimensional hyperspace.

See http://hyperdex.org/papers/hyperdex.pdf

HyperDex has pluggable backends, but its primary backend is a modified version of LevelDB (http://hyperdex.org/performance/leveldb/) -- note LevelDB is the backend used by Cayley (https://github.com/google/cayley).

On GitHub: https://github.com/rescrv/HyperDex @rescrv @seanogden

**Comment by rescrv** [comment]
It'd be great to see HyperDex as a backend for Titan.

Whomever does the porting should feel free to reach out to me with any questions.  I'd be happy to provide assistance where I can.

**Comment by bwlim** [comment]
I'm a big fan for Titan Graph Database.
I've implemented Kardin (Social Business Card Service) (http://www.kard.in/) using Titan(Cassandra+ElasticSearch) 3 server cluster on AWS. (with Play-scala application servers)

HyperDex seems wonderful to me~
I hope HyperDex could replace Cassandra and Elasticsearch as Titan storage and index backend.
HyperDex is said that it breaks CAP theorem.. (with user-configurable failure-able max node count restriction)
HyperDex is Distributed, Searchable, Consistent, Available, Fault-tolerant, ACID... (seems fancy DB :D)
Titan with Cassandra/Elasticsearch cannot provide fully ACID transaction feature,
and is "eventually" consistent (not immediately consistent)

HyperDex slides..
http://hyperdex.org/slides/2013-06-28-cloudphysics.pdf
http://hyperdex.org/slides/2012-04-27-HyperDex.pdf

**Comment by anvie** [comment]
:+1:

**Comment by takaomag** [comment]
:+1:

**Comment by rescrv** [comment]
It's worth noting that the Weaver project is a graph store developed by @dubey that is built on top of HyperDex.  It would be great to see Titan do the same.

**Comment by takaomag** [comment]
I found out about Weaver for the first time. According to [the project page](http://weaver.systems/);

> _Question_: How high is 'high throughput'?
> 
> _Answer_: Our preliminary experiments show that Weaver achieves **over 12x higher throughput than Titan** on an online social network workload similar to that of Tao. In addition, Weaver also achieves 4x lower latency than GraphLab on an offline, graph traversal workload.
> 
> _Question_: How does Weaver compare to {GraphLab/Titan/Neo4j}?
> 
> _Answer_: Weaver is a high-performance, transactional, and scalable online data store for graphs.
> - GraphLab is designed for efficient, offline graph computation.
> - **Titan** provides a similar API to Weaver, but implements transactions using **slow two-phase locking that severely limits performance**.
> - Neo4j is primarily a single-machine graph store. The high availability mode in Neo4j implements master-slave replication with eventual consistency.

It seems very young alpha project (dangerous for production!) and does not have Tinkerpop api. But it is interesting for me. I want to test and use it for some projects which require performance.

**Comment by ghost** [comment]
An issue open against Titan implies to me that there is work to be done in the Titan code base.  I don't think we want to make changes to Titan for this particular back end.  In that case, this isn't an "Issue" or feature request that needs to be open against Titan.  Someone can still show up with a technology preview in their github repo for hyperdex and at that point there could be a discussion about making the new backend part of the Titan package.  Recommend closing this.

**Comment by spmallette** [comment]
I'd agree.  If someone would like to develop the hyperdex backend, butild it in a separate repo and present it to the community on the mailing list - we can go from there.
