### ISSUE TITLE
Slow loop on Iterable returned by vertices() method 

### ISSUE THREAD

**Issue by mduruisseau** [thinkaurelius/titan#674]
Hi !

First, some technical info : 
- I work on a laptop with the following specs : 
  - Intel® Core™ i7-2620M CPU @ 2.70GHz × 4 
  - 4Go DDR3
  - Ubuntu 12.04 64 bits
- Scala 2.10.3 / titan-all v0.4.4 with gremlin-scala_2.10 v2.5.0
- I use the Titan Server package (titan-server-0.4.4.zip)
- I start it with `titan.sh -c cassandra-es start`

Then, my graph configuration :

``` scala
val config = new BaseConfiguration();
val storage = config.subset(GraphDatabaseConfiguration.STORAGE_NAMESPACE);
config.setProperty("storage.backend", "cassandra");
config.setProperty("storage.hostname", "127.0.0.1");
val index = storage.subset(GraphDatabaseConfiguration.INDEX_NAMESPACE).subset(INDEX_NAME);
index.setProperty("backend", "elasticsearch");
index.setProperty("local-mode", true);
index.setProperty("client-only", false);
index.setProperty("directory", "/home/----/titan/db/index" + File.separator + "es");
```

And for the graph creation :

``` scala
val graph = TitanFactory.open(config);
graph.makeKey("type").dataType(classOf[String]).indexed(classOf[Vertex]).make();
 ...
graph.makeKey("geo").dataType(classOf[Geoshape]).indexed(classOf[Vertex]).make();
```

So, my graph contains approximately 200k vertex, and 300k edges I think, I want to get some vertices near to another one.
For that, I use this request (`sgraph` is my graph with the Scala Wrapper) : 
`sgraph.query().has("type", "cluster").has("geo", Geo.WITHIN, Geoshape.circle(lat, lon, dist)).vertices()`

This request is fast, ~ 10/20 ms, but the loop over the Iterable is really slow, in a weird way : 

> hasNext : 2.28578 ms | next : 0.0182 ms
> hasNext : 798.240405 ms | next : 0.00468 ms
> hasNext : 0.799207 ms | next : 0.004634 ms
> hasNext : 0.798177 ms | next : 0.00459 ms
> hasNext : 1535.508366 ms | next : 0.004994 ms
> hasNext : 0.654433 ms | next : 0.004807 ms
> hasNext : 0.630001 ms | next : 0.004796 ms
> hasNext : 0.622178 ms | next : 0.004867 ms
> hasNext : 445.363685 ms | next : 0.006447 ms

... Of course, it's not always the same iteration that is slow or fast ;-)

I looked inside the code to find what could slow it that much, and I think I found something : 
The hasNext method call the "computeNext" method which is override by the "UnmodifiableIterator" of the Google common .collect lib : 

``` java
public static <T> UnmodifiableIterator<T> filter(final Iterator<T> unfiltered, final Predicate<? super T> predicate) {
    checkNotNull(unfiltered);
    checkNotNull(predicate);
    return new AbstractIterator<T>() {
        @Override protected T computeNext() {
            while (unfiltered.hasNext()) {
                T element = unfiltered.next();
                if (predicate.apply(element)) {
                    return element;
                }
            }
            return endOfData();
        }
    };
}
```

And so, for every iteration of my loop, it goes there and loop over the "unfiltered" iterable .. 
I don't know if that's the problem but that's the only thing I found that could slow the loop ... 

If somebody can help me, that would be great ! ;-)

**Comment by mbroecheler** [comment]
Hello Mickaël,

how to fix it: You have to create an external (i.e. ElasticSearch based) index for the two properties. To do that, you have to change:

``` scala
indexed(classOf[Vertex])
```

to

``` scala
indexed(INDEX_NAME,classOf[Vertex])
```

without the index name, Titan will create a "standard" index which means a hash index that does not support geographic "within" queries.

Why is this happening?
Since you (inadvertently) created two hash indexes for type and geo, Titan does not have an index that can satisfy both of your has constraints. Hence, it queries for all vertices that have type=cluster and then filters out those that don't fall within the circle. For that, it has to retrieve the location of each matching vertex which is why you see the delays during iteration.

In the future, please use our mailing list for questions like this so that the community benefits as well. This is for bugs only.

**Comment by mduruisseau** [comment]
Hello !

Thank you, it seems to be faster indeed .. ;)
Sorry for the issue here, next time I'll post on the mailing list !
