### ISSUE TITLE
Relation or Node that age and expire

### ISSUE THREAD

**Issue by hihellobolke** [thinkaurelius/titan#677]
While trying to build a graph from a streaming data and looking various graphDBs - I thought a notion of expiration of Node & relationship would be cool. A lot of use cases would exist, for graphing a streaming data...

**Comment by joshsh** [comment]
Nodes and relationships?  Surely you mean vertices and edges ;-)  A time-to-live feature supporting expiration of vertices, edges, and properties at the graph level is under development and will soon be merged into the Titan 0.5 branch.  See:

https://github.com/thinkaurelius/titan/issues/523

and:

https://github.com/thinkaurelius/titan/tree/ttl

**Comment by hihellobolke** [comment]
Awesome! awesome! awesome! Thank you!!
