### ISSUE TITLE
when will Titan support Hbase 0.96 ?

### ISSUE THREAD

**Issue by huiwenhan** [thinkaurelius/titan#683]
when will Titan support Hbase 0.96 ?

**Comment by mbroecheler** [comment]
Titan 0.5 (which is currently in M1 and release within a month) will support 0.96

**Comment by xsyn** [comment]
Hi, is 0.98 support also queued for this this release?

**Comment by xsyn** [comment]
nevermind, I see interop between 0.96 and 0.98 is meant to be seamless
