### ISSUE TITLE
indexQuery is broken in 0.5.0-M2

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#687]
```
gremlin> g = TitanFactory.open("conf/titan-cassandra-es.properties")
==>titangraph[cassandrathrift:[192.168.2.110]]
gremlin> GraphOfTheGodsFactory.load(g)
==>null
gremlin> g.query().has("age", GREATER_THAN, 100).vertices()
==>v[256]
==>v[1024]
==>v[1280]
==>v[2048]
gremlin> g.indexQuery("search","v.age:[100 TO *]").vertices()
Index with name [search] is unknown or not configured properly
Display stack trace? [yN]
```

**copy/paste friendly version:**

``` groovy
g = TitanFactory.open("conf/titan-cassandra-es.properties")
GraphOfTheGodsFactory.load(g)
g.indexQuery("search","v.age:[100 TO *]").vertices()
```

**Comment by dalaro** [comment]
I think this has to do with index API refactoring.  The backend name `search` declared for ES in the config file no longer maps 1-to-1 with with logical index name.  Here's the loader creating indices named `edges` and `vertices`, each of which is backed by `search`:

https://github.com/thinkaurelius/titan/blob/0.5.0-M2/titan-core/src/main/java/com/thinkaurelius/titan/example/GraphOfTheGodsFactory.java#L49-L55

This seems to do the right thing:

```
gremlin> g.indexQuery("vertices","v.age:[100 TO *]").vertices()._().transform { it.getElement() }.map
==>{name=saturn, age=10000}
==>{name=jupiter, age=5000}
==>{name=neptune, age=4500}
==>{name=pluto, age=4000}
```

Those function calls between `vertices()` and `map()` are a wart.  Is there a cleaner way to do this?  We might need to change the type `Iterable<Result<Vertex>>` returned by the `IndexQueryBuilder.vertices()` call to `Iterable<Vertex>` and then change `IndexQueryBuilder$ResultImpl` into a forwarding class that lazily retrieves its backing element.  Not sure on that though...

**Comment by dkuppitz** [comment]
Great, that works, although it's a bit cumbersome to tell Titan 3 times that I want either vertices or edges. In case somebody else stumbles across this issue, here's an example that shows the difference between vertex- and edge-queries:

```
gremlin> g.indexQuery("vertices","v.age:[5000 TO *]").vertices()*.getElement()._().map()
==>{name=saturn, age=10000}
==>{name=jupiter, age=5000}
gremlin> g.indexQuery("edges","e.reason:loves").edges()*.getElement()._().map()
==>{reason=loves fresh breezes}
==>{reason=loves waves}
```

**Comment by mbroecheler** [comment]
The reason is that Titan in 0.5 supports multiple vertex and edge indexes
in the same indexing backend so that the indexes can be separated from one
another. This is particularly useful in combination with labels.
Say, you have "user" and "organization" vertices. Both can have names and
what not and you want them both to be indexed but not together so that the
indexes do not pollute each other. This is now supported which makes
indexing more powerful and efficient. But it also means that you have to
specify which indexes you want to query in a direct IndexQuery since there
can be multiple vertex indexes.

On Wed, Jul 23, 2014 at 1:27 PM, Daniel Kuppitz notifications@github.com
wrote:

> Great, that works, although it's a bit cumbersome to tell Titan 3 times
> that I want either vertices or edges. In case somebody else stumbles across
> this issue, here's an example that shows the difference between vertex- and
> edge-queries:
> 
> gremlin> g.indexQuery("vertices","v.age:[5000 TO _]").vertices()_.getElement()._().map()
> ==>{name=saturn, age=10000}
> ==>{name=jupiter, age=5000}
> gremlin> g.indexQuery("edges","e.reason:loves").edges()*.getElement()._().map()
> ==>{reason=loves fresh breezes}
> ==>{reason=loves waves}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/687#issuecomment-49930324.

## 

Matthias Broecheler
http://www.matthiasb.com
