### ISSUE TITLE
Use key/value pairs in vertex centric indexes (and maybe other indexes)

### ISSUE THREAD

**Issue by mindade** [thinkaurelius/titan#691]
Vertex centric indexes are nice, but they only allow indexing on one property (or a composite of single properties). Frequently, I need to index an edge on multiple properties for the same edge in order to speed up queries. For example, say I have an event edge that has a time and a place. Now, I'm forced to create two edges with sort keys for time and place. 

I have a proposal. Sort edges on multiple key/value pairs that I can associate with an edge. In other words, let me add more than one entry to the index per edge. Taking the example above, when I add the edge it will create two index entries for the same edge, one for time and one for place. 

On the implementation side, you would still only need one index. Effectively, the 'key' would partition the index into multiple parts. When querying, a 'key' could be specified, but this might need extra syntax in gremlin. So instead, the value could be specified as 'key:value', or something like that.

Wouldn't this make vertex centric indexes much more powerful and useful?

**Comment by dkuppitz** [comment]
You can have as many sort-keys as you want, see the [Type Definition Overview](https://github.com/thinkaurelius/titan/wiki/Type-Definition-Overview#sortkeytitantype-and-signaturetitantype).

> The sort-key can be composite, that is comprised of multiple types. For composite sort keys, edges are sorted by the first type, then the second and so forth.

Is that not what you need?

**Comment by mindade** [comment]
No, that is not what I need. I need the same edge sorted on different keys, and be able to pick which sort key I want to use in the query. With a composite key, I can't use an index for say, time, in one case, and then place, in another case, for the same edge.

My problem is that some of my edges contain a fair number of properties. I want to be able to use different properties as the sort key for the same edge, rather than having to duplicate the edge multiple times with a different sort key each time. 

For example, take an edge representing an event. The event can have a start-time, end-time, location, reason, etc. When querying from a vertex, I want to be able to traverse the edge based on start-time for some queries, location for some queries .... Now, I have to create separate redundant edges and use a different sort key for each edge. In this example, I have to create an event-start-time edge, an event-location edge ... They are all redundant. But I need the different sort keys to make the queries efficient.

If I do a g.V.has() query (or g.E.has()) query, I can use any property to query on. As long as that property is indexed, I'll get good performance. But it's not the same for v.E.has queries. The edge index inside the vertex has a hard coded sort key, defined when the edge is created.

I suggested using key/value pairs in the vertex centric edge index to partition the index so that different sort key properties could be specified on queries. But that's only a suggestion. There might be better ways to do it.

Do you see that I mean? It only applies to the vertex centric index inside the edge. Am I missing something?

**Comment by mbroecheler** [comment]
Hey,

this feature has been implemented for Titan 05. There, you first define
your edge label and then can define an arbitrary number of indexes on that
label with various combinations of keys. Titan's query optimizer will pick
the best index to use for a particular query.

Cheers,
Matthias

On Sun, Jul 27, 2014 at 10:38 AM, mindade notifications@github.com wrote:

> No, that is not what I need. I need the same edge sorted on different
> keys, and be able to pick which sort key I want to use in the query. With a
> composite key, I can't use an index for say, time, in one case, and then
> place, in another case, for the same edge.
> 
> My problem is that some of my edges contain a fair number of properties. I
> want to be able to use different properties as the sort key for the same
> edge, rather than having to duplicate the edge multiple times with a
> different sort key each time.
> 
> For example, take an edge representing an event. The event can have a
> start-time, end-time, location, reason, etc. When querying from a vertex, I
> want to be able to traverse the edge based on start-time for some queries,
> location for some queries .... Now, I have to create separate redundant
> edges and use a different sort key for each edge. In this example, I have
> to create an event-start-time edge, an event-location edge ... They are all
> redundant. But I need the different sort keys to make the queries efficient.
> 
> If I do a g.V.has() query (or g.E.has()) query, I can use any property to
> query on. As long as that property is indexed, I'll get good performance.
> But it's not the same for v.E.has queries. The edge index inside the vertex
> has a hard coded sort key, defined when the edge is created.
> 
> I suggested using key/value pairs in the vertex centric edge index to
> partition the index so that different sort key properties could be
> specified on queries. But that's only a suggestion. There might be better
> ways to do it.
> 
> Do you see that I mean? It only applies to the vertex centric index inside
> the edge. Am I missing something?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/691#issuecomment-50280037.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mindade** [comment]
Wow, that's awesome. I'll start using the 05 branch. Is it 'titan05'?

**Comment by mindade** [comment]
I have the 0.5 M2 version running, but I can't find an example for creating an edge with multiple sortKeys. (The docs for vertex centric indexes in the 0.5 version is blank.) Is this handled differently now? I can see how to create multiple indexes for the edges, but I don't see how those indexes get used as a vertex centric index. It looks like a global index.

**Comment by mindade** [comment]
I think I found a hint for how to do this in the new GraphOfTheGodsFactory:

mgmt.buildEdgeIndex(battled, "battlesByTime", Direction.BOTH, Order.DESC, time);

I'll keep digging, but this looks great. I guess the sortKey is no longer needed on edges?

**Comment by mbroecheler** [comment]
We are about to release the M3 with an updated documentation. That should
make things easier for you ;-)
But, yes, you found it. Vertex-centric indexes are now created through the
management system. The sort key "time" in this particular example.

On Sun, Jul 27, 2014 at 10:40 PM, mindade notifications@github.com wrote:

> I think I found a hint for how to do this in the new GraphOfTheGodsFactory:
> 
> mgmt.buildEdgeIndex(battled, "battlesByTime", Direction.BOTH, Order.DESC,
> time);
> 
> I'll keep digging, but this looks great. I guess the sortKey is no longer
> needed on edges?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/691#issuecomment-50301934.

## 

Matthias Broecheler
http://www.matthiasb.com
