### ISSUE TITLE
gremlin gives 'need to set configuration value: root.graph.titan-version' when building from source

### ISSUE THREAD

**Issue by mindade** [thinkaurelius/titan#693]
I did the following:
1. Cloned titan.
2. git checkout titan05.
3. mvn clean install
4. bin/gremlin.sh
5. g = TitanFactory.open('conf/titan-cassandra-es.properties');

I get the following error:

"Need to set configuration value: root.graph.titan-version"

**Comment by dalaro** [comment]
I couldn't reproduce this.  My titan05 head was d27488d3521543a9ef14bcdf832e70f324919ae1.  I had an Apache Cassandra 2.0.9 instance with no data running at the time.

Do you have existing data, and if so, can you reproduce the problem on a clean Cassandra + ES?  What version of Cassandra are you running?

**Comment by mindade** [comment]
Hmmm. I really wanted to start the embedded cassandra, so I was using the wrong properties file. Not sure why it was giving that strange error. It seems to be working now. Thanks.

**Comment by davidseth** [comment]
By upgrading to Cassandra 2.0.9 I solved the "Need to set configuration value: root.graph.titan-version" problem. Previously I was using 2.0.8 and couldn't run gremlin.
