### ISSUE TITLE
Release reserved id blocks

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#7]
Currently, any id block that is reserved by a client cannot be release, that is, given back to the database so that it can reassign that block. This means, that the unused ids are lost when a client is shut down.

There is already a method stup in StorageManager for id block release (commented out). Implementing this feature would require:
- The StorageManager implementations put unused ids back into the common pool. This is easy. What is harder is using those ids again in the future. Strategy: With probability X scan the last Y entries in the id block table for the particular partition id. If there is a hole in that list, pick a hole randomly and return it as the id block. Otherwise, proceed like we currently do. The contract of the getIDBlock method is already such that it might return smaller blocks than requested.
- IDPool implementations should release unused id blocks when closed (easy)

**Comment by okram** [comment]
Is this still and issue or was this fixed?

**Comment by mbroecheler** [comment]
This is a limitation of the current release. It means that a few ids from a
block will be lost when the database is shutdown or in any way terminated.
Given that Titan has long ids loosing a few ids here and there is not
really a limitation until we hit exa-scale graphs or somebody restarts the
database every second (in which case there is probably something else
wrong).
Nonetheless, we aim to put unused ids back into the id pool. However, in a
distributed environment that is difficult to do without acquiring locks.
So, this will be future feature.

On Monday, June 4, 2012, Marko A. Rodriguez wrote:

> Is this still and issue or was this fixed?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/7#issuecomment-6100159

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by mbroecheler** [comment]
Not convinced that this is really needed. Titan now supports multiple partition spaces and people can adjust the id pool allocation size. So, while a few ids will be lost on database shutdown this should be tolerable compared to the significant overhead incurred by reusing ids. Will keep this issue open to keep thinking on it, but for now its a "no fix".

**Comment by mbroecheler** [comment]
This will not be implemented since the benefit is very limited and the amount of work and likelihood of failure too high.
