### ISSUE TITLE
Zombie lock timeout in LocalLockMediator

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#70]
Although the general-case locking code ignores locks over an age threshold as specified in the original protocol, this logic is not fully implemented in the LocalLockMediator.

Write a JUnit test with a timeout annotation to verify the current wait-forever-for-zombie-local-locks brokenness, then fix it and verify that the test passes.

**Comment by dalaro** [comment]
Thanks for extracting this from our email convo.

**Comment by dalaro** [comment]
When I wrote additional tests, I found that this wasn't correctly implemented in the general-case locking code that talks to the storage backends.  In other words, expiration of zombie locks wasn't working at all, so abnormally terminated transactions could sometimes leave zombie locks in the storage backend indefinitely.  I've added testing for both the local and remote expiration cases and fixes for both cases in titan0.1.
