### ISSUE TITLE
Rename methods for adding vertex with label

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#702]
Rename addVertex(string) and addVertex(VertexLabel) methods in TitanGraph, titanBlueprintsGraph, and TitanTransaction to addVertexWithLabel in order to remove with Collision with blueprints.

**Comment by dalaro** [comment]
4da8c8a44e1e5b05e62499fdf00ed6bba0258c19 is a follow-on commit that resolves some asymmetry between TitanGraph/TitanTransaction's method names and updates the docs.
