### ISSUE TITLE
git repo changes

### ISSUE THREAD

**Issue by mindade** [thinkaurelius/titan#704]
I tried loading the 0.5.0-M3 release and git cloning the archive. The directory structure has changed. The bin, conf, and many other directories are missing, so I can't seem to just bin/gremlin.sh anymore. Is this intentional? I can't find any new doc on the changes.

**Comment by dalaro** [comment]
You're using the git repo, not the zip archive, right?  This builds M3's bin, conf, etc and then runs `bin/gremlin.sh`:

```
git checkout 0.5.0-M3
mvn clean install -DskipTests=true
bin/gremlin.sh
```

`titan.sh` is not setup to run out of the root of the repo in M3.  It's missing a few dirs that are present in the zipfiles.

**Comment by mindade** [comment]
I can get the M3 archive or branch compiled, but I was trying the titan05 branch. That should be the latest 0.5.0, correct? I know I had this compiling last week. I'm trying it on a different machine. I just cloned the repo and did the commands above (except the checkout was for titan05). It builds, but the bin, lib, conf, and other directories are not there. I think I can use the M3 branch, but I want to stay current.

On another note, what is the best way to set up titan under Eclipse. Is there a recommended way to import titan as a project under eclipse?

**Comment by dalaro** [comment]
I unintentionally disabled building `<REPO_ROOT>/bin`, `conf`, and `lib` dirs by default while working the `-Ddev.hadoop=1` or `2` maven option into Titan's build.  The repo root dirs were installed correctly only when `-Ddev.hadoop=X` was given on the command line for a while on titan05, up until around ca904c6c598fbbe7c7101d201cbb225d2b9fdf36 and 2dfd158f7defdae74f48bd11dc56defbeba1ac81.  It's fixed on titan05 now: the default behavior in the absence of any `dev.hadoop` option is to install Titan dependencies with Hadoop 2 jars into `<REPO_ROOT>/lib`, along with the usual files `bin` and `conf`.

What are the specific Eclipse import issues?  Are you running into lifecycle mapping problems between Maven and Eclipse's internal build system?  That's the only thing I've tweaked in the past.

**Comment by dalaro** [comment]
Still not sure about the Eclipse import problems.  Closing given the lack of detail.
