### ISSUE TITLE
Allow configuration of isolation level in BerkeleyJE adapter

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#71]
http://docs.oracle.com/cd/E17277_02/html/java/com/sleepycat/je/TransactionConfig.html

**Comment by mbroecheler** [comment]
http://en.wikipedia.org/wiki/Isolation_(database_systems)

**Comment by mbroecheler** [comment]
Also accomodate high availability setups?

**Comment by dalaro** [comment]
cc2b3a5bf6edc5599a506f9eda5e01018466b9a6 on titan05 adds a `storage.isolation-level` option that accepts the values READ_UNCOMMITTED, READ_COMMITTED, REPEATABLE_READ, and SERIALIZABLE.  The BDB JE public API does not seem to have an enum for isolation levels, instead exposing them only through a series of methods that take a boolean parameter, so I made an enum in Titan's BDB JE adapter whose literals exactly match [those in described in the BDB docs](http://docs.oracle.com/cd/E17277_02/html/TransactionGettingStarted/isolation.html#degreesofisolation).

The option can be set two ways:

In the transaction configuration, e.g. `g.buildTransaction().setCustomOption("storage.isolation-level", "SERIALIZABLE").start()`.

In the graph configuration, e.g. `storage.isolation-level=READ_UNCOMMITTED` in titan's properties file, which becomes the default isolation level for all transactions that don't specify their own isolation level as shown above.

This option has no effect when transactions are disabled (`storage.transactions=false`).

**Comment by dalaro** [comment]
Split HA configuration into a new issue #576
