### ISSUE TITLE
Look into avoiding "java.class.path" system property in Reflections

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#712]
See:

https://github.com/thinkaurelius/titan/issues/700#issuecomment-51985584

Some JVM environments like Play in dev mode or exec-maven-plugin's exec:java goal seem to modify the classpath at runtime, so that the system prop and the actual classpath in use by the app's classloader hierarchy are different.  We probably want to prefer the latter by default, if Reflections supports it or we can easily bolt that on.  Don't know if this is actually feasible yet.

**Comment by randall-sosacorp** [comment]
Here are some relevant links to the issue and methodologies:
https://groups.google.com/forum/#!topic/play-framework/H17U-tTmw0U
http://stackoverflow.com/questions/11613988/how-to-get-classpath-from-classloader

There's also an [interesting example in the Hazlecast project](https://github.com/hazelcast/hazelcast/blob/v3.3-EA2/hazelcast/src/main/java/com/hazelcast/util/ServiceLoader.java).

**Comment by dalaro** [comment]
I replaced Titan's use of  the Reflections helper method`ClasspathHelper.forJavaClassPath`, which used the java.class.path property, with a call to `ClasspathHelper.forClassLoader(ClassLoader...)`.  The classloaders passed in are configurable through public methods on Titan's `ReflectiveConfigOptionLoader` class.  The default chain of classloaders is:
- The classloader that loaded ReflectiveConfigOptionLoader
- The thread context loader
- The classloader that loaded the calling class in Titan

This fixed config option loading in exec:java.  I think it will do the same in Play dev and injection containers, but the total absence of convention regarding classloader hierarchies makes it tough to guarantee.  Let's reopen or open new if the default behavior can be improved to cover a wider range of environments.

**Comment by dalaro** [comment]
Related commits:
- 69ca65b21796f5639b3ef77a71b42e91a3d12212
- 0b2620d9aec9292a4e79f53291dbc50689b7b130
- 41a29eff6e7d0e0509833ebec6ad23108a5cadc0
