### ISSUE TITLE
Exception during deletion of an edge.

### ISSUE THREAD

**Issue by asaf** [thinkaurelius/titan#713]
Hey,

In some situations while trying to delete an edge, it fails on:

``` java
Caused by: java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$2.call(StandardTitanGraph.java:248)
```

This seems to fail on this conditional check : `Preconditions.checkArgument(del.isRemoved());`

For some reason the edge is not marked as removed, 

I suspect this has something to do with transactions since as a workaround reloading the edge before marking for removal fixes the problem.

(I use 0.4.4)

 Clues?

Thanks.

**Comment by mbroecheler** [comment]
Can you send the code block that triggers this exception and the full stack
trace? Thank you

**Comment by mbroecheler** [comment]
I wasn't able to reproduce this. I am thinking that it might have to do with stale edges based on the description but that didn't reproduce this either. If anybody is seeing this, please report a full stack trace and (ideally) code to reproduce. Thanks.
