### ISSUE TITLE
Extending data types constraints

### ISSUE THREAD

**Issue by asaf** [thinkaurelius/titan#715]
Hey,

How Titan handles other constraints but unique ? such length, min/max, regexp, etc?

I currently have in mind the following approach:

Wrap Titan with pre-commit Tinkerpops's EventGraph wrapper and validate entity during commit: This is annoying because I'd like the failure to occur during the e/v.setProperty and not during the commit phase.

Is there a better approach extending properties constraints ? if not, is there anything planned?

Thanks.

**Comment by mbroecheler** [comment]
Hi Asaf,

I don't see us pushing custom validation logic into the Titan graph.
Rather, this should be accomplished by a wrapper similar to the eventgraph
you mentioned. In fact, this is going to get a lot easier with the graph
strategies approach of tinkerpop 3. @spmallette can comment more
intelligently on that, but basically it will allow you to inject light
weight wrappers.

**Comment by asaf** [comment]
@mbroecheler thanks!

@spmallette In Tinker, we have EventGraph that fire events after commits, we need such an EventGraph that fires events before commit so we can perform validations rules and rollback if some constraints are violated,
It even makes more sense to have an ValidatedGraph type with support of constraints to any usage that need some validation rules before committing data to the underline.
