### ISSUE TITLE
Kryo buffer size

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#716]
Make the Kryo buffer size configurable. Once you hit the current [hard limit of 10 MB](https://github.com/thinkaurelius/titan/blob/0.5.0/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/database/serialize/kryo/KryoSerializer.java#L26), there seems to be no way to get around it.

**Comment by dalaro** [comment]
89a77c18377c9cef6f51ab621a31c22c10ff715f exposes this specifically for Faunus.  I think the origin of this ticket was an unusually large titan-to-faunus ID hashmap emitted by Faunus's TitanGraphOutput, which would not affect TitanGraph.  We can also expose this in TitanGraph if necessary, but I haven't done that yet.  Please reopen if we need this in TitanGraph too.
