### ISSUE TITLE
Wrong property used in sample configuration

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#718]
`script-input.properties` sets:

``` properties
titan.hadoop.input.edge-copy-direction=OUT
```

Should be:

``` properties
titan.hadoop.input.edge-copy-dir=OUT
```

**Comment by okram** [comment]
Ugh. It should be 'direction' in the code. dir is not obvious.

**Comment by dalaro** [comment]
I added edge-copy-direction.  edge-copy-dir is retained and used in the absence of edge-copy-direction, but it's marked deprecated in the code (and the documentation: http://s3.thinkaurelius.com/docs/titan/0.5.1-SNAPSHOT/hadoop-config-ref.html#_titan_hadoop_input).

I found no grep hits for edge-copy-dir in `docs/faunus`, `titan-hadoop-parent/*/src/*`, or `titan-dist/src/`  -- just for -direction -- so I left the docs and test and distribution config files alone.
