### ISSUE TITLE
Titan 0.5 on Windows with cygwin

### ISSUE THREAD

**Issue by stephtr** [thinkaurelius/titan#719]
Starting Titan 0.5 with cygwin on Windows fails:

$ bin/titan.sh start -v
Starting Cassandra...
Error opening zip file or JAR manifest missing : /cygdrive/d/Programme/Titan/lib/jamm-0.2.5.jar

Error occurred during initialization of VM
agent library failed to init: Instrument

conf/cassandra-env.sh (JVM_OPTS="$JVM_OPTS -javaagent:$CASSANDRA_HOME/lib/jamm-0.2.5.jar") should be modified, the javaagent-file has to be given in Windows file-syntax (and not /cygdrive/...).

"titan.sh stop" also fails, if the path of Java contains a space (for example in C:\Program Files...), titan.sh's JPS should be modified to quote the command (for example local p=`"$JPS" -l | grep "$2" | awk '{print $1}'` instead of local p=`$JPS ...).

**Comment by dalaro** [comment]
Hi @stephtr, thanks for reporting.  A pull request would be welcome if you can submit one.

**Comment by ghost** [comment]
I recommend we close this.  Dan requested a pull request if possible and none was provided.  This cannot be that important after 482 days ?
