### ISSUE TITLE
Refactor diskstorage package

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#72]
There seems to be repeated code in the diskstorage implementations for Cassandra.
1. Centralize configuration options and default values
2. Code de-duplication by using shared abstract classes, etc

**Comment by dalaro** [comment]
I've been neglecting this for a while.  Please note that this is not limited to Cassandra.  Refactoring should also consider HBase.

A specific example: containsKeyColumn() is implemented identically in terms of get() on all of the backends.  Self-referencing OrderedKeyColumnValueStore method implementations like this one naturally form an abstract base class that could be useful for anyone implementing against a new store, even if we gradually specialize/optimize it out of the core backends.  A few of the backends also (not including HBase) still implement mutate() with a call to mutateMany().

**Comment by mbroecheler** [comment]
Major refactoring of diskstorage package has been completed in "storage" branch
