### ISSUE TITLE
ElasticSearchIndex fails to load elasticsearch.yml file

### ISSUE THREAD

**Issue by randall-sosacorp** [thinkaurelius/titan#720]
##### Brief Description

When attempting to configure Titan to read an Elasticsearch yaml configuration file while running in local mode, the settings defined in the yaml file never take effect.  Example configuration setting: `index.search.conf-file=/etc/elasticsearch/elasticsearch.yml`.  Within this configuration file, there is the following setting: `index.store.type=memory`.  This is ignored, and Elasticsearch writes to the files system.
##### Expected

Pointing Titan to the path where an Elasticsearch configuration file may be located will allow settings therein to take effect.
##### Actual

The path descriptor is treated as the content body of the configuration file.
##### Discovered Version

0.5.0
##### Detailed description

In ElasticSearchIndex.java, the YAML file is loaded on line 4 with the following block of code:

```
if (config.has(INDEX_CONF_FILE)) {
    String configFile = config.get(INDEX_CONF_FILE);
    log.debug("Configuring ES from YML file [{}]", configFile);
    Settings settings = ImmutableSettings.settingsBuilder().loadFromSource(configFile).build();
    builder.settings(settings);
} 
```

This code should invoke `ImmutableSettings.settingsBuilder().loadFromStream()` instead.  This should, in turn, invoke `SettingsLoaderFactory.loaderFromResource()` rather than `loaderFromSource()`.  Note the difference in that class:

```
    /**
     * Returns a {@link SettingsLoader} based on the resource name.
     */
    public static SettingsLoader loaderFromResource(String resourceName) {
        if (resourceName.endsWith(".json")) {
            return new JsonSettingsLoader();
        } else if (resourceName.endsWith(".yml") || resourceName.endsWith(".yaml")) {
            return new YamlSettingsLoader();
        } else if (resourceName.endsWith(".properties")) {
            return new PropertiesSettingsLoader();
        } else {
            // lets default to the json one
            return new JsonSettingsLoader();
        }
    }

    /**
     * Returns a {@link SettingsLoader} based on the actual settings source.
     */
    public static SettingsLoader loaderFromSource(String source) {
        if (source.indexOf('{') != -1 && source.indexOf('}') != -1) {
            return new JsonSettingsLoader();
        }
        if (source.indexOf(':') != -1) {
            return new YamlSettingsLoader();
        }
        return new PropertiesSettingsLoader();
    }
```

**Comment by randall-sosacorp** [comment]
Present work-around is to load the body of the desired configuration settings in titan.properties: `index.search.conf-file={ "index.store.type" : "memory" }`.

**Comment by dalaro** [comment]
You're right on the whole line, including the fix and current workaround.  This is a beautiful bug report.

If we were following the letter of the semver.org law, we should probably deprecate conf-file and introduce a new option that loads a stream to avoid breaking compatibility with 0.5.0, but the idea that `index.search.conf-file` under ES actually accepts a string literal instead of a file path is so insane that I don't think it's worth tolerating for the rest of the patch series.

**Comment by randall-sosacorp** [comment]
Thanks, Dan.

**Comment by dalaro** [comment]
`conf-file` now uses `loadFromResource` in titan05 HEAD.

**Comment by randall-sosacorp** [comment]
Thank you, Dan.
