### ISSUE TITLE
Clarification of Chapter 29 in 0.5.0 docs

### ISSUE THREAD

**Issue by mindade** [thinkaurelius/titan#721]
I just saw the documentation on graph partitioning in the new 0.5.0 docs (Chapter 29). The terminology is a little inconsistent, so I'm not sure how this is applied. 
I assume that this only applies if you have multiple 'storage.backend' statements in the configuration file? Is this correct?
The reason I ask is that our setup is having one storage backend (cassandra) and several front end Titan instances serving requests. We are not using Rexster, but are using Akka/Spray to serve our custom http requests. In this scenario, I don't have to worry about communication between the titan front end nodes, do I?
FYI, our preliminary numbers using Akka to serve requests is impressive. I'll post some numbers once we go into production.

**Comment by mindade** [comment]
I think I understand what this refers to now. The backend instances refer to the number of  instances in my cassandra cluster. So if I want to group graph items in a particular way on cassandra, these clustering parameters give me that option. Very nice. Thanks.

**Comment by mbroecheler** [comment]
Correct. In case anybody else reads this: Titan does not support multiple
storage backends in a single deployment. There is always only one primary
storage backend but there can be multiple indexing backends.
