### ISSUE TITLE
Query optimizer questions

### ISSUE THREAD

**Issue by mindade** [thinkaurelius/titan#724]
I'm trying to get a feel for how the query optimizer works in 0.5.0. Suppose I have a graph query:

g.V.has("owner","xx").has("color","blue")

Say I have 'owner' and 'color'. How will the optimizer choose which property to execute first? Is it different if I use an external search index?

I could do an indexQuery like (owner:xx AND color:blue). Does the query optimizer make this reduction?

Can (or do) the composite indexes make similar optimizations, or are they limited to single term queries?

**Comment by spmallette** [comment]
The issue tracker really isn't for "questions" on usage.  You asked it in the right place already:

https://groups.google.com/forum/#!topic/aureliusgraphs/ZWDk0rLESY0

**Comment by mindade** [comment]
Sorry, sometimes I don't get a response on the forum, but do here.

**Comment by spmallette** [comment]
I copy and paste this from a reply I once wrote to someone on our mailing list: 

> We do our best to answer everyone's questions.  Each of us has different styles for contributing to the mailing list and some of us are better suited to answer certain questions than others.  For instance, I tend to answer questions related to TinkerPop tech and usually do so as those questions come in, especially when they don't involve any research.  If they do require me to try to recreate a problem, then it might have to wait until my time is free to do so.   Others at Aurelius tend to answer questions in bulk - set aside one day a week to mash through all the pending questions that were best suited them that have gone unanswered.  We even have someone keeping track of questions that haven't been answered each week, so that things don't slip through the cracks.  We, of course, also love when the community can step in to help us answer questions, because after all, this is free software that we make available to you without much to ask for in return and any support from those out there with Titan experience is greatly and deeply appreciated.
> 
> All that said, please be patient and we will get around to your question.  If you need more immediate assistance, I'm sure that if you email info@thinkaurelius.com you will get a prompt reply to discuss options for dedicated help.

I hope that helps clarify why you might not always get an immediate response on the mailing list.

**Comment by mindade** [comment]
Ok, thanks. I do think your support is outstanding.
