### ISSUE TITLE
ES cluster name setting

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#725]
Setting `index.search.elasticsearch.cluster-name` doesn't seem to work as expected. Multiple people reported that ES wasn't recognized by Titan when the cluster name was explicitly set; removing the setting always solved the problem.

Can't tell much more about it, since I haven't found the time to reproduce it locally yet.

**Comment by dalaro** [comment]
Omitting `cluster-name` automatically set Elasticsearch's `client.transport.ignore_cluster_name` option.  Maybe setting `cluster-name` reveals some preexisting problem with cluster name validation in those configurations?

**Comment by dalaro** [comment]
Closing this until we can reproduce it.
