### ISSUE TITLE
Deleting a non-existent vertex ID returns 500 with null error/message

### ISSUE THREAD

**Issue by BryanDonovan** [thinkaurelius/titan#728]
This is another bug where I'm not sure if it's Rexster or Titan, but if you try to delete a non-existent but valid vertex ID, the response is a 500 (which might make sense, but should probably be 404), and the error response is:

```
{"message":null,"error":null}
```

E.g.,

```
$ curl -v -XDELETE "localhost:8182/graphs/graph/vertices/2560512" -H "accept: application/json"
* Adding handle: conn: 0x7f88e2004000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7f88e2004000) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8182 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8182 (#0)
> DELETE /graphs/graph/vertices/2560512 HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8182
> accept: application/json
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json;charset=UTF-8
* Server grizzly/2.2.16 is not blacklisted
< server: grizzly/2.2.16
< Access-Control-Allow-Origin: *
< Date: Mon, 25 Aug 2014 18:50:36 GMT
< Connection: close
< Transfer-Encoding: chunked
<
* Closing connection 0
{"message":null,"error":null}
```

**Comment by BryanDonovan** [comment]
p.s., I see this in the rexstitan.log file when this error occurs:

```
6816371 [Grizzly(7)] INFO  com.tinkerpop.rexster.VertexResource  - Vertex with [2560512] cannot be found.
6816371 [Grizzly(7)] ERROR com.tinkerpop.rexster.VertexResource  - javax.ws.rs.WebApplicationException
```

**Comment by mbroecheler** [comment]
Is that vertex actually in the graph or might it have been deleted concurrently?

**Comment by BryanDonovan** [comment]
It's not in the graph.  I was testing what response I could expect when we attempt to delete a non-existent vertex ID.

**Comment by BryanDonovan** [comment]
My test case is essentially:
1. Create a vertex
2. Delete the vertex
3. Try to delete the same vertex again
   ... response is a 500: {"message":null,"error":null}

**Comment by dalaro** [comment]
This one is a Rexster issue.  Some over-broad catch clauses are intercepting `WebApplicationException` instances that would otherwise propagate 404s here and turning them into 500s.  Opened Rexster PR linked above.
