### ISSUE TITLE
Incremental loading in Titan/Hadoop 0.5.0+

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#729]
In Faunus we've had [Incremental Data Loading using a TitanOutputFormat](https://github.com/thinkaurelius/faunus/wiki/Titan-Format#incremental-data-loading-using-a-titanoutputformat). It seems like we've either lost this feature in 0.5.0 or it's not documented in the [Hadoop](http://s3.thinkaurelius.com/docs/titan/0.5.0/hadoop.html) section of the docs.

**Comment by dalaro** [comment]
Took a shot at reimplementing this in bf39926f3f10ad8aacb16971d545c8595894e88c

**Comment by dalaro** [comment]
Daniel and I did some manual tire-kicking to complement the automated tests introduced along with the feature in bf39926f3f10ad8aacb16971d545c8595894e88c.  I'll update the docs in titan05 and then close this issue.

**Comment by dalaro** [comment]
Updated docs in fc65db3470d27cf53297922ef9a3e1ddb15f9446 and again in f6e44efd078981d8390d56b278318e4f83cc5046.

@dkuppitz also pointed out that the zipfile's example script was outdated; this was separately addressed in #774.
