### ISSUE TITLE
Reserved names for vertex labels

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#730]
"vertex", "element", "edge", "property", "label" should be reserved names for vertex labels, edge labels, and property keys.

**Comment by mbroecheler** [comment]
Related to #634. Needs to be revisited for the 1.0 release since this would be a backwards incompatible change.

**Comment by dalaro** [comment]
I've reserved all of the above words except "label".  That's used by a test in TP 3.0.0-incubating, but it has apparently been fixed in apache/incubator-tinkerpop@fa994d3304a885bc52725e2890e53b2a1186c92b.
