### ISSUE TITLE
Proper graph shutdown

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#734]
If a graph is not properly shut down, a background thread should do so. I believe this was supported in 0.4.

**Comment by dalaro** [comment]
I reproduced this somewhat inconsistently in testing with embeddedcassandra.  The shutdown hook ran each time, but it seemed to only kill a subset of the Cassandra daemon's threads.  Cassandra has a seemingly thorough shutdown hook, but the hook logic does not seem to be exposed through a callable public method.  In c958ad2a2bafd305a33655347fef17138ee75088, I modified gremlin.sh's Console main class to explicitly call `System.exit` just before returning from main and removed the hook I previously setup in CassandraDaemonWrapper that did an inconsistent job of killing the necessary threads.
