### ISSUE TITLE
Outdated config elements in GraphOfTheGodsFactory.create

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#740]
https://github.com/thinkaurelius/titan/blob/0.5.0/titan-core/src/main/java/com/thinkaurelius/titan/example/GraphOfTheGodsFactory.java#L28-L40

Running `g = TitanFactory.open('path/to/cfg'); GraphOfTheGodsFactory.load(g)` is the workaround.

**Comment by tomersagi** [comment]
Could you give an example of TitanFactory.open('path/to/cfg')?
the following returned an error:

> gremlin> g = TitanFactory.open('../conf/titan-berkeleydb.properties'); GraphOfTheGodsFactory.load(g)
> Backend shorthand unknown: ../conf/titan-berkeleydb.properties

**Comment by dalaro** [comment]
Try this:
1. unzip titan 0.5.0's zipfile
2. cd into the titan-0.5.0-hadoop1 or -hadoop2 directory (according to whichever version you downloaded and unzipped)
3. run `bin/gremlin.sh`
4. type at the gremlin prompt as follows (assuming the path separator char on your platform is `/`):

```
gremlin> g = TitanFactory.open('conf/titan-berkeleydb-es.properties')
==>titangraph[berkeleyje:/home/dalaro/tinkerelius/titan-0.5.0-hadoop2/conf/../db/berkeley]
gremlin> GraphOfTheGodsFactory.load(g)
==>null
gremlin> g.V.map
03:39:16 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>{name=saturn, age=10000}
==>{name=sky}
==>{name=sea}
==>{name=jupiter, age=5000}
==>{name=neptune, age=4500}
==>{name=hercules, age=30}
==>{name=alcmene, age=45}
==>{name=pluto, age=4000}
==>{name=nemean}
==>{name=hydra}
==>{name=cerberus}
==>{name=tartarus}
gremlin>
```

The `titan-berkeleydb.properties` file that ships with Titan is not useful for GotG because it only configures a storage backend without an index.  Note that I used `titan-berkeleydb-es.properties` above, which does configure an index.

**Comment by tomersagi** [comment]
Great, works fine now. 
Thanks

**Comment by ccoffey** [comment]
The _Configuring Rexster to use Titan_ [tutorial](https://github.com/thinkaurelius/titan/wiki/Rexster-Graph-Server) states "PREREQUISITE: These instructions assume that a graph has been created in Titan as described in the “Loading Data Into Titan” section of the Getting Started page."

If we are no longer suppose to execute 
g = GraphOfTheGodsFactory.create('/tmp/titan')

then what do I specify in rexster.xml for the element <graph-location>/tmp/titan</graph-location>

Because at the moment I am seeing Error: Could not get the list of graphs from Rexster when I navigate to http://localhost:8182/doghouse/main/graph

**Comment by spmallette** [comment]
@ccoffey you still point it at the directory you created the graph in.  if you followed the workaround instructions @dalaro provided as:

``` text
gremlin> g = TitanFactory.open('conf/titan-berkeleydb-es.properties')
==>titangraph[berkeleyje:/home/dalaro/tinkerelius/titan-0.5.0-hadoop2/conf/../db/berkeley]
gremlin> GraphOfTheGodsFactory.load(g)
==>null
```

Then you would set it to: `/home/dalaro/tinkerelius/titan-0.5.0-hadoop2/conf/../db/berkeley`
