### ISSUE TITLE
g.getManagementSystem() fails

### ISSUE THREAD

**Issue by tomersagi** [thinkaurelius/titan#746]
Hi,
I built titan from source today using maven on an Ubuntu machine. 
I copied the [recommended configuration](http://s3.thinkaurelius.com/docs/titan/0.5.0/configuration.html) for a standalone Berkeley DB based instance to a properties file (myp.properties) and then ran the following:

> gremlin>g = TitanFactory.open('../tomer.properties')
> gremlin>mgmt = g.getManagementSystem()
> No signature of method: groovy.lang.MissingMethodException.getManagementSystem() is applicable for argument types: () values: []
> Display stack trace? [yN]

What did I do wrong?
Thanks
Tomer

**Comment by rjbriody** [comment]
Is it possible that you accidentally built the 0.4.4 branch? The method you
are calling appeared in 0.5.0.

Bob

**Comment by tomersagi** [comment]
I cloned the master branch from here https://github.com/thinkaurelius/titan is it 0.4.4 or 0.5?

**Comment by dkuppitz** [comment]
The master branch contains the 0.4 sources. Titan 0.5 development is done in the [titan05](https://github.com/thinkaurelius/titan/tree/titan05) branch.

**Comment by rjbriody** [comment]
That is 0.4.x. If you want the 0.5.x branch then run "git checkout titan05"
to switch branches.

Downloads for 0.5.0 are also available here:
https://github.com/thinkaurelius/titan/wiki/Downloads

Bob

**Comment by tomersagi** [comment]
o.k. thanks
