### ISSUE TITLE
CassandraTransaction uses write consistency option for read consistency

### ISSUE THREAD

**Issue by ksenji** [thinkaurelius/titan#747]
public CassandraTransaction(BaseTransactionConfig c) {
        super(c);
        read =  CLevel.parse(getConfiguration().getCustomOption(CASSANDRA_WRITE_CONSISTENCY));
        write = CLevel.parse(getConfiguration().getCustomOption(CASSANDRA_WRITE_CONSISTENCY));
        log.debug("Created {}", this.toString());
    }

**Comment by dalaro** [comment]
Thanks @ksenji!  Commented in and merged #748.
