### ISSUE TITLE
How do you open an existing graph

### ISSUE THREAD

**Issue by tomersagi** [thinkaurelius/titan#752]
Hi,
I scoured the documentation and couldn't understand how to open an existing graph. 
Test case:
1. I created the GraphOfTheGods graph example according to the instructions and do some examples from the manual. 
2. I went home and came back the next day. 
3. How do I get g initialized to the same graph I created yesterday?
Thanks

**Comment by dkuppitz** [comment]
Please use our [mailing list](https://groups.google.com/forum/#!forum/aureliusgraphs) (and its search function) for those kind of questions.
