### ISSUE TITLE
gremlin query vertex by vertex label

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#755]
I defined an unique key 'bloggerId' index only in vertex label 'blogger'

when I query by bloggerId ,is correct
gremlin>g.V.has('bloggerId','tw1004449045').map
==>{favouritesCountHis=[0, 0], platform=twitter, friendsCount=13, favouritesCount=0, statusesCountHis=[22, 22], createdOn=1410504303159, vip=false, nickName=bernardo padilha, bloggerName=bernardopadilh1, createdAt=1355245535000, names=[bernardo padilha], mutualFriendCountHis=[0, 0], bloggerId=tw1004449045, gender=UNKNOWN, followersCount=4, language=pt, friendsCountHis=[13, 13], statusesCount=22, mutualFriendCount=0, followersCountHis=[4, 4]}

But when query by bloggerId and vertex label::
gremlin> g.V.has('bloggerId','tw1004449045').has('label','blogger');
==>com.thinkaurelius.titan.graphdb.vertices.CacheVertex cannot be cast to com.tinkerpop.blueprints.Edge

**Comment by dkuppitz** [comment]
It doesn't work yet in TP2, but will work with TP3 (Titan 0.9 / next release). Currently you can do this:

``` groovy
g.query().has('label','blogger').has('bloggerId','tw1004449045').vertices()
```

**Comment by boliza** [comment]
Thank you @dkuppitz

**Comment by nastacio** [comment]
In TP3

g.V().hasLabel('blogger').has('bloggerId', 'tw1004449045')
