### ISSUE TITLE
Support automatic reindexing for Berkeley DB

### ISSUE THREAD

**Issue by mjhallman** [thinkaurelius/titan#756]
There is currently only support for automatic reindexing of Cassandra and HBase. Reindexing for Berkeley DB is currently a manual process, and could be much easier.

**Comment by asaf** [comment]
+1

**Comment by mbroecheler** [comment]
This should fall out of the work we have been doing to generalize GraphComputer. No additional work necessary - just verify and close when done.

**Comment by dalaro** [comment]
This does fall out of StandardScannerExecutor more or less for free.  There doesn't seem to be a really tidy API for this though.  It doesn't fit naturally in FulgoraGraphComputer and it would complicate `submit` anyway.  I created a new IndexJobs helper class in the [issue_756](/thinkaurelius/titan/tree/issue_756) branch.  Did some ad-hoc testing with BDB in gremlin.sh just to check that creating an index post-data and reindexing made the fullscan warnings disappear.  Still needs an automated unit test and asciidoc snippet.

**Comment by dalaro** [comment]
The issue_756 branch is unnecessary.  `ManagementSystem.updateIndex(..., REINDEX)` already does the right thing:

```
g = TitanFactory.open('conf/titan-berkeleyje.properties')
stream = new FileInputStream('data/tinkerpop-modern.gio')
reader = KryoReader.build().create()
reader.readGraph(stream, g)
g.tx().commit()

g.V().has('name', 'lop')
g.tx().rollback()

m = g.openManagement()
m.buildIndex('names', Vertex.class).addKey(m.getPropertyKey('name')).buildCompositeIndex()
m.commit()
g.tx().commit()

com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.awaitGraphIndexStatus(g, 'names').status(SchemaStatus.REGISTERED).call()

m = g.openManagement()
i = m.getGraphIndex('names')
m.updateIndex(i, SchemaAction.REINDEX)
m.commit()

com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.awaitGraphIndexStatus(g, 'names').status(SchemaStatus.ENABLED).call()

g.V().has('name', 'lop')
g.tx().rollback()
```

Tested that with BDB and the output was as expected (warning about fullscan on the first query, reindex runs and index converges on enabled, no warning about fullscan on second query).

Now I'll just document this.

**Comment by dalaro** [comment]
This is documented by the linked commit just above.

Here's an updated copy of the snapshot docs with the new section: http://s3.thinkaurelius.com/docs/titan/0.9.0-SNAPSHOT/index-admin.html#_executing_a_reindex_job_on_titanmanagement

**Comment by gtiwari2015** [comment]
Hi ,

I am trying implement reindex in our Instance that we created using Titan DB 0 .5.4 with Berkeley DB . We have data loaded in our DB and now we have put the index on once column .When trying to use the above code For reindexing  , i am getting Exception java.lang.IllegalArgumentException: Update action [REINDEX] does not apply to any fields for index  ..Please let me know will the above code  work in 0.5.4 version ? and how to achieve Reindexing with titan 0.5.4 with Berkeley DB
