### ISSUE TITLE
Changing external index properties

### ISSUE THREAD

**Issue by asaf** [thinkaurelius/titan#758]
Hey,

I'm aware of the 'index cannot be dropped' limitation but hopefully there is some workaround,

Assuming I have a mixed index built using Lucene, I'd like to enhance the index with extra properties (less priority remove some),

Is there a way to do that?

As a workaround I thought of creating a new index and increment its "version" by adding some postfix to its name and then perform re-indexing process, but this very annoys me as the amount of the deprecated indices grow every time and they have no reason to live any longer.

If this is the only suggested option then close this issue.

Thanks.

**Comment by mbroecheler** [comment]
Yes, there is a methid in TitanManagement to do just that. It allows you to
add an individual key to an existing index. If the key you are adding is
newly defined in the transaction, then you don't have to do anything else.
If the key already existed you have to follow the reindexing steps and
enable the key.

**Comment by asaf** [comment]
Ahh! I guess it's the `addIndexKey`, my eyes skipped it for some reason, closing.
