### ISSUE TITLE
Resource leak in the Lucene connector

### ISSUE THREAD

**Issue by fechtner** [thinkaurelius/titan#761]
Hello, 
I've noticed problems during working with Lucene indexing in Titan, more precisely in using artifact titan-lucene 0.4.4. The problem was with closing database and indexes, the index files are still held by the application and cannot be deleted. 

I think that IndexReader (init in the line 148) in the method mutate in the class LuceneIndex (https://github.com/thinkaurelius/titan/blob/master/titan-lucene/src/main/java/com/thinkaurelius/titan/diskstorage/lucene/LuceneIndex.java) should be closed, but it is not. 

In my opinion the whole body of top for-cycle in the method mutate should be surrounded by try with finally containing closing this reader.
Tom

**Comment by dalaro** [comment]
I'll cherry-pick this back to master (0.4.5-SNAPSHOT)
