### ISSUE TITLE
support many word analyzer 

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#763]
in some situation,we should use different analyzer for different string field.

**Comment by mbroecheler** [comment]
Can you elaborate on what you mean? Could this be achieved by modifying the analyzer directly in ES?

**Comment by boliza** [comment]
my es schema like this.
yrp: {
index: not_analyzed
type: string
}
vlx: {
analyzer: whitespace
type: string
}
kjp: {
analyzer: jieba
type: string
}
It can update the schema using es api after titan create the schema.

**Comment by boliza** [comment]
@mbroecheler this issue should close,it seems the same with #933
