### ISSUE TITLE
In memory storage backend 

### ISSUE THREAD

**Issue by sebastiaansamyn-tc** [thinkaurelius/titan#773]
Hi,

Does titan have a purely in memory storage backend? If not, is this something that's planned for the future?

This could be very useful for unit testing.

Thanks!
Sebastiaan Samyn

**Comment by jbmusso** [comment]
Hi Sebastiaan,

Titan dropped support for Persistit "due to lack of continued development", though this may change in the future [as was discussed recently in the mailing list](https://groups.google.com/d/topic/aureliusgraphs/Nq91hOw8CPE/discussion).

**Comment by rjbriody** [comment]
You might also find this post interesting
http://thinkaurelius.com/2013/11/24/boutique-graph-data-with-titan/

**Comment by sebastiaansamyn-tc** [comment]
Indeed.

The reason I was asking is that we initialize a new db for every test that we run (that requires a connection to our titan db). This way we ensure that tests don't interfere via unintended db state that sticks around. 

The big downside to this approach is that BerkeleyDB takes its time to initialize a fresh db and it's considerably slowing down full runs of our test sets. I'm guessing the disk access is playing quite a big role in this, so I was thinking that an in-memory backend could potentially be much faster.

Thanks for the quick feedback!

**Comment by rjbriody** [comment]
Ah, "For testing only"!

2 things come to mind:
- Does embedded Cassandra go faster than BerkeleyDB?
- I wonder if it would it be possible to wire up a mock backend -
  something like cassandra-unit
  https://github.com/jsevellec/cassandra-unit (disclaimer: I have never
  used cassandra-unit and have no idea if it is reliable).

These are just random ideas. Someone else might have suggestions related to
testing that are actually useful.

Bob

**Comment by mbroecheler** [comment]
Titan does come with an in-memory backend for testing only. Just specify
the backend name as "inmemory".

On Thu, Oct 2, 2014 at 9:15 AM, bobb notifications@github.com wrote:

> Ah, "For testing only"!
> 
> 2 things come to mind:
> - Does embedded Cassandra go faster than BerkeleyDB?
> - I wonder if it would it be possible to wire up a mock backend -
>   something like cassandra-unit
>   https://github.com/jsevellec/cassandra-unit (disclaimer: I have never
>   used cassandra-unit and have no idea if it is reliable).
> 
> These are just random ideas. Someone else might have suggestions related
> to
> testing that are actually useful.
> 
> Bob
> 
> On Thu, Oct 2, 2014 at 11:56 AM, sebastiaansamyn-tc <
> notifications@github.com> wrote:
> 
> > Indeed.
> > 
> > The reason I was asking is that we initialize a new db for every test
> > that
> > we run (that requires a connection to our titan db). This way we ensure
> > that tests don't interfere via unintended db state that sticks around.
> > 
> > The big downside to this approach is that BerkeleyDB takes its time to
> > initialize a fresh db and it's considerably slowing down full runs of
> > our
> > test sets. I'm guessing the disk access is playing quite a big role in
> > this, so I was thinking that an in-memory backend could potentially be
> > much
> > faster.
> > 
> > Thanks for the quick feedback!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/thinkaurelius/titan/issues/773#issuecomment-57651978.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/773#issuecomment-57654796.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by espeed** [comment]
OpenHFT'S recent release of Chronicle Map might make an interesting memory
and/or memory grid backend for Titan.

http://openhft.net

**Comment by sebastiaansamyn-tc** [comment]
@mbroecheler thanks that's exactly what I needed!
Is that documented somewhere? I've already spent many hours reading titan docs and have never come across this before.

@espeed Wasn't there a hazelcast backend in 0.4? Why was it removed?

Many Thanks!

**Comment by mbroecheler** [comment]
On Thu, Oct 2, 2014 at 11:26 PM, sebastiaansamyn-tc <
notifications@github.com> wrote:

> @mbroecheler https://github.com/mbroecheler thanks that's exactly what
> I needed!
> Is that documented somewhere? I've already spent many hours reading titan
> docs and have never come across this before.
> 
> https://github.com/espeed
> 
> No, I just added the documentation on this.
> 
> @espeed https://github.com/espeed Wasn't there a hazelcast backend in
> 0.4? Why was it removed?
> 
> The problem with cache based Titan storage backends is that they don't
> scale well with high degree vertices. We experimented around a lot with
> those and got some feedback from the community and ultimately decided that
> it wasn't worth pursuing further.
> 
> Many Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/773#issuecomment-57760585.

## 

Matthias Broecheler
http://www.matthiasb.com
