### ISSUE TITLE
Is the db-cache working?

### ISSUE THREAD

**Issue by mbbeaubi** [thinkaurelius/titan#775]
Hi,

I've been doing some performance testing of Titan to evaluate it for a potential application. I'm testing with both berekley and remote cassandra as storage backends with a single titan instance running in rexster communicating with the backend.

I see no difference in memory usage in the Titan process with db-cache enabled or disabled. I'm also not seeing any significant performance difference. For instance, fetching a vertex and all linked vertices might take 200ms with a warm cache with cassandra backend. If I shutdown the titan instance (so the caches are cleared), but leave the cassandra cluster up, it still takes ~200ms when I try immediately after I restart Titan.

Here's the settings I use when I enable the cache:
<cache.db-cache>true</cache.db-cache>
<cache.db-cache-size>.5</cache.db-cache-size>
<cache.db-cache-time>0</cache.db-cache-time>

I apologize if I'm wrong about this or if I'm not understanding something, but if you could please look into it and confirm the cache is working I'd appreciate it.

Thanks,
Mike

**Comment by rjbriody** [comment]
Maybe the duration of vertex retrieval is lost in the noise relative to
other operations that occur when processing a request. For example, script
evaluation can take a long time. (This is the part where your groovy code
is parsed into executable operation.) Are you using a cached/parameterized
script? If not, try that out.

Bob

**Comment by mbroecheler** [comment]
Hi,
that is very surprising. You should see a very big difference with caching
enabled. Can you measure the time for your query in 3 different scenarios
on the gremlin shell:
1) after starting the graph
2) after starting a new transaction
3) within the same transaction

Thanks,
Matthias

On Mon, Oct 6, 2014 at 5:34 PM, mbbeaubi notifications@github.com wrote:

> Hi,
> 
> I've been doing some performance testing of Titan to evaluate it for a
> potential application. I'm testing with both berekley and remote cassandra
> as storage backends with a single titan instance running in rexster
> communicating with the backend.
> 
> I see no difference in memory usage in the Titan process with db-cache
> enabled or disabled. I'm also not seeing any significant performance
> difference. For instance, fetching a vertex and all linked vertices might
> take 200ms with a warm cache with cassandra backend. If I shutdown the
> titan instance (so the caches are cleared), but leave the cassandra cluster
> up, it still takes ~200ms when I try immediately after I restart Titan.
> 
> Here's the settings I use when I enable the cache:
> true
> .5
> 0
> 
> I apologize if I'm wrong about this or if I'm not understanding something,
> but if you could please look into it and confirm the cache is working I'd
> appreciate it.
> 
> Thanks,
> Mike
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/775.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbbeaubi** [comment]
Hi,

I'm fairly confident that the db-cache isn't working at this point. I didn't use the gremlin shell as I'm unsure how I can get accurate timings with that, but here's my simple test code:

---

private static final String uuid = "DB_1://TABLE_";

```
public static void main(String[] args) throws Exception {
    long initialTime = 0;
    long cachedTime = 0;
    TitanGraph graph = TitanConnection.INSTANCE.g();
    for (int i=0; i<100; ++i) {
        long start = System.currentTimeMillis();
        for (Vertex v : graph.getVertices(TitanConstants.PROP_OBJECT_ID, uuid + i)) {
            System.out.println(v.getId());
        }
        long end = System.currentTimeMillis();
        initialTime += end - start;

        graph.commit();

        start = System.currentTimeMillis();
        for (Vertex v : graph.getVertices(TitanConstants.PROP_OBJECT_ID, uuid + i)) {
            System.out.println(v.getId());
        }
        end = System.currentTimeMillis();
        cachedTime += end - start;
    }

    System.out.println("Initial time = " + initialTime);
    System.out.println("Cached time = " + cachedTime);

    TitanConnection.INSTANCE.g().shutdown();
}
```

---

TitanConnection is just a helper I wrote to create the graph connection. Here's the settings I'm using:

storage.backend=cassandra
storage.hostname=10.21.42.92,10.21.42.101,10.21.42.87,10.21.42.83,10.21.42.80
storage.transactions=false
storage.batch-loading=true

storage.cassandra.keyspace=titan_cassandra_eic_mikepc
storage.cassandra.read-consistency-level=QUORUM
storage.cassandra.replication-factor=3
storage.cassandra.write-consistency-level=QUORUM

cache.db-cache=true
cache.db-cache-size=.5
cache.db-cache-time=0

query.fast-property=true
query.force-index=true

index.search.backend=lucene
index.search.directory=E:/titan/idx_search

cluster.max-partitions=64
cluster.partition=false

---

The id property is indexed. Basically, I'm looking up an object by my application's id, then looking it up again. I do 100 different objects, here's my timings:

Initial time = 612
Cached time = 592

Good news is, the tx cache seems to work, if I remove the commit, here's the timings I see:
Initial time = 701
Cached time = 28

If db cache was working, I would expect to see a similar time to when I hit in the tx cache.

Thanks,
Mike

**Comment by espeed** [comment]
With only 100 objects, it's likely the objects are already in memory, cached in other places by the OS, etc, so the secondary cache might not make much difference. 

Also, as Bob pointed out, there is a lot of noise in your timing procedure, e.g. you're including the time it takes to iterate over each item and print the response. The time it takes to execute these additional operations may dwarf the time it takes for Titan to return the response, cache or no cache. 

Use the Titan Metrics utitily to get more precise readings: https://github.com/thinkaurelius/titan/wiki/Titan-Performance-and-Monitoring

**Comment by mbbeaubi** [comment]
Hi,

I think I'm not understanding how the db-cache works. I have Titan running on my box, I have Cassandra running in a remote cluster. I'm assuming that if something is cached in the db-cache, there should be no communication with the cassandra cluster to fetch that object, even if it an index look up?

BTW, here are the numbers with the prints turned off
db-cache:
Initial time = 716
Cached time = 652

tx-cache:
Initial time = 867
Cached time = 25

Anyways, I did an experiment, I put a breakpoint in right before it does the second lookup. When it hit that point, I disabled my network connection. When the lookup gets performed into the tx-cache, everything goes fine, when it goes to the db-cache, I get the following exception, and I can see your code trying to communicate with Cassandra. Is this intended?

Here's the stack:
Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not process individual retrieval call 
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:215)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8.execute(StandardTitanTx.java:1125)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8.execute(StandardTitanTx.java:994)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:195)
    at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:54)
    at com.thinkaurelius.titan.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:40)
    at com.thinkaurelius.titan.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:30)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:56)
    at com.google.common.collect.Iterables$7.iterator(Iterables.java:609)
    at test.com.infa.prototype.titan.berkley.GetObjectFromBerkley.main(GetObjectFromBerkley.java:26)
Caused by: com.thinkaurelius.titan.core.TitanException: Could not call index
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6.call(StandardTitanTx.java:1118)
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:213)
    ... 9 more
Caused by: com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:428)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.indexQuery(BackendTransaction.java:380)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.query(IndexSerializer.java:495)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6$1.call(StandardTitanTx.java:1114)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6$1.call(StandardTitanTx.java:1111)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6.call(StandardTitanTx.java:1111)
    ... 10 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Could not successfully complete backend operation due to repeated temporary exceptions after Duration[10 s]
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:86)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    ... 23 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:114)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:78)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:67)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:65)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:65)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction$5.call(BackendTransaction.java:383)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction$5.call(BackendTransaction.java:380)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    ... 24 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
    at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:48)
    at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:338)
    at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:527)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:112)
    ... 31 more

**Comment by mbroecheler** [comment]
It seems to work for me:
https://gist.github.com/mbroecheler/1450d1f7fa5d3dc75aab

This compares the cache with an embedded BDB instance (which is already
pretty fast) and cache seems to be about a factor of 2 faster.

BTW, your stack trace indicates that the cache is not enabled. The cache
overwrite KCVSProxy.getSlice() - that method should not be called with
cache enabled.

On Thu, Oct 9, 2014 at 3:26 PM, mbbeaubi notifications@github.com wrote:

> Hi,
> 
> I think I'm not understanding how the db-cache works. I have Titan running
> on my box, I have Cassandra running in a remote cluster. I'm assuming that
> if something is cached in the db-cache, there should be no communication
> with the cassandra cluster to fetch that object, even if it an index look
> up?
> 
> BTW, here are the numbers with the prints turned off
> db-cache:
> Initial time = 716
> Cached time = 652
> 
> tx-cache:
> Initial time = 867
> Cached time = 25
> 
> Anyways, I did an experiment, I put a breakpoint in right before it does
> the second lookup. When it hit that point, I disabled my network
> connection. When the lookup gets performed into the tx-cache, everything
> goes fine, when it goes to the db-cache, I get the following exception, and
> I can see your code trying to communicate with Cassandra. Is this intended?
> 
> Here's the stack:
> Exception in thread "main" com.thinkaurelius.titan.core.TitanException:
> Could not process individual retrieval call
> at
> com.thinkaurelius.titan.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:215)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8.execute(StandardTitanTx.java:1125)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8.execute(StandardTitanTx.java:994)
> at
> com.thinkaurelius.titan.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:195)
> at
> com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:54)
> at
> com.thinkaurelius.titan.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:40)
> at
> com.thinkaurelius.titan.graphdb.query.ResultSetIterator.(ResultSetIterator.java:30)
> at
> com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:56)
> at com.google.common.collect.Iterables$7.iterator(Iterables.java:609)
> at
> test.com.infa.prototype.titan.berkley.GetObjectFromBerkley.main(GetObjectFromBerkley.java:26)
> Caused by: com.thinkaurelius.titan.core.TitanException: Could not call
> index
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6.call(StandardTitanTx.java:1118)
> at
> com.thinkaurelius.titan.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:213)
> ... 9 more
> Caused by: com.thinkaurelius.titan.core.TitanException: Could not execute
> operation due to backend exception
> at
> com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
> at
> com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:428)
> at
> com.thinkaurelius.titan.diskstorage.BackendTransaction.indexQuery(BackendTransaction.java:380)
> at
> com.thinkaurelius.titan.graphdb.database.IndexSerializer.query(IndexSerializer.java:495)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6$1.call(StandardTitanTx.java:1114)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6$1.call(StandardTitanTx.java:1111)
> at
> com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
> at
> com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
> at
> com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
> at
> com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
> at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
> at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
> at
> com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6.call(StandardTitanTx.java:1111)
> ... 10 more
> Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException:
> Could not successfully complete backend operation due to repeated temporary
> exceptions after Duration[10 s]
> at
> com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:86)
> at
> com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
> ... 23 more
> Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException:
> Temporary failure in storage backend
> at
> com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:114)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:78)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:67)
> at
> com.thinkaurelius.titan.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:65)
> at
> com.thinkaurelius.titan.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:65)
> at
> com.thinkaurelius.titan.diskstorage.BackendTransaction$5.call(BackendTransaction.java:383)
> at
> com.thinkaurelius.titan.diskstorage.BackendTransaction$5.call(BackendTransaction.java:380)
> at
> com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
> ... 24 more
> Caused by:
> com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException:
> NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0),
> attempts=0]No hosts to borrow from
> at
> com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.(RoundRobinExecuteWithFailover.java:48)
> at
> com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
> at
> com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:338)
> at
> com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:527)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:112)
> ... 31 more
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/775#issuecomment-58587673.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbbeaubi** [comment]
Hi,

Sorry I didn't reply back sooner, but it's the weekend and also been pretty busy looking at your titan-hadoop product.

Put a commit in between your times calls. Without a commit there the second call is hitting in your tx-cache, which I agree is working.

Your numbers are actually proving my point. If you just compare the numbers from the first times call, you can see they are all pretty close, and always consistently higher then the second call. If the db-cache was working, I would expect all the times to be about the same after the very first call when it first adds the entry to the db-cache. I suppose I could see it being double, since it had to first miss in the tx-cache, but not 4x like you see here.

If you have the code open, could you try using the stack I sent to put a breakpoint where you say it should not be going? I swear that when I generated that stack I had db-cache enabled, so it should not have gone there as you said.

Thanks,
Mike

**Comment by mbroecheler** [comment]
I did add commit statements in the script I pasted. Sometimes I timed it
with and without commit to show the difference. And sometimes I restarted
the database.

To clarify some points:
- the database level cache is about factor 3-4 slower than the tx cache.
  That is because the database level cache keeps the data in serialized
  format to preserve memory and to not pollute the heap which makes garbage
  collection horrible. The tx cache keeps objects - that's why it is quite a
  bit faster.
- Measuring cache times right after starting a fresh jvm can be very
  misleading. That's because hot-spotting hasn't taken full effect yet. This
  is something to watch out for. You can see in my script that all times are
  getting better as the jvm warms.

Cheers,
Matthias

On Mon, Oct 13, 2014 at 11:11 PM, mbbeaubi notifications@github.com wrote:

> Hi,
> 
> Sorry I didn't reply back sooner, but it's the weekend and also been
> pretty busy looking at your titan-hadoop product.
> 
> Put a commit in between your times calls. Without a commit there the
> second call is hitting in your tx-cache, which I agree is working.
> 
> Your numbers are actually proving my point. If you just compare the
> numbers from the first times call, you can see they are all pretty close,
> and always consistently higher then the second call. If the db-cache was
> working, I would expect all the times to be about the same after the very
> first call when it first adds the entry to the db-cache. I suppose I could
> see it being double, since it had to first miss in the tx-cache, but not 4x
> like you see here.
> 
> If you have the code open, could you try using the stack I sent to put a
> breakpoint where you say it should not be going? I swear that when I
> generated that stack I had db-cache enabled, so it should not have gone
> there as you said.
> 
> Thanks,
> Mike
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/775#issuecomment-58994646.

## 

Matthias Broecheler
http://www.matthiasb.com
