### ISSUE TITLE
getProperty/setProperty for collections is asymmetrical.

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#777]
Hi,

I've recently been upgrading a web site that used Titan 0.4 to 0.5. We are using Graphson to back up the data from the graph, but am unable to load it back in.

The data out looks like this:

``` json
{"mode":"NORMAL","vertices":[{"photos":["Test","Testing"],"_id":256,"_type":"vertex"}],"edges":[]}
```

But when loading back we get the following exception:
java.lang.IllegalArgumentException: Not an single key: photos. Use addProperty instead

This also means that the following won't work:

``` java
TitanVertex vertex = (TitanVertex) graph.addVertex(null);
vertex.addProperty("photos", "Test");
vertex.addProperty("photos", "Testing");
Object value = vertex.getProperty("photos");
vertex.setProperty("photos", value);
graph.commit();
```

I'm pretty sure this used to work in 0.4 and from the client point of view using addProperty feels like it should be an optional optimisation.

The work around is to use a wrapper graph to detect if a value is an array or collection and call addProperty for each element.

**Comment by mbroecheler** [comment]
This will be fixed with the change to TP3 in Titan 0.9
