### ISSUE TITLE
is there any rest api avaible with titan so that i can use it will other language like php

### ISSUE THREAD

**Issue by mithun12000** [thinkaurelius/titan#789]
Hi all,

can you guide me how can i implement it with php language.

regards
Mithun Mandal

**Comment by avieth** [comment]
You should look into [rexster](https://github.com/tinkerpop/rexster/wiki). There's even a project called [PHP-Rexster](https://github.com/ashwinks/PHP-Rexster) which may be exactly what you need (I haven't used it, can't vouch for it).

**Comment by spmallette** [comment]
Note that Rexster is packaged with Titan as [Titan Server](http://s3.thinkaurelius.com/docs/titan/0.5.1/server.html).  In the future please direct questions like this to the Aurelius Graphs mailing list: https://groups.google.com/forum/#!forum/aureliusgraphs
