### ISSUE TITLE
Source code 0.5.1 Where?

### ISSUE THREAD

**Issue by angelcervera** [thinkaurelius/titan#794]
In this repository, I only found source for version 0.4.5-SNAPSHOT 
Where is the source code for version 0.5.1?

Regards

**Comment by dkuppitz** [comment]
https://github.com/thinkaurelius/titan/tree/0.5.1

**Comment by angelcervera** [comment]
Hi. thanks.

Other quick question.
This link is a tag, but there is not a branch for 0.5.X-SNAPSHOT
Are you working in this version? Is 0.5.X-SNAPSHOT in other repository? If you are not woking in 0.5.X, what is the versioning policy?

Sorry but I am confused.
In the last year, I was working in small projects using Titan, but now I am starting a more ambicius project and I want use the las version with Cassandra 2. The best way to understand is deep in the code, and maybe I can help with patch or documentation.
But I can not find the 0.5.X-SNAPSHOT branch.

Regards.

**Comment by mbroecheler** [comment]
We are working on 0.5.X - its in the titan05 branch.

On Mon, Oct 27, 2014 at 11:39 PM, Ángel Cervera Claudio <
notifications@github.com> wrote:

> Hi. thanks.
> 
> Other quick question.
> This link is a tag, but there is not a branch for 0.5.X-SNAPSHOT
> Are you working in this version? Is 0.5.X-SNAPSHOT in other repository? If
> you are not woking in 0.5.X, what is the versioning policy?
> 
> Sorry but I am confused.
> In the last year, I was working in small projects using Titan, but now I
> am starting a more ambicius project and I want use the las version with
> Cassandra 2. The best way to understand is deep in the code, and maybe I
> can help with patch or documentation.
> But I can not find the 0.5.X-SNAPSHOT branch.
> 
> Regards.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/794#issuecomment-60715478.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by angelcervera** [comment]
Thanks!
