### ISSUE TITLE
EdgeMap - processing order

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#799]
Edges are currently processed for each in-vertex. That leads to problems when you have a few million unidirected edges pointing to a single vertex. You usually use unidirected edges to prevent supernodes; now when you have 5M vertices each having one unidirected (by type definition) edge pointing to a _master vertex_, Faunus will load all 5M edges in a single transaction because the EdgeMap phase processes only incoming edges and thus will process all edges once it hits the aforementioned _master vertex_.

Consequently unidirected edges are helpful in Titan, but can lead to timeout and/or memory issues in Faunus.

_Matthias sent me this snippet, I guess you'll know where to find it:_:

``` java
for (final TitanEdge edge : value.query().queryAll().direction(IN).titanEdges()) {
    this.getCreateOrDeleteEdge(value, (StandardFaunusEdge)edge, context);
}
```

If the query would load `OUT`-edges instead, then we / the user wouldn't have to deal with Faunus-supernode-issues.

**Comment by mbroecheler** [comment]
This has already been changed in Titan 0.9. When the M1 comes out, it would be great if @dkuppitz could test this.

**Comment by dkuppitz** [comment]
I don't remember my exact use case, but I just did some tests using a 10M (unidirected) edge graph and everything worked smoothly, so I assume that this is fixed.
