### ISSUE TITLE
Refactor performance tests to become regression tests

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#80]
1. Extract metrics and compares those between releases
2. Enable batch for more intense reading/writing (these tests currently take waaaay to long)
3. Investigate potential Cassandra bug related to negative bloom filter size

**Comment by mbroecheler** [comment]
Use junit benchmarks, export as xml, parse xml and gather statistics (@dalaro)

Write junit benchmark tests (@mbroecheler)

**Comment by dalaro** [comment]
I merged the performance-test-rewrite branch into master.  This branch contains a combination of performance test plumbing and new Gremlin-based performance tests that use the plumbing.  Contributions:
- JUnitBenchmarkProvider, a static utility class for tests that handles JUB configuration and automatic method-round-count tuning
- GraphGenerator, a class built on Furnace that creates synthetic scale-free graphs for testing
- New Gremlin-based performance tests in GroovySerialTest.groovy.  This is an abstract class that inherits from GroovyTestSupport.groovy (which loads the test fixture graph and provides some helper methods) and which is inherited by the concrete implementation InternalCassandraGraphSerialTest.java.

Test code calls `JUnitBenchmarkProvider.get()` for a `BenchmarkRule` instance.  The returned instances have two salient non-default behaviors.
- The returned object is configured to write benchmark results to the console and to xml files in the form jub.(timestamp).xml, where timestamp is System.nanoTime() just before the test method executed.  These files are used in unattended testing and ducksboard upload.
- The returned object overrides any class- or method-level `@BenchmarkOptions(benchmarkRounds=..., warmupRounds=...)` settings.  Only `benchmarkRounds` and `warmupRounds` are overridden; other parameters in a method-level `@BenchmarkOptions` annotation are honored when present.  `warmupRounds` is currently a static final variable (1), and `benchmarkRounds` is loaded from a file.  It defaults to ../titan-test/data/jub-effort.txt, though the path can be overridden via the environment variable JUB_EFFORT_FILE.

The "effort file" is line-oriented and looks like this:

```
com.thinkaurelius.titan.graphdb.thrift.InternalCassandraGraphSerialTest.testEdgeTraversalUsingVertexCentricIndex 9.191
com.thinkaurelius.titan.graphdb.thrift.InternalCassandraGraphSerialTest.testFramedUidAndPropertyLookup 6.812
com.thinkaurelius.titan.graphdb.thrift.InternalCassandraGraphSerialTest.testGlobalEdgePropertyQuery 1.000
(...)
```

When the environment variable JUB_EFFORT_GENERATE is set, the returned `BenchmarkRule` will estimate, based on a single execution of each test method, the benchmarkRounds required for each test method to run approximately TARGET_RUNTIME (set to 5s).  The result is calculated and written as floating-point.  JUBProvider passes that to `Math.ceil(...)` to get an integral `benchmarkRounds`.

All of this functionality is hidden from a performance test's point of view.  It only needs to include this line:

```
@Rule public TestRule benchmark = JUnitBenchmarkProvider.get()
```
