### ISSUE TITLE
Hadoop's titanlib folder JARs don't include Titan libraries

### ISSUE THREAD

**Issue by miechus** [thinkaurelius/titan#800]
We're trying to integrate Titan Hadoop in a webapp running in either Jetty or Tomcat containers. When running Jetty as Maven plugin we realized that only one Maven library is copied to the titanlib folder in HDFS and submitted jobs generate this error:

```
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.thinkaurelius.titan.hadoop.formats.noop.NoOpOutputFormat not found
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.createOutputCommitter(MRAppMaster.java:475)
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceInit(MRAppMaster.java:376)
    at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
```

The problem is in the com.thinkaurelius.titan.hadoop.config.job.AbstractDistCacheConfigurer class in the configureByClasspath() method. In our case on the Maven JAR plexus-classworlds-2.4.jar is copied over, all because the configureByClasspath() method only supports reading the JAR names from the java.class.path system property.

While this approach will work well in case of stand-alone Titan executed from the Gremlin CLI, it will not work for web applications that are wrapped with container-specific classloaders that don't set all the JARs in the classpath.

We would need to have an option to provide a custom configurer provider interface such as this:

```
public interface JobClasspathConfigurerProvider {

    public JobClasspathConfigurer provide(Configuration conf, JobClasspathConfigurerType type);

}
```

Where the configurer types would be MAPRED and DIST_CACHE

Ideally, we would also want a way to intercept the Hadoop pipeline execution so that a custom pre- and post-processor can be injected based on a Hadoop graph configuration property. This way custom file uploads would block the execution of the job until all custom files are uploaded.

Is there currently any way to resolve this problem?

**Comment by dalaro** [comment]
I think there are two ways to approach this.

One is to pack a mapreduce job jar that contains all of the dependencies needed for Titan-Hadoop execution.  This is essentially how Faunus worked up through version 0.4.4.  It's still supported in 0.5.x by setting `mapred.jar` (Hadoop 1) or `mapreduce.job.jar` (Hadoop 2) in the configuration.  But this is also cumbersome and space-inefficient, since the job jar contains a copy of every classfile needed by Titan-Hadoop jobs -- it's often just a copy of the whole classpath.

I just introduced an alternative in 4ba6d1f6b88b4444633ca9883c786a533bb9ef2d.  When titan.hadoop.mr.classpath-configurer is set, it's interpreted as the full package and classname of an implementation of JobClasspathConfigurer, and instantiated using the no-arg constructor it's assumed to have.  This is not as flexible as the SPI you sketched, and the details are subject to change before release, but it seems like this would work for the Plexus case you described.  Thoughts?

**Comment by miechus** [comment]
Dan,

Looking at the changes it does seem like this would solve our issue.

I was wondering if it would also be possible to add a parameter to the configuration that would allow to skip the copy of the JAR files to titanlib (especially if you're invoking many jobs it seems like it could be done outside of the Titan process in a more streamlined (i.e. periodic) sync process). Or, even more elegant, if there could be an interface implementation (class name provided same way as the solution you implemented for the JAR files) that the code would delegate to in order to make the decision whether to copy the JAR files or not. This way implementing applications could, for example, provide logic that would require the re-sync of the JARs on a periodic basis.

Thanks a lot

**Comment by dalaro** [comment]
@miechus Please let me know if you're seeing something different in testing.  However, setting classpath-configurer should disable the copy to titanlib.  This is the logic that determines which JobClasspathConfigurer is used at runtime:  https://github.com/thinkaurelius/titan/blob/titan05/titan-hadoop-parent/titan-hadoop-core/src/main/java/com/thinkaurelius/titan/hadoop/config/job/JobClasspathConfigurers.java#L34-L69.

The new classpath-configurer option takes first precedence, then the mapred jar configurer is used (if its config option is set), and only if those two are absent does the dist cache configurer and titanlibs copy come into play.  At least, that's how it's intended to work.  Would that meet the need?

**Comment by miechus** [comment]
@dalaro You're right - using only the configurer will solve this. The use of some external static object would be needed as the configurer instances are instantiated on a per-job basis and would not maintain the state but this can be worked around.

**Comment by dalaro** [comment]
Sounds good.  Please reopen/open-new if a Titan bug or unseen limitation in the approach comes up during Plexus integration.
