### ISSUE TITLE
Could be an error in bdb.html

### ISSUE THREAD

**Issue by angelcervera** [thinkaurelius/titan#801]
Could be an error in titan-config-ref.html

In the documentation :

TitanGraph g = TitanFactory.build()
    .set("storage.backend", "berkeleyje");
    .set("storage.directory", "/tmp/graph");
    .open()

and should be :

TitanGraph g = TitanFactory.build()
    .set("storage.backend", "berkeleyje")
    .set("storage.directory", "/tmp/graph")
    .open();

Pay attention to the ";" at the end of each line.

**Comment by dalaro** [comment]
This is fixed in titan05.  I also cherry-picked this back to 0.5.0_docs and 0.5.1_docs branches that I've been keeping locally off their respective release tags and rebuilt+redeployed the docs for both of those versions.
