### ISSUE TITLE
Where is the source for the `com.thinkaurelius.titan.hadoop` package?

### ISSUE THREAD

**Issue by dminkovsky** [thinkaurelius/titan#804]
New to Java and Titan, so I'm sorry if this question is really stupid, but: I'm not able to find the source files for the `com.thinkaurelius.titan.hadoop` package. Noticed it in `gremlin.sh`, wanted peek at it, and have spend the last long while looking for them! Found them on http://mvnrepository.com/, but can't find them anywhere in the thinkaurelius repos here on GitHub.

**Comment by rjbriody** [comment]
Here is the github project:

https://github.com/thinkaurelius/titan

Titan 0.5x development is on it's own branch.

https://github.com/thinkaurelius/titan/tree/titan05/titan-hadoop-parent/titan-hadoop-core/src/main/java/com/thinkaurelius/titan/hadoop

**Comment by dminkovsky** [comment]
Hi @rjbriody,

Thanks for this response. Had missed this branch. Noticed other issues where you direct people to the mailing list. Will research/post question there going forward.
