### ISSUE TITLE
Web server doesn't respond

### ISSUE THREAD

**Issue by burlaka** [thinkaurelius/titan#805]
Hello!
Something strange with the web-server of titandb. He stops responding to http requests after 3-5 min after the start. Browser infinitely waits for the answer. Only one thing I have changed in configuration is base-uri in the rexster-cassandra.xml and rexster-cassandra-es.xml. I try 4.4.0 and 5.1.0 version.

Many thanks.

**Comment by spmallette** [comment]
Might be related to this issue in Rexster:

https://github.com/tinkerpop/rexster/issues/271

the summary of which is to increase thread pool sizes.

**Comment by burlaka** [comment]
Yes. This is my case. I think that increase thread-pool is not a best solution, because problem may occure after sometime again.
I have read in one of you comment: "In TinkerPop3 we will be leaving Grizzly behind in favor of Netty." Do you have any plan for it? I'm planing to use titandb in big project and stability is critical for me.

**Comment by spmallette** [comment]
If you are installing in a production environment it is quite likely that the default thread pool settings are inadequate so you will want to increase them anyway.  The defaults are set purposely low for those just getting started.  I've not heard of an environment yet where increasing the thread pool size doesn't solve this issue in the environments where it is a problem (typical RHEL).  

TinkerPop3 is already well into milestone releases and the next major release of Titan will support it.  You can read about Gremlin Server (Rexster's replacement) here:

http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#gremlin-server

As my comment alluded, It is built on Netty and I think has a better model for processing large result sets and such.  The docs don't reflect this as the feature is under development but it will now have a REST API that matches the features of the Gremlin Extension for Rexster.
