### ISSUE TITLE
Solr scoring does not work as expected

### ISSUE THREAD

**Issue by arnonyogev** [thinkaurelius/titan#808]
When using indexQuery() on a Solr backend, all returned vertices are scored 1.0.
1. Create a TitanGraph (we used in-memory for unit tests) and add a "text" property key:
   PropertyKey textKey = mgmt.makePropertyKey("text").dataType(String.class).make();
   mgmt.buildIndex(VERTICES_PROP_INDEX, Vertex.class).addKey(textKey).buildMixedIndex(INDEX_NAME);
   mgmt.commit();
2. Add 3 vertices with different "text" properties:
   v1.setProperty("text", "Hello Hello Hello Hello Hello Hello Hello Hello");
   v2.setProperty("text", "Hello abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad abab abab fsdfsd  sfdfsd  sdffs fsdsdf fdf fsdfsd aera fsad");
   v3.setProperty("text", "Hello");
3. Use indexQuery() to search for vertices:
   graph.indexQuery(VERTICES_PROP_INDEX, v.text:(Hello))

Result: The 3 vertices are returned, all with the same score of 1.0.
When performing the same scenario with a Lucene backend, the scores are different as expected.

**Comment by xedin** [comment]
@mbroecheler I've pushed changes to issue_808 branch (referenced in the issue). Basically only after reading actual code I was able to figure out that wildcard query that we were using "_:_" with filter sub-query converts to ConstantScoreQuery which sets all of the results of the query to score of 1.0f, so I've changed the code to set conditions to "?q=" instead, which actually computes the score, and added a test in TitanIndexTest to check if we return different 3 scores (determined via HashSet) while doing query from the description. 

As a side note, @arnonyogev, Lucene and Solr in the test case now return the same score values up to 7 digits (0.71231794, 0.629606, 0.17807949), which is how it should be as they use the same TF-IDF similarity scoring.

**Comment by arnonyogev** [comment]
Will the fix be available for the 0.9 branch as well? Noticed that 0.9.0-M1 was released recently.

**Comment by dalaro** [comment]
I merged this into titan05 a while back via ea126c7edb1a5092d48c1fe96093f1b6a8eb5a5c.  It was included (barely) in 0.5.2.  This has also been cherry-picked into titan09 as 8c4cb727599bf9ee2811020ce6714c3f8dece52d, which was part of 0.9.0-M1.  Apologies for not updating the issue sooner.
