### ISSUE TITLE
Astyanax Error on shutdown

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#81]
When shutting down, an error is logged.

**Comment by mbroecheler** [comment]
Upgrade to newest version of Astyanax. However, there seems to be an issue with modification re-ordering in the newest version that leads to test case failure:
https://github.com/Netflix/astyanax/issues/164
Once that is fixed:
1) Make sure that the shutdown error is gone
2) That repeated connections to exhaust sockets (#54)

**Comment by xedin** [comment]
I seen that error happening before my test modifications, target/test.log in titan-cassandra is clean now, closing.
