### ISSUE TITLE
TitanVertexQuery with adjacent

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#810]
if direction is Direction.BOTH the result is incorrect.
my schema is

``` Java
PropertyKey userId = mgmt.makePropertyKey("bloggerId").dataType(String.class).make();
TitanGraphIndex bloggerIdIndex = mgmt.buildIndex("bloggIdIndex", Vertex.class).addKey(userId).unique().buildCompositeIndex();
mgmt.setConsistency(bloggerIdIndex, ConsistencyModifier.LOCK);
mgmt.addIndexKey(getExternalIndex(Vertex.class), userId, Mapping.STRING.getParameter());

times = mgmt.makePropertyKey("times").dataType(Integer.class).make();
 EdgeLabel edgeLabel = mgmt.makeEdgeLabel("mention").make();
mgmt.buildEdgeIndex(edgeLabel, "labelIndex", Direction.BOTH, Order.DESC, times);
```

test code is

``` Java
 Vertex[] vertexes = new Vertex[3];
        for (int i = 0; i < vertexes.length; i++) {
            Vertex vertex = tx.addVertex();
            vertex.setProperty("bloggerId", "key-" + i);
            vertexes[i] = vertex;
        }
Edge edge1 = vertexes[0].addEdge("mention", vertexes[1]);
Edge edge2 = vertexes[0].addEdge("mention",vertexes[2]);
Edge edge3 = vertexes[1].addEdge("mention", vertexes[2]);

Iterable iterable = vertexes[1].query().direction(Direction.BOTH).adjacent(vertexes[2]).vertices();
```

The size of iterable is 2.

Is this a bug of TitanVertexQuery or I'am full understand of the method adjacent

**Comment by mbroecheler** [comment]
I copy-pasted your code and ran it against Titan 0.5.1 and it produced the right answer - the size of the iterable was 1.

**Comment by boliza** [comment]
Thanks I will test myself .I find that error,in titan 0.5.0

**Comment by boliza** [comment]
@mbroecheler I run this test in 0.5.1(I build my selft).but the data has already create,but the size of this itreable was 2...

**Comment by mbroecheler** [comment]
That is strange. Something might be wrong with your setup. I literally
copied the code into a test case, changed "Vertex" to "TitanVertex" and got
the right result.

On Thu, Nov 20, 2014 at 6:16 PM, Ranger Tsao notifications@github.com
wrote:

> @mbroecheler https://github.com/mbroecheler I run this test in 0.5.1(I
> build my selft).but the data has already create,but the size of this
> itreable was 2...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/810#issuecomment-63914909.

## 

Matthias Broecheler
http://www.matthiasb.com
