### ISSUE TITLE
Unsynchronize result in Rexster doghouse, maybe from cache

### ISSUE THREAD

**Issue by angelcervera** [thinkaurelius/titan#812]
Is Doghouse returning cached values?

Steps to reproduce the error:
1/ Connect to Rexster doghouse.
2/ Create a Vertex using Rest API and POST request:
http://192.168.1.155:8182/graphs/graph/vertices?key1=key1value&key2=key2value

> ```
> {
>    "version": "2.5.0",
>    "results":
>    {
>        "key1": "key1value",
>        "key2": "key2value",
>        "_id": 27392,
>        "_type": "vertex"
>    },
>    "queryTime": 134.20419
> }
> ```

3/ Search in Rexster Dog House console:

> g.v(27392).map
> ==>{key1=key1value, key2=key2value}

4/ Search using Rest API and get request:
http://192.168.1.155:8182/graphs/graph/vertices/27392

> ```
> {
>    "version": "2.5.0",
>    "results":
>    {
>        "key1": "key1value",
>        "key2": "key2value",
>        "_id": 27392,
>        "_type": "vertex"
>    },
>    "queryTime": 3.917217
> }
> ```

5/ Update using API Rest and PUT request
http://192.168.1.155:8182/graphs/graph/vertices/27392?key1=key1valueNEW&key2=key2valueNEW

> ```
> {
>    "version": "2.5.0",
>    "results":
>    {
>        "key1": "key1valueNEW",
>        "key2": "key2valueNEW",
>        "_id": 27392,
>        "_type": "vertex"
>    },
>    "queryTime": 9.947745
> }
> ```

6/ Search in Rexster Dog House console. **The result is not ok. Old values are showed**:

> g.v(27392).map
> ==>{key1=**key1value**, key2=**key2value**}

7/ To be sure, search vertices with the new value:

> g.v.filter{it.key2=='key2valueNEW'}
> ==>v[27392]

8/ Check again to be sure that the vertex has been updated, using using Rest API and get request:
http://192.168.1.155:8182/graphs/graph/vertices/27392

> ```
> {
>    "version": "2.5.0",
>    "results":
>    {
>        "key1": "key1valueNEW",
>        "key2": "key2valueNEW",
>        "_id": 27392,
>        "_type": "vertex"
>    },
>    "queryTime": 3.076738
> }
> ```

**So, using Rexter Doghouse, filter is ok, but show old values.** 
Using http://s3.thinkaurelius.com/downloads/titan/titan-0.5.1-hadoop2.zip

**Comment by spmallette** [comment]
If you use the web console then you are likely getting cached values from Titan as the console is operating in the context of a session and that session has a transaction.  If you want the new values in the console, issue a `g.rollback()` after you issue the request to update via the REST API.  

The REST API should always get the latest results, because it automatically issues a `g.rollback()`  at the start of the request.  In other words, the request to the REST API represents a complete transaction and thus always gets the latest data.

Please let me know if that results the problem

**Comment by angelcervera** [comment]
I understand.
But if the console is working in a transaction with old values, Why not the search? It is a strange combination.

> g.v.filter{it.key2=='key2valueNEW'} **is not under the transaction**.

but

> g.v(27392).map **is under transacation**.

And if the vertex is never updated in the transaction, I think that the value should be always the real value and not the value of the last retrieve. right?

**Comment by spmallette** [comment]
@mbroecheler maybe it's just late on a sunday, but i'm not sure i know the answer to this one.  what is the expected behavior here?

**Comment by angelcervera** [comment]
Other example.
Pay attention in the g.V after the g.V.remove()
Should return an empty list, but return the previous list.
However, g.V.count() is working right.

> gremlin> g.V
> ==>v[45056]
> ==>v[45312]
> gremlin> g.V.remove()
> ==>null
> gremlin> g.V.count()
> ==>0
> gremlin> g.V
> **==>v[45056]**
> **==>v[45312]**
> gremlin> g.commit()
> ==>null
> gremlin> g.V
> gremlin> g.V.count()
> ==>0
> gremlin>

**Comment by mbroecheler** [comment]
@spmallette Did we see this before where the session gets mapped onto different transactions for separate requests?

**Comment by mbroecheler** [comment]
With the move to Gremlin Server for 1.0 this does not require a fix.
