### ISSUE TITLE
Wrong return from Rexster on PUT and Vertex not found.

### ISSUE THREAD

**Issue by angelcervera** [thinkaurelius/titan#814]
When a vertex is updated using RestFul API over Rexster, if the Vertex does not exits, Rexster responses with status **500** (Internal server error) and the message in the body is

> {"message":null,"error":null}

Blueprints does not talk about the correct behavior, but IMO should response with a status **404** and a message like

> {"message":"Vertex with [zzzzz] cannot be found."}

In the GET, this is the behavior and IMO is right.

Could be a defect in tinkerpop/rexster?

**Comment by spmallette** [comment]
I believe that this issue is related to this (as of yet unmerged) PR:

https://github.com/tinkerpop/rexster/pull/367

I haven't had time to apply this change consistently across the Rexster which is why I didn't apply the PR just yet.

**Comment by angelcervera** [comment]
Yes, thanks.
