### ISSUE TITLE
Errors when building titan-all 0.5.1 in an ivy project

### ISSUE THREAD

**Issue by levin-royl** [thinkaurelius/titan#818]
Errors when building titan in an ivy project:
## This is the ivy.xml file:

<?xml version="1.0"?>
<!DOCTYPE ivy-module [
    <!ENTITY titan.version "0.5.1">
    <!ENTITY blueprints.version "2.5.0">
]>
<ivy-module version="2.0" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://ant.apache.org/ivy/schemas/ivy.xsd">

```
<info organisation="com.ibm" module="graphdb-jars" revision="&titan.version;" status="integration" />

<publications>
    <artifact name="${ivy.organisation}-${ivy.module}" type="jar" ext="jar" />
```

```
</publications> 
```

```
<dependencies>
    <!-- internal -->
    <dependency org="com.tinkerpop.blueprints" name="blueprints" rev="&blueprints.version;" />      
    <dependency org="com.tinkerpop.blueprints" name="blueprints-core" rev="&blueprints.version;" />

    <dependency org="com.thinkaurelius.titan" name="titan-all" rev="&titan.version;">
        <exclude org="log4j" name="log4j" />
        <exclude org="org.slf4j" name="slf4j-log4j12" />
    </dependency>

    <dependency org="org.slf4j" name="slf4j-log4j12" rev="1.7.7"/>
    <dependency org="log4j" name="log4j" rev="1.2.17"/>

</dependencies>
```

</ivy-module>
## This is the error I get in Eclipse:

Some projects fail to be resolved
Impossible to resolve dependencies of com.ibm#graphdb-jars;0.5.1
unresolved dependency: org.restlet.jee#org.restlet;2.1.1: not found
unresolved dependency: org.restlet.jee#org.restlet.ext.servlet;2.1.1: not found
unresolved dependency: org.restlet.jse#org.restlet;2.1.1: not found

**Comment by spmallette** [comment]
I'm not sure why this wouldn't work with ivy given that maven dependencies have been fine all along.  If this is somehow still an issue with Titan 1.0 you might want to bring it up on the mailing list.
