### ISSUE TITLE
Multi-properties don't work in Titan 0.9.0-Experimental

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#819]
Titan defaults to cardinality ONE for vertex properties. We should have this be MANY as this is now "standard TinkerPop."

``` groovy
gremlin> v = g.addVertex('name','marko','name','bob')
==>v[2560256]
gremlin> v.valueMap()
==>[name:[bob]]
gremlin> v.property('name','marko')
==>vp[name->marko]
gremlin> v.valueMap()
==>[name:[marko]]
gremlin>
```

**Comment by mbroecheler** [comment]
We will do this for 1.0 but cannot do it for 0.9 because we want to maintain backwards compatibility to 0.5.
Explicitly define your keys for now.

**Comment by fitzoh** [comment]
Per the conversation [here](https://groups.google.com/forum/#!topic/gremlin-users/N4R5GO6fHiQ) Single is now the default cardinality

**Comment by mbroecheler** [comment]
This should now be resolved. Essentially, for Titan it is strongly encouraged to declare the properties keys explicitly and define their cardinality. Titan will then use that cardinality in updates as one would expect. The default cardinality remains single.
