### ISSUE TITLE
Selective Replication of Sub-Graph --> Replicating Master data vertices across cluster nodes

### ISSUE THREAD

**Issue by phani1kumar** [thinkaurelius/titan#829]
I am new to the Graph theory as such. But I've gone through the documentation out there and gathered some knowledge around the subject. I am aiming for a start-up basing around the Titan Graph database. 

Coming to the subject line: Selective replication of sub-graph.
I could expect my graph data to grow beyond multiple nodes and also across geographies. 2-3 nodes present in Asia and 2-3 nodes in Europe and 2-3 nodes in USA. All the 6-9 nodes are going to be part of the same cluster. Now in this set-up there will be some master data vertices which would mostly participate in 90% of the queries. If the master data vertices are present in only few of these nodes of Asia, then all the queries in Europe, USA would end-up in "Edge Cut" scenarios, which will result in expensive queries. 

For this, if I can mark a portion of my graph to be replicated in all the nodes of my cluster, then 90% queries will always be executed locally in the individual nodes giving me a best performance. 

I would like to know if there is a way to achieve this selective replication of the sub-graph in Titan, if yes, how I can achieve this - any pointers will be of great help.

Example: 
Considering the Health  Care data, the deceases information as master data, and persons getting through the deceases, recovering from the deceases, the duration they are with that decease, and treatment they went through could be treated as incident data. In this case, the deceases data need to be replicated across all the nodes of the cluster, because mostly the deceases information is going to be same across the world (except for some local deceases, maintaining a copy of this is not going to be a harm). 

In the above example the deceases master information could be in the tune of million vertices, where as the incident data could be in the tune of billions of vertices. Hence replicating the million vertices as a trade-off for better performance seems logical to me.

**Comment by mbroecheler** [comment]
This is a question on the mailing list:
https://groups.google.com/forum/#!searchin/aureliusgraphs/Replication/aureliusgraphs/DWZ5NE7Tn-s/0vpICpFjMeUJ
