### ISSUE TITLE
Should we go full in on BerkeleyDB as opposed to "local"

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#83]
gremlin> g = TitanFactory.open('/tmp/titan')
==>titangraph[local:/tmp/titan]

....?should be?

gremlin> g = TitanFactory.open('/tmp/titan')
==>titangraph[berkeleyje:/tmp/titan]

**Comment by mbroecheler** [comment]
added berkeleyje as a configuration option for the backend.
