### ISSUE TITLE
A question about Titan Gremlin Execution plan.

### ISSUE THREAD

**Issue by levin-royl** [thinkaurelius/titan#836]
I have a question about how titan implements graph traversal queries.

For instance a Gremlin query such as:
g.v(1).outE('knows','created').interval('weight',0.5,1.0).has('date',2012).inV.name

What I want to know is, what is the plan for executing such a query --- i.e. what happens behind the scenes? 
For instance, does the edge filtering take place in the database backend (say in cassandra) or are all the edges imported into the titan JVM and the filtering takes place there? Also, is there any concurrency going on here or is the query processed completely synchronously.

Finally, if I do a Gremlin query with a loop and provide a WhileFunction object, is the code of this function sent over to the database backend JVM (e.g. Cassandra) or is the data imported to the titan JVM and the function applied there (i.e., without sending any byte code).

Thanks.

**Comment by mbroecheler** [comment]
Please use our mailing list for questions. The issue tracker is for bugs and features only.
https://groups.google.com/forum/#!forum/aureliusgraphs
