### ISSUE TITLE
Maven build causes dozens of "[WARNING] We have a duplicate..." errors

### ISSUE THREAD

**Issue by cjroth** [thinkaurelius/titan#84]
I'm trying to build my project with Titan and Maven is spitting out many dozens of "[WARNING] We have a duplicate..." messages. This only started happening when I added Titan.

I'm wondering if there's some modifications to my pom.xml that I could make to solve this. Maybe changing the Shade plugin's configuration? I think I could also add dependency excludes, but there are so many duplicates that that seems unrealistic.

**Comment by cjroth** [comment]
Update - was able to include it by compiling it with maven-assembly-plugin.

**Comment by mbroecheler** [comment]
You mean that by including the maven-assembly-plugin those warning messages went away?

**Comment by cjroth** [comment]
Yes - removing the shade plugin and replacing with the maven-assembly-plugin worked.

**Comment by mbroecheler** [comment]
Thanks. I have added an FAQ section to the documentation (https://github.com/thinkaurelius/titan/wiki/Building-Titan) if somebody else runs into this issue in the future.

**Comment by cjroth** [comment]
Awesome :)

I've also received a recommendation to try the RPM plugin. When I get a chance, I'll test that as well and compare.

I'm using DropWizard, here is the issue with the shade-alternative suggestions: https://groups.google.com/forum/#!topic/dropwizard-user/HyqfIKbsgc8
