### ISSUE TITLE
ShutdownThread not playing well with others

### ISSUE THREAD

**Issue by mjc-** [thinkaurelius/titan#842]
Greetings!

After some digging, it looks like the call to removeShutdownHook() here:
https://github.com/thinkaurelius/titan/blob/titan05/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/database/StandardTitanGraph.java#L164

is throwing IllegalState exception as it is being called during shutdown.

This appears to be expected behaviour
https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#removeShutdownHook(java.lang.Thread)

I think the fix would be to remove this call altogether, unless I'm missing something. 

Alternatively, catching that exception would help avoid the problem this causes. Currently the unhandled exception in the ShutdownThread this throws means that any other ShutdownHooks in a Titan client app are unlikely to get called.

Thanks!

**Comment by mjc-** [comment]
After thinking a bit more about this, shutdown() isn't solely called in the process of the ShutdownThread.  Catching the IllegalStateException is likely the right fix.

**Comment by dalaro** [comment]
I took the try-catch approach a while back in part of the test harness (https://github.com/thinkaurelius/titan/blob/titan05/titan-test/src/main/java/com/thinkaurelius/titan/DaemonRunner.java#L100).  It seems to work, but the stakes are much lower in there than in StandardTitanGraph.

A tidier approach might be to move all of the code except hook deregistration out of `shutdown` to a new method `shutdownInternal`, then make `shutdown` just call `shutdownInternal` and then deregister the hook.  The hook would call `shutdownInternal` directly.  Just sketching this -- need to squint at the code a bit and make sure it's reasonable.

**Comment by dalaro** [comment]
I took the approach described in my last comment with 1c37382e35f9d0901ed67d26aace6c539d049c82, and I also made the `shutdown` method try-catch around hook removal.  An IAE during hook removal will be logged at `WARN`, but it won't be propagated up the stack.
