### ISSUE TITLE
Guava 11 compatibility/shading for Hadoop clusters

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#845]
#844 showed how using Guava API elements newer than 11 can blow up on a Hadoop cluster.

We could go back to the MapReduce job-jar approach, where we copy every class in Titan's dependency tree (and Titan) to a fat jar, then shade the whole thing, and call `Job.setJar` on that instead of using the distributed cache.  It's inflexible and wasteful of space, but it will work even if Hadoop forces Guava 11 to the front of the classpath.  I would love to find a way around this that would let us use the distributed cache.  I don't see one.

Just shading Titan's own artifacts might help a bit, but it can't completely guard against recurrence when we upgrade dependencies or exercise new code paths in existing dependencies, since there are paths to Guava versions later than 11 through many dependencies out of Titan's direct control.  And I don't want to upload a huge chunk of our dependency tree in shaded form to Maven Central if I can avoid it.  Building a fat shaded MapReduce job-jar is kind of a compromise.

TP3 is currently on Guava 15.0.  Some of this may apply there as well.

**Comment by mbroecheler** [comment]
Related to #854.
