### ISSUE TITLE
Defining image type as SerialBlob in the Titan Graph node throws java.lang.IllegalArgumentException?

### ISSUE THREAD

**Issue by javajpn** [thinkaurelius/titan#847]
I am using Titan graph database and cassandra as a storage back end. One of my requirement is need to save avatar image into cassandra back end over titan Graph.

I have defined data type for Image as SerialBlob in the following Node. //Subscriber node

 public interface Subscriber extends VertexFrame {

```
  @Property(TitanConstants.AVATAR_IMAGE)
  public void setImage(SerialBlob avatarImage);

  @Property(TitanConstants.AVATAR_IMAGE)
  public SerialBlob getImage();
```

 }
While committing titanGraph I am getting below Exception:

[error] play - Cannot invoke the action, eventually got an error: com.thinkaurel
ius.titan.core.TitanException: Could not commit transaction due to exception dur
ing persistence
[error] application -

! @6kapbn96f - Internal server error, for (POST) [/upload] ->

play.api.Application$$anon$1: Execution exception[[TitanException: Could not com
mit transaction due to exception during persistence]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_
2.11-2.3.2.jar:2.3.2]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_
2.11-2.3.2.jar:2.3.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun
$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.2.jar:
2.3.2]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun
$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.2.jar:
2.3.2]
        at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
Caused by: com.thinkaurelius.titan.core.TitanException: Could not commit transac
tion due to exception during persistence
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(St
andardTitanTx.java:1029) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commi
t(TitanBlueprintsGraph.java:57) ~[titan-core-jre6-0.4.4.jar:na]
        at tv.seachange.portal.controllers.PortalController.upload(PortalControl
ler.java:493) ~[na:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$8$$anonfun$apply$8.appl
y(routes_routing.scala:168) ~[na:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$8$$anonfun$apply$8.appl
y(routes_routing.scala:168) ~[na:na]
Caused by: com.thinkaurelius.titan.core.TitanException: Unexpected exception dur
ing backend operation
        at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(Bac
kendOperation.java:67) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(St
andardTitanGraph.java:320) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(St
andardTitanTx.java:1018) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commi
t(TitanBlueprintsGraph.java:57) ~[titan-core-jre6-0.4.4.jar:na]
        at tv.seachange.portal.controllers.PortalController.upload(PortalControl
ler.java:493) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Cannot de-/serialize object: java
x.sql.rowset.serial.SerialBlob@1808bcc
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java
:148) ~[guava-16.0.1.jar:na]
        at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoDataOutpu
t.writeClassAndObject(KryoDataOutput.java:87) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.writeRelation
(EdgeSerializer.java:340) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.persist(S
tandardTitanGraph.java:345) ~[titan-core-jre6-0.4.4.jar:na]
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.access$00
0(StandardTitanGraph.java:49) ~[titan-core-jre6-0.4.4.jar:na]

 How the Image is saved in Titan Graph Database?? Could you please help me on this??

**Comment by mbroecheler** [comment]
The image would be stored as a binary array.

On Mon, Nov 24, 2014 at 10:45 PM, javajpn notifications@github.com wrote:

> I am using Titan graph database and cassandra as a storage back end. One
> of my requirement is need to save avatar image into cassandra back end over
> titan Graph.
> 
> I have defined following Node. //Subscriber node
> 
> public interface Subscriber extends VertexFrame {
> 
>   @Property(TitanConstants.AVATAR_IMAGE)
>   public void setImage(Blob avatarImage);
> 
>   @Property(TitanConstants.AVATAR_IMAGE)
>   public Blob getImage();
> 
> }
> //This method stores image into cassandra storage back end over titanGraph
> 
> public static Subscriber persistSubscriber(Blob avatarImage){
> 
>   Subscriber subscriber = TitanSchema.getFramedGraph().addVertex(null,
>             Subscriber.class);
>   subscriber.setImage(avatarImage);
> 
> }
> //This method gets Image from File and calls above persistSubscriber method
> 
> public static Result saveImage() throws IOException{
> MultipartFormData multipartFormData =
> request().body().asMultipartFormData();
> for(FilePart filePart : multipartFormData.getFiles()){
> fileName = filePart.getFilename();
> File file = filePart.getFile();
> InputStream inputStream = new FileInputStream(file);
> /_**How to convert inputstream to Blob object_*/
> persistSubscriber(Have to pass Blob object. How to create Blob from
> InputSream??)
> 
> }
> 
> return ok("Image saved");
> }
> Could anybody share How can I convert InputStream to Blob object in
> saveImage method?? or How the Image is saved in Titan Graph Database??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/847.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by javajpn** [comment]
@ mbroecheler Thanks for your response.. First I stored image as binary array. But time taken to store  image was inconsistent. For saving same image one time took  more than 1 min & another time took only 2 secs. That is why I am looking for  saving image as Blob, but that could not happen. Size of that image file I tried is 1.3 MB. Please correct me if I have done anything wrong

**Comment by mbroecheler** [comment]
I wouldn't recommend storing files of such large size in Titan as a property but rather in an external system with a pointer to it in Titan.
