### ISSUE TITLE
Create TitanXXXInputFormat extends InputFormat<NullWritable,VertexWritable>

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#848]
With Hadoop-Gremlin now in master/ and nearly fully re-written, it is very easy for Titan to interact with Hadoop -- both OLTP or OLAP.  If Titan can provide a `TitanXXXInputFormat` then we will be able to read data out of Titan and into GiraphGraphComputer, OLTP iterators, and (in the future), MapReduceGraphComputer.

Titan simply needs to "pop off" `VertexWritable` objects which are pretty basic. I provide the class definition below as I may be moving around classes in packages and don't want a broken link. You can see how simple it is --- return `new VertexWritable(titanVertex)`. Once it goes into the "Hadoop stream" it gets turned into a Kryo binary representation and the "Titan-ness" goes away.

Finally, note that you don't need a `TitanXXXOutputFormat` as that no longer makes sense now that we have `BulkLoaderVertexProgram` (its not an `OutputFormat` but a MapReduce program). 

``` java
public final class VertexWritable<V extends Vertex> implements Writable, WrappedVertex<V> {

    private Vertex vertex;
    private static final KryoWriter KRYO_WRITER = KryoWriter.build().create();
    private static final KryoReader KRYO_READER = KryoReader.build().create();

    public VertexWritable(final Vertex vertex) {
        this.vertex = vertex;
    }

    public void set(final Vertex vertex) {
        this.vertex = vertex;
    }

    public Vertex get() {
        return this.vertex;
    }

    @Override
    public V getBaseVertex() {
        return (V) this.vertex;
    }

    @Override
    public void readFields(final DataInput input) throws IOException {
        final ByteArrayInputStream inputStream = new ByteArrayInputStream(new byte[WritableUtils.readVInt(input)]);
        final Graph gLocal = TinkerGraph.open();
        this.vertex = KRYO_READER.readVertex(inputStream, Direction.BOTH,
                detachedVertex -> DetachedVertex.addTo(gLocal, detachedVertex),
                detachedEdge -> DetachedEdge.addTo(gLocal, detachedEdge));

    }

    @Override
    public void write(final DataOutput output) throws IOException {
        final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        KRYO_WRITER.writeVertex(outputStream, this.vertex, Direction.BOTH);
        WritableUtils.writeVInt(output, outputStream.size());
        output.write(outputStream.toByteArray());
        outputStream.close();
    }

    @Override
    public boolean equals(final Object other) {
        return other instanceof VertexWritable && ElementHelper.areEqual(this.vertex, ((VertexWritable) other).get());
    }

    @Override
    public int hashCode() {
        return this.vertex.hashCode();
    }
}
```

@mbroecheler

**Comment by dalaro** [comment]
I pulled TP3 master and looked at the builtin formats that extend `<NullWritable,VertexWritable>`.  I see that GraphSONInputFormat, for instance, still emits TinkerVertex instances wrapped in VertexWritable.  Since Titan's IF already emits TinkerVertex too, I think the immediate changes on the Titan side will be straightforward.  I'll take a crack at it.

**Comment by dalaro** [comment]
37b3a45a2fe440c1aa2c845ae1f0fb49c5ce0ef8 and 24fe518569bb08299be62bd4d862243edc1472f7 refactored titan09's titan-hadoop to account for the TP3 changes.  The new approach in TP3 has substantially simplified the Titan side.

Coincidentally, I ran into trouble trying to execute a MapReduce on GiraphGraphComputer  without at least one VertexProgram.  The `memory` field on GiraphGraphComputer is null in this case, which threw NPE in a couple of places when I tried testing my changes with a BulkDumpMapReduce job.  It's orthogonal to the input format changes though, so I temporarily hacked around it for testing purposes, and then dumping from Titan produced GraphSON output that matched expectations (I used Grateful Dead).

**Comment by okram** [comment]
Great! Yes, the Hadoop refactoring to go with the newly created `VertexWritable` and a consistent `<NullWritable,VertexWritable>` format was the trick.

In terms of a `null` memory field in `GiraphGraphComputer` when there is no `VertexProgram` --- I just realized it when I ran the `GiraphGraphComputer` integration tests:

``` java
Caused by: java.lang.NullPointerException
    at com.tinkerpop.gremlin.process.computer.MapReduce.addResultToMemory(MapReduce.java:146)
    at com.tinkerpop.gremlin.hadoop.process.computer.util.MapReduceHelper.executeMapReduceJob(MapReduceHelper.java:118)
    at com.tinkerpop.gremlin.hadoop.process.computer.giraph.GiraphGraphComputer.run(GiraphGraphComputer.java:159)
    ... 10 more
```

I accidentally introduced this in my refactoring yesterday and did not run the integration tests -- in fact the first test is :) :

``` java
@Test
    @LoadGraphWith(MODERN)
    public void shouldAllowMapReduceWithNoVertexProgram() throws Exception {
        final ComputerResult results = get_g_compute_mapXageX_reduceXsumX_memoryXnextX_memoryKeyXageSumX().submit().get();
        assertEquals(123, results.memory().<Integer>get("ageSum").intValue());
    }
```

I have fixed the problem. You should be good to go. I ran all the `ComputerTest` integration tests and a few of the `TraversalVertexProgram` ones (it takes 3+ hours for all) and they are green.

**Comment by dalaro** [comment]
Thanks for fixing that so quickly.  I stashed my workarounds, pulled, rebuilt, and reran BulkDumpMapReduce.  The fix looks good.

**Comment by dalaro** [comment]
These names might change, but as of a036dc600658e2adb9884bc6bd184d34bb75ac5e, the `<NullWritable, VertexWritable>` formats are:
- com.thinkaurelius.titan.hadoop.formats.cassandra.CassandraInputFormat
- com.thinkaurelius.titan.hadoop.formats.hbase.HBaseInputFormat
