### ISSUE TITLE
"IllegalArgumentException: Vertex id..." thrown when setting property on a FaunusVertex with an ID < 0

### ISSUE THREAD

**Issue by bcajes** [thinkaurelius/titan#851]
Negative long IDs seem valid when constructing a FaunusVertex, but the following exception is thrown when setproperty is called in this example:

(new FaunusVertex(new ModifiableHadoopConfiguration(), -10)).setProperty("foo", "baz")
java.lang.IllegalArgumentException: Vertex id %d [-10]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
        at com.thinkaurelius.titan.hadoop.StandardFaunusProperty.<init>(StandardFaunusProperty.java:58)

(new FaunusVertex(new ModifiableHadoopConfiguration(), 1)).setProperty("foo", "baz") //works

**Comment by mbroecheler** [comment]
Negative ids should not be supported and we don't plan to support them for compatibility with Titan.
