### ISSUE TITLE
Notion of "chunks" in ScanJob

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#857]
Introduce "startChunk()" and "endChunk()" in ScanJob and VertexScanJob similar to VertexProgram#workerIterationStart/End to mark the beginning and end of a logical unit of work.

In the job implementations, move the transaction start/commit into those respective methods so that the length of the transaction can be better controlled.
In FulgoraGraphComputer call the respective VertexProgram methods and move those calls out of the main execute method.

Implement this in StandardJobExecutor and the Hadoop based variant. For Hadoop, the chunk should map to the split size.

Make the chunk size configurable.

**Comment by okram** [comment]
We will probably be introducing "workerIterationStart/End()" to TP3 MapReduce as well. Just a heads up so you don't code yourself in hole.

**Comment by dalaro** [comment]
Is the benefit here for Fulgora?

For MR, I don't see how this makes a difference.  We can open a graph in `setup` and the transaction in `startChunk`, but there will still only be one of each call per MR map task in that order.

For Fulgora, maybe this helps a monster computation by decoupling a shared graph's lifetime from the lifetimes of its many shorter-lived chunk txs.  Although VertexJobConverter.GraphProvider might already help with that.  Not sure I get it.

In MR, `setup` opens a graph and a tx, and `teardown` closes them.  Each method is required to be invoked an equal and positive number of times (asserted in `SimpleScanJob.runBasicTests`) when all the global invocations are added up through metrics.  The calls already align with splits, so I think the contract there is already similar to `workerIterationStart` and `workerIterationEnd`.  This is in contrast to `VertexProgram.setup` and `terminate` called on just one node (e.g. Giraph master) at the beginning and end of each superstep.

Now I'm just confusing myself...
