### ISSUE TITLE
Titan should remove "poor man's hyper edges" in 0.9.0.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#860]
While this is a nice idea, the problem I see is during bulk dumping and then re-loading. Correct me if I'm wrong, but we will not be able to get the ID's correct as there are no edges to the vertex with the "hyper-referenced" vertex.

**Comment by okram** [comment]
Also, I'm seeing that this is breaking Rexster.. I suspect similar problems will emerge in TP3 GremlinServer, I/O, and of course, OLAP.

**Comment by mbroecheler** [comment]
The current plan is to drop them for 1.0. The reason I don't want to drop them for 0.9 is that this would create an incompatibility to 0.5.
