### ISSUE TITLE
One (Vertex)ScanJob, VertexProgram, MapReduce per thread

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#865]
in FulgoraGraphComputer and StandardScannerExecutor to be truthful to parallel execution semantic.

**Comment by dalaro** [comment]
Please elaborate.  What does it mean for instance to have one MapReduce per thread?  Does this have anything to do with the following line from the top of FulgoraGraphComputer?

``` java
private int numThreads = 1;//Math.max(1,Runtime.getRuntime().availableProcessors());
```

(https://github.com/thinkaurelius/titan/blob/titan09/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/olap/computer/FulgoraGraphComputer.java#L57)
