### ISSUE TITLE
Remove Index limitation from documentation

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#867]

**Comment by dalaro** [comment]
http://s3.thinkaurelius.com/docs/titan/0.5.3-SNAPSHOT/limitations.html#_unable_to_drop_indices

**Comment by dalaro** [comment]
@mbroecheler This issue would make sense to me on the 0.9.0 milestone, since titan09 already has index removal scanjobs implemented and documented.  I don't see how this applies to 0.5.3.  Did we backport index removal to titan05?  I'm looking through the tree, but I don't see it.

**Comment by dalaro** [comment]
I think this was removed on titan09 a long time ago via dae0a97f33211968619429f66ed4708f81496404
