### ISSUE TITLE
Rexster Docs Missing Steps

### ISSUE THREAD

**Issue by espeed** [thinkaurelius/titan#87]
The Titan Rexster docs are missing a few steps, such as building the jar-with-dependencies using `mvn:single` and the steps for creating the titanexample DB to get it running with Rexster. 

See https://github.com/thinkaurelius/titan/wiki/Rexster-Graph-Server

And jar-with-dependencies is commented out in the pom.xml.

See https://groups.google.com/d/topic/aureliusgraphs/_WlNYsFUzZk/discussion

**Comment by spmallette** [comment]
damn...james, you're right.  marko told me something shifted in the pom and i didn't connect it to this getting messed up.  i'll correct it as fast as i can.

**Comment by spmallette** [comment]
james, i've modified the wiki page.  i've simplified things a bit to simply say: make a titan directory in the rexster ext folder and then copy the lib files from titan into it.

**Comment by espeed** [comment]
Thanks Stephen. It would probably help pull things together to include the
steps for creating the titanexample DB, or at least linking to those steps.

On Mon, Sep 17, 2012 at 12:22 PM, stephen mallette <notifications@github.com

**Comment by spmallette** [comment]
Good point...missed that suggestion in the original bit you wrote....I've made a few more modifications.

**Comment by espeed** [comment]
I think the Rexster/Titan docs are still missing some steps...

[WARN] GraphConfigurationContainer - Could not load graph titanexample. Please check the XML configuration.
[WARN] GraphConfigurationContainer - GraphConfiguration could not be found or otherwise instantiated:.com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration
[WARN] GraphConfigurationContainer - com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration

**Comment by spmallette** [comment]
i'll walk through them again...

**Comment by espeed** [comment]
I'm still getting this error because when following the Rexster docs and building Rexster from source -- Rexster's `mvn clean install` is not copying the Titan jar files into `rexster/rexster-server/target/rexster-server-2.2.0-SNAPSHOT-standalone/ext/titan`.

For one thing, the doc paths are inconsistent: 

```
To add Titan to Rexster, first make a directory as in:

mkdir REXSTER_HOME/ext/titan
Then, if building Titan from source:

cp TITAN_HOME/target/titan-x.y.z-standalone/lib/*.* REXSTER_HOME/rexster-server-x.y.z/ext/titan
or, if using the Titan zipped distribution download:

cp TITAN_HOME/lib/*.* REXSTER_HOME/rexster-server-x.y.z/ext/titan
```

See https://github.com/thinkaurelius/titan/wiki/Rexster-Graph-Server

**Comment by spmallette** [comment]
I fixed that issue with the path inconsistencies you mentioned...jeez...how many times did i go through those docs and miss that.  

The docs don't contain what to do if building rexster from source.  Since Titan will likely never depend on anything other than a static official build, that doesn't seem necessary.  I would expect most people would download 2.1.0 and go.  

In any case, if you are building rexster from source, then you would copy to REXSTER_HOME/rexster-server/target/rexster-*-standalone/ext

**Comment by espeed** [comment]
The previous docs said this:

If building Titan and Rexster from source, copy the target/titan-0.1-SNAPSHOT-jar-with-dependencies.jar to the Rexster ./rexster-server/src/main/ext directory and then do mvn clean install on Rexster.

**Comment by spmallette** [comment]
Since titan doesn't jar with dependencies anymore, we didn't want to present confusion in that way and chose to assume that Titan would run with a built/released rexster version.  Do things work for you now?
