### ISSUE TITLE
Documentation bugs.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#872]
http://s3.thinkaurelius.com/docs/titan/0.9.0-M1/arch-overview.html
http://s3.thinkaurelius.com/docs/titan/0.9.0-M1/getting-started.html (Gremlin2)
http://s3.thinkaurelius.com/docs/titan/0.9.0-M1/gremlin.html (Gremlin2)

...there is alot more Gremlin than just the titanbasics.txt. It would be good for Titan guys to go through each line one by one and make sure its all right -- with appropriate links to TP3 docs.

**Comment by BrynCooke** [comment]
I've made a first stab at this. If there are other specific doc issues we should open them up individually.
