### ISSUE TITLE
Tinkerpop 2.6.0 with Neo4j 2.1.5

### ISSUE THREAD

**Issue by nipadadbhawala** [thinkaurelius/titan#875]
Hi,

I was looking at the pom for Neo4j implementation file and my observation is that it depends on neo4j version 2.0.1 community edition. What I am looking is to use the enterprise edition of Neo4j and potentially the latest version such as 2.1.5 or 2.1.6. Have you certified Tinkerpop 2.6 to work with any other version of Neo4j?

From the Neo4J documentation here

http://neo4j.com/docs/2.1.4/tutorials-java-embedded-setup.html, it seems I should be able to do

org.neo4j
neo4j-enterprise
2.1.5
pom
Would this approach be correct if this works? also if I run all the tests that come with Tinkerpop 2.6 with the above mentioned configuration, would that suffice?

thanks,
Nipa

**Comment by dalaro** [comment]
Does this issue involve Titan?

**Comment by spmallette** [comment]
Clearly not a Titan question - answered here: https://github.com/tinkerpop/blueprints/issues/517
