### ISSUE TITLE
Project maturity

### ISSUE THREAD

**Issue by angelcervera** [thinkaurelius/titan#876]
I started to use Titan in the last month (after test and use Neo4J and other blueprints implementations) and I find inconsistency between the documentation, strange behavior (for example, the behavior of cache inside transactions), problems trying to integrate with enterprise application (for example, a lot of dependencies requirements only to use the client), etc.

I think that it is a great project, but maybe we need more time.

Are there a list of success case use of Titan and information about?
Do you recommend to use the last release for a production environment or is better use the last SNAPSHOT and test before?

Regards and thanks.

**Comment by anvie** [comment]
I use Titan for production started a year ago, currently I have no big issue with the 0.5.x version, at least not yet.
Btw, I think you better ask question like this to the group: https://groups.google.com/forum/#!forum/aureliusgraphs

**Comment by angelcervera** [comment]
Hi @anvie 
Thanks t¡for the link.
