### ISSUE TITLE
Regex support in Lucene

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#879]

**Comment by dalaro** [comment]
Reenable Regex support in the Lucene backend; tests should be reactivated and begin failing. Implement to compliance with the test expectations.  Same tests should already run and pass on the ES backend.

**Comment by dalaro** [comment]
Added with test coverage.  This only covers `REGEX`.  We could open another issue for `CONTAINS_REGEX`, which is still unsupported in Lucene.
