### ISSUE TITLE
Failed to find cutom serializer

### ISSUE THREAD

**Issue by holub** [thinkaurelius/titan#888]
titan 5.2: g.commit() ignore registered custom serializer that implements AttributeSerializer.

**Comment by mbroecheler** [comment]
Do you have a test case that reproduces this?

**Comment by holub** [comment]
I have custom serializer for java.util.UUID which implements AttributeSerializer.
I can't promise but I'll try to create the simplest version of my code.

**Comment by holub** [comment]
My vision of problem:
1. Graph has version 4.4
2. Switching to 5.2 we missed information about keyTypes
3. Trying to access the keyType we get Object
4. For Object we uses backup serializer (Kryo) which has no idea about our custom Type.
