### ISSUE TITLE
DynamoDB: Storage Backend

### ISSUE THREAD

**Issue by danieljoppi** [thinkaurelius/titan#889]
Some anything prevision off integration with DynamoDB?
Very difficult to create the connector?
I'm thinking of creating it if they have forecast? Any idea of a connector already created that can build me?

**Comment by mbroecheler** [comment]
@danieljoppi Have a look at the mailing list archive for a discussion of DynamoDB:
https://groups.google.com/forum/#!forum/aureliusgraphs

**Comment by amcp** [comment]
Amazon Web Services open sourced the [DynamoDB Storage Backend for Titan](https://github.com/awslabs/dynamodb-titan-storage-backend) yesterday.

**Comment by danieljoppi** [comment]
great!!!
