### ISSUE TITLE
Consider KryoPool support in titan09

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#895]
The version of Kryo used by titan05 does not appear to include KryoPool.  It may be available in the later version (presently 2.24) used on titan09, in which case it might be a good candidate for a KryoInstanceCache implementation.

This issue assumes #877 gets closed and cherry-picked forward to titan09.

**Comment by mbroecheler** [comment]
That's nice. I didn't know KryoPool existed. Is that thread safe?

**Comment by mbroecheler** [comment]
Actually, I think we should get rid of Kryo altogether since TP3 now uses it.
