### ISSUE TITLE
Wrong transaction managment

### ISSUE THREAD

**Issue by usov-andrey** [thinkaurelius/titan#900]
First, sorry for my english. I very like this project, but i have one problem.

Every new thread create the new transaction and put it in TitanBlueprintsGraph.txs, TitanBlueprintsTransaction.openTx and StandardTitanGraph.openTransactions. If in that thread does not use graph.commit opened transactions will not close and still consume memory.

We have the memory leak. If u try to work with small max heap soon u will get OutOfMemory.  

And we have a wrong work with BerkleyDB with standard configuration.
For example, in first http request i get edges of the graph and in the next http request i try to change edge property and commit. I have error in the commit, because still have lock on the first request. Transaction in first request is still alive.
In my project i have solved this problem with graph.commit before release any thread, but in really u have to rewrite transaction management without ThreadLocal, because u can't control when transaction release. U have to remove the transaction in releasing current thread. 

In past TitanBlueprintsGraph.openTx is WeakHashMap, what can prevent memory leaks, but still have problems with BerkleyDB. Now it's ConcurrentHashMap, same StandardTitanGraph.openTransactions.

Thank you.

**Comment by dalaro** [comment]
If you want to avoid ThreadLocal, then use `TitanGraph.newTransaction`.  The program must still call `rollback` or `commit` on the objects returned by `newTransaction`.  In other words, if your app is already leaking open transactions somehow, then switching away from ThreadLocal is not necessarily going to fix the leak.

The `newTransaction` method is part of Blueprints (the `ThreadedTransactionalGraph` interface).

If the program opens thread-bound transactions, then the program should ensure that each affected thread calls either `commit` or `rollback` to free the resources associated with those transactions.  I don't understand how that's a Titan bug per se.
