### ISSUE TITLE
gremlin.sh buggy in 0.5.2

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#903]
`gremlin.sh` in 0.5.2 ignores the `-e` and `-i` parameters. You can find a partially fixed version [here](https://gist.github.com/dkuppitz/b7c804ef71f0d8bd86ca). This version brings back the `-e` functionality, but still fails for `-i`. I'm not sure how to solve this one:

```
daniel@cube ~/titan $ bin/gremlin.sh -i "println 'Hello World'"
Exception in thread "main" java.io.FileNotFoundException: bin/titan-hadoop.properties (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.InlineScriptExecutor.main(InlineScriptExecutor.java:52)
```

**Comment by 245987242** [comment]
hi

**Comment by dalaro** [comment]
The diff of your gremlin.sh against the current gremlin.sh appears to exactly revert 018827a538979a93c0b1cd9b4de240e72a235f72.  In that commit, I broke `-e`.  Reverting does fix it, but it also introduces a regression on the problem that commit tried to fix: invoking, say `bin/gremlin.sh -l INFO path/to/script.groovy` dies with `Gremlin initialization file not found at [-l]`.

I think we can fix both problems by moving the `shift` below the `getopt` loop.  The shell main class should never see the shell options anyway.  Here's the commit: 4f9ceb067e1e965615d6f71f5921016a305de312.

With these changes, `-i` and `-e` both appear to work.

I wrote a `test.groovy` file containing this:

``` groovy
g = TitanFactory.open('conf/titan-cassandra-es.properties')
GraphOfTheGodsFactory.load(g)
g.shutdown()
```

And then ran this:

``` bash
bin/titan.sh start
bin/gremlin.sh -e test.groovy
bin/gremlin.sh -i conf/hadoop/titan-cassandra-input.properties 'g.V.map()'
cat jobs/job-0/sideeffect-m-0000*
3072    {_id=[3072], name=[tartarus]}
1536    {_id=[1536], name=[hercules], age=[30]}
1792    {_id=[1792], name=[alcmene], age=[45]}
2816    {_id=[2816], name=[cerberus]}
1280    {_id=[1280], name=[neptune], age=[4500]}
256     {_id=[256], name=[saturn], age=[10000]}
768     {_id=[768], name=[sea]}
2560    {_id=[2560], name=[hydra]}
512     {_id=[512], name=[sky]}
2304    {_id=[2304], name=[nemean]}
1024    {_id=[1024], name=[jupiter], age=[5000]}
2048    {_id=[2048], name=[pluto], age=[4000]}
```

The commit also appears to avoid breaking `gremlin.sh -l LOGLEVEL SCRIPTFILE`:

```
cat > hello.groovy <<EOF
> println('hello world')
> EOF
bin/gremlin.sh -l ERROR hello.groovy 

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
hello world
==>null
gremlin> 
```

I thought `-e` expected that it will be followed by a script filename at least as far back as 0.3.2:

https://github.com/thinkaurelius/titan/blob/0.3.2/titan-core/src/main/java/com/thinkaurelius/titan/tinkerpop/gremlin/ScriptExecutor.java#L19

Is this incorrect?  It seems like you're using it differently.

You could certainly say that `gremlin.sh -e <scriptfile> arg...` is barely differentiated from `gremlin.sh <scriptfile>`, and that there should be some option that supports an arbitrary expression on the commandline without necessarily specifying a file (like `perl -e`).  And `-i` doesn't meet that need -- it supports an expression on the commandline, but it also requires a HadoopFactory config file.  That's entirely reasonable, though changing/adding options might be better suited to titan09.

Please reopen if I've missed something.
