### ISSUE TITLE
Use http://s3.thinkaurelius.com/docs/titan/current for documentation links in javadocs

### ISSUE THREAD

**Issue by jaceklaskowski** [thinkaurelius/titan#905]
Javadoc should use http://s3.thinkaurelius.com/docs/titan/current to refer to documentation pages in `@see` annotations. It now uses https://github.com/thinkaurelius/titan/wiki.

From [com.thinkaurelius.titan.core.TitanFactory](https://github.com/thinkaurelius/titan/blob/titan05/titan-core/src/main/java/com/thinkaurelius/titan/core/TitanFactory.java#L57):

```
     * @param shortcutOrFile Configuration file name or configuration short-cut
     * @return Titan graph database configured according to the provided configuration
     * @see <a href="https://github.com/thinkaurelius/titan/wiki/Graph-Configuration">Graph Configuration Wiki</a>
     */
    public static TitanGraph open(String shortcutOrFile) {
        return open(getLocalConfiguration(shortcutOrFile));
    }
```

**Comment by dalaro** [comment]
Thanks.   In addition to the instance you found, grep turned up some other similar wiki links in different javadoc comments.  I think I got them all in da15f294ed693e30409e76d8f88e27d7aa257c41.
