### ISSUE TITLE
Titan server 0.5.2 does not recover from backend failure

### ISSUE THREAD

**Issue by smalyshev** [thinkaurelius/titan#908]
I'm running Titan server 0.5.2 on top of Cassandra and if Cassandra goes down, I get exceptions like this:

```
23126 [pool-3-thread-1] WARN  com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog  - Could not read messages for timestamp [Timepoint[1419916997444000 μs]] (this read will be retried)
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:144)
at com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog$MessagePuller.run(KCVSLog.java:706)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
...

Caused by: java.net.SocketException: Broken pipe
at java.net.SocketOutputStream.socketWrite0(Native Method)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)

... 22 more
```

(full text here: http://pastebin.com/1nMgZ6eN) and the connection never recovers. Worse yet, connecting to the server with rexster console starts to give this error on any query:

```
==>An error occurred while processing the script for language [groovy]. All transactions across all graphs in the session have been concluded with failure: java.util.concurrent.ExecutionException: javax.script.ScriptException: javax.script.ScriptException: com.thinkaurelius.titan.core.TitanException: Could not process individual retrieval call 
```

So far I have found no way to recover from it except shutting down the Titan server and restarting it again. I do not think it is good to run it in production this way - so that any problem on the storage backend would make the server permanently unusable even after the storage backend came up and will require manual restart.

**Comment by spmallette** [comment]
Are you seeing this when explicitly using Titan Server (i.e. using `titan.sh`)?  I don't see this problem when running a cassandra instance and rexster instance separately.  I can kill cassandra, rexster will throw some errors if it tries to connect, then if i restart cassandra, rexster is happy to start working again. I did configure rexster to work with `storage.backend=cassandra` for what that is worth (i.e astyanax).

I didn't try Rexster Console at all....but generally speaking, Rexster Console isn't always good at reconnecting to a Rexster instance that has gone down.  A restart is sometimes necessary.  In this case though, Rexster has stayed up and cassandra has gone down, so I would expect that once Rexster recovers its connection to cassandra, Rexster Console should start working again.

**Comment by smalyshev** [comment]
@spmallette yes, this is using titan.sh and connecting via rexster-console.sh. I'm using storage.backend=cassandrathrift now but I can try with just cassandra. Restarting just the console does not help, the full server restart is the only thing that works for me.

**Comment by spmallette** [comment]
i didn't expect the console restart to help fix the server.  i just meant that if the console gets into that state AND rexster recovers, you might need to restart the console.

**Comment by smalyshev** [comment]
The problem is that rexster does not recover.Here is what happens when I tried it with storage.backend=cassandrathrift:

Here's a normal query that returns a result:

```
rexster[groovy]> g.wd('novalue')
==>v[512]
```

Here I restart cassandra:

```
rexster[groovy]> g.wd('novalue')
==>Could not process individual retrieval call 
```

Restart the connection:

```
exster[groovy]> ?r
resetting session with Rexster [127.0.0.1:8184]--> done
rexster[groovy]> g = rexster.getGraph('wikidata')
==>titangraph[cassandrathrift:[localhost]]
rexster[groovy]> g.wd('novalue')
==>Could not process individual retrieval call 
```

Restart the console:

```
rexster[groovy]> ?q
closing session with Rexster [127.0.0.1:8184]--> done
smalyshev:~/titan-0.5.2-hadoop2$ sh bin/rexster-console.sh 
        (l_(l
(_______( 0 0
(        (-Y-) <woof>
l l-----l l
l l,,   l l,,
opening session [127.0.0.1:8184]
?h for help

rexster[groovy]> g = rexster.getGraph('wikidata')
==>titangraph[cassandrathrift:[localhost]]
rexster[groovy]> g.wd('novalue')
==>Could not process individual retrieval call 
```

and this continues until I restart the server. After restart it works again:

```
smalyshev:~/titan-0.5.2-hadoop2$ sh bin/titan.sh -c wikidata stop
Killing Titan + Rexster (pid 37894)...
smalyshev:~/titan-0.5.2-hadoop2$ sh bin/titan.sh -c wikidata start
Forking Titan + Rexster...
-n Connecting to Titan + Rexster (127.0.0.1:8184)
-n .
-n .
-n .
-n .
-n .
 OK (connected to 127.0.0.1:8184).
Run rexster-console.sh to connect.
smalyshev:~/titan-0.5.2-hadoop2$ sh bin/rexster-console.sh 
        (l_(l
(_______( 0 0
(        (-Y-) <woof>
l l-----l l
l l,,   l l,,
opening session [127.0.0.1:8184]
?h for help

rexster[groovy]> g = rexster.getGraph('wikidata')
==>titangraph[cassandrathrift:[localhost]]
rexster[groovy]> g.wd('novalue')
==>v[512]
```

**Comment by spmallette** [comment]
I understand that Rexster isn't recovering for you and that is your primary problem - again, my side note about Rexster Console was just an observation.  

Please try `cassandra` for your `storage.backend` setting as it works for me.  I get the same failure as you when i use `cassandrathrift`.  using `cassandra` will use the astyanax client, which must be more robust when it comes to failure.

**Comment by smalyshev** [comment]
@spmallette Thanks, I will try the "cassandra" setting and report if it solves it.

**Comment by smalyshev** [comment]
@spmallette  Looks like "cassandra" setting fixes the problem. Thanks!

**Comment by spmallette** [comment]
good - i don't think this is actually a problem with Titan Server - it is just the nature of `cassandrathrift`.  As there is a workaround and i doubt there is actually a "fix" for this issue, i'm going to close this one.

**Comment by nik9000** [comment]
Is it worth marking cassandrathrift as deprecated or just noting this somewhere in the docs?

**Comment by spmallette** [comment]
i don't think it's "deprecated" as thrift still has its place in Titan usage.  perhaps we could update the docs with a note to say that "when using with Rexster configure with `cassandra` as oppose to `cassandrathrift` because...."

**Comment by spmallette** [comment]
Note added to the docs on the `titan05` branch.
