### ISSUE TITLE
Query translator bug - Solr

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#909]
Hey,
Per the mailing list discussion here (https://groups.google.com/forum/#!searchin/aureliusgraphs/solr|sort:relevance/aureliusgraphs/TOMZ7SyCUv4/jH46ErXCWUYJ) this issue is being opened to address unexpected behavior:
gremlin> g=TitanFactory.open('./solr.properties')
==>titangraph[cassandra:[1.23.456.789]]
gremlin> mgmt = g.getManagementSystem()
==>com.thinkaurelius.titan.graphdb.database.management.ManagementSystem@348ec43e
gremlin> name = mgmt.makePropertyKey('name').dataType(String.class).make()
==>name
gremlin> mgmt.buildIndex('nameindex',Vertex.class).addKey(name).buildMixedIndex("search")
==>com.thinkaurelius.titan.graphdb.database.management.TitanGraphIndexWrapper@4a100c1
gremlin> mgmt.commit()
==>null
gremlin> v1=g.addVertex()
==>v[256]
gremlin> v1.setProperty('name', 'hercules was here')
==>null
gremlin> g.commit()
==>null
gremlin> v1.map()
==>name=hercules was here
gremlin> g.query().has('name', REGEX, '._her._').vertices()
17:11:09 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [(name REGEX ._her._)]. For better performance, use indexes
17:11:09 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [(name REGEX ._her._)]. For better performance, use indexes
==>v[256]
gremlin> g.query().has('name', CONTAINS, 'here').vertices()
==>v[256]
gremlin> g.query().has('name', CONTAINS, 'was here').vertices()
17:11:38 ERROR com.thinkaurelius.titan.diskstorage.solr.SolrIndex  - Query did not complete because parameters were not recognized :
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: org.apache.solr.search.SyntaxError: Cannot parse '++1l1_t:(was) +1l1_t:(here)  ': Encountered " "+" "+ "" at line 1, column 1.
Was expecting one of:
.......

**Comment by mbroecheler** [comment]
Can you retry this against Titan 0.5.2. This should have been fixed in that release.

**Comment by xedin** [comment]
@mbroecheler Pull is at https://github.com/thinkaurelius/titan/pull/923, I have also added a test to make sure that we cover this everywhere.

**Comment by dalaro** [comment]
thanks @xedin, I merged #923 into titan05
