### ISSUE TITLE
Full scan with OR for a key that is indexed via composite index 

### ISSUE THREAD

**Issue by asaf** [thinkaurelius/titan#916]
Hey,

I have a composite index for key FOO
if I search for 'FOO='x'' Titan uses the index just fine,
But a query such:

`g.V().has('FOO', T.in, ['x', 'y'])` causes a full scan with the message:

`
Query requires iterating over all vertices [((FOO = x OR FOO = y))]. For better performance, use indexes
`

Why?

Thanks.

**Comment by boliza** [comment]
In this case I think you should create mixed index on field FOO.

**Comment by jbmusso** [comment]
Which version of Titan do you use? This could be the same issue as this one: https://github.com/thinkaurelius/titan/issues/679

**Comment by asaf** [comment]
0.5.0, i'll try with 0.5.2 and close the issue if it's solved.

Thanks!
