### ISSUE TITLE
Duplicate properties after singleProperty call in Titan 0.9

### ISSUE THREAD

**Issue by smalyshev** [thinkaurelius/titan#918]
I create a vertex with this code:

```
gremlin> v = g.addVertex('wikibaseId', 'Q1')
==>v[66560768]
gremlin> v.singleProperty('contentHash', 'test')
==>vp[contentHash->test]
gremlin> g.tx().commit()
```

Then I do this:

```
gremlin> v = g.V().has('wikibaseId', 'Q1').next()
==>v[66560768]
gremlin> v.singleProperty('contentHash', 'test2')
==>vp[contentHash->test2]
gremlin> v = g.V().has('wikibaseId', 'Q1').next()
==>v[66560768]
gremlin> v.singleProperty('contentHash', 'test2')
==>vp[contentHash->test2]
gremlin> v = g.V().has('wikibaseId', 'Q1').next()
==>v[66560768]
gremlin> v.singleProperty('contentHash', 'test3')
==>vp[contentHash->test3]
gremlin> v.properties('contentHash')
==>vp[contentHash->test3]
==>vp[contentHash->test]
```

As you can see, I have now two properties named contentHash - even though I specifically asked to make it a single property. It also leads to this unpleasant effect:

```
gremlin> v.property('contentHash')
Multiple properties exist for the provided key, use Vertex.properties(contentHash)
Display stack trace? [yN] 
```

I.e. despite me always using `singleProperty`, I can not use `property()` reliably. The duplicates disappear after the commit, but committing after each property change would be very expensive. 

Both `wikibaseId` and `contentHash` are declared as String keys with default (i.e. `SINGLE`, as the docs say) cardinality:

```
mgmt.makePropertyKey('contentHash').dataType(String.class).make()
mgmt.makePropertyKey('wikibaseId').dataType(String.class).make()
```

so they aren't even supposed to be able to hold many values. Yet that's what happens.

**Comment by mbroecheler** [comment]
This is fixed with upgrade to TP3 M8 on current titan09 branch.
