### ISSUE TITLE
Make use of _all in ES queries

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#920]
ES has the virtual field `_all`, which allows you to search for any term in every field. Usually you would create an aggregate field in Titan, which is a pain, since you always have to keep it in sync with other fields. It would be great if we could do something like  `g.indexQuery("index-name", "_all:foo").vertices()`.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-all-field.html

**Comment by BrynCooke** [comment]
As far as I can tell this already works.
I had a look at also adding this to a standard gremlin query, but some stuff especially around text handling (TEXT vs STRING) won't make sense. Therefore I think this is better left as indexQuery only.

**Comment by dkuppitz** [comment]
Cool, I just tried it again and indeed it works. Not sure why I opened the ticket, maybe it wasn't possible in 0.5.x.

**Comment by BrynCooke** [comment]
I'm trying to make it a bit nicer. We get a warning in the logs that will confuse users. The syntax will be more in line with the existing indexQuery. e.g. v.*:"test"
