### ISSUE TITLE
Supernode edge loading heap utilisation problems

### ISSUE THREAD

**Issue by DanielThomas** [thinkaurelius/titan#93]
We're seeing heap utilisation problems when dealing with supernodes (say 1M edges w/ a given label). The query is completely executed when hasNext() is first called on the iterator, in the case of ~1M edges, leading to over 350MB in retained heap between the ColumnFamily and the Titan objects.

Our query is a little convoluted, as we tag edges with a start and end timestamp:

```
    val pipe = startingNode ->;
    pipe.
      outE(relType).has('End', null).inV.
      has(Graph.ID, sharedId).
      inE(relType).has('End', null).outV
```

However, the behaviour can be demonstrated with a far simpler test using Gremlin:

```
g = TitanFactory.open("test")
supernode = g.addVertex(null)
i = 0
while( i < 1000000 ) {
  i++
  supernode.addEdge('test',g.addVertex(null))
}
g.stopTransaction(com.tinkerpop.blueprints.TransactionalGraph.Conclusion.SUCCESS)
supernode.outE('test').count()
```

Attach with a debugger, and note on the first hasNext call all edges are retrieved:

```
Thread [main] (Suspended)   
    owns: PersistStandardTitanVertex  (id=85)   
    StandardTitanGraph.loadRelations(AtomicQuery, InternalTitanTransaction) line: 272   
    StandardPersistTitanTx.loadRelations(AtomicQuery) line: 150 
    PersistStandardTitanVertex(AbstractTitanVertex).ensureLoadedEdges(AtomicQuery) line: 88 
    PersistStandardTitanVertex(StandardTitanVertex).getRelations(AtomicQuery, boolean) line: 71 
    SimpleTitanQuery(SimpleAtomicQuery).edges() line: 461   
    PersistStandardTitanVertex(AbstractTitanVertex).getEdges(Direction, String...) line: 177    
    OutEdgesPipe(VerticesEdgesPipe).processNextStart() line: 45 
    OutEdgesPipe(VerticesEdgesPipe).processNextStart() line: 15 
    OutEdgesPipe(AbstractPipe<S,E>).hasNext() line: 90  
    GremlinGroovyPipeline<S,E>(Pipeline<S,E>).hasNext() line: 105   
```

I noticed Titan's queries can have limits, though they're only set by Gremlin when using range(int, int) for a vertex operation, and can't be applied as a workaround for AbstractTitanVertex.getEdges:

```
    @Override
    public Iterable<Edge> getEdges(Direction dir, String... labels) {
        return new SimpleTitanQuery(this).direction(dir).labels(labels).edges();
    }
```

Is there a suggested design/workaround for mitigating these issues? Are improvements planned to make these queries lazy/incremental loaded?

**Comment by mbroecheler** [comment]
Hey Danny,

yes, Titan will load all edges into memory at once given such a query. The
primary strategy to avoid this is using vertex centric indices. For
instance, if you have timestamps you can get a slice of edges for a
particular period of time. Also, you can nicely combine vertex centric
indices with limit() to get you the 100 most recent edges, for instance.

Generally, it would be smarter for Titan to stream in edges incrementally
from the storage backend. A research prototype version of Titan does this
and is the basis for this publication:
http://www.knowledgefrominformation.com/2011/04/16/budget-match-cost-effective-subgraph-matching-on-large-networks/

However, the goal here is query optimization for complex queries (something
we will be soon be coming into the main titan version) and the incremental
loading technique is mostly used to avoid supernodes during query
processing.

If it is necessary for you to really pull in all 1M+ edges (i.e. indices
and limit() won't do anything for you) then you are likely entering OLAP
land and Faunus (just open sourced) is the better tool for that. While
Faunus is not yet optimized for very high degree vertices it will certainly
get there soon.

If you can disclose this, it would be good to know if that query that you
are interested in is an OLTP or OLAP query for we did not anticipate
supporting such massive data queries on the OLTP side.

On Fri, Sep 21, 2012 at 4:59 AM, Danny Thomas notifications@github.comwrote:

> We're seeing heap utilisation problems when dealing with supernodes (say
> 1M edges w/ a given label). The query is completely executed when hasNext()
> is first called on the iterator, in the case of ~1M edges, leading to over
> 350MB in retained heap between the ColumnFamily and the Titan objects.
> 
> Our query is a little convoluted, as we tag edges with a start and end
> timestamp:
> 
> ```
> val pipe = startingNode ->;
> pipe.
>   outE(relType).has('End', null).inV.
>   has(Graph.ID, sharedId).
>   inE(relType).has('End', null).outV
> ```
> 
> However, the behaviour can be demonstrated with a far simpler test using
> Gremlin:
> 
> g = TitanFactory.open("test")
> supernode = g.addVertex(null)
> i = 0
> while( i < 1000000 ) {
>   i++
>   supernode.addEdge('test',g.addVertex(null))
> }
> g.stopTransaction(com.tinkerpop.blueprints.TransactionalGraph.Conclusion.SUCCESS)
> supernode.outE('test').count()
> 
> Attach with a debugger, and note on the first hasNext call all edges are
> retrieved:
> 
> Thread [main](Suspended)
>     owns: PersistStandardTitanVertex  (id=85)
>     StandardTitanGraph.loadRelations(AtomicQuery, InternalTitanTransaction) line: 272
>     StandardPersistTitanTx.loadRelations(AtomicQuery) line: 150
>     PersistStandardTitanVertex(AbstractTitanVertex).ensureLoadedEdges(AtomicQuery) line: 88
>     PersistStandardTitanVertex(StandardTitanVertex).getRelations(AtomicQuery, boolean) line: 71
>     SimpleTitanQuery(SimpleAtomicQuery).edges() line: 461
>     PersistStandardTitanVertex(AbstractTitanVertex).getEdges(Direction, String...) line: 177
>     OutEdgesPipe(VerticesEdgesPipe).processNextStart() line: 45
>     OutEdgesPipe(VerticesEdgesPipe).processNextStart() line: 15
>     OutEdgesPipe(AbstractPipe<S,E>).hasNext() line: 90
>     GremlinGroovyPipeline<S,E>(Pipeline<S,E>).hasNext() line: 105
> 
> I noticed Titan's queries can have limits, though they're only set by
> Gremlin when using range(int, int) for a vertex operation, and can't be
> applied as a workaround for AbstractTitanVertex.getEdges:
> 
> ```
> @Override
> public Iterable<Edge> getEdges(Direction dir, String... labels) {
>     return new SimpleTitanQuery(this).direction(dir).labels(labels).edges();
> }
> ```
> 
> Is there a suggested design/workaround for mitigating these issues? Are
> improvements planned to make these queries lazy/incremental loaded?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/93.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by DanielThomas** [comment]
Matthias, thanks. This is an OLTP query, and we do have a timestamp field that is a primary key, so the latest vertexes would be coming off the query in that order anyway, so a vertex centric index/limit() approach seems to be exactly what we need to deal with this for the moment.
