### ISSUE TITLE
Non-existing method in the documentation for Unidirected Edges

### ISSUE THREAD

**Issue by smalyshev** [thinkaurelius/titan#930]
In chapter 25.4 in the docs here: http://s3.thinkaurelius.com/docs/titan/0.9.0-M1/advanced-schema.html#_unidirected_edges

the code example is:

```
mgmt = g.openManagement()
mgmt.makeEdgeLabel('author').unidirected().make()
mgmt.commit()
user = g.v(4)
u = g.v(8)
v = g.v(16)
v.addEdge('knows',u).singleProperty('author',user)
```

However, if you try to run this code, you discover that it produces an exception:

```
No signature of method: com.thinkaurelius.titan.graphdb.relations.StandardEdge.singleProperty() is applicable for argument types: (java.lang.String, com.thinkaurelius.titan.graphdb.vertices.CacheVertex)
```

This is because Edge objects don't seem to have singleProperty(), only property().

**Comment by mbroecheler** [comment]
Yes, it should be `property('author',user)` - thanks
