### ISSUE TITLE
Support indexQuery return objects via Rexster 

### ISSUE THREAD

**Issue by JPMoresmau** [thinkaurelius/titan#934]
Hello,

Via the Rexster client I think invoking an indexQuery works:

```
client.execute("g.indexQuery('myIndex', '_exists_:v.name').vertices()");
```

However, the resulting list contains String objects only, that look like:

```
com.thinkaurelius.titan.graphdb.query.graph.IndexQueryBuilder$ResultImpl@26e5a0ac
```

So it looks like the query is correctly executed on the server, but a `toString()` is done on the result objects, instead of serializing properly at least the vertices.

Thanks!

**Comment by spmallette** [comment]
Rexster doesn't have a way to serialize Titan specific classes - it deals in some general commodities that likely apply to all graphs (e.g. Vertex, Edge, etc).  

You will want to amend the script you send to rexster to include a way to iterate the return values to something it understands:

``` java
for (Result<Vertex> result : graph.indexQuery("search","v.text:(farm uncle berry)").vertices()) {
   System.out.println(result.getElement() + ": " + result.getScore());
}
```

The above is the Java way - a groovy approach might be:

``` groovy
g.indexQuery('myIndex', '_exists_:v.name').vertices()._().toList()
```

or if it won't go to `Pipeline` with `_()` then

``` groovy
l=[];g.indexQuery('myIndex', '_exists_:v.name').vertices().each{l<<it}
```

TinkerPop3 allows for graphs to supply their own serializers for their own classes thus allowing Rexster's replacement (Gremlin Server) to better convert "custom" classes to JSON or other formats.  HTH

**Comment by dkuppitz** [comment]
This should work:

``` groovy
g.indexQuery('myIndex', '_exists_:v.name').vertices()*.getElement()
```

**Comment by JPMoresmau** [comment]
@spmallette , I had no luck with your suggestions, but @dkuppitz 's worked!! Thanks to you both. @dkuppitz , I got back a Map<String,Object> instead of a Vertex, but I can work with that!

**Comment by spmallette** [comment]
oops - i left something out of my second one:

``` groovy
l=[];g.indexQuery('myIndex', '_exists_:v.name').vertices().each{l<<it};l
```

...didn't return `l`.  i didn't think to use the spread operator like @dkuppitz did - that's smart - looks much nicer.  glad this workaround is good for you.
