### ISSUE TITLE
TitanFactory not imported when running Gremlin script

### ISSUE THREAD

**Issue by vadasg** [thinkaurelius/titan#96]
I can create a new graph in an interactive Gremlin shell with no problems:

vadasg$ ./titan-0.1.0/bin/gremlin.sh

```
     \,,,/
     (o o)
```

-----oOOo-(_)-oOOo-----
gremlin> g = TitanFactory.open('/tmp/titantest1')
==>titangraph[local:/tmp/titantest1]
gremlin> exit

However, when I do the same thing in a script that I run with Gremlin I get the following error:

vadasg$ echo "g = TitanFactory.open('/tmp/titantest2')" > titantest2.groovy
vadasg$ ./titan-0.1.0/bin/gremlin.sh -e titantest2.groovy 
javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: TitanFactory for class: Script1

Marko gave me the workaround:  import TitanFactory explicitly in the script:

```
echo "import com.thinkaurelius.titan.core.TitanFactory; g = TitanFactory.open('/tmp/titantest2')" > titantest2.groovy
bin/gremlin.sh -e titantest2.groovy 

titan$ ls /tmp/titantest2/
00000000.jdb    je.info.0   je.info.0.lck   je.lck
```

It would be good if this were fixed in Titan so the workaround is not needed.

**Comment by okram** [comment]
Fixed. Pushed to 0.2-SNAPSHOT.

```
titan$ echo "g = TitanFactory.open('/tmp/titantest2')" > titantest2.groovy
titan$ bin/gremlin.sh -e titantest2.groovy 
titan$ 
```
