### ISSUE TITLE
Add unit test of titan-hadoop Cassandra widerows, fix spurious row-breaks

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#963]
ColumnFamilyRecordReader's widerows option is technically honored when provided in titan-hadoop's config since #694, but because TitanCassandraRecordReader incorrectly assumes it will still get all of a row's columns in one call even when widerows is enabled, it's unusuable.  TCRR produces a bunch of fragmentary vertices from distinct chunks of a single row's columns and chaos ensues.

The binary-row-to-FaunusVertex logic in `TitanHadoopGraph.readHadoopVertex` may need to be broken into a builder pattern that can accommodate incremental vertex construction as the widerow iterator passes in columns over several calls.

**Comment by dalaro** [comment]
I added a test that reads from Titan using widerows=true (3c776d48e6d7d40359c2d7080409fd590d695728).  That broke as expected.  3736b37212d3a9e2278e44e4b070ba02b32cceea is the fix.  The fix just pulls all of the columns into memory, processes each chunk, and then releases that chunk before moving onto the next.  It only passes a FaunusVertex object reflecting all those chunks of columns up to the task layer when it reaches the end of a row or the end of the query iterator.  So, this doesn't save any memory in the task processes -- it's still only intended to avoid thrift frame size exceeded exceptions.

**Comment by spmallette** [comment]
Thanks for the widerows fix dan - thrift frame size exceeded exceptions are annoying to deal with.
