### ISSUE TITLE
Bump Elasticsearch to latest version

### ISSUE THREAD

**Issue by Ghost93** [thinkaurelius/titan#964]
As requested here:

https://groups.google.com/d/msgid/aureliusgraphs/79862633-6148-47e4-8ac4-eab3d715880d%40googlegroups.com?utm_medium=email&utm_source=footer

Latest version is 1.4.2.

Thanks

**Comment by zazzcode** [comment]
Please note the latest version of ElasticSearch is 1.4.4 and this version is required for using the new Kabana 4.
http://www.elasticsearch.org/blog/kibana-4-literally/ 
If possible please bring Titan 0.9 compatible with ElasticSearch 1.4.4

**Comment by BrynCooke** [comment]
We currently have some unit tests failing. As soon as we have a stable build I'll upgrade the dependency to the latest ES version available.

**Comment by zazzcode** [comment]
ElasticSearch now at v1.5.   Where you able to resolve your unit test issues?  Is ElasticSearch version bumped in latest build?

https://www.elastic.co/blog/elasticsearch-1-5-0-released

thanks

**Comment by BrynCooke** [comment]
This needs to be solved first:
https://github.com/thinkaurelius/titan/issues/990

Once it is I will bump to the latest release.

**Comment by zazzcode** [comment]
Looks like you solved #990 – says “Closed”

Looking forward to Titan 0.9/1.0

Thanks for all your hard work –

~Michael
