### ISSUE TITLE
Setting storage.cassandra.thrift.frame-size do not  change the max frame size

### ISSUE THREAD

**Issue by crakjie** [thinkaurelius/titan#967]
Setting the configuration of storage.cassandra.thrift.frame-size before TitanGraph.open(conf) do not change the max frame size

**Comment by dalaro** [comment]
What is the value of `storage.backend` in your config?

**Comment by crakjie** [comment]
"cassandra"

**Comment by boliza** [comment]
@crakjie cassandra not support this config, only cassandrathrift support this config

**Comment by crakjie** [comment]
I'm confused, what is the difference between cassandrathrift which use cassandra thrift and cassandra which use cassandra thrift but which cannot be configured ?

**Comment by boliza** [comment]
storage.backend=cassandra means use use the cassandra driver astyanax.

In your case you should set storage.backend=cassandrathrift

Your can take look at the doc http://s3.thinkaurelius.com/docs/titan/0.5.3/cassandra.html#_cassandra_specific_configuration

**Comment by crakjie** [comment]
When I use storage.backend=cassandra I have an exception about the thrift frame size.
So I simply try to increase the frame size with storage.cassandra.thrift.frame-size.
If it's not with this property which property should I use?

**Comment by boliza** [comment]
You must change the storage.backend to cassandrathrift to solve that exception. When your storage.backend is cassandra the config storage.cassandra.thrift.frame-size does not work

**Comment by crakjie** [comment]
Yes but, isn't it suppose to work? Because storage.backend=cassandra also use thrift.

**Comment by boliza** [comment]
@crakjie  cassandra use astyanax driver and astyanax did't provide an interface to set this config.You should read this discuss.
https://groups.google.com/forum/#!msg/aureliusgraphs/xl5SqhL5UaU/qaSHU-8GIAAJ

**Comment by dalaro** [comment]
thanks @boliza.

Long story short, `storage.backend=cassandrathrift` uses a different client implementation than `storage.backend=astyanax`, and `storage.backend=cassandra` is just an alias for Astyanax.  We didn't see a way to modify the frame size setting through Astyanax, so the option is ignored there.  This is not a design decision -- if somebody finds a tidy way to control the frame size in Astynax, that would probably make a nice PR.

**Comment by crakjie** [comment]
Problematic but it makes sense, I have seen Astyanax is discontinued, so I think there is no way  this will be fixed.
