### ISSUE TITLE
Query.has() with ORing of values.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#97]
It would be good to have Query.has() have a definition of:

   Query.has(String key, Compare compare, Object... values)

Where the values are OR'd. Very convenient when propagated through to Gremlin.

@mbroecheler  In Faunus, we have g.v(1)....has('name','marko','peter').  This is OR, where name can be either marko or peter.  has(String key, Object... values). I was going to add this to Gremlin as its very handy and removes the need for filter{it.name.equals('marko') | it.name.equals('peter')}. However, I realized that has() pipe in Gremlin (when using optimization) compiles down to QueryPipe which uses vertex centric indices. Therefore, Query.has() in Blueprints must repspect the OR'ing. I can do this for DefaultQuery of course, but I'm wondering if Titan supports this?

**Comment by okram** [comment]
Going through what I want to do with Gremlin -- this feature would be highly appreciated as it would allow us to still remain in "Query-world" if has()-ORing is supported by Blueprints Query.

**Comment by mbroecheler** [comment]
This feature will roll out with Blueprints 2.4.0 and something that we need to accomodate for in the Titan query answering.
I am currently favoring an approach whereby we refactor the query processing pipeline (for both vertex centric queries and StandardElementQueries) into:

QueryBuilder -> execute -> query optimizer -> list of atomic queries plus execution flags (fitted or not) wrapped in a QueryPlan object -> execution against backend plus post filtering

**Comment by okram** [comment]
Please see has(key,predicate,value) in Blueprints. And predicate
Contains.IN.

This removes the ORing at the has() level and is predicate specififc.

http://markorodriguez.com

**Comment by okram** [comment]
Done. This is now handled not as OR but via Contains in new Blueprints.
