### ISSUE TITLE
KeyIndexableGraph.createKeyIndex vs TitanManagement.buildIndex().buildCompositeIndex()

### ISSUE THREAD

**Issue by syan4826** [thinkaurelius/titan#986]
Hello,
After reading code and document in Titan and Blueprint, I am a bit confused by this two type of index.
KeyIndexableGraph.createKeyIndex in Blueprint API
and 
TitanManagement.buildIndex().buildCompositeIndex() in Titan API
What's the different between these two ?

Thanks,

Yan

**Comment by spmallette** [comment]
The Blueprints methods are a generalization of index management in graphs and is insufficient for usage with the robust schema management functions of Titan.  Focus your usage on the `TitanManagement` API.

**Comment by syan4826** [comment]
Thank you.
