### ISSUE TITLE
Support Solr 5.0

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#987]
Solr 5.x has removed various types that are used in schema.xml. 

Where X is Int, Float, Long, Double or Date

XField becomes TrieXField
SortedXField becomes TrieXField

I am not sure what the impact will be if any.

**Comment by mbroecheler** [comment]
Is that something we should investigate for Titan 1.0 and upgrade to Solr 5.x? What's your recommendation here?

**Comment by BrynCooke** [comment]
I don't think we can upgrade to Solr 5.0. Instead we can upgrade to 4.10.4 Which matches the version of Lucene that elastic search requires.

**Comment by BrynCooke** [comment]
Actually we can upgrade to Solr 5.0.
We only use the Solr client rather than embedding it so it is fine to co-exist with older versions of lucene.
