### ISSUE TITLE
In latest versions TitanGraphTransaction extends Gremlin Graph class instead of blueprint TransactionGraph class

### ISSUE THREAD

**Issue by mailsanjayyadav** [thinkaurelius/titan#993]
Not sure if this is intentional. Can someone explain. I had written generic code to use multiple graph dbs -  ne04j and titan. But because of this change I cannot cast TitanGraph to blueprints Graph class. 

In 0.5.4
public interface TitanGraphTransaction extends com.tinkerpop.blueprints.TransactionalGraph, KeyIndexableGraph, SchemaManager {

In 0.9.0-M1
public interface TitanGraphTransaction extends *.gremlin.Graph, SchemaManager {

**Comment by spmallette** [comment]
note that Titan 0.5.x and prior version depends on TinkerPop2.  Titan 0.9.x depends on TinkerPop3. TP3 has an entirely new interface model, so interfaces like `TransactionalGraph`, `KeyIndexableGraph`, etc. no longer exist.  Please see the TP3 documentation for the latest information on the changes: http://tinkerpop.incubator.apache.org/docs/3.0.0-SNAPSHOT/

**Comment by mailsanjayyadav** [comment]
So it means, tinkerpop3 and tinkerpop2 are backward incompatible in some sense.

**Comment by spmallette** [comment]
correct - to accomplish some of the "next generation" features we needed to, a complete re-thinking of the APIs was required.

**Comment by mailsanjayyadav** [comment]
Hi,

I was thinking if it is safe to start using 0.9.x version of titan. My graph is already in production on version 0.5.4. I am ready to recreate it using new version as it is still in early stages. It has max of 1 Million edges on one vertex. Which version should i use for my latest developments.

**Comment by spmallette** [comment]
i would not do a production migration until 1.0 is released, but i'd recommend doing some development against 0.9 and figure out your data migration strategy until that happens.
